import { $, $$, on, esc, fmt, fdate, ftime, CLS, badge, chip, toast, download, TODAY, polyAreaHa } from '../util.js';
import { S, ST, G, P, munName, prediosById, estudioById, refresh, monthly } from '../state.js';
import * as ch from '../charts.js';
import { kpi, tag, icon, stars, projChip, modal, estadoChip, conChip, forestChart } from '../ui.js';
import { createMap, attachControls } from '../mapkit.js';
import { simulator } from './admin.js';
import { VERSION } from '../semaforo.js';
import { analyzeFiles, runChecks, verdict, renderChecks, verdictBox, CHECK_DEFS } from '../verify.js';
import { sha256File, ledgerVerify, ledgerAppend, ledgerHash, shortHash, parseLasHeader } from '../integrity.js';
import { SOURCES, CATS, AVO_MM } from '../sources.js';
import { prepPolys, mx, my } from '../map.js';
import { GF } from '../domain/gf.js';
import { PARAMS, todayIso } from '../domain/core.js';
import { bump, entregasSemarnat } from '../domain/mce.js';

const hdr = (t, p, act = '') => `<div class="page-h"><div><h1>${t}</h1>${p ? `<p>${p}</p>` : ''}</div><div class="act">${act}</div></div>`;

// ---------- Semáforo forestal ----------
function semaforo(main, params) {
  const pr = params && params.id ? prediosById[params.id].properties : null; let tab = 0;
  main.innerHTML = hdr('Semáforo forestal', 'Algoritmo transparente de clasificación con Índice de Reversibilidad. Simule un caso, revise las reglas y la calibración contra verificación de campo.', `<span class="chip vio">${VERSION}</span> <span class="chip warn">Modo sombra: sin efectos jurídicos</span>`) + `<div class="tabs" id="tb">${['Simulador', 'Reglas y versiones', 'Calibración'].map((t, i) => `<button data-t="${i}" class="${i ? '' : 'on'}">${t}</button>`).join('')}</div><div id="tc"></div>`;
  const T = [
    () => `${pr ? `<div class="note info tiny" style="margin-bottom:10px">Cargado el predio <b class="mono">${pr.id}</b> (${CLS[pr.cls].name}). Ajuste las variables para ver cómo cambiaría su clasificación.</div>` : ''}<div class="card"><div id="sm"></div></div>`,
    () => `<div class="grid g2"><div class="card"><h3>Reglas de decisión</h3><ol class="tiny" style="line-height:1.85;color:#45544F;padding-left:18px;margin-top:8px"><li><b>Gris</b> si no hay polígono validado o la información es insuficiente.</li><li><b>Verde</b> si no hay ruptura de cobertura posterior a la fecha de referencia.</li><li><b>Amarillo</b> si hay ruptura detectada sin validación humana: sin efectos y sin publicación.</li><li>Con validación humana: cualquier <b>causal determinante</b> → <b>Rojo</b>.</li><li>Sin causal: Índice &lt; 50 → <b>Rojo</b>; 50-74 → <b>Naranja N2</b>; ≥ 75 → <b>Naranja N1</b>.</li><li>Un predio naranja <b>nunca</b> regresa a verde: una restauración exitosa cierra la obligación, no borra el historial.</li><li>Sólo se publican clasificaciones firmes (tras notificación y audiencia).</li></ol></div>
      <div class="card"><h3>Versiones del algoritmo</h3><div class="tw" style="margin-top:8px"><table class="tbl"><thead><tr><th>Versión</th><th>Fecha</th><th>Estado</th></tr></thead><tbody><tr><td class="mono">SF-v0.1</td><td>mar-2026</td><td>${chip('Retirada')}</td></tr><tr><td class="mono">SF-v0.2</td><td>jun-2026</td><td>${chip('Calibración piloto', 'info')}</td></tr><tr><td class="mono">${VERSION}</td><td>sep-2026</td><td>${chip('Vigente en modo sombra', 'warn')}</td></tr></tbody></table></div><p class="tiny dim" style="margin-top:10px">Cada cambio de versión requiere aprobación del Comité Técnico, auditoría académica y queda sellado en la bitácora. Las clasificaciones emitidas conservan la versión con que se calcularon.</p></div></div>`,
    () => { const cm = [[212, 14, 3, 0, 9], [11, 38, 6, 1, 4], [4, 5, 47, 6, 2], [0, 1, 7, 38, 0], [6, 3, 1, 0, 32]]; const L = ['verde', 'amarillo', 'naranja', 'rojo', 'gris']; const tot = cm.flat().reduce((a, b) => a + b, 0), okk = cm.reduce((a, r, i) => a + r[i], 0); return `<div class="grid g21"><div class="card"><div class="ch"><h3>Matriz de confusión vs verificación de campo</h3><div class="sp">${tag('demo')}</div></div><div class="tw" style="margin-top:8px"><table class="tbl"><thead><tr><th>Algoritmo ↓ / Campo →</th>${L.map(c => `<th class="num" style="color:${CLS[c].color}">${CLS[c].name}</th>`).join('')}<th class="num">Exactitud</th></tr></thead><tbody>${cm.map((r, i) => `<tr><td>${badge(L[i])}</td>${r.map((v, j) => `<td class="num" style="${i === j ? 'background:rgba(46,125,50,.08);color:#2E7D32;font-weight:600' : v > 8 ? 'background:rgba(168,114,15,.08)' : ''}">${v}</td>`).join('')}<td class="num">${fmt(r[i] / r.reduce((a, b) => a + b, 0) * 100, 0)} %</td></tr>`).join('')}</tbody></table></div></div>
      <div class="card"><h3>Exactitud global</h3><div style="text-align:center">${ch.gauge(Math.round(okk / tot * 100), 100, okk / tot >= .9 ? '#2E7D32' : '#A8720F', 'Meta ≥ 90 % antes de efectos')}</div><p class="tiny dim">Muestra estratificada de ${tot} predios verificados por brigadas y por LiDAR nivel C. Los errores de omisión de huertas menores a 1 ha (verde que debió ser amarillo) son el punto débil documentado en la literatura (omisión de aguacate de ~29 % a 90 m).</p></div></div>`; },
  ];
  const show = i => { tab = i; $$('#tb button', main).forEach(b => b.classList.toggle('on', +b.dataset.t === i)); $('#tc', main).innerHTML = T[i](); if (i === 0) simulator($('#sm', main), pr ? { v: pr.v, poligono: pr.cls !== 'gris', perdida: ['amarillo', 'naranja', 'rojo'].includes(pr.cls), validada: ['naranja', 'rojo'].includes(pr.cls), causales: pr.cau ? [pr.cau] : [] } : {}); };
  on(main, 'click', '#tb button', (e, b) => show(+b.dataset.t)); show(0);
}

// ---------- Evaluación de restauración ----------
function restauracion(main) {
  let sel = null; main.className = 'main flush';
  main.innerHTML = `<div class="split"><div style="flex:1;min-width:0;padding:16px 18px;overflow:auto">${hdr('Evaluación de restauración', 'Revise proyectos y verifique el avance con LiDAR (antes, durante, después). La calificación de cinco estrellas se calcula con supervivencia, copa, estructura vertical y diversidad.')}<div class="tw"><table class="tbl" id="tb"></table></div></div><aside class="side" id="pn" style="width:400px"></aside></div>`;
  const draw = () => { $('#tb', main).innerHTML = `<thead><tr><th>Proyecto</th><th>Predio</th><th>Municipio</th><th>Tipo</th><th class="num">Ha</th><th>Estado</th><th>Calif.</th></tr></thead><tbody>${S.proyectos.map(r => `<tr class="cl ${r.id === sel ? 'act' : ''}" data-id="${r.id}"><td class="mono">${r.id}</td><td class="mono">${r.pid}</td><td>${esc(munName[r.mun])}</td><td class="dim">${esc(r.tipo)}</td><td class="num">${fmt(r.ha, 1)}</td><td>${projChip(r.st)}</td><td>${stars(r.stars)}</td></tr>`).join('')}</tbody>`; };
  const detail = () => { const r = S.proyectos.find(x => x.id === sel), pn = $('#pn', main); if (!r) { pn.innerHTML = '<div class="dim" style="text-align:center;padding:40px">Seleccione un proyecto.</div>'; return; }
    const steps = ['En evaluación', 'Aprobado', 'En ejecución', 'En verificación', 'Cerrado']; const ix = steps.indexOf(r.st);
    pn.innerHTML = `<div class="ch"><h2 class="mono">${r.id}</h2><div class="sp">${projChip(r.st)}</div></div><p style="margin:8px 0">${esc(r.tipo)} · ${fmt(r.ha, 1)} ha · predio <a class="mono" data-p="${r.pid}">${r.pid}</a></p><div class="steps">${steps.map((s, i) => `<div class="${i < ix ? 'done' : i === ix ? 'now' : ''}"><b>${i + 1}</b>${s}</div>`).join('')}</div>
    <h3>Rúbrica de verificación</h3>${[['Supervivencia al 2.º año', 'sv', 0, 100, r.surv ?? 70, '%'], ['Cobertura de copa lograda (LiDAR)', 'cc', 0, 100, 60, '%'], ['Estructura vertical (estratos)', 'ev', 0, 100, 55, '%'], ['Diversidad de especies nativas', 'dv', 0, 100, 65, '%']].map(x => `<div style="margin:8px 0"><div style="display:flex;justify-content:space-between;font-size:12px"><span>${x[0]}</span><span class="mono" id="v-${x[1]}">${x[4]}${x[5]}</span></div><input type="range" min="${x[2]}" max="${x[3]}" value="${x[4]}" data-r="${x[1]}"></div>`).join('')}
    <div id="sc" style="margin:12px 0"></div><div style="display:flex;gap:8px;flex-wrap:wrap">${ix < 4 ? `<button class="btn ok" id="adv">Avanzar a «${steps[ix + 1]}»</button>` : ''}<button class="btn" id="cal">Calificar y cerrar</button></div>`;
    const calc = () => { const v = k => +$(`[data-r=${k}]`, pn).value; const s = v('sv') * .4 + v('cc') * .25 + v('ev') * .2 + v('dv') * .15; const n = Math.max(0, Math.min(5, Math.round(s / 20))); $('#sc', pn).innerHTML = `<div class="card" style="padding:10px"><div class="tiny dim">Puntaje ponderado</div><div style="display:flex;align-items:center;gap:12px"><span class="mono" style="font-size:26px">${fmt(s, 0)}</span>${stars(n)}</div></div>`; pn._n = n; }; calc();
    pn.oninput = e => { const t = e.target; if (t.dataset.r) { $('#v-' + t.dataset.r, pn).textContent = t.value + '%'; calc(); } };
    const adv = $('#adv', pn); adv && (adv.onclick = () => { r.st = steps[ix + 1]; ledgerAppend(S.ledger, 'Dictaminador-01', 'RESTAURACION_' + r.st.toUpperCase().replace(/ /g, '_'), r.id); if (r.st === 'En ejecución' && !r.plant) r.plant = Math.round(r.ha * 1100); toast('Proyecto avanzó a «' + r.st + '»'); refresh(); draw(); detail(); });
    $('#cal', pn).onclick = () => { r.stars = pn._n; r.surv = +$('[data-r=sv]', pn).value; r.st = 'Cerrado'; ledgerAppend(S.ledger, 'Dictaminador-01', 'RESTAURACION_CALIFICADA', r.id); toast('Proyecto cerrado con ' + r.stars + ' estrellas'); refresh(); draw(); detail(); };
    const a = $('[data-p]', pn); a && (a.onclick = () => window.__go('admin', 'padron', { id: r.pid })); };
  draw(); detail(); on(main, 'click', 'tr.cl', (e, t) => { sel = t.dataset.id; draw(); detail(); });
}

// ---------- Indicadores y reportes ----------
function indicadores(main) {
  const mm = monthly(); const lids = S.estudios;
  main.innerHTML = hdr('Indicadores y reportes', 'Matriz de indicadores para resultados (MIR) con método de cálculo y medio de verificación. Genera el informe trimestral de rendición de cuentas a SEMARNAT.', `<button class="btn pri" id="rep">${icon('file', 15)} Generar informe trimestral</button>`) +
    `<div class="grid g4">${kpi({ l: 'Predios validados', v: fmt(ST.validated * 100, 0) + ' %', s: 'meta 85 %', c: '#235B4E' })}${kpi({ l: 'Estudios aceptados 1.ª revisión', v: fmt(lids.filter(e => e.ver === 'Íntegro').length / lids.length * 100, 0) + ' %', s: 'meta 70 %', c: '#2E7D32' })}${kpi({ l: 'Expedientes enviados', v: 37, s: '29 con respuesta de la autoridad', c: '#9F2241' })}${kpi({ l: 'Tiempo alerta → validación', v: '6 d', s: 'mediana · meta ≤ 10 d hábiles', c: '#A8720F' })}</div>
    <div class="grid g3" style="margin-top:14px">${kpi({ l: 'Dictámenes entregados a SEMARNAT', v: fmt(entregasSemarnat().length), s: 'modo «insumo técnico» con acuse', c: '#235B4E' })}${kpi({ l: 'Certificados federales apoyados en evidencia estatal', v: fmt(entregasSemarnat().filter(e => e.certificadoFederal).length), s: 'se actualiza con la respuesta de SEMARNAT' })}${kpi({ l: 'Constancias de cumplimiento (autoridad)', v: fmt(S.procedimientos.filter(p => p.constancia).length), s: 'procedimientos resueltos', c: '#2E7D32' })}</div>
    <div class="grid g2" style="margin-top:14px"><div class="card"><div class="ch"><h3>Alertas por mes</h3><div class="sp">${tag('demo')}</div></div>${ch.line([{ name: 'Alertas', color: '#235B4E', pts: mm.map((m, i) => [i, m[1]]), area: true, dots: true }], { h: 210, xticks: mm.map((m, i) => i).filter(i => i % 2 === 0), ymin: 0 })}<div class="tiny dim">${mm.map((m, i) => i % 2 === 0 ? `${i}=${m[0]}` : '').filter(Boolean).join(' · ')}</div></div>
    <div class="card"><div class="ch"><h3>Predios por semáforo (superficie, ha)</h3></div>${ch.hstack(['verde', 'amarillo', 'naranja', 'rojo', 'gris'].map(c => ({ label: CLS[c].name, parts: [{ v: Math.round(ST.ha[c]), color: CLS[c].color, name: CLS[c].name }] })), { rh: 30, ml: 90 })}</div></div>
    <div class="card" style="margin-top:14px"><div class="ch"><h3>Matriz de indicadores (extracto)</h3></div><div class="tw" style="margin-top:8px"><table class="tbl"><thead><tr><th>Nivel</th><th>Indicador</th><th>Método de cálculo</th><th>Frecuencia</th><th>Medio de verificación</th></tr></thead><tbody>${[['Fin', 'Cambio neto anual de cobertura forestal en la franja aguacatera', 'Ha ganadas − ha perdidas en el año, con el umbral legal', 'Anual', 'Monitoreo satelital validado; línea base LiDAR'], ['Propósito', 'Superficie agrícola mapeada con polígono validado', 'Ha validadas / ha de cultivo mapeadas × 100', 'Semestral', 'Padrón; mapa de cultivos'], ['C1', 'Registros validados', 'Validados / declarados × 100', 'Trimestral', 'Plataforma'], ['C2', 'Exactitud del mapa de cobertura', 'Exactitud global y errores por clase vs muestra', 'Anual', 'Informe de validación auditado'], ['C3', 'Estudios prediales aceptados en 1.ª revisión', 'Aceptados sin observaciones / presentados', 'Trimestral', 'Dictámenes'], ['C4', 'Exactitud de la clasificación', 'Coincidencia con campo en muestra estratificada', 'Anual', 'Auditoría académica'], ['C5', 'Supervivencia a 2 años', 'Plantas vivas / establecidas', 'Anual', 'Muestreo de campo'], ['C7', 'Informes a SEMARNAT en plazo', 'Entregados / comprometidos', 'Trimestral', 'Acuses']].map(r => `<tr><td><span class="chip">${r[0]}</span></td><td>${r[1]}</td><td class="dim">${r[2]}</td><td>${r[3]}</td><td class="dim">${r[4]}</td></tr>`).join('')}</tbody></table></div></div>`;
  $('#rep', main).onclick = () => { const html = `<!doctype html><meta charset="utf-8"><title>Informe trimestral</title><body style="font-family:system-ui;max-width:800px;margin:30px auto"><h1>Informe trimestral a SEMARNAT — 3.er trimestre 2026</h1><p><b>DEMOSTRACIÓN.</b> Cifras ilustrativas generadas por el prototipo.</p><table border=1 cellpadding=6 style="border-collapse:collapse"><tr><th>Indicador</th><th>Valor</th></tr><tr><td>Predios inscritos</td><td>${ST.tot}</td></tr><tr><td>Verde / Amarillo / Naranja / Rojo / Gris</td><td>${ST.cnt.verde} / ${ST.cnt.amarillo} / ${ST.cnt.naranja} / ${ST.cnt.rojo} / ${ST.cnt.gris}</td></tr><tr><td>Alertas últimos 90 días</td><td>${ST.a90}</td></tr><tr><td>Superficie en restauración</td><td>${fmt(ST.resHa, 0)} ha</td></tr><tr><td>Estudios LiDAR íntegros</td><td>${S.estudios.filter(e => e.ver === 'Íntegro').length} de ${S.estudios.length}</td></tr><tr><td>Bitácora: registros encadenados</td><td>${S.ledger.length}; cabeza ${ledgerVerify(S.ledger).head || 'ROTA'}</td></tr></table></body>`; download('Informe_SEMARNAT_T3_2026.html', html, 'text/html'); ledgerAppend(S.ledger, 'Director', 'INFORME_GENERADO', 'T3-2026'); toast('Informe generado y registrado'); };
}

// ---------- Levantamientos LiDAR / dron ----------
function lidar(main, params) {
  _vizHook(main);
  let sel = (params && params.id) || S.estudios[0].id, filt = ''; main.className = 'main flush';
  main.innerHTML = `<div class="split"><div style="flex:1;min-width:0;padding:16px 18px;overflow:auto">${hdr('Levantamientos LiDAR / dron', 'Recepción, verificación de integridad y dictamen de cada levantamiento. Cada archivo se sella con SHA-256 al recibirse y cualquier alteración posterior se detecta.', `<button class="btn pri" data-viz>${icon('layers', 14)} Visor 3D y análisis</button>`)}
    <div class="card" style="margin-bottom:12px"><div class="ch"><h3>Verificador de archivos</h3><div class="sp">${icon('hash', 16)}</div></div><div class="two" style="margin-top:8px"><div class="drop" id="vdz" style="padding:16px">Suelte uno o varios archivos (LAS/LAZ, JPG, CSV…) para calcular su huella y buscarla en los manifiestos sellados<input type="file" id="vfi" multiple hidden></div><div id="vres" class="tiny dim">Los archivos se procesan localmente; sólo se compara la huella.</div></div></div>
    <div class="split-h"><select id="ff"><option value="">Todos</option><option>Íntegro</option><option>Con observaciones</option><option>Rechazado</option></select><span class="tiny dim" id="ct"></span></div><div class="tw"><table class="tbl" id="tb"></table></div></div><aside class="side" id="pn" style="width:520px"></aside></div>`;
  const draw = () => { const l = S.estudios.filter(e => !filt || e.ver === filt); $('#ct', main).textContent = l.length + ' levantamientos'; $('#tb', main).innerHTML = `<thead><tr><th>Estudio</th><th>Predio</th><th>Fecha</th><th>Aeronave / sensor</th><th class="num">pts/m²</th><th>Verificación</th></tr></thead><tbody>${l.map(e => `<tr class="cl ${e.id === sel ? 'act' : ''}" data-id="${e.id}"><td class="mono">${e.id}${e.nuevo ? ' <span class="chip info">nuevo</span>' : ''}</td><td class="mono">${e.pid}</td><td>${fdate(e.fecha)}</td><td class="dim">${esc(e.aero.modelo)} / ${esc(e.sensor.modelo)}</td><td class="num">${e.dens}</td><td>${estadoChip(e.ver)}</td></tr>`).join('')}</tbody>`; };
  const detail = (override) => { const e = estudioById[sel] || S.estudios.find(x => x.id === sel), pn = $('#pn', main); if (!e) return; const checks = override || e.checks; const v = verdict(checks);
    pn.innerHTML = `<div class="ch"><h2 class="mono">${e.id}</h2><div class="sp"><a class="btn sm" data-p="${e.pid}">Predio ${e.pid}</a></div></div>${verdictBox(v)}
    <h3 style="margin:14px 0 6px">Metadatos del vuelo</h3><dl class="kv"><dt>Fecha / ventana</dt><dd class="mono">${fdate(e.fecha)} · ${e.utc0.slice(11, 16)}–${e.utc1.slice(11, 16)} UTC</dd><dt>Aeronave</dt><dd>${esc(e.aero.marca)} ${esc(e.aero.modelo)} <span class="mono dim">${esc(e.aero.serie)}</span></dd><dt>Sensor</dt><dd>${esc(e.sensor.modelo)} <span class="mono dim">${esc(e.sensor.serie)}</span></dd><dt>Calibración</dt><dd>${esc(e.sensor.cal)}</dd><dt>Altura / velocidad</dt><dd class="mono">${e.agl} m AGL · ${e.vel} m/s</dd><dt>Autorización</dt><dd class="mono">${esc(e.autoriz)}</dd><dt>Operador</dt><dd class="mono">${e.oper}</dd><dt>Producto</dt><dd class="mono">${fmt(e.npts)} pts · ${e.dens} pts/m² · ${e.area} ha</dd><dt>CRS</dt><dd class="tiny">${esc(e.crs)}</dd></dl>
    <h3 style="margin:14px 0 4px">Comprobaciones de integridad (${checks.length})</h3>${renderChecks(checks)}
    <h3 style="margin:14px 0 6px">Manifiesto de archivos sellado</h3><div class="tw"><table class="tbl"><tbody>${e.files.map(f => `<tr><td>${esc(f.n)}<div class="tiny dim">${esc(f.role)} · ${f.mb} MB</div></td><td><div class="hash">${f.sha}</div>${f.ok === false ? `<div class="hash" style="color:#B3261E">actual: ${f.sha_now}</div>` : ''}</td></tr>`).join('')}</tbody></table></div>
    <div class="drop" id="mdz" style="margin-top:12px;padding:14px">Suelte los archivos entregados para <b>re-verificarlos contra este manifiesto</b><input type="file" id="mfi" multiple hidden></div>
    <div style="display:flex;gap:8px;margin-top:12px;flex-wrap:wrap"><button class="btn ok" data-d="acept">Aceptar para dictamen</button><button class="btn" data-d="acl">Solicitar aclaración</button><button class="btn danger" data-d="rech">Rechazar</button></div>`;
    const dz = $('#mdz', pn), fi = $('#mfi', pn); dz.onclick = () => fi.click(); ['dragover', 'dragenter'].forEach(ev => dz.addEventListener(ev, x => { x.preventDefault(); dz.classList.add('over'); })); ['dragleave', 'drop'].forEach(ev => dz.addEventListener(ev, x => { x.preventDefault(); dz.classList.remove('over'); }));
    const go = async fl => { dz.innerHTML = 'Calculando huellas…'; const infos = await analyzeFiles(fl); const manifest = e.files.map(f => ({ name: f.n, sha: f.sha })); const ck = runChecks({ pid: e.pid, fecha: e.fecha, autoriz: e.autoriz, aeroModelo: e.aero.modelo, aeroSerie: e.aero.serie, sensorModelo: e.sensor.modelo, sensorSerie: e.sensor.serie }, infos, manifest, { selfId: e.id, signed: true }); detail(ck); toast('Re-verificación contra manifiesto completada', verdict(ck).f ? 'bad' : 'ok'); };
    fi.onchange = () => go([...fi.files]); dz.addEventListener('drop', x => go([...x.dataTransfer.files]));
    on(pn, 'click', '[data-d]', (x, b) => { const map = { acept: 'ESTUDIO_ACEPTADO', acl: 'ACLARACION_SOLICITADA', rech: 'ESTUDIO_RECHAZADO' }; ledgerAppend(S.ledger, 'Dictaminador-03', map[b.dataset.d], e.id); toast('Decisión registrada en la bitácora'); });
    const a = $('[data-p]', pn); a && (a.onclick = () => window.__go('admin', 'padron', { id: e.pid })); };
  draw(); detail(); on(main, 'click', 'tr.cl', (x, t) => { sel = t.dataset.id; draw(); detail(); }); main.addEventListener('change', x => { if (x.target.id === 'ff') { filt = x.target.value; draw(); } });
  const dz = $('#vdz', main), fi = $('#vfi', main); dz.onclick = () => fi.click(); ['dragover', 'dragenter'].forEach(ev => dz.addEventListener(ev, x => { x.preventDefault(); dz.classList.add('over'); })); ['dragleave', 'drop'].forEach(ev => dz.addEventListener(ev, x => { x.preventDefault(); dz.classList.remove('over'); }));
  const quick = async fl => { const out = $('#vres', main); out.innerHTML = 'Calculando…'; const infos = await analyzeFiles(fl); const known = []; S.estudios.forEach(e => e.files.forEach(f => known.push({ sha: f.sha, e: e.id, n: f.n }))); S.uploads.forEach(u => known.push({ sha: u.sha, e: u.study, n: u.name })); out.innerHTML = infos.map(i => { const m = known.find(k => k.sha === i.sha); return `<div style="margin-bottom:8px"><b>${esc(i.name)}</b> <span class="dim">${fmt(i.size / 1024)} KB · ${i.kind}</span><div class="hash">${i.sha}</div>${m ? `<span class="chip ok">Coincide con ${m.e} · ${esc(m.n)}</span>` : '<span class="chip warn">No coincide con ningún archivo sellado</span>'}${i.las ? `<div class="tiny dim">LAS ${i.las.version} · ${fmt(i.las.count)} pts · creado ${i.las.created || '?'} · ${esc(i.las.software)}</div>` : ''}${i.exif && i.exif.tags && i.exif.tags.Model ? `<div class="tiny dim">EXIF: ${esc(i.exif.tags.Make || '')} ${esc(i.exif.tags.Model)} · ${esc(i.exif.tags.DateTimeOriginal || '')}${i.exif.lat != null ? ` · ${i.exif.lat.toFixed(5)}, ${i.exif.lon.toFixed(5)}` : ''}</div>` : ''}</div>`; }).join(''); };
  fi.onchange = () => quick([...fi.files]); dz.addEventListener('drop', x => quick([...x.dataTransfer.files]));
}

// ---------- Ingesta de datos históricos ----------
const DTYPES = [
  { k: 'predios', name: 'Polígonos de predios (padrón histórico)', ext: '.geojson, .gpkg, .shp.zip', req: ['folio_origen', 'anio'], desc: 'Padrones previos de SADER, SENASICA, empacadoras, catastro o RAN.' },
  { k: 'alertas', name: 'Alertas y detecciones históricas', ext: '.csv, .geojson', req: ['lon', 'lat', 'fecha'], desc: 'Hansen GFC, GLAD/RADD, Guardián Forestal, FIRMS.' },
  { k: 'cobertura', name: 'Cobertura / series raster', ext: '.tif (COG), .zip', req: [], desc: 'Landsat/Sentinel/HLS derivados, Serie INEGI, GFC2020.' },
  { k: 'lidar', name: 'Levantamientos LiDAR previos', ext: '.las, .laz, .copc.laz', req: [], desc: 'Nubes de puntos históricas (INEGI, proyectos académicos, empresas).' },
  { k: 'imagen', name: 'Ortofotos e imágenes históricas', ext: '.tif, .jpg, .zip', req: [], desc: 'INEGI 1974/1995, VHR comercial, dron.' },
  { k: 'expedientes', name: 'Expedientes, denuncias y autorizaciones', ext: '.csv', req: ['expediente', 'fecha'], desc: 'PROFEPA, Fiscalía, SEMARNAT (CUSTF/MIA), PPA.' },
  { k: 'referencia', name: 'Capas de referencia', ext: '.geojson, .gpkg, .shp.zip', req: [], desc: 'ANP, núcleos agrarios, hidrografía, cuencas, INEGI USV serie VII, Inventario Nacional Forestal.' },
  { k: 'autorizaciones', name: 'Autorizaciones (CUSTF, MIA, agua)', ext: '.csv, .geojson', req: ['folio', 'vigencia'], desc: 'Autorizaciones de cambio de uso de suelo en terreno forestal (SEMARNAT) y otras; alimentan la segunda condición del dictamen.' },
  { k: 'owp', name: 'Catálogo de municipios aprobados (OWP)', ext: '.csv', req: ['cve_mun'], desc: 'Lista oficial SENASICA/APHIS de municipios del plan de trabajo; alimenta la geocerca de la zona autorizada.' },
];
function parseCSV(t) { const L = t.replace(/^﻿/, '').split(/\r?\n/).filter(x => x.trim()); if (!L.length) return { h: [], rows: [] }; const d = (L[0].match(/;/g) || []).length > (L[0].match(/,/g) || []).length ? ';' : ','; const h = L[0].split(d).map(x => x.trim().replace(/^"|"$/g, '').toLowerCase()); return { h, d, rows: L.slice(1).map(l => { const c = l.split(d).map(x => x.trim().replace(/^"|"$/g, '')); const o = {}; h.forEach((k, i) => o[k] = c[i]); return o; }) }; }
const MBB = [-103.8, 17.9, -100.0, 20.4];
async function validateFile(file, type) {
  const R = { name: file.name, size: file.size, steps: [], layer: null, records: null }; const add = (k, s, d) => R.steps.push({ k, s, d });
  R.sha = await sha256File(file); add('Recepción y huella SHA-256', 'ok', `${fmt(file.size / 1024)} KB · ${R.sha.slice(0, 16)}…`);
  const n = file.name.toLowerCase(); const head = new Uint8Array(await file.slice(0, 4).arrayBuffer());
  const isJson = /\.(geo)?json$/.test(n), isCsv = /\.(csv|txt)$/.test(n), isTif = /\.tiff?$/.test(n), isLas = /\.la[sz]$/.test(n), isZip = /\.zip$/.test(n), isGpkg = /\.gpkg$/.test(n), isImg = /\.(jpe?g|png)$/.test(n);
  if (isJson) {
    let gj; try { gj = JSON.parse(await file.text()); add('Formato GeoJSON', 'ok', 'JSON válido'); } catch (e) { add('Formato GeoJSON', 'fail', 'No es JSON válido: ' + e.message); return R; }
    const fs = gj.type === 'FeatureCollection' ? gj.features : gj.type === 'Feature' ? [gj] : []; if (!fs.length) { add('Esquema', 'fail', 'No contiene Features'); return R; }
    R.records = fs.length; const geoms = fs.map(f => f.geometry).filter(Boolean); const types = {}; geoms.forEach(g => types[g.type] = (types[g.type] || 0) + 1); add('Esquema', 'ok', `${fs.length} elementos · geometrías: ${Object.entries(types).map(([k, v]) => k + ' ' + v).join(', ')}`);
    const dt = DTYPES.find(d => d.k === type); const props = fs[0].properties || {}; const missing = dt.req.filter(r => !(r in props) && !fs.every(f => f.properties && r in f.properties) && !(f => f)(0)); const miss = dt.req.filter(r => !fs.some(f => f.properties && r in f.properties)); add('Campos obligatorios', miss.length ? 'warn' : 'ok', miss.length ? 'Faltan: ' + miss.join(', ') + ' (se completarán o se marcarán como desconocidos)' : dt.req.length ? 'Presentes: ' + dt.req.join(', ') : 'Sin campos obligatorios para este tipo');
    let bad = 0, out = 0, ha = 0; const ptsAll = []; fs.forEach(f => { const g = f.geometry; if (!g) { bad++; return; } const rings = g.type === 'Polygon' ? [g.coordinates[0]] : g.type === 'MultiPolygon' ? g.coordinates.map(p => p[0]) : []; rings.forEach(r => { if (!r || r.length < 4 || r[0][0] !== r[r.length - 1][0] || r[0][1] !== r[r.length - 1][1]) bad++; else { ha += polyAreaHa(r); } r && r.forEach(c => { if (c[0] < MBB[0] || c[0] > MBB[2] || c[1] < MBB[1] || c[1] > MBB[3]) out++; }); }); if (g.type === 'Point') { ptsAll.push(g.coordinates); if (g.coordinates[0] < MBB[0] || g.coordinates[0] > MBB[2] || g.coordinates[1] < MBB[1] || g.coordinates[1] > MBB[3]) out++; } });
    add('Geometría', bad ? 'fail' : 'ok', bad ? `${bad} geometrías inválidas (anillos abiertos o de menos de 4 vértices)` : `Todas las geometrías son válidas${ha ? ' · ' + fmt(ha, 1) + ' ha en total' : ''}`);
    add('CRS y rango', out ? 'warn' : 'ok', out ? `${out} coordenadas fuera de Michoacán o en un CRS proyectado. GeoJSON exige WGS84 (lon, lat)` : 'Coordenadas WGS84 dentro de Michoacán');
    const ids = fs.map(f => f.properties && (f.properties.folio_origen || f.properties.id)).filter(Boolean); const dupe = ids.length - new Set(ids).size; add('Deduplicación', dupe ? 'warn' : 'ok', dupe ? dupe + ' identificadores repetidos' : 'Sin duplicados internos');
    if (geoms.some(g => g.type.includes('Polygon'))) { const pf = prepPolys({ features: fs.filter(f => f.geometry && f.geometry.type.includes('Polygon')) }); let tr = 0; S.predios.features.forEach(pr => { const c = pr.geometry.coordinates[0]; const cx = mx(c.reduce((a, p) => a + p[0], 0) / c.length), cy = my(c.reduce((a, p) => a + p[1], 0) / c.length); if (pf.some(f => cx >= f.bb[0] && cx <= f.bb[2] && cy >= f.bb[1] && cy <= f.bb[3])) tr++; }); add('Traslape con el padrón vigente', tr ? 'warn' : 'ok', tr ? `${tr} predios vigentes caen en la caja envolvente de la capa (revisar)` : 'Sin traslapes'); R.layer = { type: 'poly', fc: { type: 'FeatureCollection', features: fs.filter(f => f.geometry && f.geometry.type.includes('Polygon')) } }; }
    else if (ptsAll.length) R.layer = { type: 'pt', pts: ptsAll };
  } else if (isCsv) {
    const { h, rows, d } = parseCSV(await file.text()); R.records = rows.length; add('Formato CSV', rows.length ? 'ok' : 'fail', `${rows.length} filas · separador «${d}» · columnas: ${h.join(', ')}`); if (!rows.length) return R;
    const dt = DTYPES.find(x => x.k === type); const miss = dt.req.filter(r => !h.includes(r)); add('Campos obligatorios', miss.length ? 'fail' : 'ok', miss.length ? 'Faltan columnas: ' + miss.join(', ') : dt.req.length ? 'Presentes: ' + dt.req.join(', ') : 'Sin campos obligatorios');
    if (h.includes('lon') && h.includes('lat')) { let bad = 0, out = 0; const pts = []; rows.forEach(r => { const lo = parseFloat(String(r.lon).replace(',', '.')), la = parseFloat(String(r.lat).replace(',', '.')); if (isNaN(lo) || isNaN(la)) bad++; else { if (lo < MBB[0] || lo > MBB[2] || la < MBB[1] || la > MBB[3]) out++; else pts.push([lo, la]); } }); add('Coordenadas', bad ? 'fail' : out ? 'warn' : 'ok', bad ? `${bad} filas sin coordenadas numéricas` : out ? `${out} filas fuera de Michoacán (posible inversión lat/lon o CRS)` : 'Todas dentro de Michoacán'); R.layer = { type: 'pt', pts }; }
    if (h.includes('fecha')) { const bad = rows.filter(r => isNaN(new Date(r.fecha))).length; add('Fechas', bad ? 'warn' : 'ok', bad ? bad + ' fechas no interpretables (use AAAA-MM-DD)' : 'Todas interpretables'); }
    const seen = new Set(); let dup = 0; rows.forEach(r => { const k = JSON.stringify(r); if (seen.has(k)) dup++; seen.add(k); }); add('Deduplicación', dup ? 'warn' : 'ok', dup ? dup + ' filas idénticas' : 'Sin filas repetidas');
  } else if (isLas) { const b = await file.slice(0, 1200).arrayBuffer(); const L = parseLasHeader(b); add('Formato LAS/LAZ', L ? 'ok' : 'fail', L ? `LAS ${L.version} · PDRF ${L.pdrf} · ${fmt(L.count)} puntos · creado ${L.created || '?'}` : 'Encabezado LASF no reconocido'); if (L) { add('CRS', L.nVlr || L.wkt ? 'ok' : 'warn', L.nVlr ? 'VLR de proyección presente' : 'Sin VLR de CRS: se requiere declararlo'); R.records = L.count; } }
  else if (isTif) { const ok = (head[0] === 0x49 && head[1] === 0x49) || (head[0] === 0x4D && head[1] === 0x4D); add('Formato GeoTIFF', ok ? 'ok' : 'fail', ok ? 'Firma TIFF válida. La lectura de bandas, CRS y COG se hace en el procesador del servidor (GDAL).' : 'Firma TIFF no reconocida'); }
  else if (isGpkg) { const s = new TextDecoder().decode(await file.slice(0, 15).arrayBuffer()); add('Formato GeoPackage', s.startsWith('SQLite format') ? 'ok' : 'fail', 'Firma SQLite ' + (s.startsWith('SQLite format') ? 'válida. Capas y CRS se inspeccionan en el servidor.' : 'no reconocida')); }
  else if (isZip) add('Formato ZIP', head[0] === 0x50 && head[1] === 0x4B ? 'ok' : 'fail', head[0] === 0x50 ? 'Firma ZIP válida. El contenido (shapefile/GeoTIFF) se descomprime y valida en el servidor.' : 'No es un ZIP válido');
  else if (isImg) add('Formato imagen', 'ok', 'Imagen registrada; EXIF y georreferencia se validan al catalogar.');
  else add('Formato', 'warn', 'Extensión no reconocida: se conserva como anexo con su huella.');
  return R;
}

function ingesta(main) {
  const st = { type: 'predios', meta: { nombre: '', fuente: '', licencia: 'CC BY 4.0', corte: '', res: '', crs: 'WGS84 (EPSG:4326)', resp: '', notas: '' }, files: [], res: null };
  if (!S.datasets.length) S.datasets.push(
    { id: 'DS-001', name: 'Límites municipales de Michoacán (113)', type: 'referencia', src: 'geoBoundaries (CC BY 4.0)', ver: '1.0', n: 113, sha: 'real', date: '2026-09-28', state: 'Publicado', real: true },
    { id: 'DS-002', name: 'Ríos y lagos principales', type: 'referencia', src: 'Natural Earth (dominio público)', ver: '1.0', n: 7, sha: 'real', date: '2026-09-28', state: 'Publicado', real: true },
    { id: 'DS-003', name: 'Padrón piloto (predios de demostración)', type: 'predios', src: 'Generado para el prototipo', ver: '0.1', n: S.predios.features.length, sha: 'demo', date: '2026-09-29', state: 'Demostración', real: false },
    { id: 'DS-004', name: 'Alertas piloto', type: 'alertas', src: 'Generado para el prototipo', ver: '0.1', n: S.alertas.length, sha: 'demo', date: '2026-09-29', state: 'Demostración', real: false });
  main.innerHTML = hdr('Ingesta de datos históricos', 'Cargue información previa (padrones, alertas, series, LiDAR, expedientes). Cada carga pasa por validación automática, conserva su procedencia y su huella, se versiona y queda en la bitácora.', `<button class="btn" id="tpl">${icon('download', 15)} Descargar plantillas de ejemplo</button>`) +
    `<div class="steps" id="stp"></div><div id="sc"></div>
    <div class="card" style="margin-top:16px"><div class="ch"><h3>Catálogo de conjuntos de datos</h3></div><div class="tw" style="margin-top:8px"><table class="tbl" id="cat"></table></div></div>`;
  const stepsBar = n => { $('#stp', main).innerHTML = ['Tipo de conjunto', 'Procedencia', 'Archivos', 'Validación', 'Publicación'].map((s, i) => `<div class="${i < n ? 'done' : i === n ? 'now' : ''}"><b>PASO ${i + 1}</b>${s}</div>`).join(''); };
  const catalog = () => { $('#cat', main).innerHTML = `<thead><tr><th>ID</th><th>Conjunto</th><th>Tipo</th><th>Fuente</th><th>Versión</th><th class="num">Registros</th><th>Huella</th><th>Estado</th></tr></thead><tbody>${S.datasets.map(d => `<tr><td class="mono">${d.id}</td><td>${esc(d.name)}</td><td>${chip(d.type)}</td><td class="dim">${esc(d.src)}</td><td class="mono">${d.ver}</td><td class="num">${fmt(d.n)}</td><td class="hash">${d.sha.length > 20 ? shortHash(d.sha) : d.sha}</td><td>${d.real ? tag('real') : d.state === 'Demostración' ? tag('demo') : chip(d.state, 'ok')}</td></tr>`).join('')}</tbody>`; };
  const s0 = () => { stepsBar(0); $('#sc', main).innerHTML = `<div class="grid g3">${DTYPES.map(d => `<div class="card cl" data-t="${d.k}" style="cursor:pointer;${st.type === d.k ? 'border-color:#235B4E;background:rgba(35,91,78,.08)' : ''}"><b>${d.name}</b><p class="tiny dim" style="margin:6px 0">${d.desc}</p><div class="mono tiny">${d.ext}</div></div>`).join('')}</div><div style="margin-top:14px;text-align:right"><button class="btn pri" id="nx">Continuar →</button></div>`; };
  const s1 = () => { stepsBar(1); const m = st.meta; $('#sc', main).innerHTML = `<div class="card"><h3>Procedencia y metadatos (ISO 19115-1)</h3><div class="two" style="margin-top:10px"><label class="f">Nombre del conjunto<input id="m-nombre" value="${esc(m.nombre)}" placeholder="Padrón de huertas exportadoras 2019"></label><label class="f">Fuente / proveedor<input id="m-fuente" value="${esc(m.fuente)}" placeholder="SENASICA / Comité de Sanidad Vegetal"></label><label class="f">Licencia o condición de uso<select id="m-licencia">${['CC BY 4.0', 'Dominio público', 'Convenio de intercambio', 'Uso interno / reservado', 'Comercial con licencia'].map(x => `<option ${m.licencia === x ? 'selected' : ''}>${x}</option>`).join('')}</select></label><label class="f">Fecha de corte de la información<input id="m-corte" type="date" value="${m.corte}"></label><label class="f">Resolución / escala<input id="m-res" value="${esc(m.res)}" placeholder="30 m · 1:50 000 · 0.5 m"></label><label class="f">Sistema de coordenadas<input id="m-crs" value="${esc(m.crs)}"></label><label class="f">Responsable de la carga<input id="m-resp" value="${esc(m.resp)}" placeholder="Analista-07"></label><label class="f">Notas / limitaciones conocidas<input id="m-notas" value="${esc(m.notas)}"></label></div></div><div style="margin-top:14px;display:flex;justify-content:space-between"><button class="btn ghost" id="bk">← Atrás</button><button class="btn pri" id="nx">Continuar →</button></div>`; };
  const s2 = () => { stepsBar(2); const dt = DTYPES.find(d => d.k === st.type); $('#sc', main).innerHTML = `<div class="card"><h3>Archivos — ${dt.name}</h3><div class="drop" id="dz" style="margin-top:10px">Suelte aquí sus archivos (${dt.ext}) o haga clic<br><span class="tiny">Campos requeridos: ${dt.req.join(', ') || 'ninguno'} · la validación es local en su navegador</span><input type="file" id="fi" multiple hidden></div><div id="fl" class="tiny" style="margin-top:8px">${st.files.map(f => `<div class="mono">${esc(f.name)} <span class="dim">${fmt(f.size / 1024)} KB</span></div>`).join('')}</div></div><div style="margin-top:14px;display:flex;justify-content:space-between"><button class="btn ghost" id="bk">← Atrás</button><button class="btn pri" id="nx" ${st.files.length ? '' : 'disabled'}>Validar →</button></div>`; const dz = $('#dz', main), fi = $('#fi', main); dz.onclick = () => fi.click(); const add = fl => { st.files.push(...fl); s2(); }; fi.onchange = () => add([...fi.files]); ['dragover', 'dragenter'].forEach(ev => dz.addEventListener(ev, e => { e.preventDefault(); dz.classList.add('over'); })); ['dragleave', 'drop'].forEach(ev => dz.addEventListener(ev, e => { e.preventDefault(); dz.classList.remove('over'); })); dz.addEventListener('drop', e => add([...e.dataTransfer.files])); };
  const s3 = async () => { stepsBar(3); $('#sc', main).innerHTML = `<div class="card"><h3>Validación automática</h3><div id="vr" style="margin-top:8px"><div class="dim">Procesando…</div></div></div>`; const all = []; for (const f of st.files) all.push(await validateFile(f, st.type)); st.res = all; const worst = all.flatMap(r => r.steps).some(s => s.s === 'fail') ? 'fail' : all.flatMap(r => r.steps).some(s => s.s === 'warn') ? 'warn' : 'ok';
    $('#vr', main).innerHTML = all.map(r => `<div style="margin-bottom:14px"><b class="mono">${esc(r.name)}</b> <span class="dim tiny">${r.records != null ? fmt(r.records) + ' registros' : ''}</span>${r.steps.map(s => `<div class="chk"><span class="ic ${s.s}">${{ ok: '✓', warn: '!', fail: '✕' }[s.s]}</span><div><b>${esc(s.k)}</b><small>${esc(s.d)}</small></div></div>`).join('')}</div>`).join('') + `<div id="pv" class="card pad0" style="height:300px;margin-top:8px;display:${all.some(r => r.layer) ? 'block' : 'none'}"></div>` + (worst === 'fail' ? '<div class="note bad tiny">Hay fallas. Corrija los archivos y vuelva a cargarlos; no se puede publicar.</div>' : worst === 'warn' ? '<div class="note tiny">Hay observaciones. Puede pasar a <b>staging</b> y publicarla después de revisión humana.</div>' : '<div class="note info tiny">Validación sin observaciones.</div>');
    const lay = all.find(r => r.layer); if (lay) { const map = createMap($('#pv', main), { ids: new Set(), showAlerts: false, showLidar: false, showRest: false }); map.show('predios', false); map.show('alertas', false); map.show('lidar', false); map.show('rest', false); const tmp = { id: 'tmp', name: 'previa', visible: true, prep: lay.layer.type === 'poly' ? prepPolys(lay.layer.fc) : lay.layer.pts.map(p => ({ pt: [mx(p[0]), my(p[1])] })) }; S.userLayers.push(tmp); const xs = [], ys = []; if (lay.layer.type === 'poly') lay.layer.fc.features.forEach(f => (function w(c) { if (typeof c[0] === 'number') { xs.push(c[0]); ys.push(c[1]); } else c.forEach(w); })(f.geometry.coordinates)); else lay.layer.pts.forEach(p => { xs.push(p[0]); ys.push(p[1]); }); if (xs.length) map.fitBounds([Math.min(...xs), Math.min(...ys), Math.max(...xs), Math.max(...ys)], 50, false); main._pv = () => { map.destroy(); S.userLayers = S.userLayers.filter(l => l !== tmp); }; }
    $('#sc', main).insertAdjacentHTML('beforeend', `<div style="margin-top:14px;display:flex;justify-content:space-between"><button class="btn ghost" id="bk">← Atrás</button><button class="btn pri" id="nx" ${worst === 'fail' ? 'disabled' : ''}>Continuar →</button></div>`); };
  const s4 = () => { stepsBar(4); const recs = st.res.reduce((a, r) => a + (r.records || 0), 0); const nm = st.meta.nombre || st.files[0].name; const root = st.res.map(r => r.sha).join('').slice(0, 64);
    $('#sc', main).innerHTML = `<div class="card"><h3>Revisión y publicación versionada</h3><dl class="kv" style="margin-top:8px"><dt>Conjunto</dt><dd>${esc(nm)}</dd><dt>Tipo</dt><dd>${esc(DTYPES.find(d => d.k === st.type).name)}</dd><dt>Fuente</dt><dd>${esc(st.meta.fuente || '—')}</dd><dt>Licencia</dt><dd>${esc(st.meta.licencia)}</dd><dt>Fecha de corte</dt><dd>${st.meta.corte || '—'}</dd><dt>Archivos</dt><dd class="mono">${st.files.length}</dd><dt>Registros</dt><dd class="mono">${fmt(recs)}</dd><dt>Huellas SHA-256</dt><dd>${st.res.map(r => `<div class="hash">${r.sha}</div>`).join('')}</dd></dl><div class="note info tiny" style="margin-top:10px">Al publicar se crea la <b>versión 1.0</b>, se asocia la procedencia, se registra en la bitácora encadenada y, si tiene geometría, la capa aparece en el Mapa GIS. Las cargas posteriores del mismo conjunto crean nuevas versiones sin borrar las anteriores.</div></div><div style="margin-top:14px;display:flex;justify-content:space-between"><button class="btn ghost" id="bk">← Atrás</button><div style="display:flex;gap:8px"><button class="btn" id="stg">Guardar en staging</button><button class="btn ok" id="pub">${icon('check', 15)} Aprobar y publicar v1.0</button></div></div>`;
    const fin = pubd => { const id = 'DS-' + String(S.datasets.length + 1).padStart(3, '0'); S.datasets.push({ id, name: nm, type: st.type, src: st.meta.fuente || 'Carga manual', ver: pubd ? '1.0' : '0.9-staging', n: recs, sha: root, date: todayIso(), state: pubd ? 'Publicado' : 'Staging', real: false }); S.ingestLog.push({ id, nm }); if (pubd && st.type === 'owp' && st.files[0]) st.files[0].text().then(tx => { const P = parseCSV(tx); const ids = P.rows.map(r => { const c = String(r.cve_mun || r.clave || '').replace(/\D/g, ''); const n = String(r.municipio || r.nombre || '').toLowerCase(); return Object.keys(GF.mun).find(k => (c && (GF.mun[k].cve === c || GF.mun[k].cve.endsWith(c.slice(-3)))) || (n && GF.mun[k].n.toLowerCase() === n)); }).filter(Boolean); if (ids.length) { PARAMS.owp.municipios = [...new Set(ids)]; PARAMS.owp.demo = false; PARAMS.owp.estado = `Cargado por Ingesta (${id}): ${PARAMS.owp.municipios.length} municipios`; bump(); toast('Catálogo OWP aplicado a la geocerca: ' + PARAMS.owp.municipios.length + ' municipios'); } }); const lay = st.res.find(r => r.layer); if (lay && pubd) S.userLayers.push({ id, name: nm, visible: true, prep: lay.layer.type === 'poly' ? prepPolys(lay.layer.fc) : lay.layer.pts.map(p => ({ pt: [mx(p[0]), my(p[1])] })) }); ledgerAppend(S.ledger, st.meta.resp || 'Analista-07', pubd ? 'DATASET_INGESTADO' : 'DATASET_EN_STAGING', id); window.__refreshBadges(); toast(pubd ? 'Conjunto publicado como ' + id + ' v1.0' : 'Guardado en staging como ' + id); st.files = []; st.res = null; st.meta.nombre = ''; s0(); catalog(); };
    $('#stg', main).onclick = () => fin(false); $('#pub', main).onclick = () => fin(true); };
  const steps = [s0, s1, s2, s3, s4]; let cur = 0; const go = n => { if (main._pv) { main._pv(); main._pv = null; } cur = n; steps[n](); };
  on(main, 'click', '[data-t]', (e, c) => { st.type = c.dataset.t; s0(); }); on(main, 'click', '#nx', () => { if (cur === 1) { ['nombre', 'fuente', 'licencia', 'corte', 'res', 'crs', 'resp', 'notas'].forEach(k => st.meta[k] = $('#m-' + k, main).value); } go(cur + 1); }); on(main, 'click', '#bk', () => go(cur - 1));
  $('#tpl', main).onclick = () => {
    const ring = (cx, cy, r) => [[cx - r, cy - r * .8], [cx + r, cy - r * .8], [cx + r * 1.1, cy + r * .8], [cx - r, cy + r * .9], [cx - r, cy - r * .8]];
    const fc = { type: 'FeatureCollection', features: [0, 1, 2, 3, 4, 5].map(i => ({ type: 'Feature', properties: { folio_origen: 'SENASICA-2019-' + (1000 + i), anio: 2019, cultivo: 'Aguacate', fuente: 'Padrón 2019 (ejemplo)' }, geometry: { type: 'Polygon', coordinates: [ring(-102.0 + i * .006, 19.42 + (i % 2) * .004, .0018)] } })) };
    download('ejemplo_predios_historicos.geojson', JSON.stringify(fc, null, 1), 'application/geo+json');
    const rows = ['lon,lat,fecha,fuente,ha']; for (let i = 0; i < 30; i++) rows.push([(-102.05 + Math.sin(i * 2) * .06).toFixed(5), (19.4 + Math.cos(i * 3) * .05).toFixed(5), `2019-0${1 + (i % 9)}-${10 + (i % 15)}`, 'GLAD-L', (0.2 + (i % 7) * .3).toFixed(2)].join(','));
    setTimeout(() => download('ejemplo_alertas_historicas.csv', rows.join('\n'), 'text/csv'), 300); setTimeout(() => download('ejemplo_expedientes.csv', 'expediente,fecha,autoridad,municipio,estado\nPROFEPA/2019/0412,2019-06-11,PROFEPA,Tancítaro,Resuelto\nFGE/2020/0088,2020-02-03,Fiscalía,Peribán,En trámite\n', 'text/csv'), 600); toast('Se descargaron 3 archivos de ejemplo para probar la ingesta'); };
  s0(); catalog(); return () => { if (main._pv) main._pv(); };
}

// ---------- Fuentes y monitoreo ----------
function fuentes(main) {
  let fc = '', fp = '', fe = ''; const E = { real: ['Cargada (real)', 'ok'], demo: ['Simulada', 'warn'], conectar: ['Conector por construir', 'info'], convenio: ['Requiere convenio', 'vio'], contratar: ['Por contratar', 'bad'], propia: ['Captura propia', 'ok'] };
  const cnt = k => SOURCES.filter(s => s.pri === k).length;
  main.innerHTML = hdr('Fuentes de datos y monitoreo', 'Qué datos conseguir, en qué orden y con qué frecuencia refrescarlos para que la plataforma esté nutrida y pueda monitorear. En este prototipo sólo la geografía de referencia y las cifras de contexto son datos reales.', `<button class="btn" id="csv">${icon('download', 15)} Exportar plan (CSV)</button>`) +
    `<div class="grid g4">${kpi({ l: 'Fuentes catalogadas', v: SOURCES.length, s: '9 categorías' })}${kpi({ l: 'P0 · arranque (0-3 meses)', v: cnt('P0'), s: 'imprescindibles', c: '#B3261E' })}${kpi({ l: 'P1 · piloto (3-9 meses)', v: cnt('P1'), s: 'profundizan el análisis', c: '#A8720F' })}${kpi({ l: 'Requieren convenio', v: SOURCES.filter(s => s.estado === 'convenio').length, s: 'gestión institucional', c: '#9F2241' })}</div>
    <div class="card" style="margin-top:14px"><h3>Ritmo de monitoreo recomendado</h3><div class="grid g4" style="margin-top:10px">${[['Diario a semanal', 'Alertas integradas GFW, FIRMS, denuncias ciudadanas, Guardián Forestal (API)', '#B3261E'], ['Cada 5-12 días', 'Sentinel-2 / HLS, Sentinel-1 y NISAR: series por predio y detección propia', '#A8720F'], ['Mensual a trimestral', 'Autorizaciones SEMARNAT, expedientes PROFEPA/Fiscalía, REPDA, padrón de empacadoras', '#235B4E'], ['Anual o por evento', 'Hansen, INEGI (uso de suelo, ortofotos, marco geoestadístico), CONANP, LiDAR nivel A, imágenes VHR', '#2E7D32']].map(x => `<div style="border-left:3px solid ${x[2]};padding-left:10px"><b>${x[0]}</b><div class="tiny dim" style="margin-top:3px">${x[1]}</div></div>`).join('')}</div></div>
    <div class="split-h" style="margin-top:14px"><select id="fc"><option value="">Todas las categorías</option>${CATS.map((c, i) => `<option value="${i}">${c}</option>`).join('')}</select><select id="fp"><option value="">Toda prioridad</option><option>P0</option><option>P1</option><option>P2</option></select><select id="fe"><option value="">Todo estado</option>${Object.entries(E).map(([k, v]) => `<option value="${k}">${v[0]}</option>`).join('')}</select><span class="tiny dim" id="ct"></span></div><div class="tw"><table class="tbl" id="tb"></table></div>`;
  const draw = () => { const l = SOURCES.filter(s => (fc === '' || s.cat === +fc) && (!fp || s.pri === fp) && (!fe || s.estado === fe)); $('#ct', main).textContent = l.length + ' fuentes'; $('#tb', main).innerHTML = `<thead><tr><th>Pri.</th><th>Fuente</th><th>Producto</th><th>Uso en el programa</th><th>Acceso</th><th>Cadencia</th><th>Formato</th><th>Estado</th></tr></thead><tbody>${l.map(s => `<tr><td><span class="chip ${s.pri === 'P0' ? 'bad' : s.pri === 'P1' ? 'warn' : ''}">${s.pri}</span></td><td><b>${esc(s.src)}</b><div class="tiny dim">${CATS[s.cat]}</div></td><td class="dim">${esc(s.prod)}</td><td>${esc(s.uso)}${s.nota ? `<div class="tiny dim" style="margin-top:3px">${esc(s.nota)}</div>` : ''}</td><td>${esc(s.acc)}</td><td class="nowrap">${esc(s.cad)}</td><td class="mono tiny">${esc(s.fmt)}</td><td>${chip(E[s.estado][0], E[s.estado][1])}</td></tr>`).join('')}</tbody>`; }; draw();
  main.addEventListener('change', e => { const t = e.target; if (t.id === 'fc') fc = t.value; if (t.id === 'fp') fp = t.value; if (t.id === 'fe') fe = t.value; if (['fc', 'fp', 'fe'].includes(t.id)) draw(); });
  $('#csv', main).onclick = () => download('plan_fuentes_de_datos.csv', '﻿Prioridad,Categoria,Fuente,Producto,Uso,Acceso,Cadencia,Formato,Estado,Nota\n' + SOURCES.map(s => [s.pri, CATS[s.cat], s.src, s.prod, s.uso, s.acc, s.cad, s.fmt, E[s.estado][0], s.nota].map(x => JSON.stringify(x)).join(',')).join('\n'), 'text/csv');
}

// ---------- Bitácora ----------
function bitacora(main) {
  let backup = null; main.innerHTML = hdr('Bitácora de auditoría', 'Registro encadenado e inalterable: cada evento incluye el hash del anterior. Si alguien modifica un registro, la cadena se rompe y el sistema lo detecta.', `<button class="btn pri" id="vf">${icon('shield', 15)} Verificar cadena</button> <button class="btn" id="tp">Simular alteración</button> <button class="btn ghost" id="rs" style="display:none">Restaurar</button> <button class="btn ghost" id="ex">${icon('download', 14)} Exportar JSON</button>`) + `<div id="bn"></div><div class="tw" style="max-height:calc(100vh - 300px)"><table class="tbl" id="tb"></table></div>`;
  const draw = (badSeq) => { $('#tb', main).innerHTML = `<thead><tr><th class="num">#</th><th>Fecha</th><th>Actor</th><th>Acción</th><th>Objeto</th><th>Hash previo</th><th>Hash del registro</th></tr></thead><tbody>${S.ledger.slice().reverse().map(e => `<tr style="${badSeq && e.seq >= badSeq ? 'background:' + (e.seq === badSeq ? 'rgba(179,38,30,.08)' : 'rgba(179,38,30,.04)') : ''}"><td class="num">${e.seq}</td><td class="mono tiny">${ftime(e.ts)}</td><td>${esc(e.actor)}</td><td><b class="tiny">${esc(e.acc)}</b></td><td class="mono tiny">${esc(e.obj)}</td><td class="hash">${shortHash(e.prev)}</td><td class="hash">${shortHash(e.hash)}</td></tr>`).join('')}</tbody>`; };
  const verify = () => { const r = ledgerVerify(S.ledger); $('#bn', main).innerHTML = r.ok ? `<div class="verdict ok" style="margin-bottom:12px"><div style="font-size:26px">🛡</div><div><div class="big">Cadena íntegra</div><div class="tiny dim">${r.n} registros verificados · cabeza <span class="hash">${r.head}</span></div></div></div>` : `<div class="verdict fail" style="margin-bottom:12px"><div style="font-size:26px">⛔</div><div><div class="big">Cadena rota en el registro #${r.seq}</div><div class="tiny dim">${r.why}. Todos los registros posteriores pierden validez hasta su investigación.</div></div></div>`; draw(r.ok ? 0 : r.seq); };
  verify();
  $('#vf', main).onclick = () => { verify(); toast('Verificación completada'); };
  $('#tp', main).onclick = () => { const i = Math.floor(S.ledger.length / 2); backup = { i, actor: S.ledger[i].actor }; S.ledger[i].actor = 'Usuario-NoAutorizado'; $('#rs', main).style.display = ''; verify(); toast('Se modificó en memoria el actor del registro #' + S.ledger[i].seq + '. Verifique de nuevo.', 'warn'); };
  $('#rs', main).onclick = () => { if (backup) S.ledger[backup.i].actor = backup.actor; backup = null; $('#rs', main).style.display = 'none'; verify(); };
  $('#ex', main).onclick = () => download('bitacora_dosel.json', JSON.stringify(S.ledger, null, 1), 'application/json');
}
function _vizHook(main) { main.addEventListener('click', e => { if (e.target.closest('[data-viz]')) window.__go('admin', 'visor'); }); }
export const views = { semaforo, restauracion, indicadores, lidar, ingesta, fuentes, bitacora };
