import { $, $$, on, esc, fmt, fdate, ftime, CLS, badge, chip, toast, download, TODAY } from '../util.js';
import { S, ST, G, P, munName, prediosById, alertaById, estudioById, refresh, monthly } from '../state.js';
import * as ch from '../charts.js';
import { kpi, tag, icon, stars, projChip, predioFicha, modal, estadoChip, conChip, forestChart, varsBars, beforeAfter } from '../ui.js';
import { createMap, attachControls, locate, AL_COLOR } from '../mapkit.js';
import { mapPage } from './mapPage.js';
import { evaluate, VARS, CAUSALES, VERSION } from '../semaforo.js';
import { renderChecks, verdict, verdictBox } from '../verify.js';
import { ledgerAppend, shortHash } from '../integrity.js';
import { SOURCES } from '../sources.js';

const hdr = (t, p, act = '') => `<div class="page-h"><div><h1>${t}</h1>${p ? `<p>${p}</p>` : ''}</div><div class="act">${act}</div></div>`;
const ageDays = a => Math.round((TODAY - new Date(a.d)) / 864e5);
const OPEN = ['Detectada', 'En validación'];
const stChip = s => `<span class="chip" style="border-color:${AL_COLOR[s]}55;color:${AL_COLOR[s]}">${s}</span>`;

// ---------- Simulador / emisor de clasificación (reutilizable) ----------
export function simulator(host, init = {}) {
  const st = { poligono: init.poligono ?? true, perdida: init.perdida ?? true, validada: init.validada ?? true, v: init.v ? init.v.slice() : [12, 9, 9, 9, 6, 6, 6, 3], causales: new Set(init.causales || []) };
  host.innerHTML = `<div class="two"><div><div class="grid" style="gap:6px;margin-bottom:10px"><label style="display:flex;gap:8px;align-items:center"><input type="checkbox" id="s-pol" ${st.poligono ? 'checked' : ''}> Polígono validado</label><label style="display:flex;gap:8px;align-items:center"><input type="checkbox" id="s-per" ${st.perdida ? 'checked' : ''}> Pérdida de cobertura detectada</label><label style="display:flex;gap:8px;align-items:center"><input type="checkbox" id="s-val" ${st.validada ? 'checked' : ''}> Validación humana con imagen de alta resolución</label></div>
    ${VARS.map((v, i) => `<div style="margin-bottom:6px"><div style="display:flex;justify-content:space-between;font-size:12px"><span title="${esc(v.hint)}">${v.k} · ${esc(v.name)}</span><span class="mono" id="sv${i}">${st.v[i]}/${v.max}</span></div><input type="range" min="0" max="${v.max}" value="${st.v[i]}" data-i="${i}"></div>`).join('')}
    <h3 style="margin:10px 0 4px">Causales determinantes</h3>${CAUSALES.map((c, i) => `<label style="display:flex;gap:8px;font-size:12.5px;padding:2px 0"><input type="checkbox" data-c="${i}" ${st.causales.has(c) ? 'checked' : ''}>${esc(c)}</label>`).join('')}</div>
    <div id="sim-out"></div></div>`;
  const out = $('#sim-out', host); let last;
  const calc = () => { const r = evaluate({ poligono: st.poligono, perdida: st.perdida, validada: st.validada, v: st.v, causales: [...st.causales] }); last = r; const c = CLS[r.cls];
    out.innerHTML = `<div class="verdict" style="border-color:${c.color}66;background:${c.color}14"><span class="lamp" style="width:34px;height:34px;border-radius:50%;background:${c.color};box-shadow:0 0 22px ${c.color};flex:none"></span><div><div class="big" style="color:${c.color}">${c.name}${r.nivel ? ' · ' + r.nivel : ''}</div><div class="tiny dim">${c.desc}</div></div></div>
    ${r.idx != null ? `<div style="margin:12px 0 4px;display:flex;align-items:center;gap:12px">${ch.gauge(r.idx, 100, r.idx >= 75 ? '#2E7D32' : r.idx >= 50 ? '#A8720F' : '#B3261E', 'Reversibilidad')}<div class="tiny dim">Umbrales: <b>&lt; 50</b> rojo · <b>50-74</b> naranja N2 · <b>≥ 75</b> naranja N1. Una causal determinante fuerza rojo.</div></div>` : ''}
    <h3 style="margin:10px 0 6px">Ruta de decisión</h3><ol class="tiny" style="margin:0;padding-left:18px;line-height:1.7;color:#45544F">${r.route.map(x => `<li>${esc(x)}</li>`).join('')}</ol>
    <div class="note info tiny" style="margin-top:10px"><b>Efectos:</b> ${esc(r.efectos)}</div><div class="tiny dim" style="margin-top:8px">Versión del algoritmo: <span class="mono">${VERSION}</span> · sujeto a auditoría académica y calibración con campo antes de producir efectos jurídicos.</div>`; host.dispatchEvent(new CustomEvent('sim', { detail: { st, r } })); };
  host.addEventListener('input', e => { const t = e.target; if (t.dataset.i != null) { st.v[+t.dataset.i] = +t.value; $('#sv' + t.dataset.i, host).textContent = t.value + '/' + VARS[+t.dataset.i].max; } calc(); });
  host.addEventListener('change', e => { const t = e.target; if (t.id === 's-pol') st.poligono = t.checked; if (t.id === 's-per') st.perdida = t.checked; if (t.id === 's-val') st.validada = t.checked; if (t.dataset.c != null) { const c = CAUSALES[+t.dataset.c]; t.checked ? st.causales.add(c) : st.causales.delete(c); } calc(); });
  calc(); return { get: () => ({ st, r: last }) };
}

// ---------- Centro de mando ----------
function centro(main) {
  const al = S.alertas.filter(a => OPEN.includes(a.st)).sort((a, b) => a.d.localeCompare(b.d)); const mm = monthly(); const lidRej = S.estudios.filter(e => e.ver !== 'Íntegro');
  const top = Object.values(ST.perMun).filter(m => m.n).sort((a, b) => (b.rojo + b.naranja) - (a.rojo + a.naranja)).slice(0, 9);
  const funnel = ['Detectada', 'En validación', 'Confirmada', 'Notificada', 'En audiencia', 'Firme', 'Descartada'].map(s => ({ label: s, value: S.alertas.filter(a => a.st === s).length, color: AL_COLOR[s] }));
  const stI = { ok: S.estudios.filter(e => e.ver === 'Íntegro').length, w: S.estudios.filter(e => e.ver === 'Con observaciones').length, f: S.estudios.filter(e => e.ver === 'Rechazado').length };
  main.innerHTML = hdr('Centro de mando', 'Estado operativo del monitoreo forestal: alertas por validar, clasificaciones, integridad de estudios y actividad del sistema.', `<span class="chip ok"><span class="pulse"></span>Monitoreo activo</span>`) +
    `<div class="grid g5">${kpi({ l: 'Alertas por validar', v: ST.open, s: 'mediana 6 días hábiles', c: '#A8720F', sp: ch.spark(mm.slice(-8).map(x => x[1]), '#A8720F') })}${kpi({ l: 'Alertas 7 días', v: ST.a7, s: ST.a30 + ' en 30 días', c: '#235B4E' })}${kpi({ l: 'Predios rojos', v: ST.cnt.rojo, s: fmt(S.predios.features.filter(f => f.properties.cls === 'rojo').reduce((a, f) => a + (f.properties.aff || 0), 0), 0) + ' ha afectadas', c: '#B3261E' })}${kpi({ l: 'Estudios con observación', v: lidRej.length, s: stI.f + ' rechazados por integridad', c: '#A8720F' })}${kpi({ l: 'Padrón validado', v: fmt(ST.validated * 100, 0) + ' %', s: ST.cnt.gris + ' en gris', c: '#2E7D32' })}</div>
  <div class="grid g21" style="margin-top:14px"><div class="card pad0" style="height:440px;position:relative"><div id="cm" style="height:100%"></div></div>
    <div class="card" style="max-height:440px;overflow:auto"><div class="ch"><h3>Cola prioritaria</h3><div class="sp"><button class="btn sm" data-go="alertas">Ver todas</button></div></div>${al.slice(0, 9).map(a => `<div class="cl" data-al="${a.id}" style="padding:8px 0;border-bottom:1px solid rgba(111,124,119,.22);cursor:pointer"><div style="display:flex;gap:8px;align-items:center"><i class="dot" style="background:${AL_COLOR[a.st]}"></i><span class="mono tiny">${a.id}</span><span class="tiny dim" style="margin-left:auto">${ageDays(a)} d</span></div><div class="tiny" style="margin-top:2px">${esc(munName[a.mun])} · ${fmt(a.ha, 2)} ha · <span class="dim">${esc(a.src)}</span></div></div>`).join('')}</div></div>
  <div class="grid g3" style="margin-top:14px"><div class="card"><div class="ch"><h3>Semáforo por municipio</h3></div>${ch.hstack(top.map(m => ({ label: munName[m.id], parts: [{ v: m.verde, color: CLS.verde.color, name: 'Verde' }, { v: m.amarillo, color: CLS.amarillo.color, name: 'Amarillo' }, { v: m.naranja, color: CLS.naranja.color, name: 'Naranja' }, { v: m.rojo, color: CLS.rojo.color, name: 'Rojo' }, { v: m.gris, color: CLS.gris.color, name: 'Gris' }] })), { rh: 26 })}</div>
    <div class="card"><div class="ch"><h3>Embudo de alertas</h3></div>${ch.bars(funnel, { h: 230, rot: true })}</div>
    <div class="card"><div class="ch"><h3>Integridad de levantamientos</h3></div><div style="display:flex;gap:14px;align-items:center"><div style="width:120px">${ch.donut([{ name: 'Íntegro', v: stI.ok, color: '#2E7D32' }, { name: 'Con observaciones', v: stI.w, color: '#A8720F' }, { name: 'Rechazado', v: stI.f, color: '#B3261E' }], { s: 120, sub: 'estudios' })}</div><div class="tiny" style="line-height:1.9"><div>${chip('Íntegro ' + stI.ok, 'ok')}</div><div>${chip('Con observaciones ' + stI.w, 'warn')}</div><div>${chip('Rechazado ' + stI.f, 'bad')}</div></div></div>${lidRej.slice(0, 3).map(e => `<div class="cl tiny" data-lid="${e.id}" style="padding:6px 0;border-top:1px solid rgba(111,124,119,.22);cursor:pointer"><span class="mono">${e.id}</span> ${estadoChip(e.ver)}<div class="dim">${esc((e.checks.find(c => c.s !== 'ok') || {}).det || '')}</div></div>`).join('')}</div></div>
  <div class="grid g2" style="margin-top:14px"><div class="card"><div class="ch"><h3>Actividad reciente (bitácora encadenada)</h3><div class="sp"><button class="btn sm" data-go="bitacora">Abrir</button></div></div>${S.ledger.slice(-6).reverse().map(e => `<div style="padding:6px 0;border-bottom:1px solid rgba(111,124,119,.22);display:flex;gap:10px" class="tiny"><span class="mono dim">${ftime(e.ts)}</span><span>${esc(e.actor)} · <b>${esc(e.acc)}</b> · <span class="mono">${esc(e.obj)}</span></span><span class="hash" style="margin-left:auto">${shortHash(e.hash)}</span></div>`).join('')}</div>
    <div class="card"><div class="ch"><h3>Frescura de las fuentes</h3><div class="sp"><button class="btn sm" data-go="fuentes">Plan de fuentes</button></div></div>${[['Alertas integradas GFW (GLAD/RADD/DIST)', 'hace 5 h', 'ok'], ['Sentinel-2 L2A', 'hace 1 d', 'ok'], ['NASA FIRMS (focos de calor)', 'hace 3 h', 'ok'], ['Guardián Forestal (API)', 'sin conexión (por convenio)', 'warn'], ['Hansen GFC v1.13', 'anual · vigente', 'ok'], ['SEMARNAT autorizaciones', 'sin conexión (por convenio)', 'warn']].map(r => `<div style="display:flex;gap:10px;padding:7px 0;border-bottom:1px solid rgba(111,124,119,.22);font-size:12.5px"><i class="dot" style="background:${r[2] === 'ok' ? '#2E7D32' : '#A8720F'}"></i><span>${r[0]}</span><span class="dim" style="margin-left:auto">${r[1]}</span></div>`).join('')}<div class="tiny dim" style="margin-top:6px">${tag('demo')} Estado de conectores simulado.</div></div></div>`;
  on(main, 'click', '[data-go]', (e, b) => window.__go('admin', b.dataset.go)); on(main, 'click', '[data-al]', (e, b) => window.__go('admin', 'alertas', { id: b.dataset.al })); on(main, 'click', '[data-lid]', (e, b) => window.__go('admin', 'lidar', { id: b.dataset.lid }));
  const map = createMap($('#cm', main), { heat: true, showLidar: false, showRest: false, z: 7.4 }); map.show('lidar', false); map.show('rest', false); map.show('heat', true); map.setFilters({ alStates: new Set(OPEN.concat(['Confirmada'])) }); map.fitBounds([-102.9, 19.0, -101.0, 19.9], 20, false); attachControls($('#cm', main).parentElement, map, { sat: true });
  map.on('click', ({ hit }) => { if (hit && hit.layer === 'alertas') window.__go('admin', 'alertas', { id: hit.p.id }); else if (hit && hit.layer === 'predios') window.__go('admin', 'padron', { id: hit.p.id }); });
  return () => map.destroy();
}

// ---------- Expediente de predio (drawer) ----------
export function expediente(host, id, onClose) {
  const f = prediosById[id]; if (!f) return; const p = f.properties; const est = S.estudios.filter(e => e.pid === id); const proy = S.proyectos.filter(r => r.pid === id); const al = S.alertas.filter(a => a.pid === id);
  const d = document.createElement('div'); d.className = 'drawer';
  d.innerHTML = `<div class="ch" style="margin-bottom:10px"><h2 class="mono">${p.id}</h2>${badge(p.cls)}<div class="sp"><button class="btn sm ghost" id="dx">✕ Cerrar</button></div></div>
  <div class="tabs" id="tb">${['Resumen', 'Historial', 'Semáforo', 'LiDAR', 'Restauración', 'Trazabilidad'].map((t, i) => `<button data-t="${i}" class="${i ? '' : 'on'}">${t}</button>`).join('')}</div><div id="tc"></div>`;
  host.appendChild(d);
  const T = [
    () => `<div class="card pad0" style="height:200px;margin-bottom:12px"><div id="dmap" style="height:100%"></div></div><dl class="kv"><dt>Productor</dt><dd class="mono">${p.prd}</dd><dt>Municipio</dt><dd>${esc(munName[p.mun])}</dd><dt>Superficie</dt><dd class="mono">${fmt(p.ha, 1)} ha</dd><dt>Cultivo</dt><dd>${esc(p.cul)}</dd><dt>Tenencia</dt><dd>${esc(p.ten)}${p.ten !== 'Pequeña propiedad' ? ' <span class="chip info">Competencia federal (PROFEPA)</span>' : ' <span class="chip info">Competencia estatal (Fiscalía)</span>'}</dd><dt>Constancia</dt><dd>${conChip(p.con)}</dd><dt>Situación</dt><dd>${esc(p.est)}</dd>${p.aff ? `<dt>Superficie afectada</dt><dd class="mono">${fmt(p.aff, 1)} ha (${p.ly})</dd><dt>Detección</dt><dd>${esc(p.det || '—')}</dd>` : ''}<dt>Estudios LiDAR</dt><dd>${est.length}</dd><dt>Proyectos de restauración</dt><dd>${proy.length}</dd><dt>Alertas</dt><dd>${al.length}</dd></dl><div style="margin-top:14px;display:flex;gap:8px;flex-wrap:wrap"><button class="btn sm" data-a="lidar">Solicitar estudio LiDAR</button><button class="btn sm" data-a="hist">Emitir Historial Forestal</button><button class="btn sm" data-a="maps">Ver en mapa GIS</button></div>`,
    () => `<h3>Cobertura arbórea 1993-2025 ${tag('demo')}</h3>${forestChart(p, 520, 220)}<h3 style="margin-top:14px">Antes / después ${tag('demo')}</h3><div id="ba"></div><div class="tiny dim" style="margin-top:6px">Arrastre el control. La validación humana se hace con imágenes de 0.3-0.5 m; aquí se muestra una escena ilustrativa.</div><h3 style="margin-top:14px">Alertas</h3>${al.length ? al.map(a => `<div class="tiny" style="padding:4px 0"><span class="mono dim">${fdate(a.d)}</span> · ${stChip(a.st)} · ${esc(a.src)}</div>`).join('') : '<div class="dim tiny">Sin alertas.</div>'}`,
    () => `<div class="two"><div><h3>Clasificación vigente</h3><div style="margin:8px 0">${badge(p.cls)} ${p.niv ? chip(p.niv, 'info') : ''}</div><div class="tiny dim">${CLS[p.cls].desc}</div>${p.cau ? `<div class="note bad tiny" style="margin-top:8px"><b>Causal:</b> ${esc(p.cau)}</div>` : ''}<h3 style="margin:14px 0 6px">Variables del Índice</h3>${varsBars(p)}</div><div><h3>Ruta de decisión (motor ${VERSION})</h3>${(() => { const r = evaluate({ poligono: p.cls !== 'gris', perdida: ['amarillo', 'naranja', 'rojo'].includes(p.cls), validada: ['naranja', 'rojo'].includes(p.cls), v: p.v || [0, 0, 0, 0, 0, 0, 0, 0], causales: p.cau ? [p.cau] : [] }); return `<ol class="tiny" style="padding-left:18px;line-height:1.7;color:#45544F">${r.route.map(x => `<li>${esc(x)}</li>`).join('')}</ol><div class="note info tiny"><b>Efectos:</b> ${esc(r.efectos)}</div>`; })()}<button class="btn sm" style="margin-top:12px" data-a="sim">Abrir en simulador</button></div></div>`,
    () => est.length ? est.map(e => `<div class="card" style="margin-bottom:10px"><div class="ch"><b class="mono">${e.id}</b>${estadoChip(e.ver)}<div class="sp"><button class="btn sm" data-lid="${e.id}">Verificación completa</button></div></div><div class="tiny dim" style="margin-top:6px">${fdate(e.fecha)} · ${esc(e.aero.modelo)} + ${esc(e.sensor.modelo)} · ${e.dens} pts/m² · ${e.area} ha</div><div class="tiny" style="margin-top:6px">${(e.checks.find(c => c.s === 'fail') || e.checks.find(c => c.s === 'warn') || { det: 'Sin observaciones.' }).det}</div></div>`).join('') : `<div class="note tiny">Este predio no tiene levantamiento. ${['naranja', 'rojo', 'verde'].includes(p.cls) ? 'Se requiere para la constancia o para medir la línea base de restauración.' : ''}</div><button class="btn pri sm" style="margin-top:10px" data-a="lidar">Solicitar estudio LiDAR</button>`,
    () => proy.length ? proy.map(r => `<div class="card" style="margin-bottom:10px"><div class="ch"><b class="mono">${r.id}</b>${projChip(r.st)}</div><p style="margin:6px 0">${esc(r.tipo)} · ${fmt(r.ha, 1)} ha</p><div class="tiny dim">Especies: ${r.esp.map(esc).join(', ')}</div><div class="tiny" style="margin-top:6px">Plantas: <b class="mono">${fmt(r.plant)}</b> · Supervivencia: <b class="mono">${r.surv ? r.surv + ' %' : '—'}</b> · ${stars(r.stars)}</div></div>`).join('') : '<div class="dim">Sin proyectos de restauración.</div>',
    () => { const rel = S.ledger.filter(e => e.obj === id || al.find(a => a.id === e.obj) || est.find(x => x.id === e.obj)); return `<div class="timeline">${(rel.length ? rel : S.ledger.slice(-3)).map(e => `<div class="done"><b class="tiny">${esc(e.acc)}</b> <span class="dim tiny">· ${esc(e.actor)}</span><div class="mono tiny dim">${ftime(e.ts)}</div><div class="hash">${e.hash}</div></div>`).join('')}</div><div class="tiny dim">Cada registro incluye el hash del anterior: alterar cualquier evento rompe la cadena.</div>`; }];
  const tc = $('#tc', d); const showT = i => { tc.innerHTML = T[i](); $$('#tb button', d).forEach(b => b.classList.toggle('on', +b.dataset.t === i));
    if (i === 0) { const m = createMap($('#dmap', d), { ids: new Set([id]), showAlerts: false, showLidar: false, showRest: false }); m.show('mun', true); locate(m, id); d._map = m; } else if (d._map) { d._map.destroy(); d._map = null; }
    if (i === 1) beforeAfter($('#ba', d), p); };
  showT(0);
  on(d, 'click', '#tb button', (e, b) => showT(+b.dataset.t));
  const close = () => { if (d._map) d._map.destroy(); d.remove(); onClose && onClose(); }; $('#dx', d).onclick = close;
  on(d, 'click', '[data-a]', (e, b) => { const a = b.dataset.a; if (a === 'lidar') { ledgerAppend(S.ledger, 'Dictaminador-03', 'ESTUDIO_SOLICITADO', id); toast('Solicitud de estudio LiDAR nivel B notificada al productor'); } if (a === 'hist') { ledgerAppend(S.ledger, 'Dictaminador-03', 'HISTORIAL_EMITIDO', id); toast('Historial Forestal emitido y registrado'); } if (a === 'maps') { window.__go('admin', 'gis', { id }); } if (a === 'sim') { window.__go('admin', 'semaforo', { id }); } });
  on(d, 'click', '[data-lid]', (e, b) => window.__go('admin', 'lidar', { id: b.dataset.lid }));
  return d;
}

// ---------- Mapa GIS ----------
function gis(main, params) {
  const adminFicha = id => predioFicha(id, 'admin') + `<div class="sec"><h3>Variables del Índice</h3>${varsBars(prediosById[id].properties)}</div>`;
  const alertPanel = a => `<div class="ch"><h2 class="mono">${a.id}</h2><div class="sp">${stChip(a.st)}</div></div><dl class="kv" style="margin-top:8px"><dt>Fecha de detección</dt><dd>${fdate(a.d)}</dd><dt>Fuente</dt><dd>${esc(a.src)}</dd><dt>Confianza</dt><dd>${esc(a.conf)}</dd><dt>Superficie</dt><dd class="mono">${fmt(a.ha, 2)} ha</dd><dt>Municipio</dt><dd>${esc(munName[a.mun])}</dd><dt>Predio</dt><dd class="mono">${a.pid || 'Fuera del padrón'}</dd></dl><div style="margin-top:14px;display:flex;gap:8px"><button class="btn sm ghost" id="sb-back">← Volver</button><button class="btn sm pri" id="sb-al">Ir a validación</button></div>`;
  const m = mapPage(main, { level: 'admin', focus: params && params.id, adminFicha, alertPanel,
    areaPanel: a => `<div class="ch"><h2>Análisis de área</h2></div><div class="kpi card" style="margin:10px 0"><div class="l">Superficie dibujada</div><div class="v">${fmt(a.area, 1)} ha</div></div><dl class="kv"><dt>Predios dentro</dt><dd class="mono">${a.n}</dd><dt>Superficie de predios</dt><dd class="mono">${fmt(a.ha, 1)} ha</dd><dt>Verde / Amarillo</dt><dd class="mono">${a.by.verde} / ${a.by.amarillo}</dd><dt>Naranja / Rojo</dt><dd class="mono">${a.by.naranja} / ${a.by.rojo}</dd><dt>Sin información (gris)</dt><dd class="mono">${a.by.gris}</dd><dt>Superficie afectada</dt><dd class="mono">${fmt(a.aff, 1)} ha</dd><dt>Alertas en el área</dt><dd class="mono">${a.alertas} (${a.abiertas} abiertas)</dd></dl><div style="margin-top:12px;display:flex;gap:8px;flex-wrap:wrap"><button class="btn sm ghost" id="sb-back">← Volver</button><button class="btn sm" id="sb-filter">Filtrar mapa al área</button><button class="btn sm" id="sb-exp">Exportar predios (CSV)</button></div>`,
    sideHome: () => `<h2>Mapa GIS de operación</h2><p class="dim tiny" style="margin:6px 0 12px">Herramientas de análisis espacial sobre el padrón, las alertas y los levantamientos.</p><div class="grid" style="gap:8px"><button class="btn" id="sb-draw">⬠ Dibujar área de análisis</button><button class="btn ghost" id="sb-clear">Quitar filtros de área</button></div><div class="sec"><h3>Resumen visible</h3><dl class="kv" style="margin-top:6px"><dt>Alertas abiertas</dt><dd class="mono">${ST.open}</dd><dt>Predios rojos</dt><dd class="mono">${ST.cnt.rojo}</dd><dt>Levantamientos</dt><dd class="mono">${S.estudios.length}</dd></dl></div><div class="note tiny" style="margin-top:12px"><b>Consejo:</b> use el candado de colores para ver primero los predios rojos y naranjas; el mapa de calor muestra dónde se concentran las alertas.</div><div class="sec"><h3>Simbología</h3><div class="tiny" style="line-height:2"><span style="color:#235B4E">◆</span> Levantamiento íntegro · <span style="color:#A8720F">◆</span> con observación · <span style="color:#B3261E">◆</span> rechazado<br><span style="color:#2E7D32">▲</span> Proyecto de restauración<br><span style="color:#235B4E">●</span> alerta detectada · <span style="color:#A8720F">●</span> en validación · <span style="color:#A8720F">●</span> confirmada</div></div>` });
  const side = m.side; side.addEventListener('click', e => { if (e.target.id === 'sb-al') { const id = $('.ch h2', side).textContent; window.__go('admin', 'alertas', { id }); } if (e.target.id === 'sb-clear') { m.map.setFilters({ ids: null }); m.map.clearDrawn(); toast('Filtro de área retirado'); } if (e.target.id === 'sb-exp') { const a = window.__lastArea; } });
  m.map.on('draw', ring => { import('../mapkit.js').then(k => { const a = k.areaStats(ring); window.__lastArea = a; setTimeout(() => { const b = $('#sb-exp', side); b && (b.onclick = () => { const rows = a.ids.map(id => prediosById[id].properties); download('predios_area.csv', '﻿id,municipio,ha,cultivo,semaforo\n' + rows.map(p => [p.id, munName[p.mun], p.ha, p.cul, p.cls].join(',')).join('\n'), 'text/csv'); }); }, 30); }); });
  return m.cleanup;
}

// ---------- Padrón ----------
function padron(main, params) {
  let q = '', cls = '', mun = '', cul = '', sort = 'id', dir = 1, shown = 80; const rows = S.predios.features.map(f => f.properties);
  main.innerHTML = hdr('Padrón de predios', 'Registro georreferenciado de predios inscritos. Cada predio tiene un folio público seudonimizado; el nombre del titular nunca se muestra aquí ni se publica.', `<button class="btn" id="ex">${icon('download', 14)} Exportar CSV</button>`) +
    `<div class="split-h"><input id="q" placeholder="Buscar por folio o productor…" style="min-width:230px"><select id="fcl"><option value="">Todos los colores</option>${Object.keys(CLS).map(c => `<option value="${c}">${CLS[c].name}</option>`).join('')}</select><select id="fm"><option value="">Todos los municipios</option>${Object.values(ST.perMun).filter(m => m.n).sort((a, b) => munName[a.id].localeCompare(munName[b.id])).map(m => `<option value="${m.id}">${esc(munName[m.id])}</option>`).join('')}</select><select id="fcu"><option value="">Todos los cultivos</option>${['Aguacate', 'Berries', 'Durazno', 'Maíz', 'Agave', 'Otro'].map(c => `<option>${c}</option>`).join('')}</select><span class="tiny dim" id="cnt"></span></div><div class="tw" style="max-height:calc(100vh - 250px)"><table class="tbl" id="tb"></table></div>`;
  const draw = () => { let r = rows.filter(p => (!q || p.id.toLowerCase().includes(q) || p.prd.toLowerCase().includes(q)) && (!cls || p.cls === cls) && (!mun || p.mun === mun) && (!cul || p.cul === cul)); r.sort((a, b) => dir * (typeof a[sort] === 'number' ? a[sort] - b[sort] : String(a[sort] ?? '').localeCompare(String(b[sort] ?? '')))); $('#cnt', main).textContent = fmt(r.length) + ' predios'; const col = [['id', 'Folio'], ['prd', 'Productor'], ['mun', 'Municipio'], ['ha', 'Ha'], ['cul', 'Cultivo'], ['ten', 'Tenencia'], ['cls', 'Semáforo'], ['ir', 'Índice'], ['con', 'Constancia'], ['est', 'Situación']];
    $('#tb', main).innerHTML = `<thead><tr>${col.map(([k, l]) => `<th class="s ${k === 'ha' || k === 'ir' ? 'num' : ''}" data-k="${k}">${l}${sort === k ? (dir > 0 ? ' ▲' : ' ▼') : ''}</th>`).join('')}</tr></thead><tbody>${r.slice(0, shown).map(p => `<tr class="cl" data-id="${p.id}"><td class="mono">${p.id}</td><td class="mono dim">${p.prd}</td><td>${esc(munName[p.mun])}</td><td class="num">${fmt(p.ha, 1)}</td><td>${esc(p.cul)}</td><td class="dim">${esc(p.ten)}</td><td>${badge(p.cls)}</td><td class="num">${p.ir ?? '—'}</td><td>${conChip(p.con)}</td><td class="dim tiny">${esc(p.est)}</td></tr>`).join('')}</tbody>${r.length > shown ? `<tfoot><tr><td colspan="10" style="text-align:center;padding:10px"><button class="btn sm" id="mo">Mostrar más (${fmt(r.length - shown)})</button></td></tr></tfoot>` : ''}`; };
  draw();
  main.addEventListener('input', e => { if (e.target.id === 'q') { q = e.target.value.toLowerCase(); shown = 80; draw(); } }); main.addEventListener('change', e => { const t = e.target; if (t.id === 'fcl') cls = t.value; if (t.id === 'fm') mun = t.value; if (t.id === 'fcu') cul = t.value; if (['fcl', 'fm', 'fcu'].includes(t.id)) { shown = 80; draw(); } });
  on(main, 'click', 'th.s', (e, t) => { const k = t.dataset.k; dir = sort === k ? -dir : 1; sort = k; draw(); }); on(main, 'click', '#mo', () => { shown += 200; draw(); });
  on(main, 'click', 'tr.cl', (e, r) => { $$('.drawer', main).forEach(x => x.remove()); expediente(main, r.dataset.id); });
  $('#ex', main).onclick = () => { download('padron_predios.csv', '﻿Folio,Productor,Municipio,Superficie_ha,Cultivo,Tenencia,Semaforo,Indice,Constancia,Situacion\n' + rows.map(p => [p.id, p.prd, munName[p.mun], p.ha, p.cul, p.ten, p.cls, p.ir ?? '', p.con, p.est].map(x => JSON.stringify(x)).join(',')).join('\n'), 'text/csv'); ledgerAppend(S.ledger, 'Dictaminador-03', 'EXPORTACION_PADRON', 'padron'); toast('Exportación registrada en la bitácora'); };
  main.style.position = 'relative'; if (params && params.id) expediente(main, params.id);
}

// ---------- Alertas y validación ----------
function alertas(main, params) {
  let filt = 'abiertas', sel = params && params.id; const list = () => S.alertas.filter(a => filt === 'todas' ? true : filt === 'abiertas' ? OPEN.includes(a.st) : a.st === filt).sort((a, b) => b.d.localeCompare(a.d));
  main.className = 'main flush';
  main.innerHTML = `<div class="split"><div style="flex:1;min-width:0;display:flex;flex-direction:column;padding:16px 18px;overflow:auto">${hdr('Alertas y validación', 'Cada alerta satelital se valida por una persona con imagen de alta resolución antes de producir efecto alguno (máximo 10 días hábiles).')}<div class="split-h"><div class="pill-tabs" id="ft">${['abiertas', 'todas', 'Confirmada', 'Notificada', 'Firme', 'Descartada'].map(f => `<button data-f="${f}" class="${f === filt ? 'on' : ''}">${f[0].toUpperCase() + f.slice(1)}</button>`).join('')}</div><span class="tiny dim" id="ct"></span></div><div class="tw" style="flex:1"><table class="tbl" id="tb"></table></div></div><aside class="side" id="pn" style="width:430px"></aside></div>`;
  const draw = () => { const l = list(); $('#ct', main).textContent = l.length + ' alertas'; $('#tb', main).innerHTML = `<thead><tr><th>ID</th><th>Fecha</th><th>Municipio</th><th>Fuente</th><th class="num">Ha</th><th>Conf.</th><th>Estado</th><th class="num">Edad</th></tr></thead><tbody>${l.slice(0, 200).map(a => `<tr class="cl ${a.id === sel ? 'act' : ''}" data-id="${a.id}"><td class="mono">${a.id}</td><td>${fdate(a.d)}</td><td>${esc(munName[a.mun])}</td><td class="dim">${esc(a.src)}</td><td class="num">${fmt(a.ha, 2)}</td><td>${esc(a.conf)}</td><td>${stChip(a.st)}</td><td class="num" style="color:${OPEN.includes(a.st) && ageDays(a) > 14 ? '#B3261E' : 'inherit'}">${ageDays(a)} d</td></tr>`).join('')}</tbody>`; };
  const detail = () => { const pn = $('#pn', main); const a = alertaById[sel]; if (!a) { pn.innerHTML = `<div class="dim" style="text-align:center;padding:40px 10px">${icon('alert', 34)}<div style="margin-top:8px">Seleccione una alerta para validarla.</div></div>`; return; }
    const pr = a.pid ? prediosById[a.pid].properties : null; const open = OPEN.includes(a.st);
    pn.innerHTML = `<div class="ch"><h2 class="mono">${a.id}</h2><div class="sp">${stChip(a.st)}</div></div><dl class="kv" style="margin:10px 0"><dt>Detección</dt><dd>${fdate(a.d)} · ${esc(a.src)} · confianza ${esc(a.conf)}</dd><dt>Superficie</dt><dd class="mono">${fmt(a.ha, 2)} ha</dd><dt>Ubicación</dt><dd class="mono">${a.lat.toFixed(5)}, ${a.lon.toFixed(5)}</dd><dt>Predio</dt><dd>${pr ? `<a class="mono" data-p="${pr.id}">${pr.id}</a> ${badge(pr.cls)}` : '<span class="chip warn">Fuera del padrón</span>'}</dd><dt>Municipio</dt><dd>${esc(munName[a.mun])}</dd></dl>
    <h3>Evidencia antes / después ${tag('demo')}</h3><div id="ba" style="margin-top:6px"></div>
    <div class="note tiny" style="margin:10px 0"><b>Antes de decidir:</b> compare con autorizaciones federales vigentes (SEMARNAT), ANP y focos de calor de FIRMS. Una alerta no siempre es deforestación (sequía, incendio, cosecha).</div>
    ${open ? `<div style="display:grid;grid-template-columns:1fr 1fr;gap:8px"><button class="btn ok" data-act="conf">✓ Confirmar pérdida</button><button class="btn danger" data-act="desc">✕ Falso positivo</button><button class="btn" data-act="lidar">Solicitar LiDAR</button><button class="btn" data-act="esc">Escalar a jurídico</button></div>` : `<div class="tiny dim">Estado actual: ${esc(a.st)}. Esta alerta ya fue procesada.</div>`}
    <h3 style="margin-top:14px">Trazabilidad</h3>${S.ledger.filter(e => e.obj === a.id).map(e => `<div class="tiny" style="padding:3px 0"><span class="mono dim">${ftime(e.ts)}</span> ${esc(e.acc)} · ${esc(e.actor)}</div>`).join('') || '<div class="tiny dim">Sin eventos adicionales.</div>'}`;
    const proxy = pr || { id: a.id, cls: 'amarillo', ha: Math.max(1, a.ha * 3), aff: a.ha, ly: 2026, cau: null };
    beforeAfter($('#ba', pn), proxy.id.startsWith('PF') ? { ...proxy, aff: a.ha, ly: Number(a.d.slice(0, 4)) } : (() => { const f = { type: 'Feature', geometry: { type: 'Polygon', coordinates: [[[a.lon - .002, a.lat - .0015], [a.lon + .002, a.lat - .0015], [a.lon + .0022, a.lat + .0015], [a.lon - .002, a.lat + .0016], [a.lon - .002, a.lat - .0015]]] }, properties: proxy }; prediosById[a.id] = f; return { ...proxy, cls: 'amarillo', ha: 6, aff: a.ha * 2 }; })());
  };
  const act = (a, kind) => {
    if (kind === 'desc') { a.st = 'Descartada'; ledgerAppend(S.ledger, 'Analista-07', 'ALERTA_DESCARTADA', a.id); toast('Alerta descartada como falso positivo'); }
    else if (kind === 'lidar') { a.st = 'En validación'; ledgerAppend(S.ledger, 'Analista-07', 'ESTUDIO_SOLICITADO', a.id); toast('Se solicitó levantamiento LiDAR nivel B al productor'); }
    else if (kind === 'esc') { a.st = 'En validación'; ledgerAppend(S.ledger, 'Analista-07', 'ESCALADA_JURIDICO', a.id); toast('Escalada al área jurídica'); }
    else if (kind === 'conf') {
      const pr = a.pid ? prediosById[a.pid].properties : null; const m = modal(`<h2>Confirmar pérdida y clasificar</h2><p class="dim tiny">${pr ? `Predio <b class="mono">${pr.id}</b>.` : 'La alerta está fuera del padrón: se creará un caso de investigación de oficio.'} Estime el Índice de Reversibilidad con las evidencias (LiDAR, imagen VHR, campo). El resultado sólo produce efectos después de la notificación y la audiencia.</p><div id="sm"></div><div style="text-align:right;margin-top:14px"><button class="btn ghost" data-close>Cancelar</button> <button class="btn pri" id="emit">Emitir clasificación</button></div>`, { w: '900px' });
      const sm = simulator(m.q('#sm'), { v: pr && pr.v ? pr.v : undefined }); m.q('#emit').onclick = () => { const { r } = sm.get(); a.st = 'Confirmada'; if (pr) { pr.cls = r.cls; pr.ly = Number(a.d.slice(0, 4)); pr.aff = a.ha; pr.est = 'Notificada'; pr.ir = r.idx; pr.niv = r.nivel; pr.v = sm.get().st.v.slice(); pr.cau = sm.get().st.causales.size ? [...sm.get().st.causales][0] : undefined; pr.con = r.cls === 'rojo' ? 'Suspendida' : 'Condicionada'; } ledgerAppend(S.ledger, 'Dictaminador-03', 'CLASIFICACION_EMITIDA', a.pid || a.id); refresh(); toast('Clasificación ' + CLS[r.cls].name + ' emitida; se notifica al interesado'); m.close(); draw(); detail(); window.__refreshBadges(); }; return; }
    refresh(); window.__refreshBadges(); draw(); detail();
  };
  draw(); detail();
  on(main, 'click', '#ft button', (e, b) => { filt = b.dataset.f; $$('#ft button', main).forEach(x => x.classList.toggle('on', x === b)); draw(); }); on(main, 'click', 'tr.cl', (e, r) => { sel = r.dataset.id; draw(); detail(); }); on(main, 'click', '[data-act]', (e, b) => act(alertaById[sel], b.dataset.act)); on(main, 'click', '[data-p]', (e, a) => window.__go('admin', 'padron', { id: a.dataset.p }));
}
export const views = { centro, gis, padron, alertas };
