import { $, $$, on, esc, fmt, chip, toast, download } from '../util.js';
import { S, munName } from '../state.js';
import * as ch from '../charts.js';
import { kpi, tag, icon, modal } from '../ui.js';
import { prepPolys, prepPts } from '../map.js';
import { createMap, attachControls } from '../mapkit.js';
import { ledgerAppend } from '../integrity.js';
import { H, hById, PARAMS, ESTADOS, me, pOf, centroid, transit, elegibilidad, listaVersion, elegibles, maskRfc, dating } from '../domain/core.js';
import { EMP, balance, capacidad, ratioComp, registrarComp, newCompRing, lineaCaptura, recaudacion, laboral } from '../domain/trace.js';
import { hdr, estChip, who } from './verif.js';
import { SIAP, BANDAS, rendimiento, bandaDe, altitud } from '../domain/trace.js';
import { MET } from '../domain/core.js';
import { alertasBalance, revisarBalance, procDe, AUTORIDADES, ETAPAS_PROC, registrarProcedimiento, resolverProcedimiento, azulesSinProcedimiento, cohortes, semLaboral, CLA, faseVigente, CORTE, EXPORTADORES, conciliacionVelagro, universoChip, soloLectura, bump } from '../domain/mce.js';

// ---------- Balance de masa y cadena ----------
export function chainOf(q) {
  q = q.trim().toUpperCase(); let lotes = [];
  if (q.startsWith('EMB-')) lotes = S.lotes.filter(l => l.emb === q); else if (q.startsWith('LOT-')) lotes = S.lotes.filter(l => l.id === q); else if (q.startsWith('HUE-')) lotes = S.lotes.filter(l => l.uid === q);
  return lotes;
}
function balanceView(main) {
  const B = balance().sort((a, b) => b.ratio - a.ratio); const fl = B.filter(b => b.flag === 'Posible lavado'), rv = B.filter(b => b.flag === 'Revisar'); const rej = S.consultas.filter(c => !c.elegible);
  const bins = [0, .25, .5, .75, 1, 1.15, 1.35, 1.75, 2.5].map((x, i, a) => ({ label: i < a.length - 1 ? `${x}-${a[i + 1]}` : `≥${x}`, value: B.filter(b => b.ent > 0 && b.ratio >= x && (i === a.length - 1 || b.ratio < a[i + 1])).length, color: x >= PARAMS.balanceFraude ? '#B3261E' : x >= PARAMS.balanceTolerancia ? '#A8720F' : '#235B4E' }));
  const AL = alertasBalance(); const venc = AL.filter(a => a.vencida);
  main.innerHTML = hdr('Trazabilidad y balance de masa', 'El satélite no ve el lavado de fruta; el balance de masa sí. Se cruza lo que cada huerta entrega a las empacadoras con su capacidad productiva (superficie × rendimiento SIAP por municipio y franja de altitud).', who()) +
    `<div class="card" style="margin-bottom:14px"><div class="ch"><h3>Parámetros del balance · ${MET.id} v${MET.ver}</h3><div class="sp"><span class="tiny dim">editables por Dictaminación; cada cambio versiona la metodología</span></div></div><div class="grid g4" style="margin-top:8px"><label class="tiny">Tolerancia «revisar» (×)<input type="number" step=".01" id="btol" value="${PARAMS.balanceTolerancia}"></label><label class="tiny">Umbral «posible lavado» (×) · la especificación propone 1.3<input type="number" step=".01" id="bfra" value="${PARAMS.balanceFraude}"></label><label class="tiny">SLA de revisión (horas)<input type="number" id="bsla" value="${PARAMS.slaBalanceHoras}"></label><label class="tiny">Trabajadores por tonelada<input disabled placeholder="pendiente de DOF (Factor Técnico)" value=""></label></div></div>
    <div class="card" style="margin-bottom:14px"><div class="ch"><h3>Alertas de balance y SLA de ${PARAMS.slaBalanceHoras} h</h3><div class="sp">${venc.length ? `<span class="chip bad">${venc.length} con SLA vencido · suben a la cola prioritaria del Centro de mando</span>` : '<span class="chip ok">Sin SLA vencido</span>'}</div></div><div class="tw" style="max-height:260px"><table class="tbl"><thead><tr><th>Huerta</th><th>Señal</th><th class="num">Razón</th><th>Detectada</th><th class="num">Horas sin revisión</th><th>Estado</th><th></th></tr></thead><tbody>${AL.slice(0, 120).map(a => `<tr><td class="mono tiny">${a.h.uid}</td><td>${a.flag === 'Posible lavado' ? '<span class="chip bad">Posible lavado</span>' : '<span class="chip warn">Revisar</span>'}</td><td class="num">${a.ratio.toFixed(2)}×</td><td class="mono tiny">${a.detectada}</td><td class="num ${a.vencida ? 'bad' : ''}">${a.revisada ? '—' : fmt(a.horas)}</td><td>${a.revisada ? `<span class="chip ok">Revisada · ${esc(a.revisada.user)}</span>` : a.vencida ? '<span class="chip bad">SLA vencido</span>' : '<span class="chip warn">En plazo</span>'}</td><td>${a.revisada ? '' : `<button class="btn sm" data-rv="${a.h.uid}">Marcar revisada</button>`}</td></tr>`).join('') || '<tr><td colspan="7" class="dim">Sin alertas.</td></tr>'}</tbody></table></div></div>` +
    `<div class="grid g4">${kpi({ l: 'Lotes recibidos · temporada 2025-26', v: fmt(S.lotes.length), s: fmt(S.lotes.reduce((s, l) => s + l.t, 0)) + ' t en ' + EMP.length + ' empacadoras' })}${kpi({ l: 'Posible lavado de fruta', v: fmt(fl.length), s: `entregas > ${PARAMS.balanceFraude}× la capacidad`, c: '#B3261E' })}${kpi({ l: 'Por revisar', v: fmt(rv.length), s: `entre ${PARAMS.balanceTolerancia}× y ${PARAMS.balanceFraude}×`, c: '#A8720F' })}${kpi({ l: 'Recepciones rechazadas', v: fmt(rej.length), s: 'huerta no elegible o sin capacidad remanente', c: '#A8720F' })}</div>
    <div class="grid g2" style="margin-top:14px"><div class="card"><div class="ch"><h3>Entregado / capacidad productiva (huertas con entregas)</h3>${tag('demo')}</div>${ch.bars(bins, { h: 220 })}<div class="tiny dim">Aguacate: tabla SIAP por municipio y franja de altitud (abajo); berries ${PARAMS.rendimiento.Berries} t/ha y limón ${PARAMS.rendimiento['Limón']} t/ha.</div></div>
    <div class="card"><div class="ch"><h3>Cadena huerta → lote → empacadora → embarque</h3></div><div style="display:flex;gap:6px;margin:8px 0"><input id="cq" placeholder="EMB-00012, LOT-000123 o HUE-…" style="flex:1"><button class="btn" id="cb">Rastrear</button></div><div id="co" class="tiny dim">Ingrese un embarque, lote o huerta. Ejemplo: <a data-q="${S.embarques[5].id}" class="mono">${S.embarques[5].id}</a>.</div></div></div>
    <div class="card" style="margin-top:14px"><div class="ch"><h3>Huertas con entregas por encima de su capacidad</h3><div class="sp"><button class="btn sm ghost" id="bx">${icon('download', 12)} CSV</button></div></div><div class="tw" style="max-height:340px"><table class="tbl"><thead><tr><th>Huerta</th><th>Municipio</th><th>Cultivo</th><th class="num">Ha</th><th class="num">Capacidad (t)</th><th class="num">Entregado (t)</th><th class="num">Razón</th><th>Señal</th><th>Estado</th></tr></thead><tbody>${B.filter(b => b.flag !== 'Normal').map(b => `<tr class="cl" data-h="${b.h.uid}"><td class="mono tiny">${b.h.uid}</td><td>${esc(munName[b.h.mun])}</td><td>${esc(b.h.cul)}</td><td class="num">${fmt(pOf(b.h).ha, 1)}</td><td class="num">${fmt(b.cap, 1)}</td><td class="num">${fmt(b.ent, 1)}</td><td class="num"><b>${b.ratio.toFixed(2)}×</b></td><td>${chip(b.flag, b.flag === 'Posible lavado' ? 'bad' : 'warn')}</td><td>${estChip(b.h.estado)}</td></tr>`).join('')}</tbody></table></div></div>
    <div class="card" style="margin-top:14px"><div class="ch"><h3>Consultas de elegibilidad rechazadas (empacadoras)</h3></div><div class="tw" style="max-height:260px"><table class="tbl"><thead><tr><th>Fecha</th><th>Empacadora</th><th>Huerta</th><th class="num">t</th><th>Motivo</th><th>Vía</th></tr></thead><tbody>${rej.slice(0, 80).map(c => `<tr><td class="mono tiny">${c.ts.replace('T', ' ').slice(0, 16)}</td><td class="mono tiny">${c.emp}</td><td class="mono tiny">${c.uid}</td><td class="num">${c.t}</td><td class="tiny">${esc(c.motivo)}</td><td class="tiny">${c.via}</td></tr>`).join('')}</tbody></table></div></div>`;
  const trace = q => { const ls = chainOf(q); const o = $('#co', main); if (!ls.length) { o.innerHTML = 'Sin resultados.'; return; } const hs = [...new Set(ls.map(l => l.uid))];
    o.innerHTML = `<div class="tw" style="max-height:260px"><table class="tbl"><thead><tr><th>Embarque</th><th>Lote</th><th>Fecha</th><th>Empacadora</th><th>Huerta</th><th class="num">t</th><th>Estado actual</th></tr></thead><tbody>${ls.slice(0, 120).map(l => `<tr><td class="mono tiny">${l.emb || '—'}</td><td class="mono tiny">${l.id}</td><td class="mono tiny">${l.fecha}</td><td class="mono tiny">${l.emp}</td><td class="mono tiny">${l.uid}</td><td class="num">${l.t}</td><td>${estChip(hById[l.uid].estado)}</td></tr>`).join('')}</tbody></table></div><div class="tiny" style="margin-top:6px">${ls.length} lotes · ${hs.length} huertas · ${fmt(ls.reduce((s, l) => s + l.t, 0), 1)} t · ${hs.some(u => !ESTADOS[hById[u].estado].eleg) ? '<b style="color:#B3261E">contiene fruta de huertas hoy no elegibles</b>' : 'todas las huertas elegibles hoy'}</div>`; };
  const munSIAP = [...new Set(H.filter(h => h.cul === 'Aguacate').map(h => h.mun))].sort((a, b) => munName[a].localeCompare(munName[b]));
  main.insertAdjacentHTML('beforeend', `<div class="card" style="margin-top:14px"><div class="ch"><h3>Rendimiento de aguacate por municipio y franja de altitud (t/ha)</h3><div class="sp"><span class="chip warn">Valores ILUSTRATIVOS · cargar tabla SIAP</span></div></div><div class="tiny dim" style="margin:4px 0 8px">${esc(SIAP.fuente)}. La altitud de cada huerta proviene de un modelo de elevación de demostración (pendiente: Continuo de Elevaciones Mexicano de INEGI). Edite una celda para fijar el valor oficial.</div><div class="tw" style="max-height:320px"><table class="tbl"><thead><tr><th>Municipio</th>${BANDAS.map(b => `<th class="num">${b[0]}</th>`).join('')}</tr></thead><tbody>${munSIAP.map(m => `<tr><td>${esc(munName[m])}</td>${BANDAS.map(b => { const k = m + '|' + b[0]; const hh = H.find(h => h.mun === m && h.cul === 'Aguacate' && bandaDe(h)[0] === b[0]); const v = SIAP.overrides[k] ?? (hh ? rendimiento(hh) : null); return `<td class="num">${v == null ? '<span class="dim">—</span>' : `<input class="mono" data-siap="${k}" value="${v}" style="width:62px;text-align:right">`}</td>`; }).join('')}</tr>`).join('')}</tbody></table></div></div>`);
  if (!main._bw) { main._bw = 1; main.addEventListener('change', e => { const t = e.target; const u = me(); if (!['btol', 'bfra', 'bsla'].includes(t.id) && !t.dataset.siap) return; if (u.rol !== 'dictamen') { toast('Sólo la Dirección de Dictaminación puede cambiar parámetros', 'warn'); return; }
    if (t.id === 'btol') PARAMS.balanceTolerancia = +t.value; if (t.id === 'bfra') PARAMS.balanceFraude = +t.value; if (t.id === 'bsla') PARAMS.slaBalanceHoras = +t.value; if (t.dataset.siap) SIAP.overrides[t.dataset.siap] = +t.value;
    const [a, b, c] = MET.ver.split('.').map(Number); MET.ver = `${a}.${b}.${c + 1}`; ledgerAppend(S.ledger, u.id, 'PARAMETRO_METODOLOGIA', MET.id + ' v' + MET.ver, JSON.stringify({ [t.id || t.dataset.siap]: t.value })); bump(); toast('Nueva versión de metodología ' + MET.ver); balanceView(main); });
  on(main, 'click', '[data-rv]', (e, b) => { const r = revisarBalance(b.dataset.rv, me()); if (!r.ok) return toast(r.why, 'warn'); toast('Alerta de balance revisada'); balanceView(main); }); }
  $('#cb', main).onclick = () => trace($('#cq', main).value); on(main, 'click', '[data-q]', (e, a) => { $('#cq', main).value = a.dataset.q; trace(a.dataset.q); });
  on(main, 'click', '[data-h]', (e, r) => window.__go('admin', 'huertas', { id: r.dataset.h }));
  $('#bx', main).onclick = () => download('balance_de_masa.csv', 'uid,municipio,cultivo,superficie_ha,capacidad_t,entregado_t,razon,senal,estado\n' + B.map(b => [b.h.uid, munName[b.h.mun], b.h.cul, pOf(b.h).ha, b.cap, b.ent, b.ratio.toFixed(3), b.flag, b.h.estado].join(',')).join('\n'), 'text/csv');
}

// ---------- Compensaciones ----------
function compensaciones(main) {
  let map;
  const draw = () => { if (map) map.destroy();
    const pend = H.filter(h => h.estado === 'Bloqueado' && dating(h).brk && !S.comp.some(c => c.uid === h.uid));
    main.innerHTML = hdr('Registro único de compensaciones', `Cada hectárea que compensa una huerta (${PARAMS.compensacion.min} a ${PARAMS.compensacion.max} ha de bosque por ha convertida) lleva geometría e identificador y queda bloqueada: no puede venderse dos veces.`, `${who()} <button class="btn pri" id="nw">${icon('plus', 14)} Registrar compensación</button>`) +
      `<div class="grid g4">${kpi({ l: 'Compensaciones registradas', v: fmt(S.comp.length), s: fmt(S.comp.reduce((s, c) => s + c.ha, 0), 1) + ' ha bloqueadas' })}${kpi({ l: 'Cumplidas', v: fmt(S.comp.filter(c => c.estado === 'Cumplida').length), s: 'huertas rehabilitadas', c: '#235B4E' })}${kpi({ l: 'Huertas bloqueadas sin compensación', v: fmt(pend.length), s: 'requieren proyecto y polígono', c: '#A8720F' })}${kpi({ l: 'Intentos de doble uso detectados', v: fmt(S.ledger.filter(e => e.acc === 'COMPENSACION_RECHAZADA').length), s: 'traslape con polígono ya asignado', c: '#B3261E' })}</div>
      <div class="grid g21" style="margin-top:14px"><div class="card pad0" style="height:460px;position:relative"><div id="mp" style="height:100%"></div></div><div class="card"><div class="ch"><h3>Registro</h3></div><div class="tw" style="max-height:400px"><table class="tbl"><thead><tr><th>ID</th><th>Huerta</th><th class="num">Req.</th><th class="num">Ha</th><th>Estado</th></tr></thead><tbody>${S.comp.slice().reverse().map(c => `<tr class="cl" data-c="${c.id}"><td class="mono tiny">${c.id}</td><td class="mono tiny">${c.uid}</td><td class="num">${c.req}</td><td class="num">${c.ha}</td><td>${chip(c.estado, c.estado === 'Cumplida' ? 'ok' : 'info')}</td></tr>`).join('')}</tbody></table></div></div></div>`;
    const PR = S.procedimientos, sinP = azulesSinProcedimiento(), CO = cohortes();
    main.insertAdjacentHTML('beforeend', `<div class="grid g2" style="margin-top:14px"><div class="card"><div class="ch"><h3>Procedimientos de autoridad</h3><div class="sp">${sinP.length ? `<span class="chip bad">${sinP.length} huertas en restauración sin procedimiento</span>` : '<span class="chip ok">Toda huerta en restauración tiene procedimiento</span>'} <button class="btn sm" id="npr">${icon('plus', 12)} Registrar</button></div></div><div class="tiny dim" style="margin:4px 0 8px">Regla: toda huerta en ruta de restauración (semáforo ambiental «restauración») debe tener un procedimiento de autoridad asociado: PROFEPA (federal), PROAM (estatal) o FGE. Al resolverse por cumplimiento se emite la constancia de cumplimiento.</div><div class="tw" style="max-height:300px"><table class="tbl"><thead><tr><th>Procedimiento</th><th>Huerta</th><th>Autoridad</th><th>Expediente externo</th><th>Etapa</th><th>Constancia</th><th></th></tr></thead><tbody>${PR.map(p => `<tr><td class="mono tiny">${p.id}</td><td class="mono tiny">${p.uid}</td><td>${esc(p.autoridad)}</td><td class="mono tiny">${esc(p.externo)}</td><td>${esc(p.etapa)}</td><td class="mono tiny">${p.constancia || '—'}</td><td>${p.etapa === 'Cumplimiento' ? '' : `<button class="btn sm ghost" data-res="${p.id}">Resolver</button>`}</td></tr>`).join('')}</tbody></table></div></div>
      <div class="card"><div class="ch"><h3>Supervivencia por cohorte de plantación</h3>${tag('demo')}</div><div class="tiny dim" style="margin:4px 0 8px">Proyectos agrupados por año de plantación: verificación satelital anual y muestreo de campo (indicador C5 de Indicadores).</div><table class="tbl"><thead><tr><th>Cohorte</th><th class="num">Proyectos</th><th class="num">Ha</th><th class="num">Plantas</th><th class="num">Supervivencia satelital</th><th class="num">Muestreo de campo</th></tr></thead><tbody>${CO.map(c => `<tr><td class="mono">${c.anio}</td><td class="num">${c.n}</td><td class="num">${fmt(c.ha, 1)}</td><td class="num">${fmt(c.plant)}</td><td class="num"><b style="color:${c.sat >= 80 ? '#2E7D32' : c.sat >= 65 ? '#A8720F' : '#B3261E'}">${c.sat} %</b></td><td class="num">${c.campo} %</td></tr>`).join('')}</tbody></table></div></div>`);
    $('#npr', main).onclick = () => { const cand = H.filter(h => ['Bloqueado', 'En restauración'].includes(h.estado) && !procDe(h.uid)); const m = modal(`<h2>Registrar procedimiento de autoridad</h2><label class="f">Huerta<select id="ph">${(sinP.length ? sinP : cand).slice(0, 200).map(h => `<option value="${h.uid}">${h.uid} · ${esc(h.estado)}</option>`).join('')}</select></label><label class="f">Autoridad<select id="pa">${AUTORIDADES.map(a => `<option>${a}</option>`).join('')}</select></label><label class="f">Número de expediente externo<input id="px" placeholder="PFPA/23.2/2C.27.2/0123-2026"></label><label class="f">Etapa<select id="pe">${ETAPAS_PROC.slice(0, 3).map(a => `<option>${a}</option>`).join('')}</select></label><div style="display:flex;gap:8px;justify-content:flex-end;margin-top:12px"><button class="btn ghost" data-close>Cancelar</button><button class="btn pri" id="ok">Registrar</button></div>`, { w: '520px' });
      m.q('#ok').onclick = () => { const h = hById[m.q('#ph').value]; if (!h) return; const r = registrarProcedimiento(h, { autoridad: m.q('#pa').value, externo: m.q('#px').value, etapa: m.q('#pe').value }, me()); if (!r.ok) return toast(r.why, 'warn'); m.close(); toast('Procedimiento ' + r.p.id + ' registrado'); draw(); }; };
    on(main, 'click', '[data-res]', (e, b) => { const p = S.procedimientos.find(x => x.id === b.dataset.res); if (!p || p.etapa === 'Cumplimiento') return; const r = resolverProcedimiento(p, 'Cumplimiento de medidas de restauración y compensación', me()); if (!r.ok) return toast(r.why, 'warn'); toast('Constancia de cumplimiento ' + r.p.constancia + ' emitida'); draw(); });
    map = createMap($('#mp', main), { showAlerts: false, showLidar: false, showRest: false }); ['alertas', 'lidar', 'rest'].forEach(k => map.show(k, false));
    map.addLayer('comp', { type: 'poly', data: prepPolys({ features: S.comp.map(c => ({ type: 'Feature', properties: { id: c.id, uid: c.uid, estado: c.estado, ha: c.ha }, geometry: { type: 'Polygon', coordinates: [c.ring] } })) }), order: 25, pickable: true, minZ: 7, minPx: 3, dotR: 2.5, style: p => ({ fill: p.estado === 'Cumplida' ? '#235B4E' : '#235B4E', fa: .55, stroke: '#F2F4F0', lw: 1.4 }) });
    const tf = map.tipFn; map.tipFn = h => h.layer === 'comp' ? `<div class="mono tiny">${h.p.id}</div><div>${h.p.ha} ha · ${esc(h.p.estado)}</div><div class="tiny dim">Compensa ${h.p.uid}</div>` : tf(h);
    map.fitBounds([-102.8, 19.0, -101.3, 19.9], 20, false); attachControls($('#mp', main).parentElement, map, {});
    $('#nw', main).onclick = () => { const m = modal(`<h2>Registrar compensación</h2><label class="tiny">Huerta bloqueada<select id="hu" style="width:100%">${pend.slice(0, 200).map(h => `<option value="${h.uid}">${h.uid} · ${esc(munName[h.mun])} · requiere ${((pOf(h).aff || pOf(h).ha * .4) * ratioComp(h)).toFixed(2)} ha (${ratioComp(h)}:1)</option>`).join('')}</select></label><label class="tiny">Polígono receptor<select id="po" style="width:100%"><option value="new">Nuevo polígono en predio forestal receptor</option>${S.comp.slice(0, 30).map(c => `<option value="${c.id}">Reutilizar el polígono de ${c.id} (prueba de doble venta)</option>`).join('')}</select></label><label class="tiny">Clave catastral del predio receptor<input id="rc" value="16-000-000-00000" style="width:100%"></label><div id="pxw" style="margin-top:8px;padding:8px;border:1px solid var(--line);border-radius:8px"><div class="tiny" style="font-weight:600">Procedimiento de autoridad (obligatorio para pasar a «En restauración»)</div><div id="pxs" class="tiny dim" style="margin:4px 0"></div><div style="display:flex;gap:6px"><select id="pau">${AUTORIDADES.map(a => `<option>${a}</option>`).join('')}</select><input id="pex" class="mono" placeholder="Número de expediente externo" style="flex:1"></div></div><label class="tiny" style="display:flex;gap:6px;align-items:center;margin-top:6px"><input type="checkbox" id="tr" checked> Cambiar estado a «En restauración» (requiere dictaminador)</label><div style="display:flex;gap:8px;justify-content:flex-end;margin-top:12px"><button class="btn ghost" data-close>Cancelar</button><button class="btn pri" id="ok">Registrar y bloquear</button></div>`, { w: '560px' });
      const px = () => { const pr = procDe(m.q('#hu').value); m.q('#pxs').textContent = pr ? `Vinculado: ${pr.id} · ${pr.autoridad} ${pr.externo} · ${pr.etapa}` : 'Sin procedimiento registrado para esta huerta: indique autoridad y número de expediente externo.'; m.q('#pau').disabled = m.q('#pex').disabled = !!pr; }; px(); m.q('#hu').onchange = px;
      m.q('#ok').onclick = () => { const h = hById[m.q('#hu').value]; if (!h) return; const pv = m.q('#po').value; const req = (pOf(h).aff || pOf(h).ha * .4) * ratioComp(h); const ring = pv === 'new' ? newCompRing(h, req * 1.03, 'N' + Date.now()) : S.comp.find(c => c.id === pv).ring;
        const r = registrarComp(h, ring, me(), m.q('#rc').value); if (!r.ok) { ledgerAppend(S.ledger, me().id, 'COMPENSACION_RECHAZADA', h.uid, r.why); toast(r.why, 'warn'); return; }
        if (m.q('#tr').checked && !procDe(h.uid) && m.q('#pex').value.trim()) { const pr = registrarProcedimiento(h, { autoridad: m.q('#pau').value, externo: m.q('#pex').value, etapa: 'Inspección' }, me()); if (!pr.ok) toast(pr.why, 'warn'); }
        if (m.q('#tr').checked) { const t = transit(h, 'En restauración', me(), 'Proyecto aprobado y compensación registrada', [r.c.id], ledgerAppend); if (!t.ok) toast('Compensación registrada; el cambio de estado requiere: ' + t.why, 'warn'); }
        m.close(); toast('Compensación ' + r.c.id + ' registrada y bloqueada'); draw(); }; };
  };
  draw(); on(main, 'click', '[data-c]', (e, r) => { const c = S.comp.find(x => x.id === r.dataset.c); const xs = c.ring.map(p => p[0]), ys = c.ring.map(p => p[1]); map.fitBounds([Math.min(...xs), Math.min(...ys), Math.max(...xs), Math.max(...ys)], 120); });
  return () => map && map.destroy();
}

// ---------- Recaudación ----------
function recaudacionView(main) {
  const rec = recaudacion(); const tot = rec.reduce((s, x) => s + x[1], 0); const lab = H.filter(h => h.senasica).map(h => ({ h, l: laboral(h) })); const isnNew = lab.filter(x => x.l.registro && !x.l.isn).length;
  const catDiff = H.filter(h => { const r = (h.catastral.charCodeAt(12) % 10); return r === 3; }).length;
  main.innerHTML = hdr('Finanzas (interno)', 'Tablero de uso interno del rol Finanzas (SATMICH). La recaudación es un efecto del programa, no su propósito: se mantiene la línea de captura, el cruce ISN y el derecho por lote.', `<span class="chip bad">${icon('key', 12)} Acceso restringido · Finanzas</span> ${who()}`) +
    `<div class="note tiny" style="margin-bottom:12px"><b>Cuota del derecho: pendiente de estudio de costo.</b> Los montos usan una cuota ilustrativa de $${PARAMS.cuotaLote} por lote verificado. Variante a evaluar jurídicamente: cobrar a la empacadora por lote verificado, a costo de recuperación.</div>
    <div class="grid g4">${kpi({ l: 'Derechos por lote verificado · temporada', v: '$' + fmt(tot / 1e6, 2) + ' M', s: fmt(S.lotes.length) + ' lotes × $' + PARAMS.cuotaLote })}${kpi({ l: 'Contribuyentes ISN detectados', v: fmt(isnNew), s: 'registro patronal IMSS sin alta estatal', c: '#235B4E' })}${kpi({ l: 'Claves catastrales conciliadas', v: fmt(H.length - catDiff), s: fmt(catDiff) + ' con diferencia de superficie > 10 %', c: '#235B4E' })}${kpi({ l: 'Empacadoras contribuyentes', v: EMP.length, s: 'punto de control y de cobro' })}</div>
    <div class="grid g2" style="margin-top:14px"><div class="card"><div class="ch"><h3>Derechos por mes</h3>${tag('demo')}</div>${ch.bars(rec.map(([k, v]) => ({ label: k.slice(5) + '/' + k.slice(2, 4), value: Math.round(v / 1000), color: '#235B4E' })), { h: 220 })}<div class="tiny dim">Miles de pesos.</div></div>
    <div class="card"><div class="ch"><h3>Por RFC (empacadoras contribuyentes)</h3></div><div class="tw" style="max-height:220px"><table class="tbl"><thead><tr><th>RFC</th><th>Contribuyente</th><th class="num">Lotes</th><th class="num">Derecho (ilustrativo)</th></tr></thead><tbody>${EMP.slice(0, 40).map(e => { const n = S.lotes.filter(l => l.emp === e.id).length; return `<tr><td class="mono tiny">${maskRfc(e.id.replace('-', '') + 'XXXX000000')}</td><td class="tiny">${esc(e.nombre)}</td><td class="num">${fmt(n)}</td><td class="num">$${fmt(n * PARAMS.cuotaLote)}</td></tr>`; }).join('')}</tbody></table></div><h3 style="margin-top:12px">Emitir línea de captura</h3><label class="tiny">Contribuyente<select id="em" style="width:100%">${EMP.slice(0, 20).map(e => `<option>${e.id} · ${esc(e.nombre)}</option>`).join('')}</select></label><label class="tiny">Lotes verificados en el periodo<input type="number" id="nl" value="42" style="width:100%"></label><button class="btn pri" id="lc" style="margin-top:8px">Generar línea de captura</button><div id="lo" style="margin-top:10px"></div></div></div>`;
  $('#lc', main).onclick = () => { const n = +$('#nl', main).value || 0; const monto = n * PARAMS.cuotaLote; const emp = $('#em', main).value.split(' · ')[0]; const lc = lineaCaptura('DERECHO-VERIF', monto, emp); ledgerAppend(S.ledger, me().id, 'LINEA_CAPTURA', emp, lc);
    $('#lo', main).innerHTML = `<div class="verdict ok"><div><div class="big mono" style="font-size:15px">${lc}</div><div class="tiny dim">$${fmt(monto, 2)} · ${n} lotes · vigencia 3 días hábiles · <b>SIMULADA</b>: en producción la genera el servicio de la secretaría de finanzas.</div></div></div>`; };
}

// ---------- Laboral y agua ----------
function laboralAgua(main) {
  let tab = 'laboral', map;
  const draw = () => { if (map) { map.destroy(); map = null; }
    main.innerHTML = hdr('Módulos laboral (CLA) y de agua', 'Certificado Laboral Agrícola por fases (VELAGRO) con empresas de la cadena y REPSE, y concesiones de pozos de CONAGUA frente a ollas de agua detectadas en imagen.', who()) + `<div class="tabs" id="tb"><button data-t="laboral" class="${tab === 'laboral' ? 'on' : ''}">Laboral (CLA)</button><button data-t="agua" class="${tab === 'agua' ? 'on' : ''}">Agua (CONAGUA)</button></div><div id="bd"></div>`;
    const bd = $('#bd', main);
    if (tab === 'laboral') { const U = H.filter(h => h.senasica).map(h => ({ h, L: semLaboral(h) })); const suj = U.filter(x => x.L.sujeto); const cnt = k => suj.filter(x => x.L.color === k).length; const f = faseVigente(); const sinRepse = CORTE.filter(c => !c.repse); const vel = conciliacionVelagro();
      bd.innerHTML = `<div class="note info tiny" style="margin-bottom:12px">La especificación descarta métricas de plazas sin fuente normativa: se retiró el cálculo de «trabajadores esperados por hectárea». El semáforo laboral lo alimenta el <b>Certificado Laboral Agrícola (CLA)</b> vía VELAGRO (${esc(CLA.conexion)}). No se tratan datos personales de trabajadores.</div>
      <div class="grid g5">${kpi({ l: 'Huertas exportadoras', v: fmt(U.length), s: universoChip('exportadoras').replace(/<[^>]+>/g, '') })}${kpi({ l: 'Sujetas al CLA', v: fmt(suj.length), s: `${fmt(U.length - suj.length)} fuera del umbral (< ${CLA.umbralHa} ha del titular)` })}${kpi({ l: 'Semáforo laboral verde', v: fmt(cnt('verde')), c: '#2E7D32' })}${kpi({ l: 'Ámbar', v: fmt(cnt('ambar')), s: 'corte sin REPSE o productor sin registro', c: '#A8720F' })}${kpi({ l: 'Rojo', v: fmt(cnt('rojo')), s: 'por debajo del % exigible', c: '#B3261E' })}</div>
      <div class="grid g2" style="margin-top:14px"><div class="card"><div class="ch"><h3>Fases del CLA</h3><div class="sp">${f ? `<span class="chip info">Vigente: fase ${f.n}</span>` : ''}</div></div><table class="tbl" style="margin-top:6px"><thead><tr><th>Fase</th><th>Desde</th><th class="num">Registro patronal exigible</th><th>Factor Técnico</th><th>Alcance</th></tr></thead><tbody>${CLA.fases.map(x => `<tr style="${f && x.n === f.n ? 'background:rgba(35,91,78,.08)' : ''}"><td class="mono"><b>${x.n}</b></td><td class="mono tiny">${x.desde}</td><td class="num">${x.exige} %</td><td>${x.factor ? '<span class="chip warn">Exigible · valor pendiente de DOF</span>' : '—'}</td><td class="tiny">${esc(x.d)}</td></tr>`).join('')}</tbody></table><div class="tiny dim" style="margin-top:6px">${esc(CLA.notaFechas)}</div></div>
      <div class="card"><div class="ch"><h3>Conciliación con VELAGRO</h3>${tag('demo')}</div><p class="tiny" style="margin:6px 0">Prueba de aceptación: coincidencia con el CLA vigente en una muestra de ${vel.n} huertas.</p><div class="mono" style="font-size:30px;font-weight:600;color:${vel.pct >= 95 ? '#2E7D32' : '#A8720F'}">${vel.pct} %</div><div class="tiny dim">${vel.coinciden} de ${vel.n} coinciden · muestra simulada hasta tener conexión</div><h3 style="margin-top:12px">Empresas de corte sin REPSE</h3><div class="tiny" style="margin-top:4px">${sinRepse.length} de ${CORTE.length}: ${sinRepse.map(c => `<span class="mono">${c.id}</span>`).join(', ')}</div></div></div>
      <div class="card" style="margin-top:14px"><div class="ch"><h3>Empresas de la cadena</h3>${tag('demo')}</div><div class="tw" style="max-height:300px"><table class="tbl"><thead><tr><th>ID</th><th>Rol CLA</th><th>RFC</th><th>Registro patronal</th><th>REPSE</th></tr></thead><tbody>${CORTE.map(c => `<tr><td class="mono tiny">${c.id}</td><td>Corte</td><td class="mono tiny">${c.rfc}</td><td>${c.registro ? chip('Sí', 'ok') : chip('No', 'bad')}</td><td>${c.repse ? chip('Sí', 'ok') : chip('No', 'warn')}</td></tr>`).join('')}${EXPORTADORES.map(c => `<tr><td class="mono tiny">${c.id}</td><td>Exportador</td><td class="mono tiny">${c.rfc}</td><td>${c.registro ? chip('Sí', 'ok') : chip('No', 'bad')}</td><td class="dim">n/a</td></tr>`).join('')}</tbody></table></div></div>
      <div class="card" style="margin-top:14px"><div class="ch"><h3>Huertas con semáforo laboral ámbar o rojo</h3></div><div class="tw" style="max-height:340px"><table class="tbl"><thead><tr><th>Huerta</th><th>Municipio</th><th class="num">Ha del titular</th><th>Semáforo</th><th>Motivo</th></tr></thead><tbody>${suj.filter(x => ['ambar', 'rojo'].includes(x.L.color)).slice(0, 200).map(x => `<tr><td class="mono tiny">${x.h.uid}</td><td>${esc(munName[x.h.mun])}</td><td class="num">${fmt(x.L.sup, 1)}</td><td>${x.L.color === 'rojo' ? chip('Rojo', 'bad') : chip('Ámbar', 'warn')}</td><td class="tiny">${esc(x.L.txt)}</td></tr>`).join('')}</tbody></table></div></div>`; }
    else { const sinT = S.ollas.filter(o => !o.pozo), post = S.ollas.filter(o => o.conv && +o.det >= o.conv);
      bd.innerHTML = `<div class="grid g4">${kpi({ l: 'Ollas detectadas en imagen', v: fmt(S.ollas.length), s: fmt(S.ollas.reduce((s, o) => s + o.vol, 0) / 1000, 0) + ' mil m³ estimados' })}${kpi({ l: 'Sin concesión a < 500 m', v: fmt(sinT.length), c: '#B3261E' })}${kpi({ l: 'Pozos con título (REPDA)', v: fmt(S.pozos.length), c: '#235B4E' })}${kpi({ l: 'Ollas construidas tras la conversión', v: fmt(post.length), s: 'indicador de cambio de uso de suelo', c: '#A8720F' })}</div>
      <div class="grid g21" style="margin-top:14px"><div class="card pad0" style="height:440px;position:relative"><div id="mp" style="height:100%"></div></div><div class="card"><div class="ch"><h3>Ollas sin concesión cercana</h3>${tag('demo')}</div><div class="tw" style="max-height:380px"><table class="tbl"><thead><tr><th>Olla</th><th>Huerta</th><th class="num">m²</th><th class="num">Pozo más cercano</th></tr></thead><tbody>${sinT.slice(0, 150).map(o => `<tr><td class="mono tiny">${o.id}</td><td class="mono tiny">${o.uid}</td><td class="num">${fmt(o.m2)}</td><td class="num">${fmt(o.dist)} m</td></tr>`).join('')}</tbody></table></div></div></div>`;
      map = createMap($('#mp', bd), { showAlerts: false, showLidar: false, showRest: false }); ['alertas', 'lidar', 'rest'].forEach(k => map.show(k, false));
      map.addLayer('pozos', { type: 'point', data: prepPts(S.pozos), order: 36, pickable: true, minZ: 8, style: () => ({ fill: '#235B4E', stroke: '#0F2A24', r: 4 }) });
      map.addLayer('ollas', { type: 'point', data: prepPts(S.ollas), order: 37, pickable: true, minZ: 8, style: p => ({ shape: 'diamond', fill: p.pozo ? '#F2F4F0' : '#B3261E', stroke: '#0F2A24', r: 5 }) });
      const tf = map.tipFn; map.tipFn = h => h.layer === 'pozos' ? `<div class="mono tiny">${h.p.id}</div><div>Pozo con título · ${esc(h.p.uso)}</div><div class="tiny dim">${fmt(h.p.vol)} m³/año</div>` : h.layer === 'ollas' ? `<div class="mono tiny">${h.p.id}</div><div>Olla ${fmt(h.p.m2)} m² · detectada ${h.p.det}</div><div class="tiny dim">${h.p.pozo ? 'Concesión cercana ' + h.p.pozo : 'Sin concesión a < 500 m'}</div>` : tf(h);
      map.fitBounds([-102.6, 19.2, -101.7, 19.8], 20, false); attachControls($('#mp', bd).parentElement, map, {}); }
  };
  draw(); on(main, 'click', '#tb button', (e, b) => { tab = b.dataset.t; draw(); }); return () => map && map.destroy();
}
export const views = { balance: balanceView, compensaciones, recaudacion: recaudacionView, laboral: laboralAgua };
