import { $, $$, on, esc, fmt, chip, toast, download } from '../util.js';
import { S, munName } from '../state.js';
import * as ch from '../charts.js';
import { kpi, tag, icon, modal } from '../ui.js';
import { prepPolys, prepPts } from '../map.js';
import { createMap, attachControls } from '../mapkit.js';
import { ledgerAppend } from '../integrity.js';
import { H, hById, PARAMS, ESTADOS, me, pOf, centroid, transit, elegibilidad, listaVersion, elegibles, maskRfc, dating } from '../domain/core.js';
import { EMP, balance, capacidad, ratioComp, registrarComp, newCompRing, lineaCaptura, recaudacion, laboral } from '../domain/trace.js';
import { hdr, estChip, who } from './verif.js';

// ---------- Balance de masa y cadena ----------
export function chainOf(q) {
  q = q.trim().toUpperCase(); let lotes = [];
  if (q.startsWith('EMB-')) lotes = S.lotes.filter(l => l.emb === q); else if (q.startsWith('LOT-')) lotes = S.lotes.filter(l => l.id === q); else if (q.startsWith('HUE-')) lotes = S.lotes.filter(l => l.uid === q);
  return lotes;
}
function balanceView(main) {
  const B = balance().sort((a, b) => b.ratio - a.ratio); const fl = B.filter(b => b.flag === 'Posible lavado'), rv = B.filter(b => b.flag === 'Revisar'); const rej = S.consultas.filter(c => !c.elegible);
  const bins = [0, .25, .5, .75, 1, 1.15, 1.35, 1.75, 2.5].map((x, i, a) => ({ label: i < a.length - 1 ? `${x}-${a[i + 1]}` : `≥${x}`, value: B.filter(b => b.ent > 0 && b.ratio >= x && (i === a.length - 1 || b.ratio < a[i + 1])).length, color: x >= PARAMS.balanceFraude ? '#B3261E' : x >= PARAMS.balanceTolerancia ? '#A8720F' : '#235B4E' }));
  main.innerHTML = hdr('Trazabilidad y balance de masa', 'El satélite no ve el lavado de fruta; el balance de masa sí. Se cruza lo que cada huerta entrega a las empacadoras con su capacidad productiva (superficie × rendimiento esperado).', who()) +
    `<div class="grid g4">${kpi({ l: 'Lotes recibidos · temporada 2025-26', v: fmt(S.lotes.length), s: fmt(S.lotes.reduce((s, l) => s + l.t, 0)) + ' t en ' + EMP.length + ' empacadoras' })}${kpi({ l: 'Posible lavado de fruta', v: fmt(fl.length), s: `entregas > ${PARAMS.balanceFraude}× la capacidad`, c: '#B3261E' })}${kpi({ l: 'Por revisar', v: fmt(rv.length), s: `entre ${PARAMS.balanceTolerancia}× y ${PARAMS.balanceFraude}×`, c: '#A8720F' })}${kpi({ l: 'Recepciones rechazadas', v: fmt(rej.length), s: 'huerta no elegible o sin capacidad remanente', c: '#A8720F' })}</div>
    <div class="grid g2" style="margin-top:14px"><div class="card"><div class="ch"><h3>Entregado / capacidad productiva (huertas con entregas)</h3>${tag('demo')}</div>${ch.bars(bins, { h: 220 })}<div class="tiny dim">Rendimiento de referencia: aguacate ${PARAMS.rendimiento.Aguacate} t/ha, berries ${PARAMS.rendimiento.Berries} t/ha, limón ${PARAMS.rendimiento['Limón']} t/ha (parámetros a calibrar con SIAP y aforos de campo).</div></div>
    <div class="card"><div class="ch"><h3>Cadena huerta → lote → empacadora → embarque</h3></div><div style="display:flex;gap:6px;margin:8px 0"><input id="cq" placeholder="EMB-00012, LOT-000123 o HUE-…" style="flex:1"><button class="btn" id="cb">Rastrear</button></div><div id="co" class="tiny dim">Ingrese un embarque, lote o huerta. Ejemplo: <a data-q="${S.embarques[5].id}" class="mono">${S.embarques[5].id}</a>.</div></div></div>
    <div class="card" style="margin-top:14px"><div class="ch"><h3>Huertas con entregas por encima de su capacidad</h3><div class="sp"><button class="btn sm ghost" id="bx">${icon('download', 12)} CSV</button></div></div><div class="tw" style="max-height:340px"><table class="tbl"><thead><tr><th>Huerta</th><th>Municipio</th><th>Cultivo</th><th class="num">Ha</th><th class="num">Capacidad (t)</th><th class="num">Entregado (t)</th><th class="num">Razón</th><th>Señal</th><th>Estado</th></tr></thead><tbody>${B.filter(b => b.flag !== 'Normal').map(b => `<tr class="cl" data-h="${b.h.uid}"><td class="mono tiny">${b.h.uid}</td><td>${esc(munName[b.h.mun])}</td><td>${esc(b.h.cul)}</td><td class="num">${fmt(pOf(b.h).ha, 1)}</td><td class="num">${fmt(b.cap, 1)}</td><td class="num">${fmt(b.ent, 1)}</td><td class="num"><b>${b.ratio.toFixed(2)}×</b></td><td>${chip(b.flag, b.flag === 'Posible lavado' ? 'bad' : 'warn')}</td><td>${estChip(b.h.estado)}</td></tr>`).join('')}</tbody></table></div></div>
    <div class="card" style="margin-top:14px"><div class="ch"><h3>Consultas de elegibilidad rechazadas (empacadoras)</h3></div><div class="tw" style="max-height:260px"><table class="tbl"><thead><tr><th>Fecha</th><th>Empacadora</th><th>Huerta</th><th class="num">t</th><th>Motivo</th><th>Vía</th></tr></thead><tbody>${rej.slice(0, 80).map(c => `<tr><td class="mono tiny">${c.ts.replace('T', ' ').slice(0, 16)}</td><td class="mono tiny">${c.emp}</td><td class="mono tiny">${c.uid}</td><td class="num">${c.t}</td><td class="tiny">${esc(c.motivo)}</td><td class="tiny">${c.via}</td></tr>`).join('')}</tbody></table></div></div>`;
  const trace = q => { const ls = chainOf(q); const o = $('#co', main); if (!ls.length) { o.innerHTML = 'Sin resultados.'; return; } const hs = [...new Set(ls.map(l => l.uid))];
    o.innerHTML = `<div class="tw" style="max-height:260px"><table class="tbl"><thead><tr><th>Embarque</th><th>Lote</th><th>Fecha</th><th>Empacadora</th><th>Huerta</th><th class="num">t</th><th>Estado actual</th></tr></thead><tbody>${ls.slice(0, 120).map(l => `<tr><td class="mono tiny">${l.emb || '—'}</td><td class="mono tiny">${l.id}</td><td class="mono tiny">${l.fecha}</td><td class="mono tiny">${l.emp}</td><td class="mono tiny">${l.uid}</td><td class="num">${l.t}</td><td>${estChip(hById[l.uid].estado)}</td></tr>`).join('')}</tbody></table></div><div class="tiny" style="margin-top:6px">${ls.length} lotes · ${hs.length} huertas · ${fmt(ls.reduce((s, l) => s + l.t, 0), 1)} t · ${hs.some(u => !ESTADOS[hById[u].estado].eleg) ? '<b style="color:#B3261E">contiene fruta de huertas hoy no elegibles</b>' : 'todas las huertas elegibles hoy'}</div>`; };
  $('#cb', main).onclick = () => trace($('#cq', main).value); on(main, 'click', '[data-q]', (e, a) => { $('#cq', main).value = a.dataset.q; trace(a.dataset.q); });
  on(main, 'click', '[data-h]', (e, r) => window.__go('admin', 'huertas', { id: r.dataset.h }));
  $('#bx', main).onclick = () => download('balance_de_masa.csv', 'uid,municipio,cultivo,superficie_ha,capacidad_t,entregado_t,razon,senal,estado\n' + B.map(b => [b.h.uid, munName[b.h.mun], b.h.cul, pOf(b.h).ha, b.cap, b.ent, b.ratio.toFixed(3), b.flag, b.h.estado].join(',')).join('\n'), 'text/csv');
}

// ---------- Compensaciones ----------
function compensaciones(main) {
  let map;
  const draw = () => { if (map) map.destroy();
    const pend = H.filter(h => h.estado === 'Bloqueado' && dating(h).brk && !S.comp.some(c => c.uid === h.uid));
    main.innerHTML = hdr('Registro único de compensaciones', `Cada hectárea que compensa una huerta (${PARAMS.compensacion.min} a ${PARAMS.compensacion.max} ha de bosque por ha convertida) lleva geometría e identificador y queda bloqueada: no puede venderse dos veces.`, `${who()} <button class="btn pri" id="nw">${icon('plus', 14)} Registrar compensación</button>`) +
      `<div class="grid g4">${kpi({ l: 'Compensaciones registradas', v: fmt(S.comp.length), s: fmt(S.comp.reduce((s, c) => s + c.ha, 0), 1) + ' ha bloqueadas' })}${kpi({ l: 'Cumplidas', v: fmt(S.comp.filter(c => c.estado === 'Cumplida').length), s: 'huertas rehabilitadas', c: '#235B4E' })}${kpi({ l: 'Huertas bloqueadas sin compensación', v: fmt(pend.length), s: 'requieren proyecto y polígono', c: '#A8720F' })}${kpi({ l: 'Intentos de doble uso detectados', v: fmt(S.ledger.filter(e => e.acc === 'COMPENSACION_RECHAZADA').length), s: 'traslape con polígono ya asignado', c: '#B3261E' })}</div>
      <div class="grid g21" style="margin-top:14px"><div class="card pad0" style="height:460px;position:relative"><div id="mp" style="height:100%"></div></div><div class="card"><div class="ch"><h3>Registro</h3></div><div class="tw" style="max-height:400px"><table class="tbl"><thead><tr><th>ID</th><th>Huerta</th><th class="num">Req.</th><th class="num">Ha</th><th>Estado</th></tr></thead><tbody>${S.comp.slice().reverse().map(c => `<tr class="cl" data-c="${c.id}"><td class="mono tiny">${c.id}</td><td class="mono tiny">${c.uid}</td><td class="num">${c.req}</td><td class="num">${c.ha}</td><td>${chip(c.estado, c.estado === 'Cumplida' ? 'ok' : 'info')}</td></tr>`).join('')}</tbody></table></div></div></div>`;
    map = createMap($('#mp', main), { showAlerts: false, showLidar: false, showRest: false }); ['alertas', 'lidar', 'rest'].forEach(k => map.show(k, false));
    map.addLayer('comp', { type: 'poly', data: prepPolys({ features: S.comp.map(c => ({ type: 'Feature', properties: { id: c.id, uid: c.uid, estado: c.estado, ha: c.ha }, geometry: { type: 'Polygon', coordinates: [c.ring] } })) }), order: 25, pickable: true, minZ: 7, minPx: 3, dotR: 2.5, style: p => ({ fill: p.estado === 'Cumplida' ? '#235B4E' : '#235B4E', fa: .55, stroke: '#F2F4F0', lw: 1.4 }) });
    const tf = map.tipFn; map.tipFn = h => h.layer === 'comp' ? `<div class="mono tiny">${h.p.id}</div><div>${h.p.ha} ha · ${esc(h.p.estado)}</div><div class="tiny dim">Compensa ${h.p.uid}</div>` : tf(h);
    map.fitBounds([-102.8, 19.0, -101.3, 19.9], 20, false); attachControls($('#mp', main).parentElement, map, {});
    $('#nw', main).onclick = () => { const m = modal(`<h2>Registrar compensación</h2><label class="tiny">Huerta bloqueada<select id="hu" style="width:100%">${pend.slice(0, 200).map(h => `<option value="${h.uid}">${h.uid} · ${esc(munName[h.mun])} · requiere ${((pOf(h).aff || pOf(h).ha * .4) * ratioComp(h)).toFixed(2)} ha (${ratioComp(h)}:1)</option>`).join('')}</select></label><label class="tiny">Polígono receptor<select id="po" style="width:100%"><option value="new">Nuevo polígono en predio forestal receptor</option>${S.comp.slice(0, 30).map(c => `<option value="${c.id}">Reutilizar el polígono de ${c.id} (prueba de doble venta)</option>`).join('')}</select></label><label class="tiny">Clave catastral del predio receptor<input id="rc" value="16-000-000-00000" style="width:100%"></label><label class="tiny" style="display:flex;gap:6px;align-items:center;margin-top:6px"><input type="checkbox" id="tr" checked> Cambiar estado a «En restauración» (requiere dictaminador)</label><div style="display:flex;gap:8px;justify-content:flex-end;margin-top:12px"><button class="btn ghost" data-close>Cancelar</button><button class="btn pri" id="ok">Registrar y bloquear</button></div>`, { w: '560px' });
      m.q('#ok').onclick = () => { const h = hById[m.q('#hu').value]; if (!h) return; const pv = m.q('#po').value; const req = (pOf(h).aff || pOf(h).ha * .4) * ratioComp(h); const ring = pv === 'new' ? newCompRing(h, req * 1.03, 'N' + Date.now()) : S.comp.find(c => c.id === pv).ring;
        const r = registrarComp(h, ring, me(), m.q('#rc').value); if (!r.ok) { ledgerAppend(S.ledger, me().id, 'COMPENSACION_RECHAZADA', h.uid, r.why); toast(r.why, 'warn'); return; }
        if (m.q('#tr').checked) { const t = transit(h, 'En restauración', me(), 'Proyecto aprobado y compensación registrada', [r.c.id], ledgerAppend); if (!t.ok) toast('Compensación registrada; el cambio de estado requiere: ' + t.why, 'warn'); }
        m.close(); toast('Compensación ' + r.c.id + ' registrada y bloqueada'); draw(); }; };
  };
  draw(); on(main, 'click', '[data-c]', (e, r) => { const c = S.comp.find(x => x.id === r.dataset.c); const xs = c.ring.map(p => p[0]), ys = c.ring.map(p => p[1]); map.fitBounds([Math.min(...xs), Math.min(...ys), Math.max(...xs), Math.max(...ys)], 120); });
  return () => map && map.destroy();
}

// ---------- Recaudación ----------
function recaudacionView(main) {
  const rec = recaudacion(); const tot = rec.reduce((s, x) => s + x[1], 0); const lab = H.filter(h => h.senasica).map(h => ({ h, l: laboral(h) })); const isnNew = lab.filter(x => x.l.registro && !x.l.isn).length;
  const catDiff = H.filter(h => { const r = (h.catastral.charCodeAt(12) % 10); return r === 3; }).length;
  main.innerHTML = hdr('Recaudación', 'La plataforma emite la línea de captura del derecho con la secretaría de finanzas y muestra el retorno fiscal: derechos cobrados, contribuyentes incorporados al ISN por el cruce con IMSS y catastro actualizado.', who()) +
    `<div class="note tiny" style="margin-bottom:12px"><b>Variante a evaluar jurídicamente:</b> cobrar el derecho a la empacadora por lote verificado, no al productor (pocos contribuyentes, bajo costo de cobro, ligado al servicio real de consulta). Viabilidad por verificar en el entregable 8; la cuota se fija a costo de recuperación. Montos ilustrativos.</div>
    <div class="grid g4">${kpi({ l: 'Derechos por lote verificado · temporada', v: '$' + fmt(tot / 1e6, 2) + ' M', s: fmt(S.lotes.length) + ' lotes × $' + PARAMS.cuotaLote })}${kpi({ l: 'Contribuyentes ISN detectados', v: fmt(isnNew), s: 'registro patronal IMSS sin alta estatal', c: '#235B4E' })}${kpi({ l: 'Claves catastrales conciliadas', v: fmt(H.length - catDiff), s: fmt(catDiff) + ' con diferencia de superficie > 10 %', c: '#235B4E' })}${kpi({ l: 'Empacadoras contribuyentes', v: EMP.length, s: 'punto de control y de cobro' })}</div>
    <div class="grid g2" style="margin-top:14px"><div class="card"><div class="ch"><h3>Derechos por mes</h3>${tag('demo')}</div>${ch.bars(rec.map(([k, v]) => ({ label: k.slice(5) + '/' + k.slice(2, 4), value: Math.round(v / 1000), color: '#235B4E' })), { h: 220 })}<div class="tiny dim">Miles de pesos.</div></div>
    <div class="card"><div class="ch"><h3>Emitir línea de captura</h3></div><label class="tiny">Contribuyente<select id="em" style="width:100%">${EMP.slice(0, 20).map(e => `<option>${e.id} · ${esc(e.nombre)}</option>`).join('')}</select></label><label class="tiny">Lotes verificados en el periodo<input type="number" id="nl" value="42" style="width:100%"></label><button class="btn pri" id="lc" style="margin-top:8px">Generar línea de captura</button><div id="lo" style="margin-top:10px"></div></div></div>`;
  $('#lc', main).onclick = () => { const n = +$('#nl', main).value || 0; const monto = n * PARAMS.cuotaLote; const emp = $('#em', main).value.split(' · ')[0]; const lc = lineaCaptura('DERECHO-VERIF', monto, emp); ledgerAppend(S.ledger, me().id, 'LINEA_CAPTURA', emp, lc);
    $('#lo', main).innerHTML = `<div class="verdict ok"><div><div class="big mono" style="font-size:15px">${lc}</div><div class="tiny dim">$${fmt(monto, 2)} · ${n} lotes · vigencia 3 días hábiles · <b>SIMULADA</b>: en producción la genera el servicio de la secretaría de finanzas.</div></div></div>`; };
}

// ---------- Laboral y agua ----------
function laboralAgua(main) {
  let tab = 'laboral', map;
  const draw = () => { if (map) { map.destroy(); map = null; }
    main.innerHTML = hdr('Módulos laboral y de agua', 'Cruce huerta-IMSS (trabajo digno, previsto en el acuerdo federal) y concesiones de pozos de CONAGUA frente a ollas de agua detectadas en imagen.', who()) + `<div class="tabs" id="tb"><button data-t="laboral" class="${tab === 'laboral' ? 'on' : ''}">Laboral (IMSS)</button><button data-t="agua" class="${tab === 'agua' ? 'on' : ''}">Agua (CONAGUA)</button></div><div id="bd"></div>`;
    const bd = $('#bd', main);
    if (tab === 'laboral') { const L = H.filter(h => h.senasica).map(h => ({ h, l: laboral(h) })); const sin = L.filter(x => !x.l.registro), br = L.filter(x => x.l.registro && x.l.brecha);
      bd.innerHTML = `<div class="grid g4">${kpi({ l: 'Huertas exportadoras', v: fmt(L.length) })}${kpi({ l: 'Sin registro patronal IMSS', v: fmt(sin.length), c: '#B3261E' })}${kpi({ l: 'Con brecha de aseguramiento', v: fmt(br.length), s: `< 60 % de ${PARAMS.trabajadoresHa} trabajadores/ha`, c: '#A8720F' })}${kpi({ l: 'Trabajadores asegurados', v: fmt(L.reduce((s, x) => s + x.l.asegurados, 0)), s: 'de ' + fmt(L.reduce((s, x) => s + x.l.esperados, 0)) + ' esperados' })}</div>
      <div class="card" style="margin-top:14px"><div class="ch"><h3>Huertas con señal laboral</h3>${tag('demo')}</div><div class="tw" style="max-height:420px"><table class="tbl"><thead><tr><th>Huerta</th><th>Municipio</th><th class="num">Ha</th><th>Registro patronal</th><th class="num">Asegurados</th><th class="num">Esperados</th><th>ISN estatal</th></tr></thead><tbody>${sin.concat(br).slice(0, 200).map(x => `<tr><td class="mono tiny">${x.h.uid}</td><td>${esc(munName[x.h.mun])}</td><td class="num">${fmt(pOf(x.h).ha, 1)}</td><td class="mono tiny">${x.l.registro || '<span class="chip bad">sin registro</span>'}</td><td class="num">${x.l.asegurados}</td><td class="num">${x.l.esperados}</td><td>${x.l.isn ? chip('Alta', 'ok') : chip('Sin alta', 'warn')}</td></tr>`).join('')}</tbody></table></div><div class="tiny dim" style="margin-top:6px">El cruce requiere convenio con IMSS; el mismo cruce alimenta el padrón del ISN.</div></div>`; }
    else { const sinT = S.ollas.filter(o => !o.pozo), post = S.ollas.filter(o => o.conv && +o.det >= o.conv);
      bd.innerHTML = `<div class="grid g4">${kpi({ l: 'Ollas detectadas en imagen', v: fmt(S.ollas.length), s: fmt(S.ollas.reduce((s, o) => s + o.vol, 0) / 1000, 0) + ' mil m³ estimados' })}${kpi({ l: 'Sin concesión a < 500 m', v: fmt(sinT.length), c: '#B3261E' })}${kpi({ l: 'Pozos con título (REPDA)', v: fmt(S.pozos.length), c: '#235B4E' })}${kpi({ l: 'Ollas construidas tras la conversión', v: fmt(post.length), s: 'indicador de cambio de uso de suelo', c: '#A8720F' })}</div>
      <div class="grid g21" style="margin-top:14px"><div class="card pad0" style="height:440px;position:relative"><div id="mp" style="height:100%"></div></div><div class="card"><div class="ch"><h3>Ollas sin concesión cercana</h3>${tag('demo')}</div><div class="tw" style="max-height:380px"><table class="tbl"><thead><tr><th>Olla</th><th>Huerta</th><th class="num">m²</th><th class="num">Pozo más cercano</th></tr></thead><tbody>${sinT.slice(0, 150).map(o => `<tr><td class="mono tiny">${o.id}</td><td class="mono tiny">${o.uid}</td><td class="num">${fmt(o.m2)}</td><td class="num">${fmt(o.dist)} m</td></tr>`).join('')}</tbody></table></div></div></div>`;
      map = createMap($('#mp', bd), { showAlerts: false, showLidar: false, showRest: false }); ['alertas', 'lidar', 'rest'].forEach(k => map.show(k, false));
      map.addLayer('pozos', { type: 'point', data: prepPts(S.pozos), order: 36, pickable: true, minZ: 8, style: () => ({ fill: '#235B4E', stroke: '#0F2A24', r: 4 }) });
      map.addLayer('ollas', { type: 'point', data: prepPts(S.ollas), order: 37, pickable: true, minZ: 8, style: p => ({ shape: 'diamond', fill: p.pozo ? '#F2F4F0' : '#B3261E', stroke: '#0F2A24', r: 5 }) });
      const tf = map.tipFn; map.tipFn = h => h.layer === 'pozos' ? `<div class="mono tiny">${h.p.id}</div><div>Pozo con título · ${esc(h.p.uso)}</div><div class="tiny dim">${fmt(h.p.vol)} m³/año</div>` : h.layer === 'ollas' ? `<div class="mono tiny">${h.p.id}</div><div>Olla ${fmt(h.p.m2)} m² · detectada ${h.p.det}</div><div class="tiny dim">${h.p.pozo ? 'Concesión cercana ' + h.p.pozo : 'Sin concesión a < 500 m'}</div>` : tf(h);
      map.fitBounds([-102.6, 19.2, -101.7, 19.8], 20, false); attachControls($('#mp', bd).parentElement, map, {}); }
  };
  draw(); on(main, 'click', '#tb button', (e, b) => { tab = b.dataset.t; draw(); }); return () => map && map.destroy();
}
export const views = { balance: balanceView, compensaciones, recaudacion: recaudacionView, laboral: laboralAgua };
