// Origen certificado (temporada 2026-2027): preparación, constancia ambiental, trazabilidad de exportación.
import { $, on, esc, fmt, toast, download, fdate as fd0 } from '../util.js';
const fdate = s => fd0(String(s).length === 10 ? s + 'T12:00:00' : s);
import { icon, modal, tag, kpi } from '../ui.js';
import { S, P, munName } from '../state.js';
import { createMap, attachControls } from '../mapkit.js';
import { H, hById, hByPid, PARAMS, me, ROLES } from '../domain/core.js';
import { ACUERDO, COMP, COMP_ORD, PROC, ETAPAS, metricasEtapas, EST_C, ST_COMP, constancia, preparacion, emitirConstancias, trazar, detalleLote, detalleEmbarque, universo } from '../domain/origen.js';
import { EMP } from '../domain/trace.js';
import { hdr, who, estChip } from './verif.js';
import { Doc, qrSVG, VERIFY_BASE, hex } from '../pdf.js';
import { PARAMS as P2 } from '../domain/core.js';
import { cargarOWPDemo, vaciarOWP, alertasGeocerca, lotesFueraSinAlerta, constanciaExportador, emitirConstanciaExportador, foliosDeEmbarque, EXPORTADORES, expediente, semChip } from '../domain/mce.js';

export const cChip = e => `<span class="chip ${EST_C[e] ? EST_C[e].k : ''}">${esc(e)}</span>`;
const sChip = s => `<span class="chip ${ST_COMP[s][1]}">${ST_COMP[s][0]}</span>`;
const pct = (a, b) => b ? Math.round(100 * a / b) : 0;
const fuente = () => `<div class="tiny dim" style="margin-top:6px">Fuente del acuerdo: ${esc(ACUERDO.fuente)}. Parámetros de la constancia: versión ${esc(PARAMS.constancia.version)}, ajustables cuando se publiquen las reglas.</div>`;

// ---------- Ficha de constancia (compartida: admin, productor, público) ----------
export function constanciaCard(c, { publico = false } = {}) {
  const em = S.constancias[c.uid];
  return `<div class="verdict ${EST_C[c.estado].k === 'ok' ? 'ok' : EST_C[c.estado].k === 'bad' ? 'fail' : 'warn'}"><div style="flex:1"><div class="big">Constancia ambiental de origen · ${esc(c.estado)}</div><div class="tiny dim">${esc(EST_C[c.estado].d)}</div></div><div class="mono tiny" style="text-align:right">${c.folio}<br>Temporada ${c.vigencia.id}${em ? '<br><span class="chip ok">Emitida y firmada</span>' : '<br><span class="chip">Sin emitir</span>'}</div></div>
  <table class="tbl" style="margin-top:10px"><thead><tr><th>Componente</th><th>Resultado</th>${publico ? '' : '<th>Evidencia</th>'}</tr></thead><tbody>${c.comps.map(x => `<tr><td>${esc(x.n)}${PARAMS.constancia.bloqueantes.includes(x.k) ? ' <span class="tiny dim">(indispensable)</span>' : ''}</td><td>${sChip(x.estado)}</td>${publico ? '' : `<td class="tiny">${esc(x.det)}${x.accion && x.estado !== 'cumple' ? `<div style="color:var(--warn)">→ ${esc(x.accion)}</div>` : ''}</td>`}</tr>`).join('')}</tbody></table>
  ${c.plazo && !publico ? `<div class="note tiny" style="margin-top:8px">Condicionada: debe subsanar ${c.pend.map(x => esc(x.n.toLowerCase())).join(', ')} a más tardar el <b>${c.plazo}</b> (${PARAMS.constancia.subsanacionDH} días hábiles).</div>` : ''}`;
}
export function constanciaPDF(c) {
  const h = hById[c.uid], em = S.constancias[c.uid]; const d = new Doc(); const G = hex('#235B4E');
  d.rect(0, 752, 612, 40, G).text(56, 767, 'Constancia Ambiental de Origen', 16, true, [242, 244, 240]).text(400, 767, 'DOCUMENTO DE DEMOSTRACIÓN', 8, true, [188, 149, 92]);
  d.y = 730; d.text(56, d.y, `${PROC.id} · folio ${c.folio} · temporada ${c.vigencia.id}`, 10, true, [138, 106, 53]); d.y -= 22;
  d.qr(462, 610, 94, VERIFY_BASE + c.folio); d.text(462, 598, 'Verificación pública', 8, false, [69, 84, 79]);
  d.kv('Resultado', c.estado, { w: 390 }); d.kv('Vigencia', `${fdate(c.vigencia.ini)} – ${fdate(c.vigencia.fin)}`, { w: 390 }); d.kv('Huerta (UID)', c.uid, { w: 390 }); d.kv('Registro para exportación', h.senasica || '—', { w: 390 }); d.kv('Municipio', c.municipio, { w: 390 }); d.kv('Cultivo · superficie', `${c.cultivo} · ${fmt(c.ha, 2)} ha`, { w: 390 });
  d.y = Math.min(d.y, 590); d.h('Criterios de certificación');
  COMP_ORD().forEach(cp => { const x = c.comps.find(y => y.k === cp.k); d.kv(`${cp.cod} ${cp.n}`, `${ST_COMP[x.estado][0]} — ${x.det}${x.accion && x.estado !== 'cumple' ? ' · Acción: ' + x.accion : ''}`, { kw: 210 }); });
  if (c.plazo) d.para(`Condicionada: subsanar las observaciones a más tardar el ${c.plazo}.`, { size: 9.5, bold: true });
  d.h('Integridad'); d.kv('Huella SHA-256', c.sha, { kw: 120 }); d.kv('Firma electrónica', em ? `${em.firma} · e.firma (simulada) · ${em.ts}` : 'Pendiente de emisión', { kw: 120 }); d.kv('Sello de tiempo', em ? em.sello : '—', { kw: 120 }); d.kv('Verificación', VERIFY_BASE + c.folio, { kw: 120 });
  return d.bytes();
}
export function constanciaHTML(c) {
  const h = hById[c.uid], em = S.constancias[c.uid]; const row = (k, v) => `<tr><th>${k}</th><td>${v}</td></tr>`;
  return `<!doctype html><html lang="es"><head><meta charset="utf-8"><title>${c.folio}</title><style>body{font:13px/1.55 "IBM Plex Sans",system-ui,sans-serif;color:#1B2A26;background:#F2F4F0;max-width:820px;margin:0 auto;padding:28px}main{background:#FFFFFF;padding:28px 32px;border-top:6px solid #235B4E}h1{font:600 21px "Source Serif 4",Georgia,serif;color:#235B4E;margin:0}h2{font:600 15px "Source Serif 4",Georgia,serif;color:#235B4E;margin:20px 0 6px;padding-bottom:3px;border-bottom:2px solid #BC955C}table{border-collapse:collapse;width:100%}th,td{border:1px solid rgba(111,124,119,.3);padding:5px 8px;text-align:left;vertical-align:top}th{width:34%;background:#F2F4F0;font-weight:600}.m{font-family:"IBM Plex Mono",monospace}.demo{background:#9F2241;color:#F2F4F0;padding:6px 10px;font-size:11.5px;margin-bottom:14px}.inst{color:#45544F;font-size:12px;letter-spacing:.04em;text-transform:uppercase;margin-bottom:4px}.res{font:600 18px "Source Serif 4",Georgia,serif;color:${EST_C[c.estado].c}}.ok{color:#2E7D32}.warn{color:#A8720F}.bad{color:#B3261E}.foot{font-size:11px;color:#6F7C77;margin-top:18px}</style></head><body><main>
  <div class="demo">DOCUMENTO DE DEMOSTRACIÓN — datos, firma y sello simulados; sin validez jurídica</div>
  <div class="inst">Gobierno del Estado · Módulo de Verificación y Dictamen Forestal</div><h1>Constancia ambiental de origen</h1>
  <table style="margin-top:10px">${row('Folio', `<span class="m">${c.folio}</span>`)}${row('Temporada de exportación', `${c.vigencia.id} (${fdate(c.vigencia.ini)} – ${fdate(c.vigencia.fin)})`)}${row('Resultado', `<span class="res">${esc(c.estado)}</span>`)}${row('Marco', 'Acuerdo de origen certificado para la exportación de aguacate a EE. UU. (oct-2026); reglas de acreditación pendientes de publicación. Versión de criterios: ' + esc(PARAMS.constancia.version))}</table>
  <h2>Huerta</h2><table>${row('UID', `<span class="m">${c.uid}</span>`)}${row('Registro para exportación', h.senasica || '—')}${row('Municipio', esc(c.municipio))}${row('Cultivo · superficie', `${esc(c.cultivo)} · ${fmt(c.ha, 2)} ha`)}${row('Capacidad productiva estimada', fmt(c.cap, 1) + ' t por temporada')}</table>
  <h2>Componentes evaluados</h2><table><tr><th>Componente</th><td><b>Resultado y evidencia</b></td></tr>${c.comps.map(x => row(esc(x.n) + (PARAMS.constancia.bloqueantes.includes(x.k) ? ' (indispensable)' : ''), `<b class="${ST_COMP[x.estado][1] === 'ok' ? 'ok' : ST_COMP[x.estado][1] === 'bad' ? 'bad' : 'warn'}">${ST_COMP[x.estado][0]}</b> · ${esc(x.det)}${x.accion && x.estado !== 'cumple' ? `<br>Acción requerida: ${esc(x.accion)}` : ''}`)).join('')}</table>
  ${c.plazo ? `<p><b>Condicionada:</b> la persona productora debe subsanar las observaciones a más tardar el ${c.plazo}; de lo contrario la constancia se suspende.</p>` : ''}
  <h2>Verificación</h2><div style="display:flex;gap:16px;align-items:center">${qrSVG(VERIFY_BASE + c.folio, 120)}<div style="font-size:12px">Escanee el código o abra <span class="m">${VERIFY_BASE + c.folio}</span>. La verificación es pública y no requiere cuenta.</div></div>
  <h2>Integridad</h2><table>${row('Huella SHA-256', `<span class="m" style="font-size:11px">${c.sha}</span>`)}${row('Firma electrónica', em ? `${em.firma} · e.firma (simulada) · ${em.ts}` : 'Pendiente de emisión')}${row('Sello de tiempo', em ? em.sello : '—')}${row('Verificación', 'Consulte el folio en el portal ciudadano (Consulta de elegibilidad) o pregunte a Arbolín.')}</table>
  <div class="foot">Esta constancia no publica datos personales del titular. Las empacadoras la consultan automáticamente al recibir cada lote.</div></main></body></html>`;
}
function abrirConstancia(uid, { publico = false } = {}) {
  const c = constancia(hById[uid]); const h = hById[uid];
  const m = modal(`<div class="ch"><h2 class="mono">${uid}</h2><div class="sp">${estChip(h.estado)} <button class="btn sm ghost" data-close>✕</button></div></div><div class="tiny dim" style="margin:4px 0 10px">${esc(c.municipio)} · ${esc(c.cultivo)} · ${fmt(c.ha, 2)} ha · capacidad ${fmt(c.cap, 1)} t</div>${constanciaCard(c, { publico })}
    <div style="display:flex;gap:8px;justify-content:flex-end;margin-top:12px;flex-wrap:wrap"><button class="btn ghost" id="cpdf">${icon('download', 14)} PDF con QR</button><button class="btn ghost" id="ctz">${icon('layers', 14)} Ver trazabilidad</button>${publico ? '' : `<button class="btn" id="cem" ${S.constancias[uid] || !['Vigente', 'Condicionada'].includes(c.estado) ? 'disabled' : ''}>${icon('shield', 14)} Emitir y firmar</button>`}<button class="btn pri" id="cdl">${icon('download', 14)} Descargar constancia</button></div>`, { w: '760px' });
  m.q('#cdl').onclick = () => download(`constancia_${c.folio}.html`, constanciaHTML(constancia(hById[uid])), 'text/html');
  m.q('#ctz').onclick = () => { m.close(); window.__go('admin', 'trazabilidad', { q: uid }); };
  m.q('#cpdf').onclick = () => download(`constancia_${c.folio}.pdf`, constanciaPDF(constancia(hById[uid])), 'application/pdf');
  const e = m.q('#cem'); if (e) e.onclick = () => { const r = emitirConstancias(me(), [uid]); if (!r.ok) return toast(r.why, 'warn'); toast('Constancia emitida y firmada'); m.close(); abrirConstancia(uid); };
}

// ---------- Admin: Certificación de origen (procedimiento estandarizado PEC-CAO-01) ----------
const COL = { 'Vigente': '#2E7D32', 'Condicionada': '#BC955C', 'En trámite': '#235B4E', 'No procede': '#B3261E' };
export function manualHTML() {
  const M = metricasEtapas(); const row = (k, v) => `<tr><th>${k}</th><td>${v}</td></tr>`;
  return `<!doctype html><html lang="es"><head><meta charset="utf-8"><title>${PROC.id} · Manual del procedimiento</title><style>body{font:13px/1.6 "IBM Plex Sans",system-ui,sans-serif;color:#1B2A26;background:#F2F4F0;max-width:900px;margin:0 auto;padding:28px}main{background:#FFFFFF;padding:30px 36px;border-top:6px solid #235B4E}h1{font:600 24px "Source Serif 4",Georgia,serif;color:#235B4E;margin:4px 0}h2{font:600 16px "Source Serif 4",Georgia,serif;color:#235B4E;margin:24px 0 8px;padding-bottom:3px;border-bottom:2px solid #BC955C}table{border-collapse:collapse;width:100%;margin-top:6px}th,td{border:1px solid rgba(111,124,119,.3);padding:6px 8px;text-align:left;vertical-align:top}th{background:#F2F4F0;font-weight:600}.demo{background:#9F2241;color:#F2F4F0;padding:6px 10px;font-size:11.5px;margin-bottom:14px}.code{font-family:"IBM Plex Mono",monospace;color:#8A6A35}.meta{display:flex;gap:18px;flex-wrap:wrap;color:#45544F;font-size:12px;margin-top:6px}.ok{color:#2E7D32;font-weight:600}.bad{color:#B3261E;font-weight:600}</style></head><body><main>
  <div class="demo">DOCUMENTO DE DEMOSTRACIÓN — procedimiento modelo; datos y firmas simulados</div>
  <div class="code">${PROC.id} · versión ${PROC.version} · vigente desde ${fdate(PROC.vigencia)}</div><h1>${esc(PROC.nombre)}</h1>
  <div class="meta"><span>Alcance: ${esc(PROC.alcance)}</span><span>Temporada: ${ACUERDO.temporada.id}</span></div>
  <h2>1. Objeto</h2><p>Certificar que el aguacate destinado a Estados Unidos proviene de huertas que no se establecieron mediante la tala de bosques, que cumplen sus obligaciones hídricas, de restauración y laborales, y que su fruta se rastrea de la huerta a la frontera sin mezclarse con fruta de origen no autorizado.</p>
  <h2>2. Marco de referencia</h2><p>Acuerdo de origen certificado para la exportación de aguacate a Estados Unidos (octubre de 2026): trazabilidad reforzada y constancia ambiental. Los parámetros de este procedimiento se ajustan a las reglas federales de acreditación cuando se publiquen.</p>
  <h2>3. Etapas del procedimiento</h2><table><tr><th>#</th><th>Etapa</th><th>Responsable</th><th>Entrada</th><th>Salida</th><th>Tiempo estándar</th></tr>${ETAPAS.map(e => `<tr><td class="code">${e.n}</td><td><b>${esc(e.t)}</b></td><td>${esc(e.rol)}</td><td>${esc(e.ent)}</td><td>${esc(e.sal)}</td><td>${esc(e.tiempo)}</td></tr>`).join('')}</table>
  <h2>4. Criterios de certificación</h2><table><tr><th>Código</th><th>Criterio</th><th>Tipo</th><th>Evidencia</th><th>Verificación</th><th>Umbral</th></tr>${COMP_ORD().map(c => `<tr><td class="code">${c.cod}</td><td><b>${esc(c.n)}</b></td><td>${PARAMS.constancia.bloqueantes.includes(c.k) ? '<span class="bad">Indispensable</span>' : 'Subsanable'}</td><td>${esc(c.doc)}</td><td>${esc(c.ins)}</td><td>${esc(c.par)}</td></tr>`).join('')}</table>
  <h2>5. Resultados</h2><table>${Object.entries(EST_C).filter(([k]) => k !== 'No aplica').map(([k, v]) => row(k, esc(v.d) + (k === 'Condicionada' ? ` Plazo de subsanación: ${PARAMS.constancia.subsanacionDH} días hábiles.` : ''))).join('')}</table>
  <h2>6. Vigencia, suspensión y renovación</h2><p>La constancia vale por la temporada ${ACUERDO.temporada.id} (${fdate(ACUERDO.temporada.ini)} – ${fdate(ACUERDO.temporada.fin)}). El monitoreo satelital es continuo: si se confirma una nueva alerta en la huerta, la constancia se suspende de forma automática hasta que exista dictamen. Una constancia condicionada se suspende si no se subsana en plazo.</p>
  <h2>7. Separación de funciones</h2><p>Quien detecta no dictamina; quien dictamina no resuelve el recurso; la emisión requiere declaración de conflicto de interés vigente y cartera territorial asignada. Cada acción queda en una bitácora encadenada con huella SHA-256.</p>
  <h2>8. Trazabilidad en la cadena</h2><p>La empacadora consulta automáticamente la constancia de la huerta en cada recepción; el sistema rechaza fruta de huertas sin constancia, de estados no autorizados o que excede la capacidad productiva (balance de masa). Cada lote queda ligado a su huerta, su inspección y su cargamento.</p>
  <h2>9. Consulta pública y datos personales</h2><p>Cualquier persona puede verificar una constancia por su folio CAO o por el identificador de la huerta. No se publican nombres, RFC ni datos laborales individuales.</p>
  <h2>10. Estado actual del programa</h2><table>${row('Huertas en el programa', fmt(M.R.n))}${row('Certificables (vigentes + condicionadas)', `${fmt(M.listas)} (${pct(M.listas, M.R.n)} %)`)}${row('Constancias emitidas', fmt(M.emit))}${row('En proceso', fmt(M.R.tram.length))}${row('Denegadas', fmt(M.R.np.length))}</table>
  </main></body></html>`;
}
function origenView(main) {
  let filt = 'No procede', modo = 'huertas', map = null;
  const draw = () => {
    if (map) { map.destroy(); map = null; }
    const M = metricasEtapas(), R = M.R; const pctOk = pct(M.listas, R.n);
    const perMun = R.per.map(m => ({ ...m, ok: m.Vigente + m.Condicionada, p: pct(m.Vigente + m.Condicionada, m.n) })).sort((a, b) => b.n - a.n);
    main.innerHTML = `<div class="page-h" style="align-items:center"><div><div class="mono tiny" style="color:var(--goldt);font-weight:600;letter-spacing:.06em">${PROC.id} · VERSIÓN ${PROC.version} · VIGENTE DESDE ${fdate(PROC.vigencia).toUpperCase()}</div><h1>Certificación de Origen · Aguacate de exportación</h1><p>Procedimiento estandarizado en <b>7 etapas</b> y <b>6 criterios</b>. Cada huerta aprobada recibe una <b>Constancia Ambiental de Origen</b> con folio verificable; cada lote se rastrea de la huerta a la frontera.</p></div><div class="act">${tag('demo')} ${who()} <button class="btn" id="man">${icon('book', 14)} Manual del procedimiento</button> <button class="btn pri" id="emi">${icon('shield', 14)} Emitir constancias</button></div></div>
      <div class="arb-band" style="margin-bottom:14px;padding:0;overflow:hidden;align-items:stretch">${[['Huertas en el programa', fmt(R.n), 'registradas con UID'], ['Certificables', fmt(M.listas), pctOk + ' % del padrón'], ['Constancias emitidas', fmt(M.emit), 'con e.firma y sello'], ['En proceso', fmt(R.tram.length), 'análisis, campo o audiencia'], ['Denegadas', fmt(R.np.length), 'requieren restauración'], ['Capacidad certificable', fmt(R.capOk / 1000, 1) + ' mil t', pct(R.capOk, R.cap) + ' % del volumen']].map((x, i) => `<div style="flex:1;padding:14px 16px;${i ? 'border-left:1px solid rgba(242,244,240,.14)' : ''}"><div class="tiny" style="color:rgba(242,244,240,.75);text-transform:uppercase;letter-spacing:.06em">${x[0]}</div><div class="mono" style="font-size:26px;font-weight:600;color:${i === 4 ? '#F2F4F0' : '#BC955C'};margin:2px 0">${x[1]}</div><div class="tiny" style="color:rgba(242,244,240,.75)">${x[2]}</div></div>`).join('')}<div style="padding:14px 18px;background:var(--gdd);text-align:center;min-width:130px;display:flex;flex-direction:column;justify-content:center"><div class="tiny" style="color:rgba(242,244,240,.75)">INICIO DE TEMPORADA</div><div class="mono" style="font-size:30px;font-weight:600;color:#BC955C;line-height:1.1">T−${R.nat}</div><div class="tiny" style="color:rgba(242,244,240,.75)">${fdate(ACUERDO.temporada.ini)}</div></div></div>
      <div class="card"><div class="ch"><h3>Flujo del procedimiento</h3><div class="sp"><span class="tiny dim">cifras en tiempo real</span></div></div>
        <div style="position:relative;margin-top:14px"><div style="position:absolute;left:4%;right:4%;top:21px;height:3px;background:linear-gradient(90deg,#235B4E,#BC955C)"></div><div style="display:grid;grid-template-columns:repeat(7,minmax(0,1fr));gap:10px;position:relative">${ETAPAS.map(e => { const v = M.m[e.k]; return `<div style="text-align:center"><div style="width:44px;height:44px;border-radius:50%;margin:0 auto;background:var(--panel);border:3px solid ${e.n === 7 ? '#BC955C' : '#235B4E'};display:flex;align-items:center;justify-content:center;color:var(--g);font:600 16px var(--mono)">${e.n}</div><div style="font-weight:600;font-size:13px;margin-top:8px;line-height:1.25;min-height:32px">${esc(e.t)}</div><div class="tiny dim" style="min-height:28px">${esc(e.rol)}</div><div class="mono" style="font-size:22px;font-weight:600;color:var(--g);margin-top:4px">${fmt(v[0])}</div><div class="tiny" style="color:var(--mut)">${esc(v[1])}</div><div class="tiny" style="color:var(--goldt);margin-top:2px">${esc(v[2])}</div><div style="margin-top:8px;padding-top:6px;border-top:1px dashed var(--line2)" class="tiny dim">${icon('clock', 11)} ${esc(e.tiempo)}</div></div>`; }).join('')}</div></div></div>
      <div class="grid g21" style="margin-top:14px"><div class="card pad0" style="height:520px;position:relative"><div id="cmap" style="height:100%"></div>
          <div style="position:absolute;top:10px;left:12px;z-index:3;background:var(--panel);border:1px solid var(--line2);border-radius:8px;padding:8px 10px;box-shadow:0 2px 10px rgba(15,42,36,.15)"><div style="font:600 14px var(--serif);color:var(--g)">Mapa de certificaciones</div><div class="tabs" id="cmode" style="margin:4px 0 0;border:0"><button data-m="huertas" class="${modo === 'huertas' ? 'on' : ''}">Por huerta</button><button data-m="municipios" class="${modo === 'municipios' ? 'on' : ''}">Por municipio</button></div></div>
          <div style="position:absolute;left:12px;bottom:34px;z-index:3;background:var(--panel);border:1px solid var(--line2);border-radius:8px;padding:8px 10px;font-size:12px">${modo === 'huertas' ? Object.entries(COL).map(([k, c]) => `<div style="display:flex;align-items:center;gap:6px;margin:2px 0"><i class="dot" style="background:${c}"></i>${k} <span class="mono dim" style="margin-left:auto;padding-left:10px">${fmt(R.U.filter(x => x.estado === k).length)}</span></div>`).join('') : [['≥ 80 % certificable', '#2E7D32'], ['60 – 79 %', '#BC955C'], ['40 – 59 %', '#A8720F'], ['< 40 %', '#B3261E']].map(([k, c]) => `<div style="display:flex;align-items:center;gap:6px;margin:2px 0"><i class="dot" style="background:${c}"></i>${k}</div>`).join('')}</div></div>
        <div class="card" style="max-height:520px;overflow:auto"><div class="ch"><h3>Avance por municipio</h3></div>${perMun.map(m => `<div style="margin:9px 0"><div style="display:flex;justify-content:space-between;font-size:12.5px"><span><b>${esc(munName[m.mun])}</b> <span class="dim tiny">${m.n} huertas</span></span><span class="mono" style="color:${m.p >= 80 ? '#2E7D32' : m.p >= 60 ? '#8A6A35' : m.p >= 40 ? '#A8720F' : '#B3261E'};font-weight:600">${m.p} %</span></div><div style="display:flex;height:8px;border-radius:4px;overflow:hidden;background:var(--bg);margin-top:3px">${['Vigente', 'Condicionada', 'En trámite', 'No procede'].map(k => m[k] ? `<i title="${k}: ${m[k]}" style="width:${100 * m[k] / m.n}%;background:${COL[k]}"></i>` : '').join('')}</div></div>`).join('')}</div></div>
      <div class="card" style="margin-top:14px"><div class="ch"><h3>Criterios de certificación</h3><div class="sp"><span class="tiny dim">${esc(PARAMS.constancia.version)} · cumplimiento en el padrón</span></div></div><div class="grid g3" style="margin-top:10px">${COMP_ORD().map(cp => { const o = { cumple: 0, observacion: 0, no_cumple: 0, en_proceso: 0, no_aplica: 0 }; R.U.forEach(c => { o[c.comps.find(y => y.k === cp.k).estado]++; }); const base = R.n - o.no_aplica || 1; const ind = PARAMS.constancia.bloqueantes.includes(cp.k); return `<div style="border:1px solid var(--line);border-top:3px solid ${ind ? '#235B4E' : '#BC955C'};border-radius:8px;padding:12px;background:var(--panel)"><div style="display:flex;align-items:baseline;gap:8px"><span class="mono" style="color:var(--goldt);font-weight:600">${cp.cod}</span><b style="font-size:13.5px">${esc(cp.n)}</b><span class="chip ${ind ? 'info' : 'warn'}" style="margin-left:auto">${ind ? 'Indispensable' : 'Subsanable'}</span></div><dl class="kv" style="margin-top:8px;grid-template-columns:auto 1fr"><dt>Evidencia</dt><dd>${esc(cp.doc)}</dd><dt>Verificación</dt><dd>${esc(cp.ins)}</dd><dt>Umbral</dt><dd>${esc(cp.par)}</dd></dl><div style="display:flex;align-items:center;gap:8px;margin-top:8px"><div style="flex:1;height:8px;border-radius:4px;overflow:hidden;background:var(--bg);display:flex">${[['cumple', '#2E7D32'], ['en_proceso', '#235B4E'], ['observacion', '#A8720F'], ['no_cumple', '#B3261E']].map(([k, c]) => o[k] ? `<i title="${ST_COMP[k][0]}: ${o[k]}" style="width:${100 * o[k] / base}%;background:${c}"></i>` : '').join('')}</div><span class="mono tiny" style="text-align:right"><b>${pct(o.cumple, base)} %</b> cumple<br><span class="dim">aplica a ${fmt(base)}</span></span></div></div>`; }).join('')}</div><div class="tiny dim" style="margin-top:10px">Marco: acuerdo de origen certificado para la exportación de aguacate a EE. UU. (oct-2026). Umbrales parametrizables para homologarse con las reglas federales de acreditación.</div></div>
      <div class="card" style="margin-top:14px"><div class="ch"><h3>Expedientes de certificación</h3><div class="sp"><div class="tabs" id="cf" style="margin:0;border:0">${['No procede', 'En trámite', 'Condicionada', 'Vigente'].map(k => `<button data-f="${k}" class="${k === filt ? 'on' : ''}">${k} <span class="mono dim">${R.U.filter(c => c.estado === k).length}</span></button>`).join('')}</div></div></div>
        <div class="tw" style="max-height:420px"><table class="tbl"><thead><tr><th>Folio</th><th>Huerta</th><th>Municipio</th><th class="num">Ha</th><th>Estado legal</th><th>Resultado</th><th>Pendiente</th><th>Emisión</th></tr></thead><tbody>${R.U.filter(c => c.estado === filt).slice(0, 250).map(c => `<tr class="cl" data-c="${c.uid}"><td class="mono tiny">${c.folio}</td><td class="mono tiny">${c.uid}</td><td>${esc(c.municipio)}</td><td class="num">${fmt(c.ha, 1)}</td><td>${estChip(hById[c.uid].estado)}</td><td>${cChip(c.estado)}</td><td class="tiny">${esc(c.pend.map(x => (COMP.find(y => y.k === x.k) || {}).cod).filter(Boolean).join(' · ') || '—')}</td><td>${S.constancias[c.uid] ? '<span class="chip ok">emitida</span>' : ['Vigente', 'Condicionada'].includes(c.estado) ? '<span class="chip">por firmar</span>' : '—'}</td></tr>`).join('') || '<tr><td colspan="8" class="dim">Sin expedientes en esta categoría.</td></tr>'}</tbody></table></div></div>`;
    // ---- mapa de certificaciones ----
    const est = new Map(R.U.map(c => [c.uid, c.estado])); const pm = new Map(perMun.map(m => [m.mun, m.p]));
    map = createMap($('#cmap', main), { showAlerts: false, showLidar: false, showRest: false }); ['alertas', 'lidar', 'rest', 'predios', 'heat'].forEach(k => map.show(k, false));
    map.addLayer('caomun', { type: 'poly', data: P.mun.filter(o => pm.has(o.p.id)), order: 18, visible: modo === 'municipios', pickable: true, style: p => { const v = pm.get(p.id); const c = v >= 80 ? '#2E7D32' : v >= 60 ? '#BC955C' : v >= 40 ? '#A8720F' : '#B3261E'; return { fill: c, fa: .62, stroke: '#F2F4F0', lw: 1.2 }; } });
    map.addLayer('cao', { type: 'poly', data: P.predios.filter(o => { const h = hByPid[o.p.id]; return h && est.has(h.uid); }), order: 24, visible: modo === 'huertas', pickable: true, minZ: 6, minPx: 4, dotR: 2.4, style: p => { const c = COL[est.get(hByPid[p.id].uid)]; return { fill: c, fa: .85, stroke: c, lw: 1.1, alpha: 1 }; } });
    const tf = map.tipFn; map.tipFn = h => { if (h.layer === 'cao') { const c = constancia(hByPid[h.p.id]); return `<div class="mono tiny">${c.uid}</div><div><b>${esc(c.estado)}</b> · ${esc(c.municipio)}</div><div class="tiny dim">${c.folio}</div>`; } if (h.layer === 'caomun') { const m = perMun.find(x => x.mun === h.p.id); return `<b>${esc(h.p.name)}</b><div class="tiny">${m.p} % certificable · ${m.ok} de ${m.n} huertas</div>`; } return tf ? tf(h) : ''; };
    map.on('click', ({ hit }) => { if (hit && hit.layer === 'cao') abrirConstancia(hByPid[hit.p.id].uid); });
    requestAnimationFrame(() => map.fitBounds([-102.75, 18.95, -101.25, 19.95], 16, false));
    attachControls($('#cmap', main).parentElement, map, { sat: true });
    main.querySelectorAll('#cmode button').forEach(b => b.onclick = () => { modo = b.dataset.m; draw(); });
    main.querySelectorAll('#cf button').forEach(b => b.onclick = () => { filt = b.dataset.f; draw(); });
    $('#emi', main).onclick = () => { const r = emitirConstancias(me()); if (!r.ok) return toast(r.why, 'warn'); toast(`Se emitieron ${fmt(r.n)} constancias (${r.vig} vigentes, ${r.cond} condicionadas). Raíz de lote ${r.raiz.slice(0, 12)}… en bitácora`); draw(); };
    $('#man', main).onclick = () => download(`${PROC.id}_manual_del_procedimiento.html`, manualHTML(), 'text/html');
  };
  draw(); on(main, 'click', 'tr[data-c]', (e, r) => abrirConstancia(r.dataset.c));
  return () => { if (map) map.destroy(); };
}

// ---------- Admin: trazabilidad de exportación (huerta → frontera) ----------
function trazabilidad(main, params = {}) {
  const ej = S.embarques[Math.min(12, S.embarques.length - 1)].id;
  const riesgo = () => { const bad = new Set(universo().map(constancia).filter(c => c.estado === 'No procede').map(c => c.uid)); return S.embarques.filter(e => S.lotes.some(l => l.emb === e.id && bad.has(l.uid))); };
  main.innerHTML = hdr('Trazabilidad de exportación', 'De la huerta a la frontera: huerta de origen, corte, empacadora que recibió la fruta, inspecciones que superó y cargamento en que se incorporó. Ningún lote entra sin constancia ni con fruta de estados no autorizados.', `${tag('demo')} ${who()}`) +
    `<div class="card"><div style="display:flex;gap:8px;flex-wrap:wrap"><input id="tq" class="mono" placeholder="EMB-00012, LOT-000123, HUE-16044-00012 o CAO-2627-…" value="${esc(params.q || '')}" style="flex:1;min-width:240px"><button class="btn pri" id="tgo">Rastrear</button></div><div class="tiny dim" style="margin-top:6px">Ejemplos: <a data-t="${ej}" class="mono">${ej}</a> · <a data-t="${S.lotes[40].id}" class="mono">${S.lotes[40].id}</a> · <a data-t="${S.lotes[200].uid}" class="mono">${S.lotes[200].uid}</a>${riesgo()[0] ? ` · embarque con fruta hoy no certificable: <a data-t="${riesgo()[0].id}" class="mono">${riesgo()[0].id}</a>` : ''}</div><div id="tout" style="margin-top:12px"></div></div>
    <div class="card" style="margin-top:14px" id="owp"></div>
    <div class="grid g2" style="margin-top:14px"><div class="card"><div class="ch"><h3>Control de origen · mezclas bloqueadas</h3><div class="sp">${tag('demo')}</div></div><p class="tiny dim" style="margin:4px 0 8px">Fruta de huertas de estados no autorizados que intentó entrar a empacadoras de exportación. Sólo Michoacán y Jalisco están autorizados.</p><div class="tw" style="max-height:300px"><table class="tbl"><thead><tr><th>Fecha</th><th>Empacadora</th><th>Huerta declarada</th><th class="num">t</th><th>Motivo</th></tr></thead><tbody>${S.consultas.filter(c => c.origen).map(c => `<tr><td class="mono tiny">${c.ts.slice(0, 10)}</td><td class="mono tiny">${c.emp}</td><td class="mono tiny">${c.uid}</td><td class="num">${c.t}</td><td class="tiny">${esc(c.motivo)}</td></tr>`).join('')}</tbody></table></div></div>
    <div class="card"><div class="ch"><h3>Embarques con fruta que hoy no obtendría constancia</h3></div><p class="tiny dim" style="margin:4px 0 8px">Lotes de la temporada pasada recibidos cuando la huerta era elegible, de huertas que hoy no cumplen. Con la nueva regla se detienen en la recepción.</p><div class="tw" style="max-height:300px"><table class="tbl"><thead><tr><th>Embarque</th><th>Empacadora</th><th>Semana</th><th class="num">t</th><th></th></tr></thead><tbody>${riesgo().slice(0, 80).map(e => `<tr class="cl" data-t="${e.id}"><td class="mono tiny">${e.id}</td><td class="mono tiny">${e.emp}</td><td class="mono tiny">${e.semana}</td><td class="num">${e.t}</td><td><span class="chip bad">revisar</span></td></tr>`).join('') || '<tr><td colspan="5" class="dim">Ninguno.</td></tr>'}</tbody></table></div></div></div>`;
  const show = q => {
    const R = trazar(q); const o = $('#tout', main); if (!R) { o.innerHTML = '<div class="dim">Sin resultados. Revise el identificador.</div>'; return; }
    const l0 = R.lotes[0], d0 = detalleLote(l0), emp = EMP.find(e => e.id === l0.emp), E = R.embs[0], dE = E ? detalleEmbarque(E) : null;
    const malas = R.cs.filter(c => !['Vigente', 'Condicionada'].includes(c.estado));
    const st = (n, t, body, ok = true) => `<div style="flex:1;min-width:150px;background:var(--panel);border:1px solid var(--line);border-top:3px solid ${ok ? '#2E7D32' : '#B3261E'};border-radius:8px;padding:10px"><div class="tiny" style="color:var(--goldt);font-weight:600">${n}</div><div style="font-weight:600;margin:2px 0 4px">${t}</div><div class="tiny" style="color:var(--mut);line-height:1.45">${body}</div></div>`;
    const arrow = '<div style="align-self:center;color:var(--gold);font-size:18px">→</div>';
    o.innerHTML = `<div style="display:flex;gap:6px;flex-wrap:wrap;align-items:stretch">${st('1 · Huerta de origen', R.hs.length === 1 ? `<span class="mono">${R.hs[0].uid}</span>` : `${R.hs.length} huertas`, `${R.cs.filter(c => c.estado === 'Vigente').length} vigentes · ${R.cs.filter(c => c.estado === 'Condicionada').length} condicionadas${malas.length ? ` · <b style="color:#B3261E">${malas.length} sin constancia</b>` : ''}<br>${esc([...new Set(R.hs.map(h => munName[h.mun]))].slice(0, 3).join(', '))}`, !malas.length)}${arrow}${st('2 · Corte', d0.corte, `Cuadrilla ${d0.cuadrilla} · ${d0.cortadores} cortadores<br>${esc(d0.asegurados)}`)}${arrow}${st('3 · Recepción', `<span class="mono">${l0.emp}</span>`, `${esc(emp ? emp.nombre : '')}<br>Consulta de elegibilidad con lista ${l0.lista}`)}${arrow}${st('4 · Selección y empaque', `${R.lotes.length} lote(s)`, `${fmt(R.t, 1)} t · transporte ${d0.transporte} a ${d0.temp} °C`)}${arrow}${E ? st('5 · Inspección', dE.inspeccion.res, `${esc(dE.inspeccion.por)}<br><span class="mono">${dE.inspeccion.id}</span> · ${dE.inspeccion.fecha}`) + arrow + st('6 · Cargamento y cruce', `<span class="mono">${E.id}</span>`, `Pedimento <span class="mono">${E.pedimento}</span><br>${E.exportador} · ${E.cla}<br>Sello ${dE.sello} · ${E.cfi}<br>${esc(dE.puerto)} · ${dE.cruce} → ${esc(dE.destino)}`) : st('5 · Embarque', 'Pendiente', 'El lote aún no se incorpora a un cargamento')}</div>
      <div class="verdict ${R.ok ? 'ok' : 'fail'}" style="margin-top:10px"><div style="flex:1"><div class="big">${R.ok ? 'Origen certificado de punta a punta' : 'Cadena con fruta sin constancia'}</div><div class="tiny dim">${R.ok ? 'Todas las huertas del cargamento tienen constancia ambiental vigente o condicionada.' : 'Con la regla de la temporada 2026-2027 estos lotes se habrían detenido en la recepción: ' + malas.map(c => `${c.uid} (${c.estado.toLowerCase()})`).slice(0, 4).join(', ')}</div></div><div class="mono tiny" style="text-align:right">Sello de trazabilidad<br>${R.sello.slice(0, 16)}…</div></div>
      <div style="display:flex;gap:8px;flex-wrap:wrap;margin-top:10px"><button class="btn" data-pue="${l0.id}">${icon('download', 14)} Paquete UE del lote ${l0.id}</button>${E ? `<button class="btn ghost" data-cae="${E.exportador}">${icon('shield', 14)} Constancia de exportador ${E.exportador}</button>` : ''}${E ? `<span class="tiny dim" style="align-self:center">Folios de constancia en el pedimento: ${foliosDeEmbarque(E).slice(0, 4).join(', ')}${foliosDeEmbarque(E).length > 4 ? '…' : ''}</span>` : ''}</div>
      <div class="tw" style="max-height:260px;margin-top:10px"><table class="tbl"><thead><tr><th>Lote</th><th>Fecha</th><th>Huerta</th><th class="num">t</th><th>Constancia</th><th>Embarque</th></tr></thead><tbody>${R.lotes.slice(0, 150).map(l => { const c = constancia(hById[l.uid]); return `<tr class="cl" data-c="${l.uid}"><td class="mono tiny">${l.id}</td><td class="mono tiny">${l.fecha}</td><td class="mono tiny">${l.uid}</td><td class="num">${l.t}</td><td>${cChip(c.estado)} <span class="mono tiny dim">${c.folio}</span></td><td class="mono tiny">${l.emb || '—'}</td></tr>`; }).join('')}</tbody></table></div>`;
  };
  const owp = () => { const A = alertasGeocerca(); const n = P2.owp.municipios.length; $('#owp', main).innerHTML = `<div class="ch"><h3>Geocerca de la zona autorizada · municipios del OWP</h3><div class="sp">${n ? `<span class="chip ${P2.owp.demo ? 'warn' : 'ok'}">${n} municipios${P2.owp.demo ? ' · DEMOSTRACIÓN' : ''}</span>` : '<span class="chip warn">Catálogo vacío</span>'} ${me().rol === 'dictamen' ? (n ? '<button class="btn sm ghost" id="owpx">Vaciar</button>' : '<button class="btn sm" id="owpl">Cargar catálogo de demostración</button>') : ''}</div></div><p class="tiny dim" style="margin:4px 0 8px">${esc(P2.owp.fuente)}. ${esc(P2.owp.estado)}. Regla: huerta fuera de un municipio aprobado → «no exportable a EUA»; lote cuya huerta de origen cae fuera → alerta. Mientras el catálogo está vacío, el control opera a nivel estatal (Michoacán y Jalisco). El catálogo también se carga desde Ingesta (tipo «catálogo OWP»).</p>${n ? `<div class="grid g3">${kpi({ l: 'Lotes con origen fuera de la geocerca', v: fmt(A.length), c: '#B3261E' })}${kpi({ l: 'De ellos sin alerta', v: fmt(lotesFueraSinAlerta()), s: 'prueba: debe ser 0', c: lotesFueraSinAlerta() ? '#B3261E' : '#2E7D32' })}${kpi({ l: 'Huertas no exportables a EUA', v: fmt(universo().filter(h => !P2.owp.municipios.includes(h.mun)).length) })}</div><div class="tw" style="max-height:200px;margin-top:8px"><table class="tbl"><thead><tr><th>Alerta</th><th>Lote</th><th>Huerta</th><th>Municipio</th><th>Embarque</th></tr></thead><tbody>${A.slice(0, 100).map(a => `<tr><td class="mono tiny">${a.id}</td><td class="mono tiny">${a.lote}</td><td class="mono tiny">${a.uid}</td><td>${esc(munName[a.mun])}</td><td class="mono tiny">${a.emb || '—'}</td></tr>`).join('')}</tbody></table></div>` : ''}`;
    const l1 = $('#owpl', main); if (l1) l1.onclick = () => { cargarOWPDemo(me()); toast('Catálogo OWP de demostración cargado'); owp(); }; const l2 = $('#owpx', main); if (l2) l2.onclick = () => { vaciarOWP(me()); toast('Catálogo vaciado'); owp(); }; };
  owp();
  on(main, 'click', '[data-pue]', (e, b) => window.__go('admin', 'paquete-ue', { q: b.dataset.pue }));
  on(main, 'click', '[data-cae]', (e, b) => { const c = constanciaExportador(b.dataset.cae); const m = modal(`<div class="ch"><h2 class="mono">${c.folio}</h2><div class="sp"><button class="btn sm ghost" data-close>✕</button></div></div><div class="tiny dim">Constancia de exportador · ${esc(c.exportador.nombre)} · ${c.exportador.cla} · temporada ${c.vigencia.id}</div><div style="display:flex;gap:14px;align-items:center;margin:10px 0">${qrSVG(VERIFY_BASE + c.folio, 100)}<div><div><b>${c.amparadas.length}</b> huertas amparadas · ${c.excluidas.length} excluidas sin constancia</div><div class="tiny dim">${c.embarques} embarques de la temporada · ${c.emitida ? 'emitida' : 'sin emitir'}</div></div></div><div class="tw" style="max-height:260px"><table class="tbl"><thead><tr><th>Huerta</th><th>Constancia</th><th>Resultado</th><th>Municipio</th></tr></thead><tbody>${c.amparadas.map(a => `<tr><td class="mono tiny">${a.uid}</td><td class="mono tiny">${a.folio}</td><td>${cChip(a.estado)}</td><td>${esc(a.municipio)}</td></tr>`).join('')}</tbody></table></div><div style="display:flex;gap:8px;justify-content:flex-end;margin-top:10px"><button class="btn pri" id="caeok" ${c.emitida ? 'disabled' : ''}>Emitir y firmar</button></div>`, { w: '760px' }); m.q('#caeok').onclick = () => { const r = emitirConstanciaExportador(b.dataset.cae, me()); if (!r.ok) return toast(r.why, 'warn'); toast('Constancia de exportador ' + r.c.folio + ' emitida'); m.close(); }; });
  $('#tgo', main).onclick = () => show($('#tq', main).value);
  on(main, 'click', '[data-t]', (e, a) => { $('#tq', main).value = a.dataset.t; show(a.dataset.t); });
  on(main, 'click', 'tr[data-c]', (e, r) => abrirConstancia(r.dataset.c));
  if (params.q) show(params.q);
}

// ---------- Productor: mi constancia ----------
export function constanciaProductor(main, prd) {
  const mine = H.filter(h => h.prd === prd); const cs = mine.map(constancia).filter(c => c.estado !== 'No aplica');
  main.innerHTML = hdr('Constancia ambiental de origen', `Desde la temporada ${ACUERDO.temporada.id} (inicia el ${fdate(ACUERDO.temporada.ini)}) sólo el aguacate con origen certificado puede exportarse a Estados Unidos. Aquí ve, huerta por huerta, qué cumple y qué le falta.`, tag('demo')) +
    `<div class="grid g4" style="margin-bottom:14px">${['Vigente', 'Condicionada', 'En trámite', 'No procede'].map(k => kpi({ l: k, v: cs.filter(c => c.estado === k).length, c: EST_C[k].c })).join('')}</div>` +
    (cs.length ? cs.map(c => `<div class="card" style="margin-bottom:12px"><div class="ch"><h3 class="mono">${c.uid}</h3><div class="sp"><span class="tiny dim">${esc(c.municipio)} · ${esc(c.cultivo)} · ${fmt(c.ha, 1)} ha</span> <button class="btn sm" data-dl="${c.uid}">${icon('download', 12)} Constancia</button></div></div>${constanciaCard(c)}</div>`).join('') : '<div class="card dim">Sus huertas no tienen cultivos de exportación.</div>') + fuente();
  on(main, 'click', '[data-dl]', (e, b) => download(`constancia_${constancia(hById[b.dataset.dl]).folio}.html`, constanciaHTML(constancia(hById[b.dataset.dl])), 'text/html'));
}
export { abrirConstancia };
export const views = { origen: origenView, trazabilidad };
