// Origen certificado (temporada 2026-2027): preparación, constancia ambiental, trazabilidad de exportación.
import { $, on, esc, fmt, toast, download, fdate as fd0 } from '../util.js';
const fdate = s => fd0(String(s).length === 10 ? s + 'T12:00:00' : s);
import { icon, modal, tag, kpi } from '../ui.js';
import { S, munName } from '../state.js';
import { H, hById, PARAMS, me, ROLES } from '../domain/core.js';
import { ACUERDO, COMP, EST_C, ST_COMP, constancia, preparacion, emitirConstancias, trazar, detalleLote, detalleEmbarque, universo } from '../domain/origen.js';
import { EMP } from '../domain/trace.js';
import { hdr, who, estChip } from './verif.js';

export const cChip = e => `<span class="chip ${EST_C[e] ? EST_C[e].k : ''}">${esc(e)}</span>`;
const sChip = s => `<span class="chip ${ST_COMP[s][1]}">${ST_COMP[s][0]}</span>`;
const pct = (a, b) => b ? Math.round(100 * a / b) : 0;
const fuente = () => `<div class="tiny dim" style="margin-top:6px">Fuente del acuerdo: ${esc(ACUERDO.fuente)}. Parámetros de la constancia: versión ${esc(PARAMS.constancia.version)}, ajustables cuando se publiquen las reglas.</div>`;

// ---------- Ficha de constancia (compartida: admin, productor, público) ----------
export function constanciaCard(c, { publico = false } = {}) {
  const em = S.constancias[c.uid];
  return `<div class="verdict ${EST_C[c.estado].k === 'ok' ? 'ok' : EST_C[c.estado].k === 'bad' ? 'fail' : 'warn'}"><div style="flex:1"><div class="big">Constancia ambiental de origen · ${esc(c.estado)}</div><div class="tiny dim">${esc(EST_C[c.estado].d)}</div></div><div class="mono tiny" style="text-align:right">${c.folio}<br>Temporada ${c.vigencia.id}${em ? '<br><span class="chip ok">Emitida y firmada</span>' : '<br><span class="chip">Sin emitir</span>'}</div></div>
  <table class="tbl" style="margin-top:10px"><thead><tr><th>Componente</th><th>Resultado</th>${publico ? '' : '<th>Evidencia</th>'}</tr></thead><tbody>${c.comps.map(x => `<tr><td>${esc(x.n)}${PARAMS.constancia.bloqueantes.includes(x.k) ? ' <span class="tiny dim">(indispensable)</span>' : ''}</td><td>${sChip(x.estado)}</td>${publico ? '' : `<td class="tiny">${esc(x.det)}${x.accion && x.estado !== 'cumple' ? `<div style="color:var(--warn)">→ ${esc(x.accion)}</div>` : ''}</td>`}</tr>`).join('')}</tbody></table>
  ${c.plazo && !publico ? `<div class="note tiny" style="margin-top:8px">Condicionada: debe subsanar ${c.pend.map(x => esc(x.n.toLowerCase())).join(', ')} a más tardar el <b>${c.plazo}</b> (${PARAMS.constancia.subsanacionDH} días hábiles).</div>` : ''}`;
}
export function constanciaHTML(c) {
  const h = hById[c.uid], em = S.constancias[c.uid]; const row = (k, v) => `<tr><th>${k}</th><td>${v}</td></tr>`;
  return `<!doctype html><html lang="es"><head><meta charset="utf-8"><title>${c.folio}</title><style>body{font:13px/1.55 "IBM Plex Sans",system-ui,sans-serif;color:#1B2A26;background:#F2F4F0;max-width:820px;margin:0 auto;padding:28px}main{background:#FFFFFF;padding:28px 32px;border-top:6px solid #235B4E}h1{font:600 21px "Source Serif 4",Georgia,serif;color:#235B4E;margin:0}h2{font:600 15px "Source Serif 4",Georgia,serif;color:#235B4E;margin:20px 0 6px;padding-bottom:3px;border-bottom:2px solid #BC955C}table{border-collapse:collapse;width:100%}th,td{border:1px solid rgba(111,124,119,.3);padding:5px 8px;text-align:left;vertical-align:top}th{width:34%;background:#F2F4F0;font-weight:600}.m{font-family:"IBM Plex Mono",monospace}.demo{background:#9F2241;color:#F2F4F0;padding:6px 10px;font-size:11.5px;margin-bottom:14px}.inst{color:#45544F;font-size:12px;letter-spacing:.04em;text-transform:uppercase;margin-bottom:4px}.res{font:600 18px "Source Serif 4",Georgia,serif;color:${EST_C[c.estado].c}}.ok{color:#2E7D32}.warn{color:#A8720F}.bad{color:#B3261E}.foot{font-size:11px;color:#6F7C77;margin-top:18px}</style></head><body><main>
  <div class="demo">DOCUMENTO DE DEMOSTRACIÓN — datos, firma y sello simulados; sin validez jurídica</div>
  <div class="inst">Gobierno del Estado · Módulo de Verificación y Dictamen Forestal</div><h1>Constancia ambiental de origen</h1>
  <table style="margin-top:10px">${row('Folio', `<span class="m">${c.folio}</span>`)}${row('Temporada de exportación', `${c.vigencia.id} (${fdate(c.vigencia.ini)} – ${fdate(c.vigencia.fin)})`)}${row('Resultado', `<span class="res">${esc(c.estado)}</span>`)}${row('Marco', 'Acuerdo de origen certificado para la exportación de aguacate a EE. UU. (oct-2026); reglas de acreditación pendientes de publicación. Versión de criterios: ' + esc(PARAMS.constancia.version))}</table>
  <h2>Huerta</h2><table>${row('UID', `<span class="m">${c.uid}</span>`)}${row('Registro para exportación', h.senasica || '—')}${row('Municipio', esc(c.municipio))}${row('Cultivo · superficie', `${esc(c.cultivo)} · ${fmt(c.ha, 2)} ha`)}${row('Capacidad productiva estimada', fmt(c.cap, 1) + ' t por temporada')}</table>
  <h2>Componentes evaluados</h2><table><tr><th>Componente</th><td><b>Resultado y evidencia</b></td></tr>${c.comps.map(x => row(esc(x.n) + (PARAMS.constancia.bloqueantes.includes(x.k) ? ' (indispensable)' : ''), `<b class="${ST_COMP[x.estado][1] === 'ok' ? 'ok' : ST_COMP[x.estado][1] === 'bad' ? 'bad' : 'warn'}">${ST_COMP[x.estado][0]}</b> · ${esc(x.det)}${x.accion && x.estado !== 'cumple' ? `<br>Acción requerida: ${esc(x.accion)}` : ''}`)).join('')}</table>
  ${c.plazo ? `<p><b>Condicionada:</b> la persona productora debe subsanar las observaciones a más tardar el ${c.plazo}; de lo contrario la constancia se suspende.</p>` : ''}
  <h2>Integridad</h2><table>${row('Huella SHA-256', `<span class="m" style="font-size:11px">${c.sha}</span>`)}${row('Firma electrónica', em ? `${em.firma} · e.firma (simulada) · ${em.ts}` : 'Pendiente de emisión')}${row('Sello de tiempo', em ? em.sello : '—')}${row('Verificación', 'Consulte el folio en el portal ciudadano (Consulta de elegibilidad) o pregunte a Arbolín.')}</table>
  <div class="foot">Esta constancia no publica datos personales del titular. Las empacadoras la consultan automáticamente al recibir cada lote.</div></main></body></html>`;
}
function abrirConstancia(uid, { publico = false } = {}) {
  const c = constancia(hById[uid]); const h = hById[uid];
  const m = modal(`<div class="ch"><h2 class="mono">${uid}</h2><div class="sp">${estChip(h.estado)} <button class="btn sm ghost" data-close>✕</button></div></div><div class="tiny dim" style="margin:4px 0 10px">${esc(c.municipio)} · ${esc(c.cultivo)} · ${fmt(c.ha, 2)} ha · capacidad ${fmt(c.cap, 1)} t</div>${constanciaCard(c, { publico })}
    <div style="display:flex;gap:8px;justify-content:flex-end;margin-top:12px;flex-wrap:wrap"><button class="btn ghost" id="ctz">${icon('layers', 14)} Ver trazabilidad</button>${publico ? '' : `<button class="btn" id="cem" ${S.constancias[uid] || !['Vigente', 'Condicionada'].includes(c.estado) ? 'disabled' : ''}>${icon('shield', 14)} Emitir y firmar</button>`}<button class="btn pri" id="cdl">${icon('download', 14)} Descargar constancia</button></div>`, { w: '760px' });
  m.q('#cdl').onclick = () => download(`constancia_${c.folio}.html`, constanciaHTML(constancia(hById[uid])), 'text/html');
  m.q('#ctz').onclick = () => { m.close(); window.__go('admin', 'trazabilidad', { q: uid }); };
  const e = m.q('#cem'); if (e) e.onclick = () => { const r = emitirConstancias(me(), [uid]); if (!r.ok) return toast(r.why, 'warn'); toast('Constancia emitida y firmada'); m.close(); abrirConstancia(uid); };
}

// ---------- Admin: preparación para la temporada ----------
function origenView(main) {
  let filt = 'No procede';
  const draw = () => {
    const R = preparacion(); const listo = R.vig.length + R.cond.length;
    const compStats = COMP.map(cp => { const o = { cumple: 0, observacion: 0, no_cumple: 0, en_proceso: 0, no_aplica: 0 }; R.U.forEach(c => { const x = c.comps.find(y => y.k === cp.k); o[x.estado]++; }); return { cp, o }; });
    const mezcla = S.consultas.filter(c => c.origen); const lav = R.U.filter(c => c.comps.find(x => x.k === 'trazabilidad').estado === 'no_cumple');
    main.innerHTML = hdr('Origen certificado · temporada 2026-2027', `Desde esta temporada <b>sólo el aguacate con origen certificado podrá exportarse a Estados Unidos</b>. El acuerdo pide dos cosas: <b>trazabilidad reforzada</b> de la huerta a la frontera y una <b>constancia ambiental</b> de que la huerta no se estableció talando bosque. La plataforma ya hace ambas; aquí se mide qué tan lista está la franja aguacatera.`, `${tag('demo')} ${who()} <button class="btn" id="rdl">${icon('download', 14)} Propuesta de reglas</button> <button class="btn pri" id="emi">${icon('shield', 14)} Emitir constancias</button>`) +
      `<div class="arb-band" style="margin-bottom:14px"><div style="text-align:center;min-width:110px"><div class="mono" style="font-size:40px;font-weight:600;color:#BC955C;line-height:1">${R.nat}</div><div class="tiny" style="color:rgba(242,244,240,.8)">días naturales<br>(${R.dias} hábiles)</div></div><div><b>Arranque de la temporada de exportación: ${fdate(ACUERDO.temporada.ini)}</b><p>${pct(listo, R.n)} % de las huertas de aguacate de exportación ya cumplen lo indispensable para obtener su constancia (${fmt(listo)} de ${fmt(R.n)}). Representan ${fmt(R.capOk, 0)} t de ${fmt(R.cap, 0)} t de capacidad productiva (${pct(R.capOk, R.cap)} %). Constancias emitidas: <b>${fmt(R.emitidas)}</b>.${R.tram.length ? ` Para llegar al arranque con todo resuelto hay que cerrar <b>${fmt(R.tram.length)} revisiones y audiencias</b> en ${R.dias} días hábiles (≈ ${fmt(Math.ceil(R.tram.length / Math.max(1, R.dias)))} por día).` : ''}</p></div></div>
      <div class="grid g5">${kpi({ l: 'Huertas de aguacate de exportación', v: fmt(R.n), s: 'padrón de demostración' })}${kpi({ l: 'Constancia vigente', v: fmt(R.vig.length), s: pct(R.vig.length, R.n) + ' %', c: '#2E7D32' })}${kpi({ l: 'Condicionada', v: fmt(R.cond.length), s: `subsanar en ${PARAMS.constancia.subsanacionDH} días hábiles`, c: '#A8720F' })}${kpi({ l: 'En trámite', v: fmt(R.tram.length), s: 'revisión o audiencia abierta', c: '#235B4E' })}${kpi({ l: 'No procede', v: fmt(R.np.length), s: 'falla un componente indispensable', c: '#B3261E' })}</div>
      <div class="grid g2" style="margin-top:14px"><div class="card"><div class="ch"><h3>Medida 1 · Trazabilidad reforzada</h3><div class="sp"><button class="btn sm ghost" data-go="trazabilidad">Abrir</button></div></div><p class="tiny" style="margin:6px 0 10px;color:var(--mut)">${esc(ACUERDO.medidas[0].d)}</p>
        <dl class="kv"><dt>Huerta de origen identificada (UID)</dt><dd>${fmt(H.length)} huertas en el padrón</dd><dt>Lotes ligados a su huerta</dt><dd>${fmt(S.lotes.length)} lotes · ${fmt(S.embarques.length)} embarques</dd><dt>Consulta automática en recepción</dt><dd>${fmt(S.consultas.length)} consultas registradas</dd><dt>Intentos de mezcla con origen no autorizado</dt><dd><b style="color:#B3261E">${fmt(mezcla.length)}</b> bloqueados</dd><dt>Huertas con posible lavado de fruta</dt><dd><b style="color:#B3261E">${fmt(lav.length)}</b> (balance de masa)</dd></dl></div>
        <div class="card"><div class="ch"><h3>Medida 2 · Constancia ambiental</h3><div class="sp">${tag('demo')}</div></div><p class="tiny" style="margin:6px 0 10px;color:var(--mut)">${esc(ACUERDO.medidas[1].d)}</p>
        ${compStats.map(({ cp, o }) => { const tot = R.n || 1; const seg = [['cumple', '#2E7D32'], ['en_proceso', '#235B4E'], ['observacion', '#A8720F'], ['no_cumple', '#B3261E'], ['no_aplica', 'rgba(111,124,119,.35)']]; return `<div style="margin:7px 0"><div style="display:flex;justify-content:space-between;font-size:12.5px"><span>${esc(cp.n)}${PARAMS.constancia.bloqueantes.includes(cp.k) ? ' <span class="tiny dim">· indispensable</span>' : ''}</span><span class="mono tiny">${o.cumple} cumple · ${o.observacion} obs. · ${o.no_cumple} no</span></div><div style="display:flex;height:9px;border-radius:5px;overflow:hidden;background:var(--bg);margin-top:3px">${seg.map(([k, col]) => o[k] ? `<i title="${ST_COMP[k][0]}: ${o[k]}" style="width:${100 * o[k] / tot}%;background:${col}"></i>` : '').join('')}</div></div>`; }).join('')}</div></div>
      <div class="card" style="margin-top:14px"><div class="ch"><h3>Lo que falta definir: reglas de acreditación</h3><div class="sp"><span class="chip warn">Propuesta para discusión</span></div></div><p style="margin:6px 0 10px;color:var(--mut)">${esc(ACUERDO.pendiente)} La plataforma propone cómo acreditar cada requisito; los umbrales son parámetros y se ajustan cuando se publiquen las reglas.</p>
        <div class="tw"><table class="tbl"><thead><tr><th>Requisito</th><th>Documento que lo acredita</th><th>Inspección o verificación</th><th>Mecanismo en la plataforma</th><th>Parámetro configurable</th></tr></thead><tbody>${COMP.map(cp => `<tr><td><b>${esc(cp.n)}</b><div class="tiny dim">Medida ${cp.med === 'trazabilidad' ? '1' : '2'}${PARAMS.constancia.bloqueantes.includes(cp.k) ? ' · indispensable' : ' · subsanable'}</div></td><td class="tiny">${esc(cp.doc)}</td><td class="tiny">${esc(cp.ins)}</td><td class="tiny">${esc(cp.mec)}</td><td class="tiny">${esc(cp.par)}</td></tr>`).join('')}</tbody></table></div>${fuente()}</div>
      <div class="grid g21" style="margin-top:14px"><div class="card"><div class="ch"><h3>Huertas por resultado</h3><div class="sp"><div class="tabs" id="cf" style="margin:0;border:0">${['No procede', 'En trámite', 'Condicionada', 'Vigente'].map(k => `<button data-f="${k}" class="${k === filt ? 'on' : ''}">${k}</button>`).join('')}</div></div></div>
        <div class="tw" style="max-height:420px"><table class="tbl"><thead><tr><th>Huerta</th><th>Municipio</th><th class="num">Ha</th><th>Estado legal</th><th>Resultado</th><th>Qué falta</th><th></th></tr></thead><tbody>${R.U.filter(c => c.estado === filt).slice(0, 250).map(c => `<tr class="cl" data-c="${c.uid}"><td class="mono tiny">${c.uid}</td><td>${esc(c.municipio)}</td><td class="num">${fmt(c.ha, 1)}</td><td>${estChip(hById[c.uid].estado)}</td><td>${cChip(c.estado)}</td><td class="tiny">${esc(c.pend.map(x => x.n).join(' · ') || '—')}</td><td>${S.constancias[c.uid] ? '<span class="chip ok">emitida</span>' : ''}</td></tr>`).join('') || '<tr><td colspan="7" class="dim">Sin huertas en esta categoría.</td></tr>'}</tbody></table></div></div>
        <div class="card"><div class="ch"><h3>El sector en cifras</h3><div class="sp">${tag('real')}</div></div><dl class="kv" style="margin-top:8px">${ACUERDO.cifras.map(([k, v]) => `<dt>${esc(k)}</dt><dd class="mono">${esc(v)}</dd>`).join('')}<dt>Temporada alta</dt><dd>15-oct a abril</dd></dl><div class="note info tiny" style="margin-top:10px">Antes la certificación libre de deforestación era voluntaria (≈ 31 % de lo exportado en 2024 con Pro-Forest). Con el acuerdo, <b>todo</b> el aguacate que cruce la frontera debe llegar con origen certificado.</div><div class="tiny dim" style="margin-top:8px">${esc(ACUERDO.fuenteCorta)} · Pro-Forest: fuente estatal citada en el panorama.</div>
        <h3 style="margin-top:14px">Listos por municipio</h3><div class="tw" style="max-height:220px;margin-top:6px"><table class="tbl"><thead><tr><th>Municipio</th><th class="num">Huertas</th><th class="num">Listas</th><th class="num">%</th></tr></thead><tbody>${R.per.map(m => `<tr><td>${esc(munName[m.mun])}</td><td class="num">${m.n}</td><td class="num">${m.Vigente + m.Condicionada}</td><td class="num"><b style="color:${pct(m.Vigente + m.Condicionada, m.n) >= 80 ? '#2E7D32' : '#A8720F'}">${pct(m.Vigente + m.Condicionada, m.n)}</b></td></tr>`).join('')}</tbody></table></div></div></div>`;
    on(main, 'click', '[data-go]', (e, b) => window.__go('admin', b.dataset.go));
    main.querySelectorAll('#cf button').forEach(b => b.onclick = () => { filt = b.dataset.f; draw(); });
    on(main, 'click', 'tr[data-c]', (e, r) => abrirConstancia(r.dataset.c));
    $('#emi', main).onclick = () => { const r = emitirConstancias(me()); if (!r.ok) return toast(r.why, 'warn'); toast(`Se emitieron ${fmt(r.n)} constancias (${r.vig} vigentes, ${r.cond} condicionadas). Raíz de lote ${r.raiz.slice(0, 12)}… en bitácora`); draw(); };
    $('#rdl', main).onclick = () => download('propuesta_reglas_acreditacion_origen_certificado.csv', '﻿requisito,medida,tipo,documento,inspeccion,mecanismo_plataforma,parametro\n' + COMP.map(cp => [cp.n, cp.med === 'trazabilidad' ? 'Medida 1 · Trazabilidad reforzada' : 'Medida 2 · Constancia ambiental', PARAMS.constancia.bloqueantes.includes(cp.k) ? 'Indispensable' : 'Subsanable', cp.doc, cp.ins, cp.mec, cp.par].map(x => JSON.stringify(x)).join(',')).join('\n'), 'text/csv');
  };
  draw();
}

// ---------- Admin: trazabilidad de exportación (huerta → frontera) ----------
function trazabilidad(main, params = {}) {
  const ej = S.embarques[Math.min(12, S.embarques.length - 1)].id;
  const riesgo = () => { const bad = new Set(universo().map(constancia).filter(c => c.estado === 'No procede').map(c => c.uid)); return S.embarques.filter(e => S.lotes.some(l => l.emb === e.id && bad.has(l.uid))); };
  main.innerHTML = hdr('Trazabilidad de exportación', 'De la huerta a la frontera: huerta de origen, corte, empacadora que recibió la fruta, inspecciones que superó y cargamento en que se incorporó. Ningún lote entra sin constancia ni con fruta de estados no autorizados.', `${tag('demo')} ${who()}`) +
    `<div class="card"><div style="display:flex;gap:8px;flex-wrap:wrap"><input id="tq" class="mono" placeholder="EMB-00012, LOT-000123, HUE-16044-00012 o CAO-2627-…" value="${esc(params.q || '')}" style="flex:1;min-width:240px"><button class="btn pri" id="tgo">Rastrear</button></div><div class="tiny dim" style="margin-top:6px">Ejemplos: <a data-t="${ej}" class="mono">${ej}</a> · <a data-t="${S.lotes[40].id}" class="mono">${S.lotes[40].id}</a> · <a data-t="${S.lotes[200].uid}" class="mono">${S.lotes[200].uid}</a>${riesgo()[0] ? ` · embarque con fruta hoy no certificable: <a data-t="${riesgo()[0].id}" class="mono">${riesgo()[0].id}</a>` : ''}</div><div id="tout" style="margin-top:12px"></div></div>
    <div class="grid g2" style="margin-top:14px"><div class="card"><div class="ch"><h3>Control de origen · mezclas bloqueadas</h3><div class="sp">${tag('demo')}</div></div><p class="tiny dim" style="margin:4px 0 8px">Fruta de huertas de estados no autorizados que intentó entrar a empacadoras de exportación. Sólo Michoacán y Jalisco están autorizados.</p><div class="tw" style="max-height:300px"><table class="tbl"><thead><tr><th>Fecha</th><th>Empacadora</th><th>Huerta declarada</th><th class="num">t</th><th>Motivo</th></tr></thead><tbody>${S.consultas.filter(c => c.origen).map(c => `<tr><td class="mono tiny">${c.ts.slice(0, 10)}</td><td class="mono tiny">${c.emp}</td><td class="mono tiny">${c.uid}</td><td class="num">${c.t}</td><td class="tiny">${esc(c.motivo)}</td></tr>`).join('')}</tbody></table></div></div>
    <div class="card"><div class="ch"><h3>Embarques con fruta que hoy no obtendría constancia</h3></div><p class="tiny dim" style="margin:4px 0 8px">Lotes de la temporada pasada recibidos cuando la huerta era elegible, de huertas que hoy no cumplen. Con la nueva regla se detienen en la recepción.</p><div class="tw" style="max-height:300px"><table class="tbl"><thead><tr><th>Embarque</th><th>Empacadora</th><th>Semana</th><th class="num">t</th><th></th></tr></thead><tbody>${riesgo().slice(0, 80).map(e => `<tr class="cl" data-t="${e.id}"><td class="mono tiny">${e.id}</td><td class="mono tiny">${e.emp}</td><td class="mono tiny">${e.semana}</td><td class="num">${e.t}</td><td><span class="chip bad">revisar</span></td></tr>`).join('') || '<tr><td colspan="5" class="dim">Ninguno.</td></tr>'}</tbody></table></div></div></div>`;
  const show = q => {
    const R = trazar(q); const o = $('#tout', main); if (!R) { o.innerHTML = '<div class="dim">Sin resultados. Revise el identificador.</div>'; return; }
    const l0 = R.lotes[0], d0 = detalleLote(l0), emp = EMP.find(e => e.id === l0.emp), E = R.embs[0], dE = E ? detalleEmbarque(E) : null;
    const malas = R.cs.filter(c => !['Vigente', 'Condicionada'].includes(c.estado));
    const st = (n, t, body, ok = true) => `<div style="flex:1;min-width:150px;background:var(--panel);border:1px solid var(--line);border-top:3px solid ${ok ? '#2E7D32' : '#B3261E'};border-radius:8px;padding:10px"><div class="tiny" style="color:var(--goldt);font-weight:600">${n}</div><div style="font-weight:600;margin:2px 0 4px">${t}</div><div class="tiny" style="color:var(--mut);line-height:1.45">${body}</div></div>`;
    const arrow = '<div style="align-self:center;color:var(--gold);font-size:18px">→</div>';
    o.innerHTML = `<div style="display:flex;gap:6px;flex-wrap:wrap;align-items:stretch">${st('1 · Huerta de origen', R.hs.length === 1 ? `<span class="mono">${R.hs[0].uid}</span>` : `${R.hs.length} huertas`, `${R.cs.filter(c => c.estado === 'Vigente').length} vigentes · ${R.cs.filter(c => c.estado === 'Condicionada').length} condicionadas${malas.length ? ` · <b style="color:#B3261E">${malas.length} sin constancia</b>` : ''}<br>${esc([...new Set(R.hs.map(h => munName[h.mun]))].slice(0, 3).join(', '))}`, !malas.length)}${arrow}${st('2 · Corte', d0.corte, `Cuadrilla ${d0.cuadrilla} · ${d0.cortadores} cortadores<br>${esc(d0.asegurados)}`)}${arrow}${st('3 · Recepción', `<span class="mono">${l0.emp}</span>`, `${esc(emp ? emp.nombre : '')}<br>Consulta de elegibilidad con lista ${l0.lista}`)}${arrow}${st('4 · Selección y empaque', `${R.lotes.length} lote(s)`, `${fmt(R.t, 1)} t · transporte ${d0.transporte} a ${d0.temp} °C`)}${arrow}${E ? st('5 · Inspección', dE.inspeccion.res, `${esc(dE.inspeccion.por)}<br><span class="mono">${dE.inspeccion.id}</span> · ${dE.inspeccion.fecha}`) + arrow + st('6 · Cargamento y cruce', `<span class="mono">${E.id}</span>`, `Sello ${dE.sello} · certificado ${E.cfi}<br>${esc(dE.puerto)} · ${dE.cruce} → ${esc(dE.destino)}`) : st('5 · Embarque', 'Pendiente', 'El lote aún no se incorpora a un cargamento')}</div>
      <div class="verdict ${R.ok ? 'ok' : 'fail'}" style="margin-top:10px"><div style="flex:1"><div class="big">${R.ok ? 'Origen certificado de punta a punta' : 'Cadena con fruta sin constancia'}</div><div class="tiny dim">${R.ok ? 'Todas las huertas del cargamento tienen constancia ambiental vigente o condicionada.' : 'Con la regla de la temporada 2026-2027 estos lotes se habrían detenido en la recepción: ' + malas.map(c => `${c.uid} (${c.estado.toLowerCase()})`).slice(0, 4).join(', ')}</div></div><div class="mono tiny" style="text-align:right">Sello de trazabilidad<br>${R.sello.slice(0, 16)}…</div></div>
      <div class="tw" style="max-height:260px;margin-top:10px"><table class="tbl"><thead><tr><th>Lote</th><th>Fecha</th><th>Huerta</th><th class="num">t</th><th>Constancia</th><th>Embarque</th></tr></thead><tbody>${R.lotes.slice(0, 150).map(l => { const c = constancia(hById[l.uid]); return `<tr class="cl" data-c="${l.uid}"><td class="mono tiny">${l.id}</td><td class="mono tiny">${l.fecha}</td><td class="mono tiny">${l.uid}</td><td class="num">${l.t}</td><td>${cChip(c.estado)} <span class="mono tiny dim">${c.folio}</span></td><td class="mono tiny">${l.emb || '—'}</td></tr>`; }).join('')}</tbody></table></div>`;
  };
  $('#tgo', main).onclick = () => show($('#tq', main).value);
  on(main, 'click', '[data-t]', (e, a) => { $('#tq', main).value = a.dataset.t; show(a.dataset.t); });
  on(main, 'click', 'tr[data-c]', (e, r) => abrirConstancia(r.dataset.c));
  if (params.q) show(params.q);
}

// ---------- Productor: mi constancia ----------
export function constanciaProductor(main, prd) {
  const mine = H.filter(h => h.prd === prd); const cs = mine.map(constancia).filter(c => c.estado !== 'No aplica');
  main.innerHTML = hdr('Constancia ambiental de origen', `Desde la temporada ${ACUERDO.temporada.id} (inicia el ${fdate(ACUERDO.temporada.ini)}) sólo el aguacate con origen certificado puede exportarse a Estados Unidos. Aquí ve, huerta por huerta, qué cumple y qué le falta.`, tag('demo')) +
    `<div class="grid g4" style="margin-bottom:14px">${['Vigente', 'Condicionada', 'En trámite', 'No procede'].map(k => kpi({ l: k, v: cs.filter(c => c.estado === k).length, c: EST_C[k].c })).join('')}</div>` +
    (cs.length ? cs.map(c => `<div class="card" style="margin-bottom:12px"><div class="ch"><h3 class="mono">${c.uid}</h3><div class="sp"><span class="tiny dim">${esc(c.municipio)} · ${esc(c.cultivo)} · ${fmt(c.ha, 1)} ha</span> <button class="btn sm" data-dl="${c.uid}">${icon('download', 12)} Constancia</button></div></div>${constanciaCard(c)}</div>`).join('') : '<div class="card dim">Sus huertas no tienen cultivos de exportación.</div>') + fuente();
  on(main, 'click', '[data-dl]', (e, b) => download(`constancia_${constancia(hById[b.dataset.dl]).folio}.html`, constanciaHTML(constancia(hById[b.dataset.dl])), 'text/html'));
}
export { abrirConstancia };
export const views = { origen: origenView, trazabilidad };
