// Portal de Administración · Participación ciudadana (lo que Arbolín considera, cataloga e integra).
import { $, esc, fmt, on, toast, download, fdate } from '../util.js';
import { icon, modal, tag, kpi } from '../ui.js';
import { S, munName } from '../state.js';
import { prepPts } from '../map.js';
import { createMap, attachControls } from '../mapkit.js';
import { me } from '../domain/core.js';
import { TIPOS, PRECISION, PRECISA, ESTADOS_P, REGLAS_CAT, enmascarar, turnarATriaje, responder } from '../domain/participa.js';
import { hdr, who } from './verif.js';
import { arbolinSvg } from '../assistant/icon.js';

const munOf = p => (p.cruce && p.cruce.mun) || p.municipio;
const prChip = p => `<span class="chip ${{ Alta: 'bad', Media: 'warn', Baja: 'ok' }[p] || ''}">${esc(p)}</span>`;
const stChip = s => `<span class="chip ${{ 'Recibida': 'warn', 'En análisis': 'info', 'Turnada a triaje': 'bad', 'Turnada': 'info', 'Respondida': 'ok', 'Atendida': 'ok' }[s] || ''}">${esc(s)}</span>`;
const tpChip = t => `<span class="chip" style="border-color:${TIPOS[t].c};color:${TIPOS[t].c}">${TIPOS[t].n}</span>`;

function participacion(main, params = {}) {
  let ft = 'todas', fm = '', map = null;
  const list = () => S.participaciones.filter(p => (ft === 'todas' || p.tipo === ft || (ft === 'pend' && ['Recibida', 'En análisis'].includes(p.estado))) && (!fm || munOf(p) === fm));
  const P = S.participaciones; const n = k => P.filter(p => p.tipo === k).length;
  main.innerHTML = hdr('Participación ciudadana', `Opiniones, sugerencias, propuestas y denuncias que llegan por <b>Arbolín</b> y por el formulario web. Cada registro se <b>considera</b> (se valida y georreferencia), se <b>cataloga</b> (reglas ${REGLAS_CAT.id}) y se <b>integra</b> (folio, huella SHA-256, bitácora; las denuncias entran a la cola de triaje).`, `${tag('demo')} ${who()} <button class="btn ghost" id="pcsv">${icon('download', 14)} CSV</button> <button class="btn" id="parb">${arbolinSvg(18, { bg: false })} Probar Arbolín</button>`) +
    `<div class="grid g5" style="margin-bottom:14px">${kpi({ l: 'Participaciones', v: fmt(P.length), s: `${P.filter(p => p.canal === 'Arbolín').length} por Arbolín` })}${kpi({ l: 'Denuncias', v: fmt(n('denuncia')), s: `${P.filter(p => p.alerta).length} turnadas a triaje`, c: '#B3261E' })}${kpi({ l: 'Sugerencias y propuestas', v: fmt(n('sugerencia') + n('propuesta')), s: `${n('propuesta')} propuestas`, c: '#235B4E' })}${kpi({ l: 'Opiniones', v: fmt(n('opinion')), s: `${P.filter(p => p.cat.sentimiento === 'Negativa').length} negativas` })}${kpi({ l: 'Con punto preciso', v: P.length ? Math.round(100 * P.filter(p => p.ubicacion && PRECISA(p.ubicacion.precision)).length / P.length) + ' %' : '—', s: 'GPS, mapa o foto' })}</div>
    <div class="grid g21"><div class="card"><div class="ch"><div class="tabs" id="pf" style="margin:0;border:0;flex-wrap:wrap">${[['todas', 'Todas'], ['pend', 'Pendientes'], ['denuncia', 'Denuncias'], ['sugerencia', 'Sugerencias'], ['propuesta', 'Propuestas'], ['opinion', 'Opiniones']].map(([k, t]) => `<button data-f="${k}" class="${k === ft ? 'on' : ''}">${t}</button>`).join('')}</div><div class="sp"><select id="pm"><option value="">Todos los municipios</option>${[...new Set(P.map(munOf))].sort((a, b) => (munName[a] || '').localeCompare(munName[b] || '')).map(id => `<option value="${id}">${esc(munName[id])}</option>`).join('')}</select></div></div><div class="tw" style="max-height:520px"><table class="tbl" id="pt"></table></div></div>
    <div style="display:flex;flex-direction:column;gap:14px"><div class="card pad0" style="height:330px;position:relative"><div id="pmap" style="height:100%"></div><div class="lg" style="position:absolute;left:8px;bottom:8px;background:var(--panel);border:1px solid var(--line);border-radius:6px;padding:4px 8px;font-size:11px">${Object.values(TIPOS).map(t => `<span style="margin-right:8px"><i class="dot" style="background:${t.c}"></i> ${t.n}</span>`).join('')}</div></div><div class="card"><h3>Temas más frecuentes</h3><div id="pcat" style="margin-top:8px"></div><div class="tiny dim" style="margin-top:8px">${esc(REGLAS_CAT.nota)}</div></div></div></div>`;
  const draw = () => {
    const L = list();
    $('#pt', main).innerHTML = `<thead><tr><th>Folio</th><th>Fecha</th><th>Tipo</th><th>Tema</th><th>Municipio · localidad</th><th>Ubicación</th><th>Prioridad</th><th>Estado</th></tr></thead><tbody>${L.map(p => `<tr class="cl" data-id="${p.folio}"><td class="mono tiny">${p.folio}${p.demo ? '' : ' <span class="chip ok">nuevo</span>'}</td><td class="mono tiny">${p.ts.slice(0, 10)}</td><td>${tpChip(p.tipo)}</td><td class="tiny">${esc(p.cat.categoria)}</td><td class="tiny">${esc(munName[munOf(p)] || '—')}${p.localidad ? ' · ' + esc(p.localidad) : ''}${p.colonia ? `<div class="dim">${esc(p.colonia)}</div>` : ''}</td><td class="tiny">${p.ubicacion ? (PRECISA(p.ubicacion.precision) ? '<span class="chip ok">precisa</span>' : '<span class="chip warn">aprox.</span>') : '<span class="chip">municipal</span>'}</td><td>${p.tipo === 'denuncia' || p.cat.prioridad !== 'Baja' ? prChip(p.cat.prioridad) : '<span class="dim tiny">—</span>'}</td><td>${stChip(p.estado)}</td></tr>`).join('') || '<tr><td colspan="8" class="dim">Sin registros con este filtro.</td></tr>'}</tbody>`;
    const cnt = {}; L.forEach(p => cnt[p.cat.categoria] = (cnt[p.cat.categoria] || 0) + 1); const mxv = Math.max(1, ...Object.values(cnt));
    $('#pcat', main).innerHTML = Object.entries(cnt).sort((a, b) => b[1] - a[1]).map(([k, v]) => `<div style="display:flex;align-items:center;gap:8px;margin:5px 0;font-size:12.5px"><span style="width:46%;min-width:0;overflow:hidden;text-overflow:ellipsis;white-space:nowrap" title="${esc(k)}">${esc(k)}</span><span style="flex:1;height:9px;background:var(--bg);border-radius:5px;overflow:hidden"><i style="display:block;height:100%;width:${100 * v / mxv}%;background:var(--g)"></i></span><b class="mono" style="width:22px;text-align:right">${v}</b></div>`).join('') || '<div class="dim tiny">—</div>';
    if (map) { map.layer('parts').data = prepPts(L.filter(p => p.ubicacion).map(p => ({ ...p, lon: p.ubicacion.lon, lat: p.ubicacion.lat }))); map.redraw(); }
  };
  map = createMap($('#pmap', main), { showAlerts: false, showLidar: false, showRest: false, ids: new Set() }); ['alertas', 'lidar', 'rest', 'predios', 'heat'].forEach(k => map.show(k, false));
  map.addLayer('parts', { type: 'point', data: [], order: 60, pickable: true, pickR: 10, style: p => ({ fill: TIPOS[p.tipo].c, stroke: '#F2F4F0', r: PRECISA(p.ubicacion.precision) ? 6 : 4.5, halo: p.demo ? null : TIPOS[p.tipo].c + '44' }) });
  map.fitBounds([-103.1, 18.6, -100.6, 20.1], 10, false); attachControls($('#pmap', main).parentElement, map, { sat: true });
  map.on('click', ({ hit }) => { if (hit && hit.layer === 'parts') ficha(hit.p.folio); });
  draw();
  on(main, 'click', '#pf button', (e, b) => { ft = b.dataset.f; main.querySelectorAll('#pf button').forEach(x => x.classList.toggle('on', x === b)); draw(); });
  $('#pm', main).onchange = e => { fm = e.target.value; draw(); };
  on(main, 'click', 'tr.cl', (e, r) => ficha(r.dataset.id));
  $('#parb', main).onclick = () => window.__arbolin && window.__arbolin.abrir();
  $('#pcsv', main).onclick = () => download('participacion_ciudadana.csv', '﻿folio,fecha,canal,tipo,tema,prioridad,estado,municipio,localidad,colonia,lat,lon,precision,anonimo,fotos,huella_sha256\n' + list().map(p => [p.folio, p.ts, p.canal, TIPOS[p.tipo].n, p.cat.categoria, p.cat.prioridad, p.estado, munName[munOf(p)], p.localidad, p.colonia, p.ubicacion ? p.ubicacion.lat : '', p.ubicacion ? p.ubicacion.lon : '', p.ubicacion ? PRECISION[p.ubicacion.precision] : '', p.anonimo ? 'sí' : 'no', (p.fotos || []).length, p.hash].map(x => JSON.stringify(x ?? '')).join(',')).join('\n'), 'text/csv');
  const ficha = id => {
    const p = S.participaciones.find(x => x.folio === id); if (!p) return; const x = p.cruce; const ro = me().rol === 'auditor';
    const m = modal(`<div class="ch"><h2 class="mono">${p.folio}</h2><div class="sp">${tpChip(p.tipo)} ${stChip(p.estado)} <button class="btn sm ghost" data-close>✕</button></div></div>
      <div class="grid g2" style="margin-top:10px;gap:12px"><div><h3>Lo que dijo la persona</h3><p style="margin:6px 0 10px;white-space:pre-wrap">${esc(p.descripcion)}</p>
      <dl class="kv"><dt>Recibida</dt><dd>${fdate(p.ts)} · ${esc(p.canal)}</dd><dt>Municipio</dt><dd>${esc(munName[munOf(p)] || '—')}${x && x.mun && p.municipio && x.mun !== p.municipio ? ' <span class="chip warn">declaró ' + esc(munName[p.municipio]) + '</span>' : ''}</dd><dt>Localidad</dt><dd>${esc(p.localidad || '—')}</dd><dt>Colonia / paraje</dt><dd>${esc(p.colonia || '—')}</dd>${p.referencias ? `<dt>Referencias</dt><dd>${esc(p.referencias)}</dd>` : ''}${p.tipo === 'denuncia' ? `<dt>Cuándo</dt><dd>${p.ahora === 'ahora' ? 'En el momento del reporte' : esc(p.fecha || (p.ahora === 'antes' ? 'Hace semanas o más' : p.ahora === 'dias' ? 'Últimos días' : '—'))}</dd>` : ''}<dt>Ubicación</dt><dd>${p.ubicacion ? `<span class="mono">${p.ubicacion.lat.toFixed(5)}, ${p.ubicacion.lon.toFixed(5)}</span><div class="tiny dim">${esc(PRECISION[p.ubicacion.precision])}${p.ubicacion.acc ? ' ±' + Math.round(p.ubicacion.acc) + ' m' : ''}</div>` : 'Sólo municipio'}</dd><dt>Contacto</dt><dd>${p.anonimo ? 'Anónima' : esc(enmascarar(p.contacto)) + ' <span class="tiny dim">(sólo personal autorizado)</span>'}</dd></dl>
      ${(p.fotos || []).length ? `<h3 style="margin-top:10px">Fotografías</h3><div style="display:flex;gap:8px;flex-wrap:wrap;margin-top:6px">${p.fotos.map(f => `<div class="tiny" style="max-width:150px">${f.thumb ? `<img src="${f.thumb}" alt="" style="width:150px;border-radius:6px;display:block">` : `<div style="width:150px;height:90px;border-radius:6px;background:var(--bg);display:flex;align-items:center;justify-content:center" class="dim">${icon('eye', 20)}</div>`}<div class="hash mono" style="font-size:10px;word-break:break-all">${f.sha.slice(0, 24)}…</div>${f.lat != null ? `<div class="dim">GPS ${f.lat.toFixed(4)}, ${f.lon.toFixed(4)}</div>` : ''}</div>`).join('')}</div>` : ''}</div>
      <div><h3>Catalogación automática</h3><div style="display:flex;gap:4px;flex-wrap:wrap;margin:6px 0"><span class="chip">${esc(p.cat.categoria)}</span><span class="chip ${{ Alta: 'bad', Media: 'warn', Baja: 'ok' }[p.cat.prioridad]}">Prioridad ${p.cat.prioridad}</span>${p.cat.temas.map(t => `<span class="chip">${esc(t)}</span>`).join('')}${p.cat.sentimiento ? `<span class="chip">${esc(p.cat.sentimiento)}</span>` : ''}</div>
      <dl class="kv"><dt>Se turna a</dt><dd>${p.cat.autoridad.map(esc).join('<br>')}</dd>${p.cat.motivos.length ? `<dt>Motivos</dt><dd>${p.cat.motivos.map(esc).join('<br>')}</dd>` : ''}<dt>Plazo de respuesta</dt><dd>${esc(p.vence)} <span class="tiny dim">(${p.cat.plazo} días hábiles, ilustrativo)</span></dd></dl>
      <h3 style="margin-top:10px">Cruce geográfico</h3>${x ? `<dl class="kv"><dt>Huerta inscrita</dt><dd>${x.huerta ? `<a data-h="${x.huerta.uid}" class="mono">${x.huerta.uid}</a> · ${esc(x.huerta.estado)}` : 'Fuera del padrón'}</dd><dt>ANP</dt><dd>${esc(x.anp || 'No')}</dd><dt>Núcleo agrario</dt><dd>${esc(x.ran || (x.muestra ? 'No' : 'Fuera de la tesela de muestra'))}</dd><dt>Subcuenca</dt><dd>${esc(x.sub || '—')}</dd><dt>Alertas a &lt;1.5 km</dt><dd>${x.alertasCerca.length ? x.alertasCerca.map(a => `<span class="mono tiny">${a.id}</span> (${a.d} m, ${esc(a.st)})`).join('<br>') : 'Ninguna'}</dd>${x.muestra ? `<dt>Guardián Forestal</dt><dd>${x.gfAlertas || 0} alertas 2020-2026 en la celda</dd>` : ''}</dl>` : '<div class="tiny dim">Sin punto: sólo nivel municipal.</div>'}
      <h3 style="margin-top:10px">Integridad</h3><dl class="kv"><dt>Huella SHA-256</dt><dd class="hash mono" style="font-size:10.5px;word-break:break-all">${p.hash}</dd>${p.alerta ? `<dt>Alerta</dt><dd><a data-tri="${p.alerta}" class="mono">${p.alerta}</a></dd>` : ''}${p.expediente ? `<dt>Expediente</dt><dd><a data-exp="${p.expediente}" class="mono">${p.expediente}</a></dd>` : ''}</dl>
      ${p.respuesta ? `<div class="note info tiny" style="margin-top:8px"><b>Respuesta (${fdate(p.respuesta.ts)}):</b> ${esc(p.respuesta.txt)}</div>` : ''}</div></div>
      <div style="display:flex;gap:8px;justify-content:flex-end;margin-top:14px;flex-wrap:wrap">${p.tipo === 'denuncia' && !p.alerta && p.ubicacion ? `<button class="btn" id="ptr" ${ro ? 'disabled' : ''}>${icon('alert', 14)} Turnar a triaje</button>` : ''}${p.alerta ? `<button class="btn" data-tri="${p.alerta}">${icon('alert', 14)} Ver en triaje</button>` : ''}<button class="btn" id="pres" ${ro ? 'disabled' : ''}>${icon('check', 14)} Responder</button>${ro ? '<span class="tiny dim">Auditor: sólo lectura</span>' : ''}</div>`, { w: '900px' });
    const tr = m.q('#ptr'); if (tr) tr.onclick = () => { const r = turnarATriaje(p, me().id); if (!r.ok) return toast(r.why, 'warn'); m.close(); toast('Turnada a la cola de triaje como ' + p.alerta); draw(); window.__refreshBadges && window.__refreshBadges(); };
    m.q('#pres').onclick = () => { const mm = modal(`<h2>Responder ${p.folio}</h2><p class="tiny dim">La respuesta es pública por folio (la persona la consulta con Arbolín). No incluya datos personales.</p><textarea id="rt" rows="4" style="width:100%">${p.tipo === 'denuncia' ? 'Gracias por tu denuncia. Se revisó con imagen satelital y se programó visita de campo.' : 'Gracias por tu participación. Se turnó al área correspondiente y se considerará en la agenda de este trimestre.'}</textarea><div style="display:flex;gap:8px;justify-content:flex-end;margin-top:10px"><button class="btn ghost" data-close>Cancelar</button><button class="btn pri" id="rok">Publicar respuesta</button></div>`, { w: '520px' }); mm.q('#rok').onclick = () => { const v = mm.q('#rt').value.trim(); if (v.length < 10) return toast('Escriba una respuesta', 'warn'); responder(p, v, me().id); mm.close(); m.close(); toast('Respuesta registrada en bitácora'); draw(); window.__refreshBadges && window.__refreshBadges(); }; };
    m.el.addEventListener('click', e => { const a = e.target.closest('[data-tri],[data-exp],[data-h]'); if (!a) return; m.close(); if (a.dataset.tri) window.__go('admin', 'triaje', { id: a.dataset.tri }); else if (a.dataset.exp) window.__go('admin', 'expedientes', { id: a.dataset.exp }); else window.__go('admin', 'huertas', { id: a.dataset.h }); });
  };
  if (params.id) setTimeout(() => ficha(params.id), 50);
  return () => map && map.destroy();
}

// Portal Ciudadano · Participa (agregados públicos; sin textos ni datos personales)
function participaPub(main) {
  const P = S.participaciones; const by = f => { const o = {}; P.forEach(p => { const k = f(p); if (k) o[k] = (o[k] || 0) + 1; }); return Object.entries(o).sort((a, b) => b[1] - a[1]); };
  const bars = (rows, c = 'var(--g)') => { const mx = Math.max(1, ...rows.map(r => r[1])); return rows.map(([k, v]) => `<div style="display:flex;align-items:center;gap:8px;margin:5px 0;font-size:12.5px"><span style="width:48%;min-width:0;overflow:hidden;text-overflow:ellipsis;white-space:nowrap" title="${esc(k)}">${esc(k)}</span><span style="flex:1;height:9px;background:var(--bg);border-radius:5px;overflow:hidden"><i style="display:block;height:100%;width:${100 * v / mx}%;background:${c}"></i></span><b class="mono" style="width:22px;text-align:right">${v}</b></div>`).join(''); };
  main.innerHTML = hdr('Participa', 'Tu opinión, tus ideas y tus denuncias sí cuentan. Arbolín te guía paso a paso, ubica tu reporte en el mapa y te da un folio para darle seguimiento. Aquí se publica qué se ha recibido y qué respuesta se dio, sin textos ni datos personales.', tag('demo')) +
    `<div class="arb-band" style="margin-bottom:14px">${arbolinSvg(64)}<div><b>Habla con Arbolín</b><p>Pregunta cómo está el bosque en tu municipio, consulta una huerta o un folio, o deja tu opinión, sugerencia, propuesta o denuncia. Puede ser anónima.</p></div><button class="btn pri" id="pgo">Hablar con Arbolín</button></div>
    <div class="grid g4" style="margin-bottom:14px">${kpi({ l: 'Participaciones recibidas', v: fmt(P.length) })}${kpi({ l: 'Denuncias en revisión técnica', v: fmt(P.filter(p => p.alerta || ['En análisis', 'Turnada'].includes(p.estado) && p.tipo === 'denuncia').length), c: '#B3261E' })}${kpi({ l: 'Con respuesta publicada', v: fmt(P.filter(p => p.respuesta).length), c: '#2E7D32' })}${kpi({ l: 'Municipios participando', v: fmt(new Set(P.map(munOf)).size) })}</div>
    <div class="grid g3"><div class="card"><h3>Por tipo</h3><div style="margin-top:8px">${bars(by(p => TIPOS[p.tipo].n))}</div></div><div class="card"><h3>Por tema</h3><div style="margin-top:8px">${bars(by(p => p.cat.categoria))}</div></div><div class="card"><h3>Por municipio</h3><div style="margin-top:8px">${bars(by(p => munName[munOf(p)]).slice(0, 8), '#A8720F')}</div></div></div>
    <div class="card" style="margin-top:14px"><h3>Respuestas publicadas</h3><div class="tw" style="margin-top:8px"><table class="tbl"><thead><tr><th>Folio</th><th>Tipo</th><th>Tema</th><th>Municipio</th><th>Respuesta</th></tr></thead><tbody>${P.filter(p => p.respuesta).map(p => `<tr><td class="mono tiny">${p.folio}</td><td>${TIPOS[p.tipo].n}</td><td class="tiny">${esc(p.cat.categoria)}</td><td>${esc(munName[munOf(p)])}</td><td class="tiny">${esc(p.respuesta.txt)}</td></tr>`).join('') || '<tr><td colspan="5" class="dim">Aún no hay respuestas publicadas.</td></tr>'}</tbody></table></div><div class="tiny dim" style="margin-top:8px">El contenido de cada denuncia y la identidad de quien la presenta son información reservada; sólo se publica el folio, el tema, el municipio y la respuesta.</div></div>`;
  $('#pgo', main).onclick = () => window.__arbolin && window.__arbolin.abrir();
}
export const pubViews = { participa: participaPub };
export const views = { participacion };
export const pendientes = () => S.participaciones.filter(p => ['Recibida', 'En análisis'].includes(p.estado)).length;
