import { $, $$, on, esc, fmt, fdate, CLS, badge, chip, toast, download, TODAY, polyAreaHa } from '../util.js';
import { S, ST, G, P, munName, prediosById, refresh } from '../state.js';
import * as ch from '../charts.js';
import { kpi, tag, icon, stars, projChip, predioFicha, modal, estadoChip, conChip, forestChart } from '../ui.js';
import { createMap, attachControls, locate } from '../mapkit.js';
import { analyzeFiles, runChecks, verdict, renderChecks, verdictBox, CHECK_DEFS } from '../verify.js';
import { makeSamplePackage, tamper } from '../sample.js';
import { sha256Str, shortHash, ledgerAppend } from '../integrity.js';
import { prepPts } from '../map.js';
import { procedimientos as procView } from './portales.js';
import { ensureDemo } from '../domain/process.js';

// productor de demostración: el que tenga más predios
const byPrd = {}; S.predios.features.forEach(f => (byPrd[f.properties.prd] ||= []).push(f.properties.id));
const PRD = Object.keys(byPrd).sort((a, b) => byPrd[b].length - byPrd[a].length)[0];
const mine = () => S.predios.features.filter(f => f.properties.prd === PRD).map(f => f.properties);
const hdr = (t, p, act = '') => `<div class="page-h"><div><h1>${t}</h1>${p ? `<p>${p}</p>` : ''}</div><div class="act">${act}</div></div>`;
let logged = false;
function gate(main, then) {
  if (logged) return false;
  main.innerHTML = `<div style="max-width:460px;margin:60px auto"><div class="card" style="padding:26px;text-align:center">
    <div style="font-size:34px;margin-bottom:6px">${icon('key', 38)}</div><h1 style="font-size:20px">Ingreso del productor</h1>
    <p class="dim" style="margin:8px 0 18px">Acceda con su Llave MX o con su e.firma. Su información es visible sólo para usted y para personal autorizado, y cada consulta queda registrada.</p>
    <button class="btn pri" style="width:100%;justify-content:center;padding:11px" id="lg">Ingresar con Llave MX (simulado)</button>
    <div class="tiny dim" style="margin-top:12px">Cuenta de demostración: <span class="mono">${PRD}</span> · ${mine().length} predios</div></div></div>`;
  $('#lg', main).onclick = () => { logged = true; ledgerAppend(S.ledger, PRD, 'SESION_INICIADA', PRD); then(); };
  return true;
}
const nextStep = p => ({ verde: p.con === 'Vigente' ? 'Constancia vigente. Sin acciones.' : p.con === 'Por vencer' ? 'Renovar constancia (vence pronto).' : 'Completar expediente de constancia.', naranja: 'Presentar proyecto de restauración y programar verificación LiDAR.', rojo: 'Comparecer a audiencia y presentar propuesta de compensación.', amarillo: 'Aportar evidencia (fotos fechadas, autorización, LiDAR) en un plazo de 10 días hábiles.', gris: p.est === 'Polígono sin validar' ? 'Validar su polígono (cargar GeoJSON/KML o dibujar).' : 'Completar información del predio.' }[p.cls]);

function panel(main) {
  if (gate(main, () => panel(main))) return;
  const ms = mine(), ha = ms.reduce((a, p) => a + p.ha, 0);
  main.innerHTML = hdr('Buenos días, productor ' + PRD, 'Este es el estado de sus predios y lo que necesita hacer. La información es suya; usted decide qué comparte con compradores.', `<span class="chip ok">Sesión con Llave MX (simulada)</span>`) +
    `<div class="grid g4">${kpi({ l: 'Predios inscritos', v: ms.length, s: fmt(ha, 1) + ' ha' })}${kpi({ l: 'Semáforo', v: ['verde', 'amarillo', 'naranja', 'rojo', 'gris'].map(c => ms.filter(p => p.cls === c).length ? `<span style="color:${CLS[c].color}">${ms.filter(p => p.cls === c).length}</span>` : '').filter(Boolean).join('<span class="dim" style="font-size:18px"> · </span>'), s: 'por color' })}${kpi({ l: 'Pendientes', v: ms.filter(p => p.cls !== 'verde' || p.con !== 'Vigente').length, s: 'requieren acción', c: '#F59E0B' })}${kpi({ l: 'Levantamientos', v: S.estudios.filter(e => ms.find(p => p.id === e.pid)).length, s: 'recibidos y verificados', c: '#34D399' })}</div>
    <div class="grid g21" style="margin-top:14px"><div class="card pad0" style="height:420px"><div id="pm" style="height:100%"></div></div>
      <div class="card"><div class="ch"><h3>Lo que sigue</h3></div>${ms.map(p => `<div style="padding:9px 0;border-bottom:1px solid #163A27"><div style="display:flex;gap:8px;align-items:center"><span class="mono tiny">${p.id}</span>${badge(p.cls)}<span class="dim tiny" style="margin-left:auto">${fmt(p.ha, 1)} ha</span></div><div class="tiny" style="margin-top:4px;color:#CFE3D6">${nextStep(p)}</div></div>`).join('')}</div></div>
    <div class="grid g3" style="margin-top:14px">${[['Solicitar Historial Forestal', 'Reconstruya 1993-2025 de un predio', 'tramites', 'file'], ['Cargar levantamiento LiDAR', 'Verificación de integridad antes de enviar', 'levantamiento', 'drone'], ['Proyecto de restauración', 'Presente un proyecto para evaluación', 'restauracion', 'leaf']].map(a => `<div class="card" style="cursor:pointer" data-go="${a[2]}"><div style="color:var(--cyan)">${icon(a[3], 24)}</div><b style="display:block;margin-top:8px">${a[0]}</b><div class="tiny dim">${a[1]}</div></div>`).join('')}</div>`;
  on(main, 'click', '[data-go]', (e, b) => window.__go('productor', b.dataset.go));
  const map = createMap($('#pm', main), { ids: new Set(ms.map(p => p.id)), showAlerts: false, showLidar: true, showRest: true }); map.show('alertas', false); attachControls($('#pm', main).parentElement, map, { sat: true });
  const xs = [], ys = []; ms.forEach(p => prediosById[p.id].geometry.coordinates[0].forEach(c => { xs.push(c[0]); ys.push(c[1]); })); map.fitBounds([Math.min(...xs), Math.min(...ys), Math.max(...xs), Math.max(...ys)], 60, false); map.home = () => map.fitBounds([Math.min(...xs), Math.min(...ys), Math.max(...xs), Math.max(...ys)], 60);
  return () => map.destroy();
}

function predios(main) {
  if (gate(main, () => predios(main))) return;
  const ms = mine(); let sel = ms[0].id;
  main.innerHTML = hdr('Mis predios', 'Polígonos, clasificación y expediente de cada predio inscrito a su nombre.', `<button class="btn pri" id="ins">${icon('plus', 15)} Inscribir predio</button>`) + `<div class="grid g32"><div class="tw"><table class="tbl"><thead><tr><th>Folio</th><th>Municipio</th><th class="num">Ha</th><th>Semáforo</th><th>Constancia</th></tr></thead><tbody>${ms.map(p => `<tr class="cl ${p.id === sel ? 'act' : ''}" data-id="${p.id}"><td class="mono">${p.id}</td><td>${esc(munName[p.mun])}</td><td class="num">${fmt(p.ha, 1)}</td><td>${badge(p.cls)}</td><td>${conChip(p.con)}</td></tr>`).join('')}</tbody></table></div><div class="card" id="fi"></div></div>`;
  const show = id => { sel = id; $$('tr.cl', main).forEach(r => r.classList.toggle('act', r.dataset.id === id)); $('#fi', main).innerHTML = predioFicha(id, 'productor') + `<div class="note tiny" style="margin-top:10px"><b>Siguiente paso:</b> ${nextStep(prediosById[id].properties)}</div>`; }; show(sel);
  on(main, 'click', 'tr.cl', (e, r) => show(r.dataset.id));
  $('#ins', main).onclick = () => inscribir();
}
function inscribir() {
  const m = modal(`<h2>Inscribir un predio</h2><p class="dim tiny">Cargue el polígono en GeoJSON (WGS84 o ITRF2008). El sistema valida geometría, superficie y traslapes, y el predio entra como <b style="color:#8FAA98">gris</b> hasta que la administración lo valide.</p><div class="drop" id="dz">Arrastre aquí su archivo .geojson o haga clic<input type="file" id="fi" accept=".geojson,.json" hidden></div><div id="res" style="margin-top:12px"></div><div style="text-align:right;margin-top:14px"><button class="btn ghost" data-close>Cerrar</button></div>`);
  const dz = m.q('#dz'), fi = m.q('#fi'); dz.onclick = () => fi.click(); ['dragover', 'dragenter'].forEach(ev => dz.addEventListener(ev, e => { e.preventDefault(); dz.classList.add('over'); })); ['dragleave', 'drop'].forEach(ev => dz.addEventListener(ev, e => { e.preventDefault(); dz.classList.remove('over'); }));
  const proc = async f => { const res = m.q('#res'); try { const gj = JSON.parse(await f.text()); const ft = (gj.features || [gj])[0]; const geom = ft.geometry || ft; const ring = (geom.type === 'MultiPolygon' ? geom.coordinates[0][0] : geom.coordinates[0]); const ha = polyAreaHa(ring); const inMich = ring.every(c => c[0] > -103.8 && c[0] < -100 && c[1] > 17.9 && c[1] < 20.4); res.innerHTML = `<div class="chk"><span class="ic ok">✓</span><div><b>Geometría válida</b><small>${ring.length - 1} vértices · ${fmt(ha, 2)} ha</small></div></div><div class="chk"><span class="ic ${inMich ? 'ok' : 'fail'}">${inMich ? '✓' : '✕'}</span><div><b>Dentro de Michoacán</b></div></div><button class="btn pri" id="go" ${inMich ? '' : 'disabled'} style="margin-top:10px">Enviar a validación</button>`; const go = m.q('#go'); go && (go.onclick = () => { toast('Predio enviado a validación (folio provisional PF-NUE-' + Math.floor(Math.random() * 9000 + 1000) + ')'); ledgerAppend(S.ledger, PRD, 'PREDIO_INSCRITO', 'PF-NUE'); m.close(); }); } catch (e) { res.innerHTML = '<div class="note bad">No se pudo leer el archivo como GeoJSON de polígono.</div>'; } };
  fi.onchange = () => fi.files[0] && proc(fi.files[0]); dz.addEventListener('drop', e => e.dataTransfer.files[0] && proc(e.dataTransfer.files[0]));
}

function tramites(main) {
  if (gate(main, () => tramites(main))) return;
  const ms = mine(); const T = [
    ['Historial Forestal', 'Documento con la cobertura arbórea 1993-2025, alertas y fecha de referencia de cada predio.', 'Emisión inmediata si el polígono está validado', 'file', 'hist'],
    ['Constancia de Integridad Forestal', 'Se emite con el semáforo verde y, en su caso, estudio LiDAR aceptado. Verificable con código QR.', '15 días hábiles (P90)', 'shield', 'con'],
    ['Presentar evidencia o solicitar audiencia', 'Si su predio está en amarillo, naranja o rojo puede aportar pruebas antes de que la clasificación sea firme.', 'Plazo de 10 días hábiles desde la notificación', 'scale', 'aud'],
    ['Solicitar rectificación de datos personales (ARCO)', 'Acceso, rectificación, cancelación y oposición sobre sus datos.', 'Plazos de ley', 'users', 'arco']];
  main.innerHTML = hdr('Trámites', 'Todos los trámites generan un acuse con huella criptográfica y quedan en la bitácora inalterable.') + `<div class="grid g2">${T.map(t => `<div class="card"><div style="color:var(--cyan)">${icon(t[3], 24)}</div><h2 style="margin-top:8px">${t[0]}</h2><p class="dim tiny" style="margin:6px 0">${t[1]}</p><div class="tiny dim" style="margin-bottom:10px">${icon('clock', 13)} ${t[2]}</div><button class="btn pri" data-t="${t[4]}">Iniciar</button></div>`).join('')}</div>`;
  on(main, 'click', '[data-t]', (e, b) => {
    const k = b.dataset.t; const sel = `<label class="f">Predio<select id="ps">${ms.map(p => `<option value="${p.id}">${p.id} · ${fmt(p.ha, 1)} ha · ${CLS[p.cls].name}</option>`).join('')}</select></label>`;
    if (k === 'hist') { const m = modal(`<h2>Historial Forestal</h2>${sel}<div style="text-align:right"><button class="btn ghost" data-close>Cancelar</button> <button class="btn pri" id="ok">Emitir y descargar</button></div>`); m.q('#ok').onclick = () => { const p = prediosById[m.q('#ps').value].properties; const h = sha256Str('HF' + p.id + '2026-09-29'); const doc = `<!doctype html><meta charset="utf-8"><title>Historial Forestal ${p.id}</title><body style="font-family:system-ui;max-width:780px;margin:30px auto;color:#111"><h1>Historial Forestal · ${p.id}</h1><p><b>DOCUMENTO DE DEMOSTRACIÓN</b> — datos ilustrativos.</p><table cellpadding=6 border=1 style="border-collapse:collapse"><tr><td>Municipio</td><td>${munName[p.mun]}</td></tr><tr><td>Superficie</td><td>${p.ha} ha</td></tr><tr><td>Semáforo</td><td>${CLS[p.cls].name}</td></tr><tr><td>Fecha de referencia</td><td>1-ene-2018 (deforestación) · 1-ene-2012 (incendio)</td></tr></table><h3>Cobertura arbórea 1993-2025 (ilustrativa)</h3>${forestChart(p, 700, 240).replace('class="chart"', 'style="width:100%"').replace(/fill="#A7C4B2"/g, 'fill="#333"').replace(/stroke="#1D4530"/g, 'stroke="#ddd"')}<p style="font-family:monospace;font-size:12px">Huella SHA-256 del documento: ${h}<br>Verificación: /verificar/${h.slice(0, 12)}</p></body>`; download('Historial_Forestal_' + p.id + '.html', doc, 'text/html'); ledgerAppend(S.ledger, PRD, 'HISTORIAL_EMITIDO', p.id); toast('Historial emitido y registrado en la bitácora'); m.close(); }; }
    else if (k === 'con') { const m = modal(`<h2>Constancia de Integridad Forestal</h2>${sel}<div id="r"></div><div style="text-align:right"><button class="btn ghost" data-close>Cerrar</button> <button class="btn pri" id="ok">Evaluar requisitos</button></div>`); m.q('#ok').onclick = () => { const p = prediosById[m.q('#ps').value].properties; const est = S.estudios.find(e => e.pid === p.id); const reqs = [['Polígono validado', p.cls !== 'gris'], ['Sin pérdida confirmada posterior a la fecha de referencia', p.cls === 'verde'], ['Estudio LiDAR nivel B íntegro', est && est.ver === 'Íntegro'], ['Sin causales determinantes', p.cls !== 'rojo']]; m.q('#r').innerHTML = reqs.map(r => `<div class="chk"><span class="ic ${r[1] ? 'ok' : 'fail'}">${r[1] ? '✓' : '✕'}</span><div>${r[0]}</div></div>`).join(''); }; }
    else if (k === 'aud') { const m = modal(`<h2>Aportar evidencia / audiencia</h2>${sel}<label class="f">Descripción<textarea rows="3" id="d"></textarea></label><div class="drop" id="dz">Adjuntar fotografías fechadas, autorizaciones, LiDAR…</div><div style="text-align:right;margin-top:12px"><button class="btn ghost" data-close>Cancelar</button> <button class="btn pri" id="ok">Enviar</button></div>`); m.q('#ok').onclick = () => { ledgerAppend(S.ledger, PRD, 'EVIDENCIA_PRESENTADA', m.q('#ps').value); toast('Evidencia recibida. Se suspende la firmeza hasta resolver.'); m.close(); }; }
    else { toast('Solicitud ARCO registrada (demostración)'); ledgerAppend(S.ledger, PRD, 'SOLICITUD_ARCO', PRD); }
  });
}

// ---------- Cargar levantamiento con verificación previa de integridad ----------
function levantamiento(main) {
  if (gate(main, () => levantamiento(main))) return;
  const ms = mine(); const wz = { pid: ms[0].id, files: [], infos: [], checks: [], sealed: null, manifest: null, sample: false };
  main.innerHTML = hdr('Cargar levantamiento LiDAR / dron', 'Antes de enviar, su equipo calcula la huella de cada archivo y contrasta los metadatos del dron (EXIF, LAS, trayectoria, control). Los archivos no salen de su computadora hasta que usted presiona "Enviar y sellar".', `<button class="btn" id="smp">${icon('drone', 15)} Generar paquete de prueba</button>`) +
    `<div class="grid g12"><div class="card"><h3>1. Datos del vuelo</h3><div style="margin-top:10px">
      <label class="f">Predio<select id="pid">${ms.map(p => `<option value="${p.id}">${p.id} · ${fmt(p.ha, 1)} ha · ${munName[p.mun]}</option>`).join('')}</select></label>
      <label class="f">Fecha del vuelo<input type="date" id="fecha" value="2026-09-12"></label>
      <label class="f">Folio de autorización de vuelo (INEGI)<input id="aut" placeholder="INEGI/DGG/2026/4471"></label>
      <div class="two"><label class="f">Aeronave<input id="am" placeholder="DJI Matrice 350 RTK"></label><label class="f">Serie aeronave<input id="as" placeholder="1ZNBK…"></label></div>
      <div class="two"><label class="f">Sensor<input id="sm" placeholder="Zenmuse L2"></label><label class="f">Serie sensor<input id="ss" placeholder="SN…"></label></div>
      <h3 style="margin:8px 0">2. Archivos del levantamiento</h3>
      <div class="drop" id="dz"><b>Suelte aquí</b> la nube (.las/.laz), trayectoria (.csv), control (.csv), fotografías (.jpg) y bitácora de vuelo<br><span class="tiny">o haga clic para elegir</span><input type="file" id="fi" multiple hidden></div>
      <div id="fl" class="tiny" style="margin-top:8px"></div>
      <button class="btn pri" id="ver" style="margin-top:12px;width:100%;justify-content:center" disabled>${icon('shield', 15)} 3. Verificar integridad</button></div></div>
    <div><div id="out"><div class="card"><div class="dim" style="text-align:center;padding:40px 10px">${icon('hash', 34)}<div style="margin-top:8px">Cargue archivos y presione <b>Verificar</b>.<br>Puede probar el flujo completo con un <b>paquete de prueba</b> y luego intentar alterarlo.</div></div></div></div></div></div>`;
  const q = s => $(s, main); const meta = () => ({ pid: q('#pid').value, fecha: q('#fecha').value, autoriz: q('#aut').value, aeroModelo: q('#am').value, aeroSerie: q('#as').value, sensorModelo: q('#sm').value, sensorSerie: q('#ss').value, densMin: 100 });
  const listFiles = () => { q('#fl').innerHTML = wz.files.length ? wz.files.map(f => `<div class="mono" style="display:flex;justify-content:space-between;padding:2px 0"><span>${esc(f.name)}</span><span class="dim">${fmt(f.size / 1024)} KB</span></div>`).join('') : ''; q('#ver').disabled = !wz.files.length; };
  const add = fl => { wz.files.push(...fl); wz.sealed = null; listFiles(); };
  const dz = q('#dz'), fi = q('#fi'); dz.onclick = () => fi.click(); fi.onchange = () => add([...fi.files]); ['dragover', 'dragenter'].forEach(ev => dz.addEventListener(ev, e => { e.preventDefault(); dz.classList.add('over'); })); ['dragleave', 'drop'].forEach(ev => dz.addEventListener(ev, e => { e.preventDefault(); dz.classList.remove('over'); })); dz.addEventListener('drop', e => add([...e.dataTransfer.files]));
  q('#smp').onclick = async () => { const p = prediosById[q('#pid').value]; const pk = await makeSamplePackage(p, 'MUESTRA-' + p.properties.id.slice(-5)); wz.files = pk.files; wz.sample = true; wz.manifest = null; wz.sealed = null; q('#fecha').value = pk.meta.fecha; q('#aut').value = pk.meta.autoriz; q('#am').value = pk.meta.aeroModelo; q('#as').value = pk.meta.aeroSerie; q('#sm').value = pk.meta.sensorModelo; q('#ss').value = pk.meta.sensorSerie; listFiles(); toast('Paquete de prueba generado: nube LAS 1.4, trayectoria, control, foto con EXIF y bitácora'); q('#ver').click(); };
  const paint = (extra = '') => { const v = verdict(wz.checks); q('#out').innerHTML = `<div class="card">${verdictBox(v)}<div class="ch" style="margin:12px 0 4px"><h3>Comprobaciones</h3><div class="sp mono tiny dim">${wz.infos.length} archivos</div></div>${renderChecks(wz.checks)}</div>
    <div class="card" style="margin-top:12px"><h3>Manifiesto de huellas</h3><div class="tw" style="margin-top:8px;max-height:200px"><table class="tbl"><tbody>${wz.infos.map(i => `<tr><td>${esc(i.name)}<div class="tiny dim">${i.kind}${i.las ? ` · LAS ${i.las.version} · ${fmt(i.las.count)} pts` : ''}${i.exif && i.exif.tags && i.exif.tags.Model ? ` · ${esc(i.exif.tags.Make || '')} ${esc(i.exif.tags.Model)}` : ''}</div></td><td class="hash">${i.sha}</td></tr>`).join('')}</tbody></table></div>
    <div style="display:flex;gap:8px;margin-top:12px;flex-wrap:wrap"><button class="btn ok" id="seal" ${wz.sealed || v.f ? 'disabled' : ''}>${icon('hash', 15)} ${wz.sealed ? 'Manifiesto sellado' : 'Enviar y sellar manifiesto'}</button></div>${extra}</div>`;
    const sl = q('#seal'); sl && (sl.onclick = seal); };
  const run = async (manifest) => { q('#out').innerHTML = `<div class="card"><h3>Calculando huellas…</h3><div class="bar" style="margin-top:10px"><i id="pg" style="width:0"></i></div><div class="tiny dim" id="pt" style="margin-top:6px"></div></div>`; wz.infos = await analyzeFiles(wz.files, (i, p) => { const pg = q('#pg'); if (pg) { pg.style.width = ((i + p) / wz.files.length * 100) + '%'; q('#pt').textContent = wz.files[i].name; } }); wz.checks = runChecks(meta(), wz.infos, manifest || null, { signed: !!wz.sealed, selfId: wz.sealed && wz.sealed.id }); paint(manifest ? '' : ''); };
  q('#ver').onclick = () => run(wz.manifest);
  const seal = () => {
    const m = meta(); const id = 'LDR-2026-' + String(S.estudios.length + 1).padStart(4, '0'); const man = wz.infos.map(i => ({ name: i.name, sha: i.sha })); const root = sha256Str(JSON.stringify(man)); wz.manifest = man; wz.sealed = { id, root };
    const p = prediosById[m.pid]; const v = verdict(wz.checks); const nube = wz.infos.find(i => i.las); const c = p.geometry.coordinates[0]; const lon = c.reduce((a, x) => a + x[0], 0) / c.length, lat = c.reduce((a, x) => a + x[1], 0) / c.length;
    const e = { id, pid: m.pid, mun: p.properties.mun, nivel: 'B', fecha: m.fecha, oper: 'OC-099', aero: { marca: 'DJI', modelo: m.aeroModelo, serie: m.aeroSerie }, sensor: { marca: '', modelo: m.sensorModelo, serie: m.sensorSerie, cal: '—' }, gnss: 'RTK/PPK', agl: 80, vel: 6, autoriz: m.autoriz, utc0: m.fecha + 'T17:30:00Z', utc1: m.fecha + 'T18:41:00Z', area: p.properties.ha, dens: nube ? Math.round(nube.las.count / (((nube.las.max[0] - nube.las.min[0]) * (nube.las.max[1] - nube.las.min[1])) || 1)) : 0, npts: nube ? nube.las.count : 0, crs: 'ITRF2008 época 2010.0 / UTM ' + (lon < -102 ? '13' : '14') + 'N', files: wz.infos.map(i => ({ n: i.name, role: i.kind, mb: Math.max(1, Math.round(i.size / 1048576)), sha: i.sha, ok: true })), checks: wz.checks.map(x => ({ ...x })), ver: v.ver === 'Pendiente' ? 'Con observaciones' : v.ver, lon, lat, manifest: root, nuevo: true };
    S.estudios.unshift(e); P.estudios.push(...prepPts([e])); wz.infos.forEach(i => S.uploads.push({ sha: i.sha, name: i.name, study: id, guid: i.las && i.las.guid })); wz.checks.find(x => x.k === 'firma').s = 'ok'; wz.checks.find(x => x.k === 'firma').det = 'Firma electrónica registrada y sello de tiempo emitido (simulado).';
    ledgerAppend(S.ledger, 'Sistema', 'ESTUDIO_RECIBIDO', id); ledgerAppend(S.ledger, 'Sistema', 'MANIFIESTO_SELLADO', id); refresh(); window.__refreshBadges && window.__refreshBadges();
    paint(`<div class="note info tiny" style="margin-top:12px">Recibido como <b class="mono">${id}</b>. Raíz del manifiesto: <span class="hash">${root}</span><br>Cualquier cambio posterior a cualquier archivo cambiará su huella y será detectado.</div>
      <div class="sec"><h3>Simular alteración posterior (demostración)</h3><p class="tiny dim">Modifique el paquete ya sellado y vuelva a verificarlo contra el manifiesto.</p><div style="display:flex;gap:8px;flex-wrap:wrap"><button class="btn danger sm" data-tp="nube">Alterar 1 bit de la nube</button><button class="btn danger sm" data-tp="foto">Cambiar hora de la foto a 03:10</button><button class="btn danger sm" data-tp="traj">Insertar salto de 440 m en la trayectoria</button></div></div>`);
    toast('Manifiesto sellado en la bitácora encadenada'); };
  on(main, 'click', '[data-tp]', async (e, b) => { wz.files = await tamper(wz.files, b.dataset.tp); await run(wz.manifest); toast('Paquete alterado y re-verificado contra el manifiesto sellado', 'warn'); });
  return () => { };
}

function restauracion(main) {
  if (gate(main, () => restauracion(main))) return;
  const ms = mine(); const mp = S.proyectos.filter(r => ms.find(p => p.id === r.pid));
  main.innerHTML = hdr('Proyectos de restauración', 'Presente un proyecto de reforestación o regeneración. Se evalúa con criterios técnicos y se verifica con LiDAR antes, durante y después.', `<button class="btn pri" id="np">${icon('plus', 15)} Nuevo proyecto</button>`) +
    (mp.length ? `<div class="tw"><table class="tbl"><thead><tr><th>Proyecto</th><th>Predio</th><th>Tipo</th><th class="num">Ha</th><th>Estado</th><th>Avance</th></tr></thead><tbody>${mp.map(r => `<tr><td class="mono">${r.id}</td><td class="mono">${r.pid}</td><td>${esc(r.tipo)}</td><td class="num">${fmt(r.ha, 1)}</td><td>${projChip(r.st)}</td><td>${r.surv ? 'Superv. ' + r.surv + ' % ' + stars(r.stars) : '—'}</td></tr>`).join('')}</tbody></table></div>` : '<div class="card dim">Aún no tiene proyectos. Los predios naranja y rojo pueden presentar uno.</div>') +
    `<div class="card" style="margin-top:14px"><h3>Criterios de evaluación</h3><ul class="tiny" style="line-height:1.9;color:#B7D0BF;margin:8px 0 0;padding-left:18px"><li>Especies nativas adecuadas al piso altitudinal (pino-encino) y densidad de plantación.</li><li>Ecosistema de referencia y línea base LiDAR (nivel B) previa a la intervención.</li><li>Plan de mantenimiento, protección contra fuego y ganado, y garantía financiera.</li><li>Verificación: supervivencia al 2.º año ≥ umbral de la norma técnica, cobertura de copa y estructura vertical.</li></ul></div>`;
  $('#np', main).onclick = () => { const m = modal(`<h2>Nuevo proyecto de restauración</h2><label class="f">Predio<select id="ps">${ms.filter(p => p.cls === 'naranja' || p.cls === 'rojo' || true).map(p => `<option value="${p.id}">${p.id} · ${CLS[p.cls].name}</option>`).join('')}</select></label><div class="two"><label class="f">Tipo<select id="tp"><option>Regeneración natural asistida (N1)</option><option>Reforestación con especies nativas</option><option>Restauración de ribera y manantiales</option><option>Sistema agroforestal / silvopastoril</option></select></label><label class="f">Superficie (ha)<input id="ha" type="number" value="2.5" step="0.1"></label></div><label class="f">Especies nativas<input id="es" value="Pinus pseudostrobus, Quercus laurina, Alnus jorullensis"></label><div style="text-align:right"><button class="btn ghost" data-close>Cancelar</button> <button class="btn pri" id="ok">Enviar a evaluación</button></div>`); m.q('#ok').onclick = () => { const p = prediosById[m.q('#ps').value]; const c = p.geometry.coordinates[0]; const r = { id: 'RES-2026-' + String(S.proyectos.length + 1).padStart(3, '0'), pid: p.properties.id, mun: p.properties.mun, tipo: m.q('#tp').value, ha: +m.q('#ha').value, esp: m.q('#es').value.split(',').map(s => s.trim()), st: 'En evaluación', plant: 0, surv: null, stars: null, ini: '2026-09-29', lidar_base: null, lon: c[0][0], lat: c[0][1] }; S.proyectos.unshift(r); P.proyectos.push(...prepPts([r])); refresh(); ledgerAppend(S.ledger, PRD, 'PROYECTO_PRESENTADO', r.id); toast('Proyecto ' + r.id + ' recibido'); m.close(); restauracion(main); }; };
}

function avisos(main) {
  if (gate(main, () => avisos(main))) return;
  const ms = mine(); const list = [];
  ms.forEach(p => { if (p.cls === 'naranja') list.push(['Clasificación naranja (' + p.niv + ')', p.id, 'Se confirmó pérdida reversible de ' + fmt(p.aff, 1) + ' ha. Tiene 10 días hábiles para aportar evidencia o presentar proyecto de restauración.', 'warn']); if (p.cls === 'rojo') list.push(['Clasificación roja', p.id, 'Se notificó daño irreversible. Derecho de audiencia abierto.', 'bad']); if (p.cls === 'amarillo') list.push(['Alerta en validación', p.id, 'Se detectó posible pérdida; aún sin efectos. Puede aportar evidencia.', 'info']); if (p.con === 'Por vencer') list.push(['Constancia por vencer', p.id, 'Renueve su constancia para no interrumpir su certificación.', 'warn']); });
  list.push(['Bienvenido al Programa de Integridad Forestal', PRD, 'Su aviso de privacidad integral está disponible en el pie de cada trámite.', 'info']);
  main.innerHTML = hdr('Notificaciones', 'Avisos oficiales con acuse. El plazo empieza a correr al día hábil siguiente de la notificación.') + list.map(l => `<div class="card" style="margin-bottom:10px;display:flex;gap:12px"><span class="chip ${l[3]}">${l[3] === 'bad' ? 'Urgente' : l[3] === 'warn' ? 'Atención' : 'Aviso'}</span><div><b>${l[0]}</b> <span class="mono dim tiny">${l[1]}</span><div class="tiny dim" style="margin-top:3px">${l[2]}</div></div></div>`).join('');
}
function procedimientos(main) { if (gate(main, () => procedimientos(main))) return; ensureDemo(PRD); procView(main, PRD); }
export const views = { panel, predios, tramites, levantamiento, restauracion, avisos, procedimientos };
