import { $, $$, on, esc, fmt, chip, toast, download } from '../util.js';
import { S, munName } from '../state.js';
import * as ch from '../charts.js';
import { kpi, tag, icon } from '../ui.js';
import { ledgerAppend } from '../integrity.js';
import { H, PARAMS, ESTADOS, MET, me, cortes, dating, pOf, listaVersion } from '../domain/core.js';
import { CLASES, ESTRATOS, demoSample, olofsson, publicable, parseSample } from '../domain/accuracy.js';
import { hdr, estChip, evChip, who } from './verif.js';
import { registroParametros, bloqueosExternos, bump } from '../domain/mce.js';

// ---------- Cortes y fechado: tres reglas evaluadas por separado (M3) ----------
function cortesView(main) {
  const draw = () => {
    const all = H.map(h => ({ h, c: cortes(h), d: dating(h) })); const conv = all.filter(x => x.d.brk);
    const K = ['cumple', 'indeterminado', 'incumple']; const mat = K.map(e => K.map(f => conv.filter(x => x.c.proforest === e && x.c.exportacion === f).length));
    const expNoPf = all.filter(x => x.c.exportacion === 'cumple' && x.c.proforest === 'incumple');
    const ruta = all.filter(x => x.c.ruta); const incon = all.filter(x => (ESTADOS[x.h.estado].eleg && x.c.exportacion === 'incumple') || (x.h.estado === 'Bloqueado' && x.c.exportacion === 'cumple'));
    const yrs = {}; conv.forEach(x => { yrs[x.d.brk.y] = (yrs[x.d.brk.y] || 0) + 1; });
    const dense = conv.filter(x => x.d.dense.length && x.d.win.fuente.startsWith('Obs')); const annualIndet = conv.filter(x => { const w = { ini: `${x.d.brk.yPrev}-01-01`, fin: `${x.d.brk.y}-05-31` }; return w.ini < PARAMS.corteFederal.fecha && w.fin >= PARAMS.corteFederal.fecha; }).length;
    const motivo = x => x.c.anp ? 'Dentro de ANP: ' + x.c.anp : x.c.fuego ? `Incendio ${x.c.fuego.fecha} seguido de conversión` : x.c.estatal === 'incumple' ? `Deforestó en ${x.d.brk ? x.d.brk.y : '—'} (después del 1-ene-2018, antes de 2019)` : 'Ventana cruza el 1-ene-2018';
    main.innerHTML = hdr('Cortes y fechado de la conversión', 'La pregunta legal no es si hay aguacate, sino cuándo dejó de ser bosque. Se evalúan tres reglas por separado, cada una con su propio efecto; no se concilian en un solo resultado.', who()) +
      `<div class="card"><div class="ch"><h3>Parámetros de la metodología ${MET.id} v${MET.ver}</h3><div class="sp">${chip(MET.estado, 'warn')}</div></div><div class="grid g3" style="margin-top:10px">
      <div style="border:1px solid var(--line);border-top:3px solid #235B4E;border-radius:8px;padding:10px"><b>1 · Regla Pro-Forest</b><div class="tiny dim" style="margin:2px 0 6px">Efecto: elegibilidad en el programa Pro-Forest</div><label class="tiny">Deforestación desde<input type="date" id="ce" value="${PARAMS.corteEstatal.fecha}"></label><label class="tiny">Incendio seguido de conversión desde<input type="date" id="cfu" value="${PARAMS.corteFuego.fecha}"></label><div class="tiny" style="margin-top:4px">Además: fuera de área natural protegida (CONANP)</div></div>
      <div style="border:1px solid var(--line);border-top:3px solid #BC955C;border-radius:8px;padding:10px"><b>2 · Regla de exportación</b><div class="tiny dim" style="margin:2px 0 6px">Efecto: elegibilidad para exportar a EE. UU.</div><label class="tiny">Fecha de corte<input type="date" id="cf" value="${PARAMS.corteFederal.fecha}"></label><div class="tiny" style="margin-top:4px"><b>${esc(PARAMS.corteFederal.base)}</b></div></div>
      <div style="border:1px solid var(--line);border-top:3px solid #9F2241;border-radius:8px;padding:10px"><b>3 · Ruta de restauración</b><div class="tiny dim" style="margin:2px 0 6px">Efecto: obliga a restaurar y compensar</div><div class="two"><label class="tiny">Afectación desde<input type="date" id="ri" value="${PARAMS.rutaRestauracion.ini}"></label><label class="tiny">hasta<input type="date" id="rf" value="${PARAMS.rutaRestauracion.fin}"></label></div></div></div>
      <div class="grid g3" style="margin-top:10px"><label class="tiny">Umbral de ruptura (pp de cobertura)<input type="number" id="ur" value="${PARAMS.umbralRuptura}" min="5" max="60"></label><label class="tiny">Umbral de terreno forestal al corte (% cobertura)<input type="number" id="uf" value="${PARAMS.umbralForestal}" min="10" max="80"></label><div class="tiny dim" style="align-self:end">Cambiar un parámetro crea una nueva versión de la metodología y queda en la bitácora. Los dictámenes ya emitidos conservan los parámetros con que se firmaron.</div></div></div>
      <div class="grid g5" style="margin-top:14px">${kpi({ l: 'Huertas con conversión fechada', v: fmt(conv.length), s: 'de ' + fmt(H.length) + ' inscritas' })}${kpi({ l: 'Elegibles para exportar', v: fmt(all.filter(x => x.c.exportacion === 'cumple').length), s: 'regla 2019', c: '#2E7D32' })}${kpi({ l: 'Elegibles Pro-Forest', v: fmt(all.filter(x => x.c.proforest === 'cumple').length), s: 'regla 2018 + incendio + ANP', c: '#235B4E' })}${kpi({ l: 'Exportables, no Pro-Forest', v: fmt(expNoPf.length), s: 'el caso que la especificación pide explícito', c: '#A8720F' })}${kpi({ l: 'En ruta de restauración', v: fmt(ruta.length), s: 'afectación 2019–2025', c: '#9F2241' })}</div>
      <div class="grid g2" style="margin-top:14px"><div class="card"><div class="ch"><h3>Matriz de reglas (huertas con conversión)</h3>${tag('demo')}</div><table class="tbl" style="margin-top:8px"><thead><tr><th>Regla Pro-Forest ↓ · Regla de exportación →</th>${K.map(k => `<th class="num">${evChip(k)}</th>`).join('')}</tr></thead><tbody>${K.map((e, i) => `<tr><td>${evChip(e)}</td>${mat[i].map((v, j) => `<td class="num" style="${i !== j && v ? 'background:rgba(168,114,15,.12)' : ''}"><b>${v}</b></td>`).join('')}</tr>`).join('')}</tbody></table><div class="tiny dim" style="margin-top:8px">Cada regla produce su propio resultado. La celda «Pro-Forest: no cumple · exportación: cumple» reúne las huertas que deforestaron entre 2018 y 2019, se quemaron antes de convertir o están en ANP: pueden exportar, pero no entran a Pro-Forest.</div></div>
      <div class="card"><div class="ch"><h3>Año de conversión detectado</h3></div>${ch.bars(Object.keys(yrs).sort().map(y => ({ label: y.slice(2), value: yrs[y], color: +y >= +PARAMS.corteFederal.fecha.slice(0, 4) ? '#B3261E' : +y >= +PARAMS.corteEstatal.fecha.slice(0, 4) ? '#A8720F' : '#235B4E' })), { h: 220 })}<div class="tiny dim">Verde: anterior a 2018 · ámbar: 2018 (afecta sólo Pro-Forest) · rojo: 2019 en adelante (afecta exportación).</div></div></div>
      <div class="card" style="margin-top:14px"><div class="ch"><h3>Elegibles para exportar y no para Pro-Forest</h3><div class="sp"><span class="chip warn">${expNoPf.length}</span> <button class="btn sm ghost" id="dx">${icon('download', 12)} CSV</button></div></div><div class="tw" style="max-height:300px"><table class="tbl"><thead><tr><th>Huerta</th><th>Municipio</th><th>Ruptura</th><th>Ventana</th><th>Pro-Forest</th><th>Exportación</th><th>Ruta de restauración</th><th>Motivo</th></tr></thead><tbody>${expNoPf.map(x => `<tr class="cl" data-h="${x.h.uid}"><td class="mono tiny">${x.h.uid}</td><td>${esc(munName[x.h.mun])}</td><td class="mono">${x.d.brk ? x.d.brk.y : '—'}</td><td class="mono tiny">${x.c.win ? x.c.win.ini + ' → ' + x.c.win.fin : '—'}</td><td>${evChip(x.c.proforest)}</td><td>${evChip(x.c.exportacion)}</td><td>${x.c.ruta ? '<span class="chip bad">Aplica</span>' : '<span class="chip">No</span>'}</td><td class="tiny">${esc(motivo(x))}</td></tr>`).join('') || '<tr><td colspan="8" class="dim">Ninguna.</td></tr>'}</tbody></table></div></div>
      <div class="grid g2" style="margin-top:14px"><div class="card"><div class="ch"><h3>Por qué se suma Landsat y se densifica con Sentinel-2</h3></div><ul class="tiny" style="line-height:1.8;margin:6px 0 0 16px"><li>Sentinel-2 empieza en 2015-2017: no alcanza para el criterio de incendio de 2012 ni para reconstruir 2018 con robustez. El archivo Landsat (1984-hoy) cubre ambos.</li><li>Con compuestos anuales, una conversión cerca del corte cae en una ventana de hasta 17 meses: ${fmt(annualIndet)} huertas quedarían «indeterminadas» sólo con la serie anual.</li><li>Las observaciones densas (cada 5-10 días) acotan la ventana a semanas: ${fmt(dense.length)} huertas se resolvieron así.</li><li>Radar Sentinel-1 (RADD) detecta bajo nubes en temporada de lluvias; las alertas entran a la cola de triaje.</li></ul></div>
      <div class="card"><div class="ch"><h3>Estado legal frente a la regla de exportación</h3></div><div class="tw" style="max-height:260px"><table class="tbl"><thead><tr><th>Huerta</th><th>Estado</th><th>Exportación</th><th>Ventana</th></tr></thead><tbody>${incon.slice(0, 60).map(x => `<tr class="cl" data-h="${x.h.uid}"><td class="mono tiny">${x.h.uid}</td><td>${estChip(x.h.estado)}</td><td>${evChip(x.c.exportacion)}</td><td class="mono tiny">${x.c.win ? x.c.win.ini + ' → ' + x.c.win.fin : '—'}</td></tr>`).join('') || '<tr><td colspan="4" class="dim">Sin inconsistencias.</td></tr>'}</tbody></table></div></div></div>
      <div class="grid g2" style="margin-top:14px"><div class="card"><div class="ch"><h3>Registro de parámetros (metodología versionada)</h3></div><div class="tw" style="max-height:340px"><table class="tbl"><thead><tr><th>Parámetro</th><th>Valor vigente</th><th>Dónde se edita</th></tr></thead><tbody>${registroParametros().map(r => `<tr><td>${esc(r[0])}</td><td class="tiny">${esc(r[1])}</td><td><a data-go="${r[3]}">${esc(r[3])}</a></td></tr>`).join('')}</tbody></table></div></div>
      <div class="card"><div class="ch"><h3>Bloqueos externos (parámetros vacíos y etiquetados)</h3></div><div class="tw"><table class="tbl"><thead><tr><th>Dato</th><th>Módulo</th><th>Estado</th><th>Depende de</th></tr></thead><tbody>${bloqueosExternos().map(r => `<tr><td>${esc(r[0])}</td><td class="mono tiny">${r[1]}</td><td><span class="chip ${/Vacío|Sin conexión|Pendiente/.test(r[2]) ? 'warn' : 'info'}">${esc(r[2])}</span></td><td class="tiny">${esc(r[3])}</td></tr>`).join('')}</tbody></table></div><div class="tiny dim" style="margin-top:6px">No se rellenan con supuestos: el sistema los muestra vacíos hasta que exista la fuente oficial.</div></div></div>`;
    $('#dx', main).onclick = () => download('exportables_no_proforest.csv', 'uid,municipio,ruptura,ventana_ini,ventana_fin,proforest,exportacion,ruta_restauracion,motivo\n' + expNoPf.map(x => [x.h.uid, munName[x.h.mun], x.d.brk ? x.d.brk.y : '', x.c.win ? x.c.win.ini : '', x.c.win ? x.c.win.fin : '', x.c.proforest, x.c.exportacion, x.c.ruta ? 'aplica' : 'no', JSON.stringify(motivo(x))].join(',')).join('\n'), 'text/csv');
  };
  draw();
  main.addEventListener('change', e => { const t = e.target; const u = me(); if (!['ce', 'cf', 'cfu', 'ri', 'rf', 'ur', 'uf'].includes(t.id)) return; if (u.rol !== 'dictamen') { toast('Sólo la Dirección de Dictaminación puede cambiar parámetros', 'warn'); draw(); return; }
    if (t.id === 'ce') PARAMS.corteEstatal.fecha = t.value; if (t.id === 'cf') PARAMS.corteFederal.fecha = t.value; if (t.id === 'cfu') PARAMS.corteFuego.fecha = t.value; if (t.id === 'ri') PARAMS.rutaRestauracion.ini = t.value; if (t.id === 'rf') PARAMS.rutaRestauracion.fin = t.value; if (t.id === 'ur') PARAMS.umbralRuptura = +t.value; if (t.id === 'uf') PARAMS.umbralForestal = +t.value;
    const [a, b, c] = MET.ver.split('.').map(Number); MET.ver = `${a}.${b}.${c + 1}`; ledgerAppend(S.ledger, u.id, 'PARAMETRO_METODOLOGIA', MET.id + ' v' + MET.ver, JSON.stringify({ [t.id]: t.value })); bump(); listaVersion(true); toast('Nueva versión de metodología ' + MET.ver); draw(); });
  on(main, 'click', '[data-h]', (e, r) => window.__go('admin', 'huertas', { id: r.dataset.h }));
  on(main, 'click', '[data-go]', (e, a) => window.__go('admin', a.dataset.go));
}

// ---------- Exactitud medida ----------
S.accSample = S.accSample || demoSample(); S.accSrc = S.accSrc || 'demo';
export function accuracyTables(R, { compact = false } = {}) {
  const pc = (x, d = 1) => x == null ? '—' : fmt(x * 100, d) + ' %';
  return `<div class="tw"><table class="tbl"><thead><tr><th>Clase</th><th class="num">Exactitud del usuario</th><th class="num">Comisión</th><th class="num">Exactitud del productor</th><th class="num">Omisión</th><th class="num">Área mapeada (ha)</th><th class="num">Área estimada (ha) ± IC 95 %</th></tr></thead><tbody>${CLASES.map((k, i) => `<tr><td><b>${k}</b></td><td class="num">${pc(R.ua[i])} <span class="dim tiny">± ${pc(1.96 * R.uaSe[i])}</span></td><td class="num">${pc(R.comision[i])}</td><td class="num">${pc(R.pa[i])} <span class="dim tiny">± ${pc(1.96 * R.paSe[i])}</span></td><td class="num">${pc(R.omision[i])}</td><td class="num">${fmt(R.areaMap[i])}</td><td class="num"><b>${fmt(R.area[i])}</b> <span class="dim tiny">± ${fmt(R.areaCI[i])}</span></td></tr>`).join('')}</tbody></table></div>
  <div class="tiny" style="margin-top:6px">Exactitud global: <b>${pc(R.oa)}</b> ± ${pc(1.96 * R.oaSe)} · n = ${fmt(R.n)} puntos · estimadores de Olofsson et al. (2014), con estrato de amortiguamiento para capturar omisión.</div>
  ${compact ? '' : `<h3 style="margin-top:14px">Matriz de error en proporción de área</h3><div class="tw"><table class="tbl"><thead><tr><th>Mapa ↓ · Referencia →</th>${CLASES.map(k => `<th class="num">${k}</th>`).join('')}<th class="num">Total</th></tr></thead><tbody>${CLASES.map((k, i) => `<tr><td>${k}</td>${R.M[i].map((v, j) => `<td class="num" style="${i === j ? 'color:#2E7D32' : ''}">${v.toFixed(4)}</td>`).join('')}<td class="num">${R.pi[i].toFixed(4)}</td></tr>`).join('')}<tr><td>Total</td>${R.pj.map(v => `<td class="num">${v.toFixed(4)}</td>`).join('')}<td class="num">1.0000</td></tr></tbody></table></div>`}`;
}
function exactitud(main) {
  const draw = () => { const R = olofsson(S.accSample); const pb = publicable(R, PARAMS.umbralPublicacion);
    main.innerHTML = hdr('Exactitud medida', 'Muestra estratificada de puntos verificados en campo o con imagen de muy alta resolución; errores de omisión y comisión publicados; superficies con intervalo de confianza.', `${who()} <button class="btn" id="tp">${icon('download', 14)} Plantilla de muestra</button> <label class="btn pri" style="cursor:pointer">${icon('upload', 14)} Cargar muestra verificada<input type="file" id="up" accept=".csv" hidden></label>`) +
      `${S.accSrc === 'demo' ? `<div class="note tiny" style="margin-bottom:12px"><b>Muestra de demostración.</b> Los cálculos son reales; los puntos son sintéticos. Cargue la muestra verificada por las brigadas para producir las cifras oficiales.</div>` : `<div class="note info tiny" style="margin-bottom:12px">Muestra cargada: ${esc(S.accSrc)} · ${fmt(S.accSample.length)} puntos.</div>`}
      <div class="grid g4">${kpi({ l: 'Exactitud del usuario · pérdida', v: fmt(R.ua[0] * 100, 1) + ' %', s: 'comisión ' + fmt(R.comision[0] * 100, 1) + ' %', c: pb.ua ? '#2E7D32' : '#B3261E' })}${kpi({ l: 'Exactitud del productor · pérdida', v: fmt(R.pa[0] * 100, 1) + ' %', s: 'omisión ' + fmt(R.omision[0] * 100, 1) + ' %', c: pb.pa ? '#2E7D32' : '#B3261E' })}${kpi({ l: 'Pérdida estimada', v: fmt(R.area[0]) + ' ha', s: '± ' + fmt(R.areaCI[0]) + ' ha (IC 95 %)' })}${kpi({ l: 'Criterio de publicación', v: pb.ok ? 'Cumple' : 'No cumple', s: `UA ≥ ${PARAMS.umbralPublicacion.ua * 100} % · PA ≥ ${PARAMS.umbralPublicacion.pa * 100} % · IC ≤ ±${PARAMS.umbralPublicacion.semiIC * 100} %`, c: pb.ok ? '#2E7D32' : '#A8720F' })}</div>
      <div class="card" style="margin-top:14px"><div class="ch"><h3>Resultados por clase</h3><div class="sp"><button class="btn sm ghost" id="rx">${icon('download', 12)} Resultados (JSON)</button></div></div>${accuracyTables(R)}</div>
      <div class="grid g2" style="margin-top:14px"><div class="card"><div class="ch"><h3>Diseño muestral</h3></div><table class="tbl" style="margin-top:6px"><thead><tr><th>Estrato del mapa</th><th class="num">Área (ha)</th><th class="num">Peso W</th><th class="num">n</th></tr></thead><tbody>${R.rows.map(r => `<tr><td>${esc(r.k)}</td><td class="num">${fmt(r.area)}</td><td class="num">${r.W.toFixed(4)}</td><td class="num">${r.n}</td></tr>`).join('')}</tbody></table><div class="tiny dim" style="margin-top:6px">Asignación con n mínimo por estrato raro (pérdida) y estrato de amortiguamiento alrededor de la pérdida: ahí se concentra la omisión.</div></div>
      <div class="card"><div class="ch"><h3>Protocolo de verificación</h3></div><ul class="tiny" style="line-height:1.8;margin:6px 0 0 16px"><li>Puntos aleatorios estratificados, generados antes de ver el resultado del mapa.</li><li>Interpretación doble ciego con imagen de muy alta resolución y serie temporal; desacuerdos a campo.</li><li>Visita de campo con fotografías fechadas y georreferenciadas selladas con SHA-256.</li><li>Recalcular y publicar cada año o con cada nueva versión de la metodología.</li><li>Huertas menores de 1 ha: se exige confirmación con imagen de muy alta resolución antes de dictaminar.</li></ul></div></div>`;
    $('#tp', main).onclick = () => download('muestra_verificacion.csv', 'punto_id,estrato_mapa,clase_referencia,lon,lat,fecha_verificacion,metodo,brigada\n' + S.accSample.slice(0, 12).map(p => `${p.id},${p.estrato},${p.ref},,,,${p.metodo},${p.brigada || ''}`).join('\n') + '\n', 'text/csv');
    $('#rx', main).onclick = () => download('exactitud_resultados.json', JSON.stringify({ metodo: 'Olofsson et al. 2014', muestra: S.accSrc, n: R.n, clases: CLASES, exactitud_usuario: R.ua, ee_usuario: R.uaSe, exactitud_productor: R.pa, ee_productor: R.paSe, exactitud_global: R.oa, area_estimada_ha: R.area, ic95_ha: R.areaCI, area_mapeada_ha: R.areaMap }, null, 1), 'application/json');
    $('#up', main).onchange = async e => { const f = e.target.files[0]; if (!f) return; try { const { out, bad } = parseSample(await f.text()); if (out.length < 30) throw new Error('Muestra insuficiente (' + out.length + ' puntos válidos)'); S.accSample = out; S.accSrc = f.name; ledgerAppend(S.ledger, me().id, 'MUESTRA_EXACTITUD', f.name); toast(`${out.length} puntos cargados${bad.length ? ' · ' + bad.length + ' filas rechazadas' : ''}`); draw(); } catch (err) { toast(err.message, 'warn'); } };
  };
  draw();
}
export const views = { cortes: cortesView, exactitud };
