import { $, $$, on, esc, fmt, chip, toast, download } from '../util.js';
import { S, munName } from '../state.js';
import * as ch from '../charts.js';
import { kpi, tag, icon } from '../ui.js';
import { ledgerAppend } from '../integrity.js';
import { H, PARAMS, ESTADOS, MET, me, cortes, dating, pOf, listaVersion } from '../domain/core.js';
import { CLASES, ESTRATOS, demoSample, olofsson, publicable, parseSample } from '../domain/accuracy.js';
import { hdr, estChip, evChip, who } from './verif.js';

// ---------- Cortes y fechado ----------
function cortesView(main) {
  const draw = () => {
    const conv = H.map(h => ({ h, c: cortes(h), d: dating(h) })).filter(x => x.d.brk);
    const K = ['cumple', 'indeterminado', 'incumple']; const mat = K.map(e => K.map(f => conv.filter(x => x.c.estatal === e && x.c.federal === f).length));
    const disc = conv.filter(x => x.c.disc); const incon = H.map(h => ({ h, c: cortes(h) })).filter(x => (ESTADOS[x.h.estado].eleg && x.c.aplica === 'incumple') || (x.h.estado === 'Bloqueado' && x.c.aplica === 'cumple'));
    const yrs = {}; conv.forEach(x => { yrs[x.d.brk.y] = (yrs[x.d.brk.y] || 0) + 1; });
    const dense = conv.filter(x => x.d.dense.length && x.d.win.fuente.startsWith('Obs')); const annualIndet = conv.filter(x => { const w = { ini: `${x.d.brk.yPrev}-01-01`, fin: `${x.d.brk.y}-05-31` }; return w.ini < PARAMS.corteEstatal.fecha && w.fin >= PARAMS.corteEstatal.fecha; }).length;
    main.innerHTML = hdr('Cortes y fechado de la conversión', 'La pregunta legal no es si hay aguacate, sino cuándo dejó de ser bosque. Se evalúan a la vez el corte estatal y el federal, y el criterio de incendio de 2012.', who()) +
      `<div class="card"><div class="ch"><h3>Parámetros de la metodología ${MET.id} v${MET.ver}</h3><div class="sp">${chip(MET.estado, 'warn')}</div></div><div class="grid g4" style="margin-top:8px">
      <label class="tiny">Corte estatal · ${esc(PARAMS.corteEstatal.base)}<input type="date" id="ce" value="${PARAMS.corteEstatal.fecha}"></label>
      <label class="tiny">Corte federal · ${esc(PARAMS.corteFederal.base)}<input type="date" id="cf" value="${PARAMS.corteFederal.fecha}"></label>
      <label class="tiny">Regla de conciliación<select id="cc"><option value="estricta" ${PARAMS.conciliacion === 'estricta' ? 'selected' : ''}>Aplicar el corte más restrictivo</option><option value="estatal" ${PARAMS.conciliacion === 'estatal' ? 'selected' : ''}>Aplicar siempre el estatal</option><option value="federal" ${PARAMS.conciliacion === 'federal' ? 'selected' : ''}>Aplicar siempre el federal</option></select></label>
      <label class="tiny">Umbral de ruptura (pp de cobertura)<input type="number" id="ur" value="${PARAMS.umbralRuptura}" min="5" max="60"></label></div>
      <div class="tiny dim" style="margin-top:6px">Cambiar un parámetro crea una nueva versión de la metodología y queda en la bitácora. Los dictámenes ya emitidos conservan los parámetros con que se firmaron.</div></div>
      <div class="grid g4" style="margin-top:14px">${kpi({ l: 'Huertas con conversión fechada', v: fmt(conv.length), s: 'de ' + fmt(H.length) + ' en el registro' })}${kpi({ l: 'Discrepancia estatal vs federal', v: fmt(disc.length), s: 'se resuelven con la regla de conciliación', c: '#A8720F' })}${kpi({ l: 'Ventanas acotadas con observaciones densas', v: fmt(dense.length), s: 'Sentinel-2 + Landsat, 2017 en adelante', c: '#235B4E' })}${kpi({ l: 'Estado legal vs evaluación', v: fmt(incon.length), s: 'inconsistencias que requieren revisión', c: incon.length ? '#B3261E' : '#2E7D32' })}</div>
      <div class="grid g2" style="margin-top:14px"><div class="card"><div class="ch"><h3>Matriz de cortes (huertas con conversión)</h3>${tag('demo')}</div><table class="tbl" style="margin-top:8px"><thead><tr><th>Estatal ↓ · Federal →</th>${K.map(k => `<th class="num">${evChip(k)}</th>`).join('')}</tr></thead><tbody>${K.map((e, i) => `<tr><td>${evChip(e)}</td>${mat[i].map((v, j) => `<td class="num" style="${i !== j && v ? 'background:rgba(168,114,15,.12)' : ''}"><b>${v}</b></td>`).join('')}</tr>`).join('')}</tbody></table><div class="tiny dim" style="margin-top:8px">Las celdas fuera de la diagonal son la grieta entre ambos cortes: resultados distintos para la misma huerta. La plataforma los muestra y aplica una regla explícita, en lugar de dejarlos a interpretación.</div></div>
      <div class="card"><div class="ch"><h3>Año de conversión detectado</h3></div>${ch.bars(Object.keys(yrs).sort().map(y => ({ label: y.slice(2), value: yrs[y], color: +y >= +PARAMS.corteFederal.fecha.slice(0, 4) ? '#B3261E' : +y >= +PARAMS.corteEstatal.fecha.slice(0, 4) ? '#A8720F' : '#235B4E' })), { h: 220 })}<div class="tiny dim">Verde: anterior a ambos cortes · ámbar: entre cortes · rojo: posterior a ambos.</div></div></div>
      <div class="grid g2" style="margin-top:14px"><div class="card"><div class="ch"><h3>Por qué se suma Landsat y se densifica con Sentinel-2</h3></div><ul class="tiny" style="line-height:1.8;margin:6px 0 0 16px"><li>Sentinel-2 empieza en 2015-2017: no alcanza para el criterio de incendio de 2012 ni para reconstruir 2018 con robustez. El archivo Landsat (1984-hoy) cubre ambos.</li><li>Con compuestos anuales, una conversión cerca del corte cae en una ventana de hasta 17 meses: ${fmt(annualIndet)} huertas quedarían «indeterminadas» sólo con la serie anual.</li><li>Las observaciones densas (cada 5-10 días) acotan la ventana a semanas: ${fmt(dense.length)} huertas se resolvieron así.</li><li>Radar Sentinel-1 (RADD) detecta bajo nubes en temporada de lluvias; las alertas entran a la cola de triaje.</li></ul></div>
      <div class="card"><div class="ch"><h3>Inconsistencias a revisar</h3></div><div class="tw" style="max-height:260px"><table class="tbl"><thead><tr><th>Huerta</th><th>Estado</th><th>Evaluación</th><th>Ventana</th></tr></thead><tbody>${incon.slice(0, 60).map(x => `<tr class="cl" data-h="${x.h.uid}"><td class="mono tiny">${x.h.uid}</td><td>${estChip(x.h.estado)}</td><td>${evChip(x.c.aplica)}</td><td class="mono tiny">${x.c.win ? x.c.win.ini + ' → ' + x.c.win.fin : '—'}</td></tr>`).join('') || '<tr><td colspan="4" class="dim">Sin inconsistencias.</td></tr>'}</tbody></table></div></div></div>
      <div class="card" style="margin-top:14px"><div class="ch"><h3>Discrepancias entre cortes</h3><div class="sp"><button class="btn sm ghost" id="dx">${icon('download', 12)} CSV</button></div></div><div class="tw" style="max-height:300px"><table class="tbl"><thead><tr><th>Huerta</th><th>Municipio</th><th>Ruptura</th><th>Ventana</th><th>Estatal</th><th>Federal</th><th>Aplica</th><th>Estado legal</th></tr></thead><tbody>${disc.map(x => `<tr class="cl" data-h="${x.h.uid}"><td class="mono tiny">${x.h.uid}</td><td>${esc(munName[x.h.mun])}</td><td class="mono">${x.d.brk.y}</td><td class="mono tiny">${x.c.win.ini} → ${x.c.win.fin}</td><td>${evChip(x.c.estatal)}</td><td>${evChip(x.c.federal)}</td><td>${evChip(x.c.aplica)}</td><td>${estChip(x.h.estado)}</td></tr>`).join('')}</tbody></table></div></div>`;
    $('#dx', main).onclick = () => download('discrepancias_cortes.csv', 'uid,municipio,ruptura,ventana_ini,ventana_fin,estatal,federal,aplicable,estado_legal\n' + disc.map(x => [x.h.uid, munName[x.h.mun], x.d.brk.y, x.c.win.ini, x.c.win.fin, x.c.estatal, x.c.federal, x.c.aplica, x.h.estado].join(',')).join('\n'), 'text/csv');
  };
  draw();
  main.addEventListener('change', e => { const t = e.target; const u = me(); if (!['ce', 'cf', 'cc', 'ur'].includes(t.id)) return; if (u.rol !== 'dictamen') { toast('Sólo la Dirección de Dictaminación puede cambiar parámetros', 'warn'); draw(); return; }
    if (t.id === 'ce') PARAMS.corteEstatal.fecha = t.value; if (t.id === 'cf') PARAMS.corteFederal.fecha = t.value; if (t.id === 'cc') PARAMS.conciliacion = t.value; if (t.id === 'ur') PARAMS.umbralRuptura = +t.value;
    const [a, b, c] = MET.ver.split('.').map(Number); MET.ver = `${a}.${b}.${c + 1}`; ledgerAppend(S.ledger, u.id, 'PARAMETRO_METODOLOGIA', MET.id + ' v' + MET.ver, JSON.stringify({ [t.id]: t.value })); listaVersion(true); toast('Nueva versión de metodología ' + MET.ver); draw(); });
  on(main, 'click', '[data-h]', (e, r) => window.__go('admin', 'huertas', { id: r.dataset.h }));
}

// ---------- Exactitud medida ----------
S.accSample = S.accSample || demoSample(); S.accSrc = S.accSrc || 'demo';
export function accuracyTables(R, { compact = false } = {}) {
  const pc = (x, d = 1) => x == null ? '—' : fmt(x * 100, d) + ' %';
  return `<div class="tw"><table class="tbl"><thead><tr><th>Clase</th><th class="num">Exactitud del usuario</th><th class="num">Comisión</th><th class="num">Exactitud del productor</th><th class="num">Omisión</th><th class="num">Área mapeada (ha)</th><th class="num">Área estimada (ha) ± IC 95 %</th></tr></thead><tbody>${CLASES.map((k, i) => `<tr><td><b>${k}</b></td><td class="num">${pc(R.ua[i])} <span class="dim tiny">± ${pc(1.96 * R.uaSe[i])}</span></td><td class="num">${pc(R.comision[i])}</td><td class="num">${pc(R.pa[i])} <span class="dim tiny">± ${pc(1.96 * R.paSe[i])}</span></td><td class="num">${pc(R.omision[i])}</td><td class="num">${fmt(R.areaMap[i])}</td><td class="num"><b>${fmt(R.area[i])}</b> <span class="dim tiny">± ${fmt(R.areaCI[i])}</span></td></tr>`).join('')}</tbody></table></div>
  <div class="tiny" style="margin-top:6px">Exactitud global: <b>${pc(R.oa)}</b> ± ${pc(1.96 * R.oaSe)} · n = ${fmt(R.n)} puntos · estimadores de Olofsson et al. (2014), con estrato de amortiguamiento para capturar omisión.</div>
  ${compact ? '' : `<h3 style="margin-top:14px">Matriz de error en proporción de área</h3><div class="tw"><table class="tbl"><thead><tr><th>Mapa ↓ · Referencia →</th>${CLASES.map(k => `<th class="num">${k}</th>`).join('')}<th class="num">Total</th></tr></thead><tbody>${CLASES.map((k, i) => `<tr><td>${k}</td>${R.M[i].map((v, j) => `<td class="num" style="${i === j ? 'color:#2E7D32' : ''}">${v.toFixed(4)}</td>`).join('')}<td class="num">${R.pi[i].toFixed(4)}</td></tr>`).join('')}<tr><td>Total</td>${R.pj.map(v => `<td class="num">${v.toFixed(4)}</td>`).join('')}<td class="num">1.0000</td></tr></tbody></table></div>`}`;
}
function exactitud(main) {
  const draw = () => { const R = olofsson(S.accSample); const pb = publicable(R, PARAMS.umbralPublicacion);
    main.innerHTML = hdr('Exactitud medida', 'Muestra estratificada de puntos verificados en campo o con imagen de muy alta resolución; errores de omisión y comisión publicados; superficies con intervalo de confianza.', `${who()} <button class="btn" id="tp">${icon('download', 14)} Plantilla de muestra</button> <label class="btn pri" style="cursor:pointer">${icon('upload', 14)} Cargar muestra verificada<input type="file" id="up" accept=".csv" hidden></label>`) +
      `${S.accSrc === 'demo' ? `<div class="note tiny" style="margin-bottom:12px"><b>Muestra de demostración.</b> Los cálculos son reales; los puntos son sintéticos. Cargue la muestra verificada por las brigadas para producir las cifras oficiales.</div>` : `<div class="note info tiny" style="margin-bottom:12px">Muestra cargada: ${esc(S.accSrc)} · ${fmt(S.accSample.length)} puntos.</div>`}
      <div class="grid g4">${kpi({ l: 'Exactitud del usuario · pérdida', v: fmt(R.ua[0] * 100, 1) + ' %', s: 'comisión ' + fmt(R.comision[0] * 100, 1) + ' %', c: pb.ua ? '#2E7D32' : '#B3261E' })}${kpi({ l: 'Exactitud del productor · pérdida', v: fmt(R.pa[0] * 100, 1) + ' %', s: 'omisión ' + fmt(R.omision[0] * 100, 1) + ' %', c: pb.pa ? '#2E7D32' : '#B3261E' })}${kpi({ l: 'Pérdida estimada', v: fmt(R.area[0]) + ' ha', s: '± ' + fmt(R.areaCI[0]) + ' ha (IC 95 %)' })}${kpi({ l: 'Criterio de publicación', v: pb.ok ? 'Cumple' : 'No cumple', s: `UA ≥ ${PARAMS.umbralPublicacion.ua * 100} % · PA ≥ ${PARAMS.umbralPublicacion.pa * 100} % · IC ≤ ±${PARAMS.umbralPublicacion.semiIC * 100} %`, c: pb.ok ? '#2E7D32' : '#A8720F' })}</div>
      <div class="card" style="margin-top:14px"><div class="ch"><h3>Resultados por clase</h3><div class="sp"><button class="btn sm ghost" id="rx">${icon('download', 12)} Resultados (JSON)</button></div></div>${accuracyTables(R)}</div>
      <div class="grid g2" style="margin-top:14px"><div class="card"><div class="ch"><h3>Diseño muestral</h3></div><table class="tbl" style="margin-top:6px"><thead><tr><th>Estrato del mapa</th><th class="num">Área (ha)</th><th class="num">Peso W</th><th class="num">n</th></tr></thead><tbody>${R.rows.map(r => `<tr><td>${esc(r.k)}</td><td class="num">${fmt(r.area)}</td><td class="num">${r.W.toFixed(4)}</td><td class="num">${r.n}</td></tr>`).join('')}</tbody></table><div class="tiny dim" style="margin-top:6px">Asignación con n mínimo por estrato raro (pérdida) y estrato de amortiguamiento alrededor de la pérdida: ahí se concentra la omisión.</div></div>
      <div class="card"><div class="ch"><h3>Protocolo de verificación</h3></div><ul class="tiny" style="line-height:1.8;margin:6px 0 0 16px"><li>Puntos aleatorios estratificados, generados antes de ver el resultado del mapa.</li><li>Interpretación doble ciego con imagen de muy alta resolución y serie temporal; desacuerdos a campo.</li><li>Visita de campo con fotografías fechadas y georreferenciadas selladas con SHA-256.</li><li>Recalcular y publicar cada año o con cada nueva versión de la metodología.</li><li>Huertas menores de 1 ha: se exige confirmación con imagen de muy alta resolución antes de dictaminar.</li></ul></div></div>`;
    $('#tp', main).onclick = () => download('muestra_verificacion.csv', 'punto_id,estrato_mapa,clase_referencia,lon,lat,fecha_verificacion,metodo,brigada\n' + S.accSample.slice(0, 12).map(p => `${p.id},${p.estrato},${p.ref},,,,${p.metodo},${p.brigada || ''}`).join('\n') + '\n', 'text/csv');
    $('#rx', main).onclick = () => download('exactitud_resultados.json', JSON.stringify({ metodo: 'Olofsson et al. 2014', muestra: S.accSrc, n: R.n, clases: CLASES, exactitud_usuario: R.ua, ee_usuario: R.uaSe, exactitud_productor: R.pa, ee_productor: R.paSe, exactitud_global: R.oa, area_estimada_ha: R.area, ic95_ha: R.areaCI, area_mapeada_ha: R.areaMap }, null, 1), 'application/json');
    $('#up', main).onchange = async e => { const f = e.target.files[0]; if (!f) return; try { const { out, bad } = parseSample(await f.text()); if (out.length < 30) throw new Error('Muestra insuficiente (' + out.length + ' puntos válidos)'); S.accSample = out; S.accSrc = f.name; ledgerAppend(S.ledger, me().id, 'MUESTRA_EXACTITUD', f.name); toast(`${out.length} puntos cargados${bad.length ? ' · ' + bad.length + ' filas rechazadas' : ''}`); draw(); } catch (err) { toast(err.message, 'warn'); } };
  };
  draw();
}
export const views = { cortes: cortesView, exactitud };
