import { $, $$, on, esc, fmt, fdate, ftime, chip, toast, download } from '../util.js';
import { S, munName, alertaById, prediosById } from '../state.js';
import * as ch from '../charts.js';
import { kpi, tag, icon, modal, beforeAfter } from '../ui.js';
import { ledgerAppend, shortHash, sha256File } from '../integrity.js';
import { H, hById, ESTADOS, TRANS, ROLES, PARAMS, CULTIVOS, me, userById, maskRfc, dating, cortes, fires, sequia, spiSeries, transit, canTransit, pOf, businessDaysBetween, todayIso, elegibilidad } from '../domain/core.js';
import { STAGES, triage, allowed, act, stageIdx, casesOf, caseById } from '../domain/process.js';
import { gfEvidenceHTML } from './gfint.js';
import { emitir, docHTML, expedienteZip, verificarDictamen, evTxt, MODOS, entregarSemarnat } from '../domain/dictamen.js';
import { expediente, semChip, cambiarSemaforo, procDe, soloLectura, universoChip, NOTA_SEMAFOROS } from '../domain/mce.js';

export const hdr = (t, p, a = '') => `<div class="page-h"><div><h1>${t}</h1>${p ? `<p>${p}</p>` : ''}</div><div class="act">${a}</div></div>`;
export const estChip = e => `<span class="chip" style="border-color:${ESTADOS[e].c}66;color:${ESTADOS[e].c}">${esc(e)}</span>`;
export const evChip = k => chip(evTxt(k, 'es'), { cumple: 'ok', incumple: 'bad', indeterminado: 'warn' }[k]);
export const who = () => { const u = me(); return `<span class="chip info">${icon('key', 12)} ${u.id} · ${ROLES[u.rol].n}</span>`; };
const denied = (r) => { if (!r.ok) { toast(r.why, 'warn'); return true; } return false; };
export function dlExp(dic, publico = false) { download(`expediente_${dic.folio}${publico ? '_publico' : ''}.zip`, expedienteZip(dic, { publico }), 'application/zip'); }

// ---------- Serie con cortes ----------
export function seriesChart(h, w = 560, hh = 200) {
  const d = dating(h); const v = [{ x: 2012, label: 'Incendio 2012', color: '#A8720F' }, { x: 2018, label: 'Pro-Forest 2018', color: '#A8720F' }, { x: 2019, label: 'Exportación 2019', color: '#9F2241' }]; if (d.brk) v.push({ x: d.brk.y, label: 'Ruptura ' + d.brk.y, color: '#B3261E' });
  fires(h).forEach(f => v.push({ x: +f.fecha.slice(0, 4) + (+f.fecha.slice(5, 7)) / 12, label: '🔥', color: '#A8720F' }));
  return ch.line([{ name: 'Cobertura arbórea (%)', color: '#235B4E', pts: d.pts, area: true }], { w, h: hh, ymax: 100, ymin: 0, xticks: [1995, 2000, 2005, 2010, 2015, 2020, 2026], vlines: v, xmin: 1993, xmax: 2026.5 });
}

// ---------- Ficha de huerta ----------
export function fichaHuerta(host, uid, redraw) {
  const h = hById[uid]; if (!h) return; const p = pOf(h), c = cortes(h), d = dating(h), fs = fires(h), cs = casesOf(uid), dics = S.dictamenes.filter(x => x.uid === uid); const u = me();
  const sq = sequia(h, d.brk ? d.brk.y : 2026);
  const dr = document.createElement('div'); dr.className = 'drawer'; dr.style.width = 'min(640px,96vw)';
  dr.innerHTML = `<div class="ch"><h2 class="mono">${h.uid}</h2>${estChip(h.estado)}<div class="sp"><button class="btn sm ghost" data-x>✕</button></div></div>
  <div class="tiny dim" style="margin:2px 0 10px">${esc(munName[h.mun])} · ${esc(h.cul)} · ${fmt(p.ha, 2)} ha · folio anterior <span class="mono">${h.pid}</span> ${tag('demo')}</div>
  ${(() => { const X = expediente(h); return `<div class="card" style="padding:10px;margin-bottom:10px"><div class="ch"><h3>Expediente de tres semáforos</h3><div class="sp">${soloLectura(u) ? '' : '<button class="btn sm ghost" id="semx">Actualizar con evidencia</button>'}</div></div><div class="grid g3" style="gap:8px;margin-top:6px">${[['Fitosanitario', X.semaforo_fito], ['Ambiental (exportación)', X.semaforo_amb], ['Laboral (CLA)', X.semaforo_lab]].map(([n, sm]) => `<div><div class="tiny dim">${n}</div>${semChip(sm)}<div class="tiny" style="color:var(--mut);margin-top:3px">${esc(sm.txt)}</div></div>`).join('')}</div><div class="tiny dim" style="margin-top:6px">Superficie agrupada del titular: ${fmt(X.superficie_titular, 2)} ha · ${X.sujeto_cla ? 'sujeto al CLA' : 'fuera del umbral CLA'} · temporada SENASICA: ${X.temporada_senasica || '—'}</div></div>`; })()}
  <div class="grid g2" style="gap:10px"><dl class="kv"><dt>Clave SENASICA</dt><dd class="mono">${h.senasica || '— (cultivo no exportador)'}</dd><dt>Clave catastral</dt><dd class="mono">${h.catastral}</dd><dt>Núcleo agrario (RAN)</dt><dd class="mono">${h.ran || '— (pequeña propiedad)'}</dd><dt>Titular</dt><dd class="mono">${maskRfc(h.rfc)} · ${h.persona}</dd>${procDe(h.uid) ? `<dt>Procedimiento de autoridad</dt><dd>${esc(procDe(h.uid).autoridad)} · <span class="mono tiny">${esc(procDe(h.uid).externo)}</span> · ${esc(procDe(h.uid).etapa)}</dd>` : ''}</dl>
  <dl class="kv"><dt>Regla Pro-Forest (2018 · incendio 2012 · ANP)</dt><dd>${evChip(c.proforest)}${c.anp ? ' <span class="chip bad">ANP</span>' : ''}</dd><dt>Regla de exportación (${PARAMS.corteFederal.fecha.slice(0, 4)})</dt><dd>${evChip(c.exportacion)}</dd><dt>Ruta de restauración (2019–2025)</dt><dd>${c.ruta ? '<span class="chip bad">Aplica</span>' : '<span class="chip">No aplica</span>'}</dd><dt>Ventana</dt><dd class="mono tiny">${c.win ? c.win.ini + ' → ' + c.win.fin : 'sin conversión'}</dd></dl></div>
  ${c.disc ? `<div class="note tiny" style="margin-top:8px"><b>Exportable y no Pro-Forest${c.proforest === 'incumple' && c.exportacion === 'cumple' ? '' : ' (o viceversa)'}.</b> Cada regla tiene su propio efecto; no se concilian.</div>` : ''}
  ${(ESTADOS[h.estado].eleg && c.exportacion === 'incumple') || (!ESTADOS[h.estado].eleg && h.estado === 'Bloqueado' && c.exportacion === 'cumple') ? `<div class="note bad tiny" style="margin-top:8px"><b>Inconsistencia:</b> el estado legal (${h.estado}) contradice la regla de exportación vigente (${evTxt(c.exportacion)}). Requiere revisión documentada.</div>` : ''}
  <div class="sec" style="border-left:4px solid #235B4E;padding-left:10px"><div class="tiny" style="color:var(--goldt);font-weight:600;letter-spacing:.05em">DICTAMEN · AUTORIDAD ESTATAL</div><h3>Condición forestal (prueba de dos condiciones)</h3><dl class="kv" style="margin-top:6px"><dt>1. ${esc(c.condicion.pregunta1)}</dt><dd>${{ si: '<span class="chip ok">Sí</span>', no: '<span class="chip bad">No</span>', indeterminado: '<span class="chip warn">Indeterminado</span>' }[c.condicion.c1]}${c.condicion.cobertura_corte != null ? ` <span class="tiny dim">cobertura al corte ${c.condicion.cobertura_corte} %</span>` : ''}</dd><dt>2. ${esc(c.condicion.pregunta2)}</dt><dd class="tiny">${esc(c.condicion.custf.estado)}</dd><dt>Resultado</dt><dd><b>${c.condicion.resultado === 'acreditada' ? '<span class="chip ok">Acreditada</span>' : '<span class="chip bad">No acreditada</span>'}</b></dd></dl><div class="tiny dim" style="margin-top:4px">${esc(c.condicion.motivo)}. Capas a integrar: INEGI USV serie VII, Inventario Nacional Forestal (CONAFOR), CUSTF (SEMARNAT), ANP (CONANP).</div></div>
  <div class="sec"><h3>Serie de cobertura arbórea 1993-2026 · Landsat + Sentinel-2</h3>${seriesChart(h, 600, 190)}<div class="tiny dim">${d.brk ? `Ruptura ${d.brk.y}: ${d.brk.antes} % → ${d.brk.despues} % (−${d.brk.mag} pp). Ventana acotada con ${d.dense.length ? d.dense.length + ' observaciones densas' : 'la serie anual'}.` : 'Sin ruptura significativa en la serie.'}</div></div>
  <div class="grid g3" style="gap:10px;margin-top:10px"><div class="card" style="padding:10px"><div class="tiny dim">Lluvia (CHIRPS · SPI ${d.brk ? d.brk.y : 2026})</div><div class="mono" style="font-size:18px">${sq.spi}</div><div class="tiny dim">${esc(sq.txt)}</div></div>
  <div class="card" style="padding:10px"><div class="tiny dim">Altura del dosel (GEDI + mapa global)</div><div class="mono" style="font-size:18px">${h.canopy.base} → ${h.canopy.actual} m</div><div class="tiny dim">${h.canopy.gedi} huellas GEDI en el polígono</div></div>
  <div class="card" style="padding:10px"><div class="tiny dim">Incendios desde 2012 (FIRMS + NBR)</div><div class="mono" style="font-size:18px">${fs.length}</div><div class="tiny dim">${fs.map(f => `${f.fecha} · dNBR ${f.dnbr}`).join('<br>') || 'Sin focos'}</div></div></div>
  <div class="sec" style="border-left:4px solid #BC955C;padding-left:10px"><div class="tiny" style="color:var(--goldt);font-weight:600;letter-spacing:.05em">DETECCIÓN · GUARDIÁN FORESTAL (FUENTE INDEPENDIENTE)</div>${gfEvidenceHTML(prediosById[h.pid].geometry.coordinates[0], c.win)}</div>
  <div class="sec"><h3>Historial de estado legal</h3><div class="timeline" style="margin-top:8px">${h.hist.slice().reverse().map(e => `<div><div class="tiny"><b>${e.de ? esc(e.de) + ' → ' : ''}${esc(e.a)}</b> · <span class="mono dim">${ftime(e.ts)}</span></div><div class="tiny dim">${esc(e.mot)} · ${esc(e.actor)} (${esc(ROLES[e.rol]?.n || e.rol)})${e.evid && e.evid.length ? ' · evidencia: ' + e.evid.map(esc).join(', ') : ''}</div></div>`).join('')}</div></div>
  <div class="sec"><h3>Cambiar estado legal</h3><div class="tiny dim" style="margin:4px 0 8px">Actuando como ${u.id} (${ROLES[u.rol].n}). Cada cambio exige motivo y evidencia y queda en la bitácora encadenada.</div><div style="display:flex;gap:6px;flex-wrap:wrap">${TRANS.filter(t => t[0] === h.estado).map(t => { const k = canTransit(h, t[1], u); return `<button class="btn sm" data-to="${t[1]}" title="${esc(k.ok ? t[3] : k.why)}" ${k.ok ? '' : 'style="opacity:.5"'}>→ ${t[1]}</button>`; }).join('') || '<span class="tiny dim">Sin transiciones disponibles.</span>'}</div></div>
  <div class="sec"><h3>Expedientes y dictámenes</h3>${cs.map(k => `<div class="tiny" style="padding:3px 0"><a data-case="${k.id}" class="mono">${k.id}</a> · ${esc(STAGES[stageIdx(k.stage)].n)} · ${esc(k.estado)}</div>`).join('') || '<div class="tiny dim">Sin expedientes.</div>'}
  ${dics.map(x => `<div class="tiny" style="padding:3px 0"><span class="mono">${x.folio}</span> · ${esc(x.tipo)} · ${fdate(x.ts)} <button class="btn sm ghost" data-dl="${x.folio}">${icon('download', 12)} Expediente</button></div>`).join('')}
  <div style="margin-top:8px;display:flex;gap:6px;flex-wrap:wrap"><button class="btn sm pri" id="emit">Emitir dictamen</button><button class="btn sm ghost" id="leg">Ficha técnica (semáforo)</button></div></div>`;
  host.appendChild(dr);
  on(dr, 'click', '[data-x]', () => dr.remove());
  on(dr, 'click', '[data-case]', (e, a) => window.__go('admin', 'expedientes', { id: a.dataset.case }));
  on(dr, 'click', '[data-dl]', (e, b) => dlExp(S.dictamenes.find(x => x.folio === b.dataset.dl)));
  $('#leg', dr).onclick = () => window.__go('admin', 'padron', { id: h.pid });
  $('#emit', dr).onclick = () => { const m = modal(`<h2>Emitir dictamen · ${h.uid}</h2><label class="f">Tipo<select id="dt"><option>Dictamen de elegibilidad</option><option>Dictamen de conversión</option></select></label><label class="f">Modo<select id="dm">${MODOS.map(x => `<option>${x}</option>`).join('')}</select></label><label class="f">Justificación escrita (obligatoria para un dictamen rojo sin verificación de campo)<textarea id="dj" rows="3"></textarea></label><div class="tiny dim">Condición forestal: <b>${c.condicion.resultado}</b> · regla de exportación: ${evTxt(c.exportacion)}</div><div style="display:flex;gap:8px;justify-content:flex-end;margin-top:12px"><button class="btn ghost" data-close>Cancelar</button><button class="btn pri" id="ok">Firmar y emitir</button></div>`, { w: '520px' });
    m.q('#ok').onclick = () => { const r = emitir(h, me(), m.q('#dt').value, { modo: m.q('#dm').value, justificacion: m.q('#dj').value }); if (denied(r)) return; m.close(); toast('Dictamen ' + r.dic.folio + ' emitido, firmado y sellado (simulado)'); dr.remove(); fichaHuerta(host, uid, redraw); }; };
  const sx = $('#semx', dr); if (sx) sx.onclick = () => { const m = modal(`<h2>Actualizar semáforo · ${h.uid}</h2><p class="tiny dim">Todo cambio exige evidencia_id y usuario; queda en la bitácora. El semáforo ambiental sólo cambia con el procedimiento.</p><label class="f">Semáforo<select id="sk"><option value="fito">Fitosanitario</option><option value="lab">Laboral (CLA)</option><option value="amb">Ambiental</option></select></label><label class="f">Color<select id="sc"><option value="verde">Verde</option><option value="ambar">Ámbar</option><option value="rojo">Rojo</option><option value="gris">Sin dato</option></select></label><label class="f">evidencia_id<input id="se" placeholder="p. ej. SICOA-2026-000123 o folio CLA"></label><label class="f">Motivo<input id="sm"></label><div style="display:flex;gap:8px;justify-content:flex-end;margin-top:12px"><button class="btn ghost" data-close>Cancelar</button><button class="btn pri" id="ok">Registrar</button></div>`, { w: '480px' });
    m.q('#ok').onclick = () => { const r = cambiarSemaforo(h, m.q('#sk').value, m.q('#sc').value, m.q('#se').value, me(), m.q('#sm').value); if (denied(r)) return; m.close(); toast('Semáforo actualizado y asentado en bitácora'); dr.remove(); fichaHuerta(host, uid, redraw); }; };
  on(dr, 'click', '[data-to]', (e, b) => { const to = b.dataset.to; const k = canTransit(h, to, me()); if (denied(k)) return;
    const m = modal(`<h2>${esc(h.estado)} → ${esc(to)}</h2><p class="tiny dim">${esc(k.t[3])}. La evidencia se sella con SHA-256 y se registra en la bitácora.</p><label class="tiny">Motivo<textarea id="mo" rows="3" style="width:100%">${esc(k.t[3])}</textarea></label><label class="tiny">Evidencia (archivos)<input type="file" id="fi" multiple></label><div style="display:flex;gap:8px;justify-content:flex-end;margin-top:12px"><button class="btn ghost" data-close>Cancelar</button><button class="btn pri" id="ok">Registrar cambio</button></div>`, { w: '520px' });
    m.q('#ok').onclick = async () => { const files = [...m.q('#fi').files]; if (!files.length && !m.q('#mo').value.trim()) return toast('Indique motivo o evidencia', 'warn'); const ev = []; for (const f of files) ev.push(f.name + ' · ' + (await sha256File(f)).slice(0, 12)); const r = transit(h, to, me(), m.q('#mo').value.trim(), ev.length ? ev : ['Motivación escrita'], ledgerAppend); if (denied(r)) return; m.close(); toast('Estado cambiado a ' + to); dr.remove(); redraw && redraw(); fichaHuerta(host, uid, redraw); }; });
}

// ---------- Registro de huertas ----------
function huertas(main, params) {
  let q = '', fe = '', fc = '', fm = '', shown = 100;
  const rows = () => H.filter(h => (!fe || h.estado === fe) && (!fc || h.cul === fc) && (!fm || h.mun === fm) && (!q || (h.uid + ' ' + (h.senasica || '') + ' ' + h.catastral + ' ' + (h.ran || '') + ' ' + h.pid).toLowerCase().includes(q)));
  const cnt = e => H.filter(h => h.estado === e).length;
  main.style.position = 'relative';
  main.innerHTML = hdr('Registro de huertas', 'La unidad de análisis es la huerta: un polígono con identificador único ligado a la clave SENASICA, la clave catastral, el núcleo agrario (RAN) y el RFC/CURP del titular. Cada huerta tiene un expediente de tres semáforos: fitosanitario, ambiental y laboral.', `${universoChip('inscritas')} ${who()} <button class="btn" id="imp">${icon('upload', 14)} Importar padrón real</button> <button class="btn ghost" id="ex">${icon('download', 14)} CSV</button>`) +
    `<div class="grid g6" style="grid-template-columns:repeat(6,minmax(0,1fr))">${Object.keys(ESTADOS).map(e => `<div class="card kpi" style="cursor:pointer" data-fe="${e}"><div class="l">${e}</div><div class="v" style="color:${ESTADOS[e].c}">${fmt(cnt(e))}</div><div class="s">${ESTADOS[e].eleg ? 'elegible' : 'no elegible'}</div></div>`).join('')}</div>
    <div class="note info tiny" style="margin:12px 0">Padrón de demostración: ${fmt(H.length)} huertas sintéticas en ${new Set(H.map(h => h.mun)).size} de los 113 municipios. Se sustituye por el padrón de SENASICA/APEAM mediante el importador (valida claves, RFC/CURP, duplicados y geometría).</div>
    <div class="split-h" style="display:flex;gap:8px;flex-wrap:wrap;margin-bottom:8px"><input id="q" placeholder="UID, clave SENASICA, catastral o RAN" style="flex:1;min-width:220px"><select id="fe"><option value="">Todos los estados</option>${Object.keys(ESTADOS).map(e => `<option>${e}</option>`).join('')}</select><select id="fc"><option value="">Todos los cultivos</option>${CULTIVOS.map(c => `<option>${c.k}</option>`).join('')}</select><select id="fm"><option value="">Todos los municipios</option>${[...new Set(H.map(h => h.mun))].sort((a, b) => munName[a].localeCompare(munName[b])).map(m => `<option value="${m}">${esc(munName[m])}</option>`).join('')}</select></div>
    <div class="tw" style="max-height:calc(100vh - 380px)"><table class="tbl" id="tb"></table></div><div id="more" style="margin-top:8px"></div>`;
  const draw = () => { const r = rows(); $('#tb', main).innerHTML = `<thead><tr><th>UID</th><th>SENASICA</th><th>Catastral</th><th>RAN</th><th>Titular</th><th>Municipio</th><th>Cultivo</th><th class="num">Ha</th><th>Estado legal</th><th>Semáforos F · A · L</th><th>Exportación</th></tr></thead><tbody>${r.slice(0, shown).map(h => { const c = cortes(h); const X = expediente(h); const dt = s => `<i class="dot" title="${esc(s.txt)}" style="background:${{ verde: '#2E7D32', ambar: '#A8720F', rojo: '#B3261E', azul: '#235B4E', gris: '#6F7C77', fuera: 'transparent;border:1px solid #6F7C77' }[s.color]}"></i>`; return `<tr class="cl" data-id="${h.uid}"><td class="mono">${h.uid}</td><td class="mono tiny">${h.senasica || '—'}</td><td class="mono tiny">${h.catastral}</td><td class="mono tiny">${h.ran || '—'}</td><td class="mono tiny">${maskRfc(h.rfc)}</td><td>${esc(munName[h.mun])}</td><td>${esc(h.cul)}</td><td class="num">${fmt(pOf(h).ha, 1)}</td><td>${estChip(h.estado)}</td><td>${dt(X.semaforo_fito)} ${dt(X.semaforo_amb)} ${dt(X.semaforo_lab)}</td><td>${evChip(c.exportacion)}${c.disc ? ' <span class="chip warn" title="Exportable y no Pro-Forest (o viceversa)">≠ Pro-Forest</span>' : ''}</td></tr>`; }).join('')}</tbody>`; $('#more', main).innerHTML = r.length > shown ? `<button class="btn sm" id="mo">Mostrar más (${fmt(r.length - shown)})</button>` : `<span class="tiny dim">${fmt(r.length)} huertas</span>`; };
  draw();
  main.addEventListener('input', e => { if (e.target.id === 'q') { q = e.target.value.toLowerCase(); shown = 100; draw(); } });
  main.addEventListener('change', e => { const t = e.target; if (!['fe', 'fc', 'fm'].includes(t.id)) return; if (t.id === 'fe') fe = t.value; if (t.id === 'fc') fc = t.value; if (t.id === 'fm') fm = t.value; shown = 100; draw(); });
  on(main, 'click', '[data-fe]', (e, b) => { fe = fe === b.dataset.fe ? '' : b.dataset.fe; $('#fe', main).value = fe; draw(); });
  on(main, 'click', '#mo', () => { shown += 300; draw(); });
  on(main, 'click', 'tr.cl', (e, r) => { $$('.drawer', main).forEach(x => x.remove()); fichaHuerta(main, r.dataset.id, draw); });
  $('#ex', main).onclick = () => { download('registro_huertas.csv', '﻿uid,clave_senasica,clave_catastral,nucleo_agrario,rfc_enmascarado,municipio,cultivo,superficie_ha,estado_legal,semaforo_fito,semaforo_amb,semaforo_lab,sujeto_cla,regla_proforest,regla_exportacion,ruta_restauracion,condicion_forestal\n' + rows().map(h => { const c = cortes(h); const X = expediente(h); return [h.uid, h.senasica || '', h.catastral, h.ran || '', maskRfc(h.rfc), munName[h.mun], h.cul, pOf(h).ha, h.estado, X.semaforo_fito.color, X.semaforo_amb.color, X.semaforo_lab.color, X.sujeto_cla, c.proforest, c.exportacion, c.ruta, c.condicion.resultado].map(x => JSON.stringify(x)).join(','); }).join('\n'), 'text/csv'); ledgerAppend(S.ledger, me().id, 'EXPORTACION_REGISTRO', 'registro_huertas'); };
  $('#imp', main).onclick = () => importPadron();
  if (params && params.id) fichaHuerta(main, params.id, draw);
}
const RFC_RE = /^[A-ZÑ&]{3,4}\d{6}[A-Z\d]{3}$/, CURP_RE = /^[A-Z][AEIOUX][A-Z]{2}\d{6}[HM][A-Z]{5}[A-Z\d]\d$/;
function importPadron() {
  const tpl = 'clave_senasica,clave_catastral,nucleo_agrario,rfc_curp,municipio,cultivo,superficie_ha,wkt\nSV16-044-00001,16-044-123-00001,,GAMF800101AB1,Uruapan,Aguacate,3.2,"POLYGON((-102.05 19.41,-102.04 19.41,-102.04 19.42,-102.05 19.42,-102.05 19.41))"\n';
  const m = modal(`<div class="ch"><h2>Importar padrón de huertas</h2><div class="sp"><button class="btn sm ghost" data-close>✕</button></div></div><p class="tiny dim" style="margin:6px 0 10px">Fuente esperada: padrón de huertas registradas para exportación (SENASICA/APEAM, por convenio). El importador valida cada fila antes de incorporarla; nada se carga sin reporte de calidad.</p>
  <div style="display:flex;gap:8px;flex-wrap:wrap"><input type="file" id="f" accept=".csv"><button class="btn sm ghost" id="tp">${icon('download', 12)} Plantilla CSV</button></div><div id="out" style="margin-top:12px"></div>`, { w: '720px' });
  m.q('#tp').onclick = () => download('plantilla_padron_huertas.csv', tpl, 'text/csv');
  m.q('#f').onchange = async e => { const f = e.target.files[0]; if (!f) return; const txt = await f.text(); const rows = []; let cur = '', inq = false, row = []; for (const ch of txt.replace(/^﻿/, '')) { if (ch === '"') inq = !inq; else if (ch === ',' && !inq) { row.push(cur); cur = ''; } else if ((ch === '\n' || ch === '\r') && !inq) { if (cur || row.length) { row.push(cur); rows.push(row); row = []; cur = ''; } } else cur += ch; } if (cur || row.length) { row.push(cur); rows.push(row); }
    const hd = rows[0].map(x => x.trim().toLowerCase()); const need = ['clave_senasica', 'clave_catastral', 'rfc_curp', 'municipio', 'cultivo', 'superficie_ha', 'wkt']; const miss = need.filter(k => !hd.includes(k)); if (miss.length) { m.q('#out').innerHTML = `<div class="note bad">Faltan columnas: ${miss.join(', ')}</div>`; return; }
    const ix = k => hd.indexOf(k); const seen = new Set(); const errs = []; let ok = 0; const munOk = new Set(Object.values(munName).map(x => x.toLowerCase()));
    rows.slice(1).forEach((r, i) => { const e = []; const g = k => (r[ix(k)] || '').trim(); const id = g('rfc_curp').toUpperCase(); if (!RFC_RE.test(id) && !CURP_RE.test(id)) e.push('RFC/CURP con formato inválido'); if (!g('clave_senasica')) e.push('sin clave SENASICA'); if (seen.has(g('clave_senasica'))) e.push('clave SENASICA duplicada'); seen.add(g('clave_senasica')); if (!munOk.has(g('municipio').toLowerCase())) e.push('municipio no reconocido (catálogo de 113)'); if (!CULTIVOS.find(c => c.k.toLowerCase() === g('cultivo').toLowerCase())) e.push('cultivo fuera del catálogo'); const ha = +g('superficie_ha'); if (!(ha > 0)) e.push('superficie inválida'); if (!/^POLYGON\s*\(\(/i.test(g('wkt'))) e.push('geometría WKT inválida'); if (e.length) errs.push([i + 2, e.join('; ')]); else ok++; });
    ledgerAppend(S.ledger, me().id, 'PADRON_VALIDADO', f.name, await sha256File(f));
    m.q('#out').innerHTML = `<div class="verdict ${errs.length ? 'warn' : 'ok'}"><div><div class="big">${ok} filas válidas · ${errs.length} con errores</div><div class="tiny dim">Archivo sellado en la bitácora. Las filas válidas se incorporan al registro en el entorno institucional (con convenio vigente).</div></div></div>${errs.length ? `<div class="tw" style="max-height:220px;margin-top:8px"><table class="tbl"><thead><tr><th>Fila</th><th>Problema</th></tr></thead><tbody>${errs.slice(0, 200).map(x => `<tr><td class="num">${x[0]}</td><td>${esc(x[1])}</td></tr>`).join('')}</tbody></table></div>` : ''}`; };
}

// ---------- Cola de triaje ----------
function triaje(main, params) {
  let sel = params && params.id, filt = 'cola';
  const queue = () => S.cases.filter(c => c.stage === 'alerta' && c.estado === 'Abierto').map(c => ({ c, a: alertaById[c.alerta] })).concat(S.alertas.filter(a => !a.pid && ['Detectada', 'En validación'].includes(a.st)).map(a => ({ c: null, a }))).map(x => ({ ...x, t: triage(x.a) })).sort((x, y) => y.t.score - x.t.score || x.a.d.localeCompare(y.a.d));
  const cnt = k => S.cases.filter(c => c.stage === k && c.estado === 'Abierto').length;
  main.className = 'main flush';
  main.innerHTML = `<div class="split"><div style="flex:1;min-width:0;padding:16px 18px;overflow:auto">${hdr('Cola de triaje', 'Alertas continuas de radar (Sentinel-1, RADD) y ópticas (Sentinel-2, Landsat, GLAD, DIST) en todas las pasadas. Flujo: alerta → revisión de analista → visita de campo → dictamen.', who())}
    <div class="steps">${[['alerta', 'Alertas en cola'], ['revision', 'Revisadas · esperan campo'], ['campo', 'Con visita · esperan dictamen'], ['audiencia', 'En audiencia'], ['firme', 'Dictamen firme'], ['recurso', 'Recurso pendiente']].map(([k, n]) => `<div class="${k === 'alerta' ? 'now' : ''}" style="cursor:pointer" data-stage="${k}"><b>${n.toUpperCase()}</b><span class="mono" style="font-size:18px;color:var(--txt)">${k === 'alerta' ? queue().length : cnt(k)}</span></div>`).join('')}</div>
    <div class="tw"><table class="tbl" id="tb"></table></div></div><div class="side" id="pn" style="width:min(400px,34vw);flex:none;border-left:1px solid var(--line);padding:16px;overflow:auto;background:var(--panel2)"></div></div>`;
  const draw = () => { const qq = queue(); $('#tb', main).innerHTML = `<thead><tr><th>Alerta</th><th>Fecha</th><th>Fuente</th><th>Huerta</th><th>Municipio</th><th class="num">Ha</th><th class="num">SPI</th><th>Señales</th><th class="num">Prioridad</th></tr></thead><tbody>${qq.map(({ c, a, t }) => `<tr class="cl ${a.id === sel ? 'act' : ''}" data-id="${a.id}"><td class="mono">${a.id}</td><td class="mono tiny">${a.d}</td><td class="tiny">${esc(a.src)}${t.radar ? ' <span class="chip info">radar</span>' : ''}</td><td class="mono tiny">${t.h ? t.h.uid : '<span class="chip warn">fuera del padrón</span>'}</td><td>${esc(munName[a.mun])}</td><td class="num">${fmt(a.ha, 2)}</td><td class="num ${t.spi <= PARAMS.spiSequia ? 'warn' : ''}">${t.spi}</td><td class="tiny">${[t.sq.probable && '<span class="chip warn">sequía</span>', t.custf && '<span class="chip info">CUSTF</span>', t.anp && '<span class="chip bad">ANP</span>', t.fuego && '<span class="chip bad">fuego</span>'].filter(Boolean).join(' ')}</td><td class="num"><b>${t.score}</b></td></tr>`).join('') || '<tr><td colspan="9" class="dim">Cola vacía.</td></tr>'}</tbody>`; };
  const detail = () => { const pn = $('#pn', main); const a = alertaById[sel]; if (!a) { pn.innerHTML = `<div class="dim" style="text-align:center;padding:40px 10px">${icon('alert', 34)}<div style="margin-top:8px">Seleccione una alerta de la cola.</div></div>`; return; } const t = triage(a); const c = S.cases.find(k => k.alerta === a.id);
    pn.innerHTML = `<div class="ch"><h2 class="mono">${a.id}</h2><div class="sp">${chip(a.st)}</div></div><dl class="kv" style="margin:8px 0"><dt>Detección</dt><dd>${fdate(a.d)} · ${esc(a.src)} · confianza ${esc(a.conf)}</dd><dt>Superficie</dt><dd class="mono">${fmt(a.ha, 2)} ha</dd><dt>Huerta</dt><dd>${t.h ? `<a data-h="${t.h.uid}" class="mono">${t.h.uid}</a> ${estChip(t.h.estado)}` : 'Fuera del padrón'}</dd><dt>Lluvia (SPI)</dt><dd>${t.spi} ${t.sq.txt ? '· ' + esc(t.sq.txt) : ''}</dd>${t.h ? `<dt>Dosel</dt><dd class="mono">${t.h.canopy.base} → ${t.h.canopy.actual} m</dd>` : ''}</dl>
    <div class="note info tiny"><b>Sugerencia del sistema:</b> ${esc(t.sug)}</div><h3 style="margin-top:12px">Evidencia antes / después ${tag('demo')}</h3><div id="ba" style="margin-top:6px"></div>
    ${c ? `<div style="display:grid;grid-template-columns:1fr 1fr;gap:8px;margin-top:10px"><button class="btn ok" data-a="validar">✓ Validar y enviar a campo</button><button class="btn danger" data-a="descartar">✕ Descartar con motivo</button></div><div class="tiny dim" style="margin-top:6px">${(() => { const r = allowed(c, 'validar', me()); return r.ok ? 'Usted puede resolver esta alerta.' : '⚠ ' + esc(r.why); })()}</div>` : `<div class="note tiny" style="margin-top:10px">Alerta fuera del padrón: se abre investigación de oficio y se da vista a PROFEPA (competencia federal en terrenos forestales sin huerta registrada).</div><button class="btn" data-a="oficio" style="margin-top:8px">Turnar a PROFEPA/FGE</button>`}`;
    if (t.h) beforeAfter($('#ba', pn), { ...pOf(t.h), aff: a.ha, ly: +a.d.slice(0, 4) }); else $('#ba', pn).innerHTML = '<div class="tiny dim">Sin polígono de huerta.</div>';
  };
  draw(); detail();
  on(main, 'click', 'tr.cl', (e, r) => { sel = r.dataset.id; draw(); detail(); });
  on(main, 'click', '[data-h]', (e, a) => window.__go('admin', 'huertas', { id: a.dataset.h }));
  on(main, 'click', '[data-stage]', (e, d) => { if (d.dataset.stage !== 'alerta') window.__go('admin', d.dataset.stage === 'recurso' ? 'segunda' : 'expedientes', { stage: d.dataset.stage }); });
  on(main, 'click', '[data-a]', (e, b) => { const a = alertaById[sel]; const c = S.cases.find(k => k.alerta === a.id); const k = b.dataset.a;
    if (k === 'oficio') { a.st = 'En validación'; ledgerAppend(S.ledger, me().id, 'VISTA_PROFEPA', a.id); toast('Turnada a PROFEPA/FGE con expediente de oficio'); draw(); detail(); return; }
    if (k === 'validar') { const r = act(c, 'validar', me()); if (denied(r)) return; toast('Alerta validada; expediente ' + c.id + ' pasa a visita de campo'); sel = null; draw(); detail(); window.__refreshBadges && window.__refreshBadges(); return; }
    const m = modal(`<h2>Descartar alerta ${a.id}</h2><label class="tiny">Motivo<select id="mo" style="width:100%"><option>Estrés hídrico (SPI bajo, dosel estable)</option><option>Autorización de cambio de uso vigente (SEMARNAT)</option><option>Cosecha / poda / manejo forestal autorizado</option><option>Nube, sombra o artefacto del sensor</option><option>Otro (motivar)</option></select></label><label class="tiny">Motivación<textarea id="tx" rows="3" style="width:100%"></textarea></label><div style="display:flex;gap:8px;justify-content:flex-end;margin-top:10px"><button class="btn ghost" data-close>Cancelar</button><button class="btn danger" id="ok">Descartar</button></div>`, { w: '480px' });
    m.q('#ok').onclick = () => { const r = act(c, 'descartar', me(), { motivo: m.q('#mo').value + (m.q('#tx').value ? ' — ' + m.q('#tx').value : '') }); if (denied(r)) return; m.close(); toast('Alerta descartada con motivo registrado'); sel = null; draw(); detail(); }; });
}

// ---------- Expedientes (debido proceso) ----------
function expedientes(main, params) {
  let sel = params && params.id, fs = params && params.stage || 'abiertos';
  const list = () => S.cases.filter(c => fs === 'abiertos' ? c.estado === 'Abierto' && c.stage !== 'alerta' : fs === 'todos' ? true : c.stage === fs).sort((a, b) => stageIdx(b.stage) - stageIdx(a.stage) || a.id.localeCompare(b.id));
  main.className = 'main flush';
  main.innerHTML = `<div class="split"><div style="flex:1;min-width:0;padding:16px 18px;overflow:auto">${hdr('Expedientes', 'Debido proceso completo: notificación electrónica, plazo de audiencia en días hábiles, alegatos y pruebas del productor, dictamen motivado y recurso ante un área distinta.', who())}
    <div class="pill-tabs" id="ft" style="margin-bottom:10px">${[['abiertos', 'Abiertos'], ['revision', 'Esperan campo'], ['campo', 'Esperan dictamen'], ['audiencia', 'En audiencia'], ['firme', 'Firmes'], ['recurso', 'Con recurso'], ['todos', 'Todos']].map(([k, n]) => `<button data-f="${k}" class="${k === fs ? 'on' : ''}">${n}</button>`).join('')}</div>
    <div class="tw"><table class="tbl" id="tb"></table></div></div><div id="pn" style="width:min(460px,38vw);flex:none;border-left:1px solid var(--line);padding:16px;overflow:auto;background:var(--panel2)"></div></div>`;
  const plazo = c => { if (c.stage === 'audiencia') { const left = businessDaysBetween(todayIso(), c.vence); return todayIso() > c.vence ? chip('Plazo vencido ' + c.vence, 'warn') : chip(left + ' días hábiles', 'info'); } if (c.stage === 'firme' && c.estado === 'Abierto') return todayIso() > c.recVence ? chip('Causó estado', 'ok') : chip('Recurso hasta ' + c.recVence, 'info'); return ''; };
  const draw = () => { $('#tb', main).innerHTML = `<thead><tr><th>Expediente</th><th>Huerta</th><th>Municipio</th><th>Etapa</th><th>Plazo</th><th>Alegatos</th><th>Estado</th></tr></thead><tbody>${list().map(c => { const h = hById[c.uid]; return `<tr class="cl ${c.id === sel ? 'act' : ''}" data-id="${c.id}"><td class="mono">${c.id}</td><td class="mono tiny">${c.uid}</td><td>${esc(munName[h.mun])}</td><td class="tiny">${esc(STAGES[stageIdx(c.stage)].n)}</td><td>${plazo(c)}</td><td class="num">${c.alegatos.length || ''}</td><td class="tiny">${esc(c.estado)}${c.res ? ' · ' + c.res : ''}</td></tr>`; }).join('') || '<tr><td colspan="7" class="dim">Sin expedientes.</td></tr>'}</tbody>`; };
  const detail = () => { const pn = $('#pn', main); const c = caseById(sel); if (!c) { pn.innerHTML = `<div class="dim" style="text-align:center;padding:40px 10px">${icon('file', 34)}<div style="margin-top:8px">Seleccione un expediente.</div></div>`; return; } const h = hById[c.uid]; const si = stageIdx(c.stage); const u = me(); const dic = c.dicFolio && S.dictamenes.find(x => x.folio === c.dicFolio);
    pn.innerHTML = `<div class="ch"><h2 class="mono">${c.id}</h2><div class="sp">${estChip(h.estado)}</div></div><div class="tiny dim" style="margin:2px 0 10px">Huerta <a data-h="${h.uid}" class="mono">${h.uid}</a> · ${esc(munName[h.mun])} · alerta <span class="mono">${c.alerta}</span></div>
    <div class="steps" style="margin-bottom:10px">${STAGES.slice(1).map((s, i) => `<div class="${i + 1 < si || (i + 1 === si && c.estado !== 'Abierto') ? 'done' : i + 1 === si ? 'now' : ''}" style="min-width:60px"><b>${i + 1}</b>${esc(s.n)}</div>`).join('')}</div>
    ${c.stage === 'audiencia' ? `<div class="note ${todayIso() > c.vence ? '' : 'info'} tiny">Notificado el ${c.notif}. Plazo de audiencia (${PARAMS.plazoAudienciaDH} días hábiles, sin sábados, domingos ni días inhábiles) vence el <b>${c.vence}</b>.</div>` : ''}
    <h3 style="margin-top:12px">Actuaciones</h3><div class="timeline" style="margin-top:6px">${c.steps.map(s => `<div><div class="tiny"><b>${esc(STAGES[stageIdx(s.k)]?.n || s.k)}</b> · <span class="mono dim">${ftime(s.ts)}</span> · ${esc(s.actor)}</div><div class="tiny dim">${esc(s.nota)}</div>${(s.evid || []).map(e => `<div class="tiny mono dim">📎 ${esc(e.n)} · ${shortHash(e.sha)}</div>`).join('')}</div>`).join('')}
    ${c.alegatos.map(a => `<div><div class="tiny"><b>Alegatos y pruebas del productor</b> · <span class="mono dim">${ftime(a.ts)}</span></div><div class="tiny dim">${esc(a.txt)}</div>${a.files.map(e => `<div class="tiny mono dim">📎 ${esc(e.n)} · ${shortHash(e.sha)}</div>`).join('')}</div>`).join('')}
    ${c.recurso ? `<div><div class="tiny"><b>Recurso de revisión</b> · <span class="mono dim">${ftime(c.recurso.ts)}</span></div><div class="tiny dim">${esc(c.recurso.txt)}</div></div>` : ''}</div>
    <h3 style="margin-top:12px">Siguiente actuación</h3><div id="nx" style="margin-top:6px"></div>${dic ? `<div style="margin-top:10px"><button class="btn sm" data-dic="${dic.folio}">${icon('download', 12)} Expediente del dictamen ${dic.folio}</button></div>` : ''}`;
    const nx = $('#nx', pn); const btn = (a, label, kind = '') => { const r = allowed(c, a, u); return `<button class="btn ${kind}" data-act="${a}" ${r.ok ? '' : 'disabled'}>${label}</button><div class="tiny dim" style="margin:4px 0 8px">${r.ok ? '' : '⚠ ' + esc(r.why)}</div>`; };
    nx.innerHTML = c.estado !== 'Abierto' ? `<div class="tiny dim">Expediente ${esc(c.estado.toLowerCase())}.</div>` : c.stage === 'alerta' ? btn('validar', '✓ Validar alerta', 'ok') : c.stage === 'revision' ? btn('campo', 'Registrar visita de campo', 'pri') : c.stage === 'campo' ? btn('proyecto', 'Emitir proyecto de dictamen y notificar', 'pri') : c.stage === 'audiencia' ? btn('firme', 'Emitir dictamen firme', 'pri') : c.stage === 'recurso' ? `<button class="btn" data-go="segunda">Ir a segunda instancia</button>` : `<div class="tiny dim">En plazo de recurso hasta ${c.recVence}.</div>`;
  };
  draw(); detail();
  on(main, 'click', '#ft button', (e, b) => { fs = b.dataset.f; $$('#ft button', main).forEach(x => x.classList.toggle('on', x === b)); draw(); });
  on(main, 'click', 'tr.cl', (e, r) => { sel = r.dataset.id; draw(); detail(); });
  on(main, 'click', '[data-h]', (e, a) => window.__go('admin', 'huertas', { id: a.dataset.h }));
  on(main, 'click', '[data-go]', (e, b) => window.__go('admin', b.dataset.go, { id: sel }));
  on(main, 'click', '[data-dic]', (e, b) => dlExp(S.dictamenes.find(x => x.folio === b.dataset.dic)));
  on(main, 'click', '[data-act]', async (e, b) => { const c = caseById(sel); const a = b.dataset.act;
    if (a === 'campo') { const m = modal(`<h2>Visita de campo · ${c.id}</h2><p class="tiny dim">Adjunte fotografías georreferenciadas y el acta. Cada archivo se sella con SHA-256.</p><input type="file" id="fi" multiple><label class="tiny">Observaciones<textarea id="tx" rows="3" style="width:100%">Se constató el cambio de uso; se levantó acta circunstanciada.</textarea></label><div style="display:flex;gap:8px;justify-content:flex-end;margin-top:10px"><button class="btn ghost" data-close>Cancelar</button><button class="btn pri" id="ok">Registrar</button></div>`, { w: '480px' });
      m.q('#ok').onclick = async () => { const ev = []; for (const f of m.q('#fi').files) ev.push({ n: f.name, sha: await sha256File(f) }); const r = act(c, 'campo', me(), { nota: m.q('#tx').value, evid: ev.length ? ev : undefined }); if (denied(r)) return; m.close(); toast('Visita registrada'); draw(); detail(); }; return; }
    if (a === 'firme') { const m = modal(`<h2>Dictamen firme · ${c.id}</h2><p class="tiny dim">${c.alegatos.length ? 'El productor presentó alegatos y pruebas: debe valorarlos expresamente.' : 'Sin alegatos dentro del plazo.'}</p><label class="tiny">Sentido<select id="rs" style="width:100%"><option value="no">No elegible: conversión posterior al corte aplicable (Bloqueado)</option><option value="favorable">Favorable: la conversión no se acredita o es anterior al corte (Libre)</option></select></label><label class="tiny">Valoración de alegatos y pruebas<textarea id="cn" rows="4" style="width:100%"></textarea></label><div style="display:flex;gap:8px;justify-content:flex-end;margin-top:10px"><button class="btn ghost" data-close>Cancelar</button><button class="btn pri" id="ok">Firmar y sellar</button></div>`, { w: '520px' });
      m.q('#ok').onclick = () => { const r = act(c, 'firme', me(), { resultado: m.q('#rs').value, consideracion: m.q('#cn').value }); if (denied(r)) return; m.close(); toast('Dictamen ' + r.dic.folio + ' emitido y notificado'); draw(); detail(); }; return; }
    const r = act(c, a, me()); if (denied(r)) return; toast('Actuación registrada'); draw(); detail(); });
}

// ---------- Dictámenes ----------
function dictamenes(main, params) {
  let sel = (params && params.id) || (S.dictamenes[0] && S.dictamenes[0].folio), pub = false, tam = null;
  main.innerHTML = hdr('Dictámenes', 'El producto formal: folio, fecha de corte, versión de metodología, firma electrónica y constancia NOM-151. Cada uno se descarga como expediente reproducible.', who()) + `<div class="grid g12"><div class="card pad0"><div class="tw" style="max-height:640px"><table class="tbl" id="tb"></table></div></div><div class="card"><div id="pn"></div></div></div>`;
  const draw = () => { $('#tb', main).innerHTML = `<thead><tr><th>Folio</th><th>Huerta</th><th>Tipo</th><th>Modo</th><th>Emitido</th></tr></thead><tbody>${S.dictamenes.map(d => `<tr class="cl ${d.folio === sel ? 'act' : ''}" data-id="${d.folio}"><td class="mono">${d.folio}</td><td class="mono tiny">${d.uid}</td><td class="tiny">${esc(d.tipo.replace('Dictamen de ', '').replace(/^./, c => c.toUpperCase()))}</td><td class="tiny">${(d.pay.modo || MODOS[0]) === MODOS[1] ? '<span class="chip info">Insumo SEMARNAT</span>' : '<span class="chip">Constancia estatal</span>'}${(S.entregasSemarnat || []).some(e => e.folio === d.folio) ? ' <span class="chip ok">entregado</span>' : ''}</td><td class="mono tiny">${d.ts.slice(0, 10)}</td></tr>`).join('') || '<tr><td colspan="4" class="dim">Aún no hay dictámenes.</td></tr>'}</tbody>`; };
  const detail = () => { const d = S.dictamenes.find(x => x.folio === sel); const pn = $('#pn', main); if (!d) { pn.innerHTML = '<div class="dim">Seleccione un dictamen.</div>'; return; } const v = verificarDictamen(d);
    pn.innerHTML = `<div class="ch"><h2 class="mono">${d.folio}</h2><div class="sp"><label class="tiny"><input type="checkbox" id="pb" ${pub ? 'checked' : ''}> Versión pública</label></div></div>
    <div class="verdict ${v.hash && v.firma && v.sello ? 'ok' : 'fail'}" style="margin:8px 0"><div><div class="big">${v.hash && v.firma && v.sello ? 'Íntegro: huella, firma y sello coinciden' : 'ALTERADO: la huella ya no coincide con la firma y el sello'}</div><div class="tiny dim mono">SHA-256 ${shortHash(d.hash)} · firma ${v.firma ? '✓' : '✕'} · NOM-151 ${v.sello ? '✓' : '✕'} (simulados)</div></div></div>
    <div style="display:flex;gap:6px;flex-wrap:wrap;margin-bottom:8px"><button class="btn sm pri" id="zip">${icon('download', 12)} Expediente reproducible (ZIP)</button><button class="btn sm" id="html">${icon('download', 12)} Documento HTML</button><button class="btn sm ghost" id="tp">${tam ? 'Restaurar' : 'Simular alteración'}</button>${(d.pay.modo || MODOS[0]) === MODOS[1] ? `<button class="btn sm" id="sem" ${(S.entregasSemarnat || []).some(e => e.folio === d.folio) ? 'disabled' : ''}>${icon('upload', 12)} Entregar a SEMARNAT</button>` : ''}</div><div class="tiny dim" style="margin-bottom:6px">Modo: <b>${esc(d.pay.modo || MODOS[0])}</b>${(S.entregasSemarnat || []).find(e => e.folio === d.folio) ? ' · acuse ' + (S.entregasSemarnat || []).find(e => e.folio === d.folio).acuse : ''}</div>
    <iframe id="fr" style="width:100%;height:560px;border:1px solid var(--line);border-radius:8px;background:#FFFFFF"></iframe>`;
    $('#fr', pn).srcdoc = docHTML(d, { publico: pub });
    $('#pb', pn).onchange = e => { pub = e.target.checked; detail(); };
    $('#zip', pn).onclick = () => { dlExp(d, pub); ledgerAppend(S.ledger, me().id, 'EXPEDIENTE_DESCARGADO', d.folio); };
    $('#html', pn).onclick = () => download(d.folio + '.html', docHTML(d, { publico: pub }), 'text/html');
    const sb = $('#sem', pn); if (sb) sb.onclick = () => { const r = entregarSemarnat(d, me()); if (denied(r)) return; toast('Entregado a SEMARNAT · acuse ' + r.e.acuse); draw(); detail(); };
    $('#tp', pn).onclick = () => { if (tam) { d.js = tam; tam = null; } else { tam = d.js; d.js = d.js.replace(/"evaluacion_aplicable":"(\w+)"/, (m, x) => `"evaluacion_aplicable":"${x === 'cumple' ? 'incumple' : 'cumple'}"`); toast('Se alteró en memoria el resultado del dictamen', 'warn'); } detail(); };
  };
  draw(); detail(); on(main, 'click', 'tr.cl', (e, r) => { sel = r.dataset.id; tam = null; draw(); detail(); });
}

// ---------- Segunda instancia ----------
function segunda(main, params) {
  let sel = params && params.id;
  const list = () => S.cases.filter(c => c.stage === 'recurso' || c.stage === 'resolucion');
  main.innerHTML = hdr('Segunda instancia', 'Recursos de revisión resueltos por la Unidad de Revisión, un área distinta de la que dictaminó. El sistema impide que quien dictaminó resuelva su propia apelación.', who()) + `<div class="grid g12"><div class="card pad0"><div class="tw"><table class="tbl" id="tb"></table></div></div><div class="card" id="pn"></div></div>`;
  const draw = () => { $('#tb', main).innerHTML = `<thead><tr><th>Expediente</th><th>Huerta</th><th>Dictaminó</th><th>Recurso</th><th>Resolución</th></tr></thead><tbody>${list().map(c => `<tr class="cl ${c.id === sel ? 'act' : ''}" data-id="${c.id}"><td class="mono">${c.id}</td><td class="mono tiny">${c.uid}</td><td class="mono tiny">${(c.steps.find(s => s.k === 'firme') || {}).actor || '—'}</td><td class="mono tiny">${c.recurso ? c.recurso.ts.slice(0, 10) : ''}</td><td>${c.res ? chip(c.res, c.res === 'confirma' ? '' : 'ok') : chip('Pendiente', 'warn')}</td></tr>`).join('') || '<tr><td colspan="5" class="dim">Sin recursos.</td></tr>'}</tbody>`; };
  const detail = () => { const c = caseById(sel); const pn = $('#pn', main); if (!c) { pn.innerHTML = '<div class="dim">Seleccione un recurso.</div>'; return; } const r = allowed(c, 'resolver', me()); const f = c.steps.find(s => s.k === 'firme');
    pn.innerHTML = `<div class="ch"><h2 class="mono">${c.id}</h2></div><dl class="kv" style="margin:8px 0"><dt>Huerta</dt><dd class="mono">${c.uid} ${estChip(hById[c.uid].estado)}</dd><dt>Dictamen</dt><dd class="mono">${c.dicFolio || '—'} · ${f ? f.actor : ''} (${f ? ROLES[userById[f.actor].rol].area : ''})</dd><dt>Agravios</dt><dd>${c.recurso ? esc(c.recurso.txt) : '—'}</dd></dl>
    ${c.stage === 'recurso' ? `<label class="tiny">Sentido<select id="se" style="width:100%"><option value="confirma">Confirma el dictamen</option><option value="revoca">Revoca (huerta pasa a Libre)</option><option value="reponer">Ordena reponer el procedimiento</option></select></label><label class="tiny">Motivación<textarea id="mo" rows="4" style="width:100%"></textarea></label><button class="btn pri" id="ok" style="margin-top:8px" ${r.ok ? '' : 'disabled'}>Resolver</button><div class="tiny dim" style="margin-top:6px">${r.ok ? 'Resolverá como ' + me().id + ' (' + ROLES[me().rol].area + ').' : '⚠ ' + esc(r.why)}</div>` : `<div class="note info tiny">Resuelto: ${esc(c.res)} · ${esc((c.steps.find(s => s.k === 'resolucion') || {}).actor || '')}</div>`}
    <div class="note tiny" style="margin-top:12px">Pruebe la regla: cambie el rol a «Dictaminador» (DIC-01 o DIC-04) e intente resolver. El sistema lo impide aunque el usuario tenga privilegios de dictaminación.</div>`;
    const ok = $('#ok', pn); if (ok) ok.onclick = () => { const x = act(c, 'resolver', me(), { sentido: $('#se', pn).value, motivo: $('#mo', pn).value }); if (denied(x)) return; toast('Recurso resuelto'); draw(); detail(); };
  };
  if (!sel && list()[0]) sel = list()[0].id; draw(); detail(); on(main, 'click', 'tr.cl', (e, r) => { sel = r.dataset.id; draw(); detail(); });
}
export const views = { huertas, triaje, expedientes, dictamenes, segunda };
