// Catálogo de fuentes para alimentar y monitorear la plataforma. pri: P0 (arranque), P1 (piloto), P2 (consolidación)
// estado: real = ya cargada en este prototipo · demo = simulada · conectar = conector por construir · convenio · contratar · propia
export const CATS = ['Padrón y tenencia', 'Monitoreo satelital', 'Línea base histórica', 'Estructura forestal (LiDAR)', 'Referencia territorial', 'Agua, clima y fuego', 'Producción y cadena', 'Casos y autorizaciones', 'Captura propia'];
export const SOURCES = [
  // Padrón y tenencia
  { id: 'S01', cat: 0, src: 'SIAP-SADER / INEGI Censo Agropecuario', prod: 'Superficie y producción de aguacate por municipio; unidades de producción', uso: 'Universo esperado del Padrón y contraste con superficie mapeada', acc: 'Abierto', cad: 'Anual', pri: 'P0', fmt: 'CSV / API', estado: 'conectar', nota: 'En el prototipo: cuatro municipios líderes con cifra del Censo (Uruapan, S. Escalante, Tacámbaro, Ario).' },
  { id: 'S02', cat: 0, src: 'Padrón de huertas exportadoras (SENASICA / Comité de Sanidad Vegetal / empacadoras)', prod: 'Huertas registradas, predio y productor', uso: 'Semilla del Padrón; universo prioritario de certificación', acc: 'Convenio', cad: 'Trimestral', pri: 'P0', fmt: 'Tabla + polígonos', estado: 'convenio', nota: 'Cifras públicas hablan de ~58-59 mil huertas exportadoras; requiere convenio y aviso de privacidad.' },
  { id: 'S03', cat: 0, src: 'Registro Agrario Nacional (RAN / PHINA)', prod: 'Polígonos de núcleos agrarios, parcelas y tierras de uso común', uso: 'Regla de competencia (ejidal/comunal → PROFEPA); traslapes de tenencia', acc: 'Abierto parcial / convenio', cad: 'Semestral', pri: 'P0', fmt: 'Shapefile / GPKG', estado: 'convenio', nota: 'Las parcelas individuales requieren convenio.' },
  { id: 'S04', cat: 0, src: 'Catastro y Registro Público de la Propiedad (Michoacán)', prod: 'Cartografía predial y folios', uso: 'Validación de polígonos y CURT; propiedad privada', acc: 'Convenio', cad: 'Semestral', pri: 'P1', fmt: 'SHP / servicio', estado: 'convenio', nota: 'Cobertura rural irregular; la CURT es identificador, no clave primaria.' },
  { id: 'S05', cat: 0, src: 'Guardián Forestal (API del proveedor)', prod: 'Alertas, línea base 2018/2012, expedientes de denuncia', uso: 'Integración por API con propiedad estatal de los datos; no duplicar el monitoreo', acc: 'Convenio', cad: 'Semanal', pri: 'P0', fmt: 'API / PDF', estado: 'real', nota: 'Integrado: estadísticas de 113 municipios y 64 subcuencas completas; capas espaciales con muestra de tesela (consulta pública 30-sep-2026). Producción: convenio de datos y exportación original.' },
  // Monitoreo satelital
  { id: 'S06', cat: 1, src: 'Global Forest Watch — alertas integradas (GLAD-L, GLAD-S2, RADD, DIST-ALERT)', prod: 'Alertas de pérdida de cobertura a 10-30 m con nivel de confianza', uso: 'Detección temprana; disparo de alertas a validación', acc: 'Abierto (API)', cad: 'Diaria-semanal', pri: 'P0', fmt: 'API / GeoTIFF', estado: 'conectar', nota: 'DIST-ALERT incorporado a la capa integrada en enero de 2026; "una alerta no es necesariamente deforestación".' },
  { id: 'S07', cat: 1, src: 'Sentinel-2 L2A (Copernicus Data Space) / HLS (NASA)', prod: 'Multiespectral 10-30 m, revisita 2-5 días', uso: 'Series NDVI/NBR por predio; detección propia de cambios', acc: 'Abierto (STAC/API)', cad: '5 días', pri: 'P0', fmt: 'COG / STAC', estado: 'conectar', nota: 'Procesar en nube; almacenar sólo derivados por predio.' },
  { id: 'S08', cat: 1, src: 'Sentinel-1 RTC y NISAR (NASA-ISRO, vía ASF DAAC)', prod: 'Radar; penetra nubes (temporada de lluvias)', uso: 'Continuidad de vigilancia en meses nublados; separar bosque de plantación', acc: 'Abierto', cad: '6-12 días', pri: 'P1', fmt: 'GeoTIFF', estado: 'conectar', nota: 'Datos de NISAR públicos desde julio de 2026 (verificar productos disponibles).' },
  { id: 'S09', cat: 1, src: 'Imágenes de muy alta resolución (0.3-0.5 m) — Planet / Maxar / Airbus', prod: 'Antes/después para validar alertas', uso: 'Evidencia visual en expediente; validación humana', acc: 'Comercial', cad: 'Bajo demanda + archivo', pri: 'P0', fmt: 'GeoTIFF / mosaico', estado: 'contratar', nota: 'El acceso gratuito NICFI terminó en 2025; presupuestar licencia por área de interés.' },
  { id: 'S10', cat: 1, src: 'NASA FIRMS (VIIRS / MODIS)', prod: 'Focos de calor casi en tiempo real', uso: 'V6 Fuego; distinguir pérdida por incendio de desmonte', acc: 'Abierto (API)', cad: '3 h', pri: 'P0', fmt: 'CSV / GeoJSON', estado: 'conectar', nota: '' },
  // Línea base histórica
  { id: 'S11', cat: 2, src: 'Hansen / UMD Global Forest Change v1.13 (2000-2025)', prod: 'Cobertura 2000, pérdida por año (30 m)', uso: 'Historial Forestal 2001-2025 por predio (indicio, no medida)', acc: 'Abierto', cad: 'Anual', pri: 'P0', fmt: 'GeoTIFF', estado: 'conectar', nota: 'Su "bosque" (>5 m) incluye huertas maduras.' },
  { id: 'S12', cat: 2, src: 'Landsat Collection 2 (USGS) 1993-hoy', prod: 'Serie larga a 30 m', uso: 'Reconstrucción CCDC/LandTrendr por predio desde 1993', acc: 'Abierto', cad: '16 días', pri: 'P0', fmt: 'COG / STAC', estado: 'conectar', nota: 'Método publicado en franja aguacatera: exactitud global 0.97 pero omisión de aguacate ~29 % (Solórzano et al. 2025).' },
  { id: 'S13', cat: 2, src: 'INEGI — ortofotos y fotografía aérea históricas (1974, 1995…)', prod: 'Imagen histórica pre-satélite', uso: 'Línea base de bosque previa a la expansión; interpretación visual', acc: 'Abierto / solicitud', cad: 'Estática', pri: 'P1', fmt: 'TIFF / JPG', estado: 'conectar', nota: '' },
  { id: 'S14', cat: 2, src: 'INEGI — Uso del suelo y vegetación Series I a VII', prod: 'Cartografía de cobertura 1:250 000', uso: 'Comparación multitemporal y tipos de vegetación', acc: 'Abierto', cad: 'Cada ~3-5 años', pri: 'P1', fmt: 'SHP', estado: 'conectar', nota: 'Escala gruesa; no sustituye la medición por predio.' },
  { id: 'S15', cat: 2, src: 'JRC GFC2020 v3 / Google Natural Forests of the World 2020', prod: 'Mapa de bosque al 31-dic-2020', uso: 'Fecha de corte de mercados con debida diligencia (EUDR/AFi/SBTi)', acc: 'Abierto', cad: 'Estática', pri: 'P1', fmt: 'GeoTIFF', estado: 'conectar', nota: '' },
  { id: 'S16', cat: 2, src: 'CONAFOR — INFyS, SNMF, cartografía forestal, NREF', prod: 'Parcelas de campo y factores de emisión; tasas', uso: 'Calibración de biomasa/carbono y de umbrales forestales', acc: 'Abierto parcial', cad: 'Ciclos 5 años', pri: 'P1', fmt: 'CSV / SHP', estado: 'conectar', nota: 'Sitios de gob.mx pueden bloquear descarga automática: solicitar por vía oficial.' },
  // LiDAR
  { id: 'S17', cat: 3, src: 'Levantamiento LiDAR aerotransportado regional (Nivel A)', prod: 'Nube ≥ 8 pts/m², MDT/MDS/CHM', uso: 'Línea base estructural de la franja aguacatera', acc: 'Contratación', cad: 'Una vez + actualización 3-5 años', pri: 'P1', fmt: 'LAZ/COPC', estado: 'contratar', nota: 'Requiere autorización de vuelo INEGI.' },
  { id: 'S18', cat: 3, src: 'Estudios por predio con dron/LiDAR (Nivel B) presentados por el productor', prod: 'Nube ≥ 100 pts/m², trayectoria, log de vuelo, EXIF', uso: 'Estudios prediales para constancia y restauración', acc: 'Portal Productor', cad: 'Por trámite', pri: 'P0', fmt: 'LAZ + metadatos', estado: 'propia', nota: 'Cada archivo se sella con SHA-256 y se verifica al recibirse.' },
  { id: 'S19', cat: 3, src: 'NASA GEDI (L2A/L2B/L4A)', prod: 'Altura de dosel y biomasa por huella (25 m)', uso: 'Contexto estructural y control cruzado de Nivel A', acc: 'Abierto', cad: 'Según misión', pri: 'P2', fmt: 'HDF5 / GPKG', estado: 'conectar', nota: '' },
  { id: 'S20', cat: 3, src: 'INEGI — Continuo de Elevaciones Mexicano, MDE de alta resolución, red geodésica activa (RGNA)', prod: 'Terreno y estaciones de referencia para PPK/RTK', uso: 'Control vertical, geoide, correcciones de trayectoria', acc: 'Abierto', cad: 'Estática / continua', pri: 'P0', fmt: 'GeoTIFF / RINEX', estado: 'conectar', nota: '' },
  // Referencia territorial
  { id: 'S21', cat: 4, src: 'INEGI Marco Geoestadístico (estatal, municipal, AGEB, localidad)', prod: 'Límites oficiales', uso: 'Unidades de reporte y publicación', acc: 'Abierto', cad: 'Semestral', pri: 'P0', fmt: 'SHP', estado: 'real', nota: 'Prototipo: límites municipales de geoBoundaries (CC BY 4.0), 113 municipios.' },
  { id: 'S22', cat: 4, src: 'CONANP — Áreas Naturales Protegidas', prod: 'Polígonos (Mariposa Monarca, Pico de Tancítaro, Barranca del Cupatitzio…)', uso: 'Causal reforzada y exclusiones', acc: 'Abierto', cad: 'Anual', pri: 'P0', fmt: 'SHP', estado: 'conectar', nota: '' },
  { id: 'S23', cat: 4, src: 'CONABIO — Geoportal', prod: 'Ecosistemas, biodiversidad, áreas prioritarias', uso: 'V8 integridad y valor del ecosistema', acc: 'Abierto', cad: 'Variable', pri: 'P1', fmt: 'SHP / WMS', estado: 'conectar', nota: '' },
  { id: 'S24', cat: 4, src: 'Natural Earth (hidrografía y localidades de referencia)', prod: 'Ríos y lagos principales', uso: 'Cartografía base', acc: 'Abierto', cad: 'Estática', pri: 'P2', fmt: 'GeoJSON', estado: 'real', nota: 'Prototipo. Sustituir por hidrografía INEGI 1:50 000.' },
  // Agua, clima, fuego
  { id: 'S25', cat: 5, src: 'CONAGUA — REPDA (concesiones) y cuencas', prod: 'Títulos de agua y puntos de extracción', uso: 'Cruce de reservorios (ollas) con fuente legal de agua', acc: 'Abierto parcial / convenio', cad: 'Trimestral', pri: 'P1', fmt: 'CSV / SHP', estado: 'convenio', nota: 'Base para el futuro módulo Guardián del Agua.' },
  { id: 'S26', cat: 5, src: 'SMN — estaciones y Monitor de Sequía; CHIRPS / IMERG', prod: 'Precipitación, temperatura, sequía', uso: 'Distinguir estrés hídrico de pérdida; V7 regeneración', acc: 'Abierto', cad: 'Diaria-mensual', pri: 'P2', fmt: 'API / raster', estado: 'conectar', nota: '' },
  { id: 'S27', cat: 5, src: 'Reservorios y ollas detectados (Guardián Forestal / Guardián del Agua)', prod: 'Inventario de >37 mil reservorios', uso: 'Causal "infraestructura permanente"', acc: 'Convenio', cad: 'Semestral', pri: 'P1', fmt: 'GeoJSON', estado: 'real', nota: 'Muestra integrada desde Guardián Forestal (5,331 ollas en la tesela de muestra); conteo municipal completo en la API.' },
  // Producción y cadena
  { id: 'S28', cat: 6, src: 'Empacadoras y APEAM / trazabilidad de lotes', prod: 'Lote → huerta → constancia', uso: 'Nivel "Restringido": verificación del comprador', acc: 'Convenio + consentimiento', cad: 'Continua', pri: 'P2', fmt: 'API', estado: 'convenio', nota: 'No se publica nombre del productor.' },
  { id: 'S29', cat: 6, src: 'Boletines de producción SADER / Cierre agrícola', prod: 'Toneladas y valor por temporada', uso: 'Contexto del tablero ciudadano', acc: 'Abierto', cad: 'Mensual', pri: 'P2', fmt: 'HTML / CSV', estado: 'real', nota: 'Temporada 2025-26: 1,462,973 t (SADER Michoacán, ago-2026).' },
  // Casos y autorizaciones
  { id: 'S30', cat: 7, src: 'PROFEPA, Fiscalía Ambiental y PPA estatal', prod: 'Denuncias, inspecciones, resoluciones', uso: 'Estado procesal de cada expediente; indicador de seguimiento', acc: 'Convenio', cad: 'Trimestral', pri: 'P0', fmt: 'Tabla + acuses', estado: 'convenio', nota: 'A abril de 2026 se reportaron 330 denuncias a PROFEPA y 381 a la Fiscalía estatal (prensa).' },
  { id: 'S31', cat: 7, src: 'SEMARNAT — autorizaciones de cambio de uso de suelo forestal y MIA (SIGEIA)', prod: 'Autorizaciones vigentes con polígono', uso: 'Distinguir desmonte autorizado de no autorizado', acc: 'Abierto parcial / convenio', cad: 'Mensual', pri: 'P0', fmt: 'SHP / tabla', estado: 'convenio', nota: 'Es la fuente clave para que el Semáforo no marque como infracción un cambio autorizado.' },
  // Captura propia
  { id: 'S32', cat: 8, src: 'App de campo (verificación con fotos geoetiquetadas)', prod: 'Evidencia de campo y parcelas de 400 m² (Nivel C)', uso: 'Calibración del Índice de Reversibilidad y exactitud', acc: 'Propia', cad: 'Continua', pri: 'P1', fmt: 'GeoJSON + fotos', estado: 'propia', nota: '' },
  { id: 'S33', cat: 8, src: 'Denuncia ciudadana (anónima)', prod: 'Reportes con foto y ubicación', uso: 'Disparo de alertas y verificación', acc: 'Portal Ciudadano', cad: 'Continua', pri: 'P0', fmt: 'JSON', estado: 'propia', nota: '' },
  { id: 'S34', cat: 8, src: 'Estaciones meteorológicas y sensores (Guardián del Agua)', prod: 'Series climáticas locales', uso: 'Modelos de consumo hídrico y estrés', acc: 'Propia', cad: 'Continua', pri: 'P2', fmt: 'MQTT / API', estado: 'propia', nota: '' },
  // Agregadas en la reingeniería (verificación y dictamen)
  { id: 'S35', cat: 2, src: 'Dynamic World (Google/WRI) y ESA WorldCover 10 m', prod: 'Cobertura del suelo casi en tiempo real (2015-hoy) y mapas 2020/2021', uso: 'Contraste independiente de la clase de cobertura; estrato del muestreo de exactitud', acc: 'Abierto', cad: 'Continua / bienal', pri: 'P1', fmt: 'GeoTIFF / GEE', estado: 'conectar', nota: 'Referencia secundaria; no sustituye la serie propia.' },
  { id: 'S36', cat: 2, src: 'MapBiomas México', prod: 'Series anuales de cobertura y transiciones 1985-hoy', uso: 'Contraste de la reconstrucción histórica y de la fecha de conversión', acc: 'Abierto', cad: 'Anual', pri: 'P1', fmt: 'GeoTIFF / GEE', estado: 'conectar', nota: 'Útil para validar 2012 y 2018 con metodología publicada.' },
  { id: 'S37', cat: 3, src: 'Mapas globales de altura de dosel (Meta / WRI, 1 m)', prod: 'Altura de dosel a partir de imagen de muy alta resolución calibrada con GEDI', uso: 'Estructura del dosel mientras no haya vuelos LiDAR propios; separar huerta de bosque', acc: 'Abierto', cad: 'Por versión', pri: 'P0', fmt: 'COG', estado: 'conectar', nota: 'Junto con GEDI sustituye el LiDAR simulado.' },
  { id: 'S38', cat: 1, src: 'PlanetScope (3 m, diario) en zonas prioritarias', prod: 'Imagen diaria de alta resolución', uso: 'Acotar la fecha de conversión y revisar alertas en huertas pequeñas', acc: 'Pago', cad: 'Diaria', pri: 'P1', fmt: 'API', estado: 'contratar', nota: 'Sólo en la franja aguacatera y casos en disputa.' },
  { id: 'S39', cat: 6, src: 'IMSS — registros patronales y asegurados por patrón', prod: 'Trabajadores asegurados', uso: 'Módulo laboral (trabajo digno) y padrón del ISN', acc: 'Convenio', cad: 'Mensual', pri: 'P2', fmt: 'Servicio', estado: 'convenio', nota: 'Cruce por RFC; sin exponer datos personales.' },
  { id: 'S40', cat: 6, src: 'Secretaría de finanzas estatal — líneas de captura e ISN', prod: 'Referencias de pago y padrón de contribuyentes', uso: 'Emisión del derecho y tablero de Finanzas (interno)', acc: 'Convenio', cad: 'Diaria', pri: 'P1', fmt: 'Servicio web', estado: 'convenio', nota: 'Modalidad de cobro por lote verificado sujeta a dictamen jurídico.' },
  { id: 'S41', cat: 2, src: 'INEGI — Uso de Suelo y Vegetación serie VII', prod: 'Clases de uso de suelo y vegetación (1:250 000)', uso: 'Condición forestal a la fecha de corte (prueba de dos condiciones, M2)', acc: 'Abierto', cad: 'Por serie', pri: 'P0', fmt: 'Shapefile', estado: 'conectar', nota: 'Se ingesta como capa de referencia; homologa el umbral de terreno forestal' },
  { id: 'S42', cat: 2, src: 'CONAFOR — Inventario Nacional Forestal y de Suelos (INFyS)', prod: 'Conglomerados y estratos forestales', uso: 'Condición forestal y validación de la serie (M2)', acc: 'Abierto', cad: 'Quinquenal', pri: 'P0', fmt: 'CSV / Shapefile', estado: 'conectar', nota: '' },
  { id: 'S43', cat: 7, src: 'SEMARNAT — autorizaciones de cambio de uso de suelo en terreno forestal (CUSTF)', prod: 'Polígonos y vigencia de autorizaciones', uso: 'Segunda condición del dictamen (M2); tipo «autorizaciones» en Ingesta', acc: 'Convenio', cad: 'Mensual', pri: 'P0', fmt: 'Servicio', estado: 'convenio', nota: 'Sin conexión por convenio: el dictamen lo indica como «sin consulta»' },
  { id: 'S44', cat: 4, src: 'CONANP — Áreas Naturales Protegidas', prod: 'Polígonos de ANP federales', uso: 'Regla Pro-Forest (fuera de ANP) y prioridad de denuncias', acc: 'Abierto', cad: 'Anual', pri: 'P0', fmt: 'Shapefile', estado: 'conectar', nota: 'En la demostración: ANP de la tesela de Guardián Forestal' },
  { id: 'S45', cat: 6, src: 'SENASICA — SICOA (registro y certificación de huertas por temporada)', prod: 'Registro de huerta y certificación fitosanitaria por temporada', uso: 'Semáforo fitosanitario (M1) y geocerca (M6)', acc: 'Convenio', cad: 'Diaria', pri: 'P0', fmt: 'Servicio', estado: 'convenio', nota: 'Mientras tanto: gris «sin dato SENASICA»' },
  { id: 'S46', cat: 6, src: 'SENASICA / APHIS — municipios aprobados del plan de trabajo operativo (OWP)', prod: 'Catálogo municipio_aprobado_owp', uso: 'Geocerca de la zona autorizada (M6)', acc: 'Convenio', cad: 'Por temporada', pri: 'P0', fmt: 'Tabla', estado: 'convenio', nota: 'Catálogo vacío hasta obtener la lista oficial' },
  { id: 'S47', cat: 6, src: 'STPS — VELAGRO / Certificado Laboral Agrícola (CLA)', prod: 'Empresas de la cadena, registro patronal y REPSE', uso: 'Semáforo laboral (M1, M8)', acc: 'Convenio', cad: 'Semanal', pri: 'P1', fmt: 'Servicio', estado: 'convenio', nota: 'Sin datos personales de trabajadores' },
  { id: 'S48', cat: 6, src: 'SIAP — rendimiento de aguacate por municipio', prod: 'Toneladas por hectárea por municipio y ciclo', uso: 'Capacidad productiva del balance de masa (M5)', acc: 'Abierto', cad: 'Anual', pri: 'P1', fmt: 'CSV', estado: 'conectar', nota: 'La demostración usa valores ilustrativos por franja de altitud' },
  { id: 'S49', cat: 7, src: 'SESNSP y mesa de seguridad', prod: 'Incidencia y avisos por localidad y ruta', uso: 'Capa de riesgo de seguridad (M9, rol restringido)', acc: 'Convenio', cad: 'Diaria', pri: 'P1', fmt: 'Servicio', estado: 'convenio', nota: 'Sólo visible para el rol Seguridad' },
];
export const REAL_FACTS = [
  ['Acuerdo de origen certificado (oct-2026)', 'Sólo aguacate con trazabilidad y constancia ambiental entrará a EE. UU. desde la temporada 2026-27', 'Acuerdo del 1-oct-2026; Milenio impreso 2-oct-2026 (APEAM)'],
  ['Exportación de aguacate a EE. UU. (último año)', '≈ 1.25 millones de t · ≈ 120 mil empleos directos', 'APEAM vía Milenio impreso, 2-oct-2026'],
  ['Superficie de aguacate en Michoacán (Censo Agropecuario)', '164,877 ha · 28,157 unidades de producción', 'Contramuro, ago-2026 (Censo INEGI)'],
  ['Pérdida de bosque reconocida por SECMA 2018-2023', '≈ 30,000 ha', 'Quadratín, feb-2024'],
  ['Reservorios (ollas) identificados', '> 37,000', 'PCM Noticias, dic-2025'],
  ['Cosecha de aguacate 2025-26 (Michoacán)', '1,462,973 t', 'SADER Michoacán, ago-2026'],
  ['Guardián Forestal', '> 6 millones de ha · > 59,000 huertas · > 1,000 denuncias 2024-25', 'SECMA / La Voz de Michoacán'],
  ['Pro-Forest Avocado', '49,000 huertas · 391,000 t certificadas (31 % de la exportación a EE. UU. 2024)', 'SECMA'],
  ['Empacadoras comprometidas con fruta libre de deforestación', '80 (≈ 90 % de la exportación estatal)', 'La Voz de Michoacán'],
  ['Presupuesto 2026', 'SECMA $141.6 M · COFOM $169.3 M', 'Presupuesto de Egresos 2026'],
];
// Series reales de superficie de aguacate (ha)
export const AVO_MM = [[1974, 13045], [1995, 58145], [2007, 112725], [2011, 153018], [2018, 214845], [2024, 266109]]; // Morales Manilla et al. 2026 (preprint)
export const AVO_SO = [[1993, 64304], [2024, 200938]]; // Solórzano et al. 2025, Land 14:1792
