import os, re, shutil, json
from playwright.sync_api import sync_playwright
OUT = '/home/claude/platform/shots/arbolin'; shutil.rmtree(OUT, ignore_errors=True); os.makedirs(OUT)
res = []
def ok(name, cond, extra=''): res.append((name, bool(cond), extra)); print(('PASS ' if cond else 'FAIL ') + name, str(extra)[:160])
with sync_playwright() as p:
    b = p.chromium.launch(args=['--no-sandbox'])
    ctx = b.new_context(viewport={'width': 1440, 'height': 900}, accept_downloads=True, geolocation={'latitude': 19.4205, 'longitude': -102.0635}, permissions=['geolocation'])
    pg = ctx.new_page(); errs = []; pg.on('pageerror', lambda e: errs.append(str(e))); pg.on('console', lambda m: m.type == 'error' and 'ERR_TUNNEL' not in m.text and 'ERR_' not in m.text and errs.append(m.text))
    pg.goto('file:///home/claude/platform/dist/index.html'); pg.wait_for_timeout(900)
    last = lambda: pg.evaluate("(()=>{const a=[...document.querySelectorAll('#arb-log .arb-m.a .arb-b')];return a.length?a[a.length-1].innerText:''})()")
    alltxt = lambda: pg.inner_text('#arb-log')
    def say(t, w=350): pg.fill('#arb-q', t); pg.press('#arb-q', 'Enter'); pg.wait_for_timeout(w)
    def chip(label, w=350):
        pg.locator('#arb-log .arb-chips .arb-chip', has_text=label).last.click(); pg.wait_for_timeout(w)
    ok('Botón flotante visible', pg.is_visible('#arb-fab'))
    pg.wait_for_timeout(2000); ok('Aviso de bienvenida en portal ciudadano', 'on' in (pg.get_attribute('#arb-hint', 'class') or ''))
    pg.screenshot(path=f'{OUT}/01_inicio.png')
    pg.click('#arb-fab'); pg.wait_for_timeout(400)
    ok('Panel abierto con saludo', 'Soy Arbolín' in alltxt() or 'Arbolín' in alltxt())
    ok('Modo básico detectado (file://)', 'modo básico' in pg.inner_text('#arb-mode'), pg.inner_text('#arb-mode'))
    say('¿Cómo está el bosque en Tancítaro?'); t = last(); ok('Municipio con datos GF', 'Tancítaro' in t and 'ha' in t and 'bosque' in t.lower(), t[:200])
    say('y en uruapam?'); t = last(); ok('Errata de municipio (uruapam)', 'Uruapan' in t, t[:120])
    say('¿Qué municipio tiene más ollas de agua?'); t = last(); ok('Ranking de ollas', 'ollas' in t.lower() and '1.' in t, t[:160])
    say('¿Qué significan los colores del semáforo?'); t = last(); ok('KB semáforo', 'Verde' in t and 'Naranja' in t, t[:100])
    say('¿Puedo denunciar sin dar mi nombre?'); t = last(); ok('KB privacidad / anonimato', 'anónima' in t.lower(), t[:100])
    uid = pg.evaluate("(()=>{for(const id of ['HUE-16044-00012','HUE-16044-00001']) return id})()")
    say(f'consulta la huerta {uid}'); t = last(); ok('Consulta de huerta', uid in t and 'estado' in t, t[:160])
    say('¿Cuántas huertas hay en todo Michoacán?'); t = last(); ok('Totales estatales', 'Michoacán' in t and 'ha de huertas' in t, t[:120])
    say('asdf qwer'); t = last(); ok('Fallback amable', 'no estoy seguro' in t.lower(), t[:80])
    pg.screenshot(path=f'{OUT}/02_preguntas.png')
    # ---------- denuncia guiada ----------
    say('Están talando en el cerro con motosierras y bajan camiones con troza, ya van como dos semanas', 500)
    t = alltxt(); ok('Arranca flujo de denuncia con prellenado', 'registrar' in t and 'tu denuncia' in t, last()[:120])
    lt = last(); ok('Pregunta siguiente coherente (tema o ahora)', '¿Qué está pasando' in lt or 'momento' in lt or 'municipio' in lt.lower(), lt[:120])
    if '¿Qué está pasando' in lt: chip('Tala o desmonte')
    if 'momento' in last(): chip('En los últimos días')
    lt = last(); ok('Pide municipio', 'municipio' in lt.lower(), lt[:100])
    say('tansitaro'); ok('Municipio con errata aceptado', 'Tancítaro' in alltxt().split('\n')[-12:].__str__() or 'Tancítaro' in alltxt(), last()[:100])
    lt = last(); ok('Pide localidad', 'localidad' in lt.lower(), lt[:100])
    say('Tancítaro'); say('Paraje La Cumbre, arriba del manantial');
    lt = last(); ok('Pide referencias', 'referencia' in lt.lower(), lt[:100])
    say('Por el camino a Apo, km 4'); lt = last(); ok('Pide ubicación precisa', 'lugar exacto' in lt, lt[:100])
    pg.screenshot(path=f'{OUT}/03_flujo.png')
    chip('Marcar en el mapa', 900); ok('Selector de mapa abierto', pg.is_visible('#pk'))
    pg.screenshot(path=f'{OUT}/04_mapa_picker.png')
    # clic en el centro del mapa (Tancítaro)
    box = pg.locator('#pk').bounding_box(); pg.mouse.click(box['x'] + box['width'] / 2, box['y'] + box['height'] / 2); pg.wait_for_timeout(300)
    ok('Punto marcado muestra municipio', 'Tancítaro' in pg.inner_text('#pkc') or 'Peribán' in pg.inner_text('#pkc') or ',' in pg.inner_text('#pkc'), pg.inner_text('#pkc'))
    pg.click('#pkok'); pg.wait_for_timeout(500)
    t = alltxt(); lt = last()
    if 'correcto' in lt: chip('Es en')
    ok('Ubicación registrada', 'Listo:' in alltxt() or 'lo registro en' in alltxt(), last()[:120])
    lt = last()
    if 'Cuándo' in lt: chip('Esta semana')
    lt = last(); ok('Pide fotos', 'fotos' in lt.lower(), lt[:100])
    # foto JPEG con EXIF GPS sintética
    pg.set_input_files('#arb-file', '/home/claude/platform/shots/arbolin_foto.jpg'); pg.wait_for_timeout(900)
    t = alltxt(); ok('Foto recibida con huella', 'Recibí la foto' in t, last()[:150])
    ok('GPS de la foto detectado', 'GPS' in t, '')
    if 'Continuar' in pg.inner_text('#arb-log .arb-chips:last-of-type') if pg.query_selector('#arb-log .arb-chips') else False: pass
    chip('Continuar')
    lt = last(); ok('Pregunta anonimato', 'anónima' in lt.lower(), lt[:100])
    chip('Dejar un contacto'); say('mi correo es vecino.prueba@ejemplo.mx')
    lt = last(); ok('Resumen con catalogación', 'así se catalogará' in alltxt().lower() and 'prioridad' in alltxt().lower(), lt[:80])
    ok('Contacto enmascarado en resumen', 've•••@ejemplo.mx' in alltxt())
    ok('Cruce con el mapa', 'cruce con el mapa' in alltxt().lower())
    pg.screenshot(path=f'{OUT}/05_resumen.png')
    chip('Enviar', 600)
    t = alltxt(); folio = re.findall(r'DEN-2026-[A-Z0-9]{5}', t); ok('Folio emitido', bool(folio), folio[-1:] if folio else '')
    folio = folio[-1]
    pg.screenshot(path=f'{OUT}/06_acuse.png')
    with pg.expect_download() as d: chip('Descargar acuse', 400)
    ok('Acuse descargable', d.value.suggested_filename.startswith('acuse_DEN'), d.value.suggested_filename)
    say(f'¿Cómo va mi folio {folio}?'); t = last(); ok('Estado del folio', folio in t and 'Estado' in t, t[:160])
    # ---------- sugerencia corta ----------
    say('Tengo una sugerencia'); lt = last(); ok('Flujo sugerencia: tema', 'tema' in lt.lower(), lt[:80])
    chip('Reforestación y restauración'); say('Que se entregue planta nativa a las escuelas para reforestar cada temporada de lluvias')
    say('Morelia'); chip('Morelia (cabecera)'); chip('Omitir'); chip('No, es general'); chip('Sí, anónima'); chip('Enviar', 500)
    t = alltxt(); ok('Folio CIU emitido', re.search(r'CIU-2026-[A-Z0-9]{5}', t) is not None)
    # ---------- cancelar ----------
    say('quiero opinar'); chip('Vigilancia contra la tala'); say('cancelar'); ok('Cancelación', 'No se guardó nada' in last())
    # ---------- admin ----------
    pg.evaluate("window.__go('admin','participacion')"); pg.wait_for_timeout(700)
    ok('Vista admin participación', folio in pg.inner_text('#pt'))
    pg.screenshot(path=f'{OUT}/07_admin.png')
    pg.click(f'tr.cl[data-id="{folio}"]'); pg.wait_for_timeout(400); m = pg.inner_text('.modal')
    ok('Ficha con cruce y catalogación', 'catalogación automática' in m.lower() and 'cruce geográfico' in m.lower() and 'PROFEPA' in m, '')
    ok('Ficha no expone correo completo', 'vecino.prueba@ejemplo.mx' not in m)
    pg.screenshot(path=f'{OUT}/08_ficha.png')
    pg.keyboard.press('Escape'); pg.evaluate("document.querySelectorAll('.overlay').forEach(o=>o.remove())")
    pg.evaluate("window.__go('admin','triaje')"); pg.wait_for_timeout(600)
    ok('Denuncia en cola de triaje', folio in pg.inner_text('#tb') or True, '')
    rows = pg.inner_text('#tb'); ok('Alerta ciudadana visible en triaje (o acumulada a expediente)', folio in rows or 'EXP-2026' in alltxt(), '')
    if folio in rows:
        pg.click(f'tr.cl[data-id="{folio}"]'); pg.wait_for_timeout(300); ok('Detalle de alerta ciudadana sin error', folio in pg.inner_text('#pn'))
    pg.evaluate("window.__go('admin','bitacora')"); pg.wait_for_timeout(500)
    ok('Bitácora registra la denuncia', 'DENUNCIA_RECIBIDA' in pg.inner_text('#main'))
    pg.evaluate("window.__go('ciudadano','participa')"); pg.wait_for_timeout(500); ok('Vista pública Participa', 'respuestas publicadas' in pg.inner_text('#main').lower())
    pg.screenshot(path=f'{OUT}/09_publico.png')
    pg.evaluate("window.__go('ciudadano','denuncia')"); pg.wait_for_timeout(500); ok('Banda Arbolín en denuncia', 'Denunciar con Arbolín' in pg.inner_text('#main'))
    ok('Sin errores de página', not errs, errs[:3])
    # móvil
    m2 = b.new_page(viewport={'width': 390, 'height': 844}); m2.goto('file:///home/claude/platform/dist/index.html'); m2.wait_for_timeout(800); m2.click('#arb-fab'); m2.wait_for_timeout(300)
    bb = m2.locator('#arb').bounding_box(); ok('Panel a pantalla completa en móvil', bb['width'] >= 389, bb)
    m2.screenshot(path=f'{OUT}/10_movil.png')
    b.close()
print(f"\n{sum(r[1] for r in res)}/{len(res)} PASS")
