import os, re, shutil
from playwright.sync_api import sync_playwright
OUT = '/home/claude/platform/shots/origen'; shutil.rmtree(OUT, ignore_errors=True); os.makedirs(OUT)
res = []
def ok(n, c, x=''): res.append(bool(c)); print(('PASS ' if c else 'FAIL ') + n, str(x)[:180])
with sync_playwright() as p:
    b = p.chromium.launch(args=['--no-sandbox']); pg = b.new_page(viewport={'width': 1440, 'height': 900}, accept_downloads=True)
    errs = []; pg.on('pageerror', lambda e: errs.append(str(e)))
    pg.goto('file:///home/claude/platform/dist/index.html'); pg.wait_for_timeout(900)
    go = lambda po, v: (pg.evaluate(f"window.__go('{po}','{v}')"), pg.wait_for_timeout(600))
    toast = lambda: pg.evaluate("[...document.querySelectorAll('#toasts .toast')].map(t=>t.textContent).slice(-1)[0]||''")
    main = lambda: pg.inner_text('#main')
    ok('Inicio: aviso de origen certificado', 'origen certificado' in main().lower() and '13' in main())
    pg.screenshot(path=f'{OUT}/01_inicio.png', full_page=False)
    go('admin', 'centro'); ok('Centro de mando: franja de preparación', 'temporada 2026-2027' in main().lower())
    go('admin', 'origen'); t = main(); ok('Vista de preparación', 'medida 1' in t.lower() and 'medida 2' in t.lower() and 'reglas de acreditación' in t.lower())
    nums = re.findall(r'(\d+)\s*días naturales', t); ok('Cuenta regresiva 13 días', nums and nums[0] == '13', nums)
    pg.screenshot(path=f'{OUT}/02_preparacion.png', full_page=True)
    rows = pg.query_selector_all('tr[data-c]'); ok('Lista de huertas que no proceden', len(rows) > 0, len(rows))
    rows[0].click(); pg.wait_for_timeout(400); m = pg.inner_text('.modal'); ok('Ficha de constancia', 'constancia ambiental de origen' in m.lower() and 'indispensable' in m.lower())
    with pg.expect_download() as d: pg.click('#cdl')
    ok('Descarga de constancia', d.value.suggested_filename.startswith('constancia_CAO-2627-'), d.value.suggested_filename)
    html = open(d.value.path(), encoding='utf-8').read(); ok('Documento con componentes y huella', 'Componentes evaluados' in html and 'SHA-256' in html and 'DEMOSTRACIÓN' in html)
    pg.evaluate("document.querySelectorAll('.overlay').forEach(o=>o.remove())")
    pg.select_option('#role', 'DET-03'); pg.wait_for_timeout(300); go('admin', 'origen'); pg.click('#emi'); pg.wait_for_timeout(300)
    ok('Analista no puede emitir constancias', 'corresponde al rol' in toast(), toast())
    pg.select_option('#role', 'DIC-01'); pg.wait_for_timeout(300); go('admin', 'origen'); pg.click('#emi'); pg.wait_for_timeout(500)
    ok('Dictaminador emite constancias', 'Se emitieron' in toast(), toast())
    ok('Constancias emitidas visibles', 'Constancias emitidas:' in main())
    go('admin', 'bitacora'); ok('Bitácora: emisión asentada', 'CONSTANCIAS_EMITIDAS' in main())
    go('admin', 'trazabilidad'); pg.click('#tout') if False else None
    pg.locator('[data-t]').first.click(); pg.wait_for_timeout(500); t = pg.inner_text('#tout')
    ok('Cadena de 6 etapas', all(k in t for k in ['Huerta de origen', 'Corte', 'Recepción', 'Selección y empaque', 'Inspección', 'Cargamento y cruce']), t[:120])
    pg.screenshot(path=f'{OUT}/03_trazabilidad.png', full_page=True)
    risky = pg.query_selector('tr.cl[data-t]')
    if risky:
        risky.click(); pg.wait_for_timeout(500); ok('Embarque con fruta sin constancia detectado', 'sin constancia' in pg.inner_text('#tout').lower())
    ok('Mezclas bloqueadas listadas', 'Origen no autorizado' in main())
    go('empacadora', 'recepcion'); pg.click('[data-u="HUE-12043-00031"]'); pg.fill('#tn', '8'); pg.click('#ok'); pg.wait_for_timeout(300)
    ok('Recepción: estado no autorizado rechazado', 'no está autorizado' in pg.inner_text('#out'), pg.inner_text('#out')[:120])
    go('empacadora', 'recepcion'); pg.click('#ok'); pg.wait_for_timeout(300); o = pg.inner_text('#out')
    ok('Recepción: elegible con constancia', 'autorizada' in o and 'CAO-2627-' in o, o[:200])
    pg.screenshot(path=f'{OUT}/04_recepcion.png')
    go('productor', 'constancia');
    if pg.query_selector('#lg'): pg.click('#lg'); pg.wait_for_timeout(500)
    ok('Productor: mi constancia', 'Constancia ambiental de origen' in main(), main()[:100])
    pg.screenshot(path=f'{OUT}/05_productor.png', full_page=False)
    folio = re.search(r'CAO-2627-[A-F0-9]{6}', main()).group(0)
    go('ciudadano', 'elegibilidad'); pg.fill('#q', folio); pg.click('#go'); pg.wait_for_timeout(400)
    t = main(); ok('Consulta pública por folio de constancia', folio in t and 'componente' in t.lower(), t[:200])
    ok('Público sin evidencia detallada (sin registro patronal)', 'asegurados' not in t)
    pg.screenshot(path=f'{OUT}/06_publico.png', full_page=True)
    pg.click('#arb-fab'); pg.wait_for_timeout(300)
    def say(q): pg.fill('#arb-q', q); pg.press('#arb-q', 'Enter'); pg.wait_for_timeout(500)
    last = lambda: pg.evaluate("(()=>{const a=[...document.querySelectorAll('#arb-log .arb-m.a .arb-b')];return a.length?a[a.length-1].innerText:''})()")
    say('¿Qué es eso del origen certificado?'); ok('Arbolín explica el acuerdo', '15 de octubre' in last(), last()[:120])
    say(f'Revisa la constancia {folio}'); ok('Arbolín consulta constancia por folio', folio in last() and 'Resultado' in last(), last()[:150])
    pg.screenshot(path=f'{OUT}/07_arbolin.png')
    ok('Sin errores JS', not errs, errs[:3])
    b.close()
print(f'{sum(res)}/{len(res)} PASS')
